### PR TITLE
fix: inserting automatic opens for modules doesn't show right suggestion

### LINKED ISSUE #6186: Inserting automatic opens for modules doesn't show right suggestion
As seen here:

image

### Repro steps

Copy this code (in a place where you don't already have `LanguagePrimitives` open) and hover over the `GenericXXX`:

```f#
let rec inline factorial n = 
    match n with
    | _ when (n=GenericZero) -> printfn "hi!  %d" n; GenericOne
    | _ -> printfn "howdy!  %d" n; n * (factorial (n - GenericOne))
```

### Expected behavior

The _automatic opens_ feature (if that's how it's called) should open `LanguagePrimitives`

### Actual behavior

But it opens just `Microsoft.FSharp.Core` (which is redundant), after which `LanguagePrimitives` still isn't in focus and the code still won't compile.

### Known workarounds

Type the code yourself ;).

Possibly this has to do with these declarations being `let inline` inside `LanguagePrimitives` or something?

### PR DESCRIPTION
**Pull request by GennadyGS**
Fixes #6186

### CODE REVIEW

**Comment by GennadyGS** [comment]
Can somebody authorized please rerun the build.
It is failed due to [503 (Service Unavailable)](https://dev.azure.com/dnceng/public/_build/results?buildId=1531511&view=logs&j=119f12ab-97c9-53f0-7ea6-00e6f97fda11&t=d2e57700-e144-5940-d919-9fe6f85bd854&l=1258)

**Review by KevinRansom — COMMENTED** [review]
Thanks for taking care of this, I think we need a test case to ensure that this continues to do what we expect moving forward.

Thanks,
Kevin

**Comment by GennadyGS** [comment]
@KevinRansom
Completely agree. 
However I have not found any tests for code fix providers (inheritors of `CodeFixProvider`) in solution. If this is the case then probably some testing infrastructure code is required to be added first for this purpose.
Can you please suggest whether my understanding is correct.
Thanks.

**Comment by vzarytovskii** [comment]
> @KevinRansom Completely agree. However I have not found any tests for code fix providers (inheritors of `CodeFixProvider`) in solution. If this is the case then probably some testing infrastructure code is required to be added first for this purpose. Can you please suggest whether my understanding is correct. Thanks.

Maybe @cartermp knows if we have such tests already in place?

**Comment by cartermp** [comment]
The easiest thing to do would be to either add a test here or look here for how to add new tests in a new file: https://github.com/dotnet/fsharp/blob/main/tests/service/AssemblyContentProviderTests.fs

I don't recommend trying to test the actual code fix provider infrastructure. It's not designed to be testable and it doesn't contain much logic.

**Comment by GennadyGS** [comment]
@cartermp 
Thank you for suggestion.
Can you please clarify your idea.
What exactly you suggest to test if not code fix provider? 
The reference you gave me relates to different component and unfortunately does not give me the clue what test scenario should look like, what part of code it should cover and on which level.

**Comment by cartermp** [comment]
@GennadyGS nearly all IDE features like code fix providers depend on compiler APIs. As you did in this change, often changing the logic behind those APIs is necessary to add new features or fix bugs. These components are the important ones to test. The "glue" in the actual code fix provider is not very important to test, nor is it easily testable.

**Comment by GennadyGS** [comment]
@cartermp 
Thanks, I got your point and agree with it.
I haven't noticed before that my change relates to more base component.

@KevinRansom 
> ... I think we need a test case to ensure that this continues to do what we expect moving forward

In case I follow the @cartermp's suggestion, my test will not satisfy this literally, that is it will not prove that code fix provider works as expected, but rather verify that underlying component (`AssemblyContentProvider`) returns correct result. 
Would it be OK?

**Comment by KevinRansom** [comment]
@GennadyGS --- yes that will be fine.

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=12565) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=12565) before we can accept your contribution.<br/><br/>:x: GennadyGS [sign now](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=12565)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/fsharp?pullRequest=12565) it.</sub>

**Comment by GennadyGS** [comment]
@KevinRansom
Test case is added. 
PR is ready for review.
Thanks.

**Review by vzarytovskii — APPROVED** [review]

**Review by KevinRansom — APPROVED** [review]
Thank you for taking care of this.

**Comment by GennadyGS** [comment]
Thanks for review

**Pull request merged**
