### PR TITLE
SyntaxTree: introduce SynTyparDecls

### PR DESCRIPTION
**Pull request by auduchinok**
Similar to https://github.com/dotnet/fsharp/pull/6830, adds type for type parameter declaration lists.

### CODE REVIEW

**Comment by cartermp** [comment]
@auduchinok there's been some outage issues with azdo recently. This is probably related

**Comment by auduchinok** [comment]
@cartermp Yeah, I've seen it, thanks. I was hoping the issue's gone already. :)

**Comment by auduchinok** [comment]
This is ready.

**Review by dsyme — APPROVED** [review]

**Comment by dsyme** [comment]
@auduchinok Great work, thank you!

**Pull request merged**
