### PR TITLE
FCS: enable cancelation of FSI-sessions by host.

### PR DESCRIPTION
**Pull request by goswinr**
Fix for https://github.com/dotnet/fsharp/issues/14489 
On net7 (and net48) this new member allows cancellation of FSI threads in a hosted context such as WPF or WinForms.  All fsi evaluations on net7 run under  `System.Runtime.ControlledExecution.Run()`. 
 Doing the cancellation myself by wrapping it into `System.Runtime.ControlledExecution.Run()`again does not work. It would fail with `Compiler Error:input.fsx (1,1)-(1,1) interactive error internal error: The thread is already executing the ControlledExecution.Run method.` 
So hosted evaluations can only be cancelled if this or a similar  new member is added.

### CODE REVIEW

**Comment by vzarytovskii** [comment]
@KevinRansom could you please review this?

**Comment by goswinr** [comment]
@KevinRansom all checks are green now. I hope you can accept this PR. Let me know if I should update some other documentation about FSI too.

**Review by KevinRansom — CHANGES_REQUESTED** [review]
@goswinr, 
Interrupt is the API for this. TryAbort uses ThreadAbort, which has opportunities to corrupt coreclr internal state and the bcl is no longer hardened against thread abort.  The API was added for FSharp because we had no way of interrupting executing script code.

You should use Interrupt for the scenario you have in mind.  That will cause the thread to be aborted, relatively cleanly, and we can clean up our interrupt handlers.  If you have a scenario that this doesn't work for then we can figure out how to fix Interrupt.

**Comment by KevinRansom** [comment]
@goswin Thank you for ths contribution, you should use the Interrupt API to cause executing scripts to halt.  I am closing this PR.  If there are issues with Interrupt please document them and we will try to should address them.

Kevin

**Comment by goswinr** [comment]
this was solved by https://github.com/dotnet/fsharp/pull/15184

**Pull request closed without merging**
