### PR TITLE
[RFC 1082] - uint type abbreviation

### PR DESCRIPTION
**Pull request by cartermp**
RFC: https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1082-uint-type-abbreviation.md

Note that we apparently assume that `uint` exists as a type abbreviation already, both in formatting and error messages:

https://github.com/dotnet/fsharp/blob/master/src/utils/sformat.fs#L147
https://github.com/dotnet/fsharp/blob/master/src/fsharp/FSComp.txt#L790

### CODE REVIEW

**Comment by cartermp** [comment]
Okay I think we have a serious bug here. fsharpqa is failing 217 tests related to IL generation and optimizations, which this absolutely doesn't touch. @KevinRansom @TIHan any thoughts? Could adding a type abbreviation really do that?

**Comment by TIHan** [comment]
I noticed these tests failing today. I thought it was a result of a WIP PR I have, but it does not seem to be the case.

**Comment by cartermp** [comment]
Okay this is a "something is wrong in the fsharp5 branch" problem, see here: https://github.com/dotnet/fsharp/pull/8196

Unfortunately it's merged into master

**Comment by KevinRansom** [comment]
@cartermp, you should add the experimental attribute, if this is for fsharp5 :-)

[<Experimental(ExperimentalAttributeMessages.RequiresPreview)>]

**Comment by cartermp** [comment]
This will be just an incremental update to FSharp.Core instead of being gated by F# 5, even though it's a suggestion + RFC. Not much value in gating the change.

**Pull request merged**
