### PR TITLE
fix consistency.

### PR DESCRIPTION
**Pull request by sayurin**
For #6914, generate better IL code.

### CODE REVIEW

**Comment by cartermp** [comment]
@sayurin Thanks! Looks like there are some tests to get passing here: https://dev.azure.com/dnceng/public/_build/results?buildId=218343&view=ms.vss-test-web.build-test-results-tab

**Comment by sayurin** [comment]
@TIHan , thank. I'll update test code.

**Comment by KevinRansom** [comment]
@sayurin, 

thanks for this contribution, before we can move ahead with this PR, we will need the CLA signed.  I believe the comment above has the necessary link.

Thanks

KEvin

**Comment by cartermp** [comment]
@sayurin Thanks, the change overall looks good, but it does fail some tests as you can see here: https://dev.azure.com/dnceng/public/_build/results?buildId=502629&view=ms.vss-test-web.build-test-results-tab

Would you mind adjusting/adding test cases as necessary? Thanks!

**Comment by cartermp** [comment]
Closing out old PR. @sayurin if you're still interested in pursuing this work, feel free to re-open.

**Pull request closed without merging**
