### PR TITLE
Cancellable: Use AsyncLocal instead of ThreadStatic

### PR DESCRIPTION
**Pull request by majocha**
Similar to #16779, Keeping the token in `AsyncLocal` could work better in scenarios with lots of parallelism like we have in Transparent Compiler.

todo: add some tests mixing cancellable with async, TPL, thread switching etc.

related: #16137, #16348, #16536

### CODE REVIEW

**Comment by majocha** [comment]
@auduchinok, Does it make sense?

**Comment by auduchinok** [comment]
> @auduchinok, Does it make sense?

From a glance, yes, thanks! I’ll probably need to do some testing just in case, though :)

**Comment by majocha** [comment]
I'm trying to write some tests using `cancellable` CE but I'm hitting FS1118, FS1113, which might be related to #17161.

**Comment by majocha** [comment]
OK, the problem with testing the cancellable CE is as described here:
https://github.com/dotnet/fsharp/issues/7110

I can't see a clear way around this limitation.

**Review by psfinaki — APPROVED** [review]
Hey, thanks, let's get this in!

@majocha thanks for trying testing it, if you come with any extra ideas in that regard, we can do a followup.

**Pull request merged**
