### PR TITLE
Cleanup and document async.fs

### PR DESCRIPTION
**Pull request by dsyme**
The process of fixing bug #11797 via #11799 made me go back and review async.fs end-to-end.

This does the following: 

1. Very carefully documenting exactly when cancellation and trampoline/hijack checks are currently made

2. Fix https://github.com/dotnet/fsharp/issues/8675, where a cancellation check was happening before a try/finally was being entered, causing resources to be potentially dropped on the floor if cancellation happens

3. Cleanup the code that does CancellationTokenRegistration (AwaitWaitHandle, AwaitBeginEnd etc.) to be more uniform

### CODE REVIEW

**Comment by Liminiens** [comment]
Maybe  https://github.com/dotnet/fsharp/issues/8668  could also be addressed? 😇 If it still reproduces on main branch.

**Comment by dsyme** [comment]
> Maybe #8668 could also be addressed? 😇 If it still reproduces on main branch.

I was surprised but as I mentioned in #8668 reducing the allocations by the technique I tried didn't actually improve performance.

**Comment by dsyme** [comment]
This is ready.  Best to review the changes with ignore-whitespace-changes on.

**Review by KevinRansom — APPROVED** [review]
Looks good.

**Pull request merged**
