### PR TITLE
Improve perf of extension methods without type attribute

### PR DESCRIPTION
**Pull request by nojaf**
Trying out the suggestion from Don at https://github.com/dotnet/fsharp/pull/13839#discussion_r1180881070
//cc @edgarfgp

### CODE REVIEW

**Review by T-Gro — APPROVED** [review]

**Comment by T-Gro** [comment]
(I restarted CI because Linux build timed out. But I did not see any other issues => looks good)

**Review by edgarfgp — APPROVED** [review]
Thanks, Florian :)

**Review by psfinaki — COMMENTED** [review]
Cool, any benchmarks on this?

**Review by vzarytovskii — APPROVED** [review]

**Comment by nojaf** [comment]
> Cool, any benchmarks on this?

No, not really.

**Pull request merged**
