### PR TITLE
Added langversion preview for FCS tests  --- keep this open until we understand the failures

### PR DESCRIPTION
**Pull request by ncave**
- Added `--langversion:preview` for FCS tests.

### CODE REVIEW

**Comment by KevinRansom** [comment]
@ncave ,  I think the individual test case needs to specify the version of F# that it needs.  That way can have tests that ensure we don't break the old mechanism.  So I don't think this is such a great idea.

**Comment by ncave** [comment]
@KevinRansom Perhaps, although it would be nice to test backwards compatibility of preview features and make sure they're not breaking existing tests.

Feel free to close this PR, it was just meant to illustrate that some FCS tests are currently broken in this feature branch with `--langversion:preview`, somewhere around [here](https://github.com/dotnet/fsharp/blob/feature/fcsw/src/fsharp/symbols/Exprs.fs#L497-L499), that's all.

**Comment by KevinRansom** [comment]
Thanks @ncave, I expect we just ran into those issues with this PR:  https://github.com/dotnet/fsharp/pull/10145  where we turned on FSharp 5.0 language features by default.

I'm going to close this and manage thise issues using #10145

Kevin

**Comment by KevinRansom** [comment]
@ncave, nope, gonna keep it open for a bit, to ensure we figure out the failures.  Since the FSharp5 PR didn't see these same failures.

**Comment by dsyme** [comment]
I have fixed this as part of #9510

**Pull request closed without merging**
