### PR TITLE
Fix #14375 by showing and inserting correct name of entities from unopened namespace/module

### LINKED ISSUE #14375: VS completion bugs with symbols in unopened namespaces
1. Auto open namespace/module in wrong place. Currently it will insert `open` statements to the outest namespace/module, but maybe the statement should be inserted to the closest places to the function
error1

2. Treat static class as F# module, and try to open the class. 
error2

**Expected behavior**

1. `open` statement should be inserted to the closest places to the function
图片
2. Treat static class as a F# module with `[<RequireQualifiedAccess>]` like insert `Array` or `Seq`

**Related information**

Provide any related information (optional):

Microsoft Visual Studio Community 2022
Version 17.4.1

Visual F# Tools   17.4.0-beta.22512.4+525d5109e389341bb90b144c24e2ad1ceec91e7b

### PR DESCRIPTION
**Pull request by Tangent-90**
## Description

Extracted from #17252

Fixes part 2 of #14375

1. For entity in class or module, instead of trying to open the class/module, it will now include the class/module name in `DisplayName`, so it won't try to open a class now. For modules, it will only try to open the nearest parent namespace/module.

GIF 2024-5-29 0-38-13

2. It won't insert duplicated open now. And completions can now also be filter by class/module name.

GIF 2024-5-29 0-41-45

## Checklist

- [x] Test cases added
- [ ] Performance benchmarks added in case of performance changes
- [x] Release notes entry updated:

### CODE REVIEW

**Review by T-Gro — APPROVED** [review]

**Review by psfinaki — COMMENTED** [review]
Hi @Tangent-90 - thanks for another good contribution!

I get what the issue is about, yet for some reason, I cannot reproduce the exact problem described in the bug. This PR has a bit different setting though - so could I ask you to also record a small "before" gif, how things currently look on your machine?

Ideally we'd have some compiler service tests here as well - have you looked around there if there is something we can build on?

**Comment by Tangent-90** [comment]
> I get what the issue is about, yet for some reason, I cannot reproduce the exact problem described in the bug. This PR has a bit different setting though - so could I ask you to also record a small "before" gif, how things currently look on your machine?

I have no other VS installation, so I record this GIF in VSCode (but it it the same bug).

GIF 2024-5-29 19-58-45

You can see that the class `System.BitConverter` or `System.Collections.Immutable.ImmutableArray` is opened, and it may insert a duplicated one though there is a same open.

**Comment by Tangent-90** [comment]
maybe we can add test to [here](https://github.com/dotnet/fsharp/blob/main/tests%2Fservice%2FAssemblyContentProviderTests.fs)

**Comment by psfinaki** [comment]
Yeah, let's try those ones. Note they have just moved to the Compiler.Service project, but haven't changed otherwise.

**Comment by Tangent-90** [comment]
> @Tangent-90 sorry it's taking this long - I am really trying my best to verify this. Among other things, it will be helpful when writing the release notes for VS.
> 
> I have checked out your branch and I am trying to repro the last example you've shared but seems like I am still getting the incorrect behavior:
> 
> https://github.com/dotnet/fsharp/assets/5451366/4b16a459-f8c2-468a-be69-8b8cf7cd2892
> 
> How does this look for you? And what could I be doing wrong?

This pr is solving problem in completion list of unresolved symbols (press `Ctrl+J` in VS or `Alt+Right`). The bug show in your video is of the code fix, and I haven't try that before 😂.

**Comment by Tangent-90** [comment]
> But now, hopefully, I am looking at the right place and still don't notice the change... Trying Ctrl + J here:

You may need to enable this option. This is disabled by default

图片

**Comment by psfinaki** [comment]
Ohhhh I see now. Yeah that was it, now I see the difference. All good, thanks for the explanations and the testing!

**Review by psfinaki — APPROVED** [review]

**Pull request merged**
