### PR TITLE
adjust dep manager error message in FSI, when extension is not loaded

### PR DESCRIPTION
**Pull request by smoothdeveloper**
For now, it is just to check the CI.

* ideas for contents to put under https://aka.ms/dotnetdepmanager are needed
* should it be under "dotnet interactive" umbrella and adjust the URI to convey that?

https://github.com/smoothdeveloper/visualfsharp/blob/16871138b029685c77d55c721a5a54f97f5156d6/src/fsharp/Microsoft.DotNet.DependencyManager/README.md is the content I came up with initially, it was still F# specific.

It would be good, if we clarify the intents, as to what we want to do with the interactive extensions in the broader sense.

My main concern has been the user story, for users to deploy such extensions (and the documentation on that page, for it to not generate support requests, anywhere), if we can't define a canonical and stable location that works across the environments (IDEs, fsi, dotnet interactive, FSC enabled tooling), and FCS isn't making it super smooth to "it just works", then, it is unlikely the ecosystem.

With this in mind, stuff to put on the page:

* installation steps, as of today, for the different use cases (each IDE, dotnet fsi, etc.)
* materials about writing extensions, making sure that everything that the nuget one is using is documented

Having a "list of recommended extensions" on fsharp.org, would also be sensible, where it will be easier for community to maintain, without adding burden to this repository.

### CODE REVIEW

**Comment by psfinaki** [comment]
Hey @smoothdeveloper, do you still think this can be of some use? As of now, the added link leads to the <s>void</s> Bing landing page :)

**Comment by smoothdeveloper** [comment]
@psfinaki yes I do think it would be useful, but I don't have control on aka.ms and I am not clear how much Microsoft is interested in endorsing and improving the user story around the extension mechanism.

Overall, having the README.md restored in this repository, and aka.ms link pointing to it would be a first step in the right direction.

I'm open to other suggestions.

**Comment by psfinaki** [comment]
Hmm alright, I'll get to this during this week.

**Comment by psfinaki** [comment]
So I've looked at this again, and I propose the following approach. 

Feel free to add the suggested content to this [README](https://github.com/dotnet/fsharp/blob/main/src/FSharp.DependencyManager.Nuget/README.md) with this PR. I think what you've written is useful. Then after we merge this (if no one is against it), I'll add some aka.ms link to the docs, I think I know how to create them.

**Comment by 0101** [comment]
@smoothdeveloper do you want to add the README to this PR so we can link it with aka.ms?

**Comment by smoothdeveloper** [comment]
@0101 yes, and sorry for the previous messages which I didn't see!

I'll get over it this weekend.

Thanks all!

**Comment by smoothdeveloper** [comment]
I've brought back the readme that lists both nuget & paket. If it is ok, we can merge.

**Comment by smoothdeveloper** [comment]
I've added pointer to RFC and the implementation detail leveraging reflection, highlighting this uses a late binding mechanism to avoid a static dependency.

**Review by psfinaki — APPROVED** [review]
Cool, I think this is good.

**Review by 0101 — APPROVED** [review]

**Pull request merged**
