### PR TITLE
Tail recursion warning and attribute, take 3

### PR DESCRIPTION
**Pull request by dawedawe**
This is an alternative approach to https://github.com/dotnet/fsharp/pull/15260 ([RFC1011](https://github.com/fsharp/fslang-design/blob/main/RFCs/FS-1011-warn-on-recursive-without-tail-call.md))
Instead of operating in `PostInferenceChecks.fs` this PR is using the IL level to emit warnings.
It seems a lot easier to emit warnings from there, but this approach currently suffers from a lot of false positives as can be seen in the tests.

- [ ] Identify calls from outside the rec def, so we don't emit false positives
- [ ] Identify rewrites to loops, so we don't emit false positives

### CODE REVIEW

**Comment by vzarytovskii** [comment]
Haven't reviewed it in detail yet, however, the first thouhg is that ilxgen doesn't feel like the right place for doing the tailcall analysis.

**Comment by dawedawe** [comment]
> Haven't reviewed it in detail yet, however, the first thouhg is that ilxgen doesn't feel like the right place for doing the tailcall analysis.
> 
> The analysis happens when we emit call(virt)s, which is orthogonal to the F#'s (tail) recursion (when we unroll recursion to loops, etc).

@vzarytovskii  Thanks for your thoughts on this.
Yeah, I'm struggling a bit with finding the right place which provides the needed information.
Can you point me into some direction? Should it all be done in the optimizer?

**Comment by vzarytovskii** [comment]
> > Haven't reviewed it in detail yet, however, the first thouhg is that ilxgen doesn't feel like the right place for doing the tailcall analysis.
> > The analysis happens when we emit call(virt)s, which is orthogonal to the F#'s (tail) recursion (when we unroll recursion to loops, etc).
> 
> @vzarytovskii Thanks for your thoughts on this. Yeah, I'm struggling a bit with finding the right place which provides the needed information. Can you point me into some direction? Should it all be done in the optimizer?

That's a good question, I would think that post inference phase, or optimization phase are the most fitting ones.

**Comment by dawedawe** [comment]
For those following along, I thing this PR is superseded by https://github.com/dotnet/fsharp/pull/15503
Please go there for the lastest work.

**Pull request closed without merging**
