### PR TITLE
[RFC FS-1071] Witnesses passing for trait-constraints w.r.t. quotations

### PR DESCRIPTION
**Pull request by dsyme**
Implementation for [RFC FS-1071 - Witness passing for quotations using SRTP-constrained functions and methods](https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1071-witness-passing-quotations.md)

F# quotations of code using SRTP constraint trait calls don't contain sufficient information to represent the semantic intent of the code. Specifically the quotations are missing any record of the resolution of SRTP constraints or how to execute constraint calls. 

This RFC addresses this problem by incorporating the necessary information into both quotations and the code laid down for dynamic interpretation of quotations.

TODO
* [ ] Allow ReflectedDefiniton on `let inline ` functions that utilise witnesses (currently no witness arguments are bound in the generated lambda and there is no representation for the utilization of the witness. Needs new LambdaWithWitnesses to detect the witnesses)
* [ ] This example causes a failure https://github.com/Microsoft/visualfsharp/issues/968

### CODE REVIEW

**Comment by dsyme** [comment]
@cartermp @KevinRansom @TIHan One specific motivation for fixing this core problem with quotations is the need to use quotations more heavily in any future evolution of the "F# for AI models" project I've been involved in.

**Comment by TIHan** [comment]
What does the term "witness" mean in this case?

**Comment by dsyme** [comment]
> What does the term "witness" mean in this case?


A witness is the lambda term that represents the solution to an SRTP constraint, e.g. if you use `+` in generic inline math code you expect to see a type-specialized witness `(fun (a: double) (b: double) -> a + b)` for that passed in at the callsite where the generic function is called at type `double`.

Because this is only about quotations, you only see these witnesses by using the new `CallWithWitnesses` active pattern when processing the quotations.

**Comment by dsyme** [comment]
Closed in favour of https://github.com/dotnet/fsharp/pull/6810 from feature branch

**Pull request closed without merging**
