### PR TITLE
Moved CodeGen/EmittedIL/TailCalls over to NUnit

### PR DESCRIPTION
**Pull request by sergey-tihon**
part of #7075

The only strange thing is that IL for 
```fsharp
let run() = let x = 0 in foo(x,5)
```

omit name of local variable `x` ...
in bsl it was 
```
    .locals init ([0] int32 x)
```
for me it looks like 
```
    .locals init (int32 V_0)
```
full difference from bsl IL is in the commit https://github.com/dotnet/fsharp/commit/1703306fc3b84180f0b65faad7e15ee174fee6ba

### CODE REVIEW

**Comment by sergey-tihon** [comment]
@KevinRansom can you please suggest why local variable name can be omitted after ILdasm?

**Comment by cartermp** [comment]
@KevinRansom any thoughts?

**Comment by KevinRansom** [comment]
Oh the il differences are because of optimization.  The change is from building debug to building release.  I believe I fixed this with this PR:

**Comment by sergey-tihon** [comment]
@KevinRansom can you  please share the link to the PR that you mentioned?

**Comment by KevinRansom** [comment]
Thanks for this.

**Comment by sergey-tihon** [comment]
Thank you for merging this!
@KevinRansom can you please post here the link to PR you mentioned?
>  I believe I fixed this with this PR:

**Pull request merged**
