### PR TITLE
Allow moving cursor by prev/next words

### PR DESCRIPTION
**Pull request by Swoorup**
Fixes: https://github.com/dotnet/fsharp/issues/10593

move-word

New Shortcuts:
Alt+B or Ctrl + Left : Go left (back) one word.
Alt+F or Ctrl + Right: Go right (forward) one word. (If we are at the end of sentence, upon pressing this key, we advance the cursor at end of the line, even though there are no words)

### CODE REVIEW

**Comment by KevinRansom** [comment]
@Swoorup , hi this is a greatfeature.

**Comment by Swoorup** [comment]
@KevinRansom Fixed the issue. I noticed some shells like python use multiple stop characters (stopping on `',"`) when moving words compared to when deleting word which just looks for spaces, but we could always improve this later on.

**Comment by Swoorup** [comment]
@KevinRansom regarding the ctrl, I can't test it since i don't have a windows box :( 

But I think the issue was because the first match block wasn't filtering out Ctrl modifiers keys. Let me know if you find issues.

**Review by cartermp — APPROVED** [review]
Thanks! This works great on Windows as well.

**Comment by cartermp** [comment]
Just to note: tested it all and it works as per @KevinRansom's feedback

**Pull request merged**
