### PR TITLE
[WIP] PackageReference support for Legacy Project System

### PR DESCRIPTION
**Pull request by TimLariviere**
Related issue: #5849

I've started to add support for PackageReference in legacy F# projects, since @cartermp said there was no plan to implement it but a PR would be acceptable.

Few things that ease the implementation:
- Legacy C# projects already support PackageReference
- `nuget.exe` supports PackageReference in legacy F# projects perfectly
- `msbuild.exe` also supports it perfectly
- The building/debugging experience of an already restored project is on-par with `packages.config` as far as I can tell (IntelliSense-Debugger-etc.)
- Visual Studio for Mac also already support it completely for both C# and F#

So there's really only 2 issues with PackageReference:
- Packages represented as unknown files and placed at the root of the project, in the Solution Explorer of Visual Studio
- Visual Studio not detecting PackageReference as NuGet packages: so "Restore NuGet packages" doesn't restore them and "NuGet Package Manager" doesn't display them in the Installed tab nor is able to install them.

I managed to put all `PackageReference` nodes under the `References` node.
fsharp-oldformat-fix
The NuGet icon could be replaced with an official one (from the C# project system?). The one I used comes from the VS Marketplace.
Also I could use some guidance if we need to add some tests.

Regarding NuGet, I don't know how to proceed.
I didn't find anything in the source code to let NuGet knows there is packages.
Is it managed by this repository?

I'll be happy even if there's only a partial support.
Visual Studio automatically restoring the packages would be enough to make it usable.
Adding/removing packages could be done by editing the fsproj manually.

### CODE REVIEW

**Comment by cartermp** [comment]
Thanks @TimLariviere this looks like good work.

We'll have to consider how to proceed with this. The context is that we want to phase out the old project file format for F#, and in VS 2019 we'll likely take steps to default all project types to the .NET SDK if we can do it without regressing. Any that we cannot guarantee will work will still use the old kinds, but eventually it will be the new norm for F# (especially as Xamarin et. al. work towards better support for .NET SDK-style projects).

Given this, I don't see an urgency for making the support for PackageReference as good as possible. Covering the "unblock me" case as you've done here may be sufficient. We don't normally wish to accept things unless they also cover more corner cases, but in light of where we want to go I'm ready to accept something that has clear manual workarounds.

**Comment by TimLariviere** [comment]
Yes, I understand your concern with VS2019 upcoming.
The sooner we switch to full .NET SDK-style projects, the better. :)

I've mostly done this PR because most of the tools already have some support for PackageReference in legacy project format, only Visual Studio keeps me from using it today.

Is VS2019 / Xamarin SDK-style projects something that we can expect in the foreseeable future?

**Comment by cartermp** [comment]
Not sure what the timeline is from the Xamarin side, unfortunately. But _thar be dragons_ when it comes to this, so the pessimistic side of my says it'll be a while. So this PR definitely does have value on that basis 🙂

**Comment by knocte** [comment]
How about merging this PR to make it possible for folks to migrate manually to <PackageReference> items, but not make the new projects default to this yet?

**Comment by knocte** [comment]
(Edited my comment above to escape properly the &lt; and &gt; chars)

**Comment by TimLariviere** [comment]
@knocte Currently this PR is only a cosmetic fix. Visual Studio and NuGet Package Manager don't pick up the packages, and so don't restore them automatically.
Restoring with either `nuget.exe` or `msbuild.exe` before allows to debug with Visual Studio though...

I'm not sure this is a problem in the Visual F# Tools.

**Comment by KevinRansom** [comment]
Thank you for taking the time to look at this, however, I don't think we are going to do this.  The dotnet sdk is the project of choice for new F# development projects.

Thanks 

Kevin

**Pull request closed without merging**
