### PR TITLE
Moving AccessOfTypeAbbreviationTests over to NUnit

### PR DESCRIPTION
**Pull request by sergey-tihon**
This is draft of PR because want to test it and I cannot run `FSharpSuite.Tests.fsproj` on `macOS`.
I did not find out (yet) the way to quickly compile and test on Win/Parallels VM. 
I have tried `eng/Build.ps1 -restore -build` and have to turn off VM after 30 min of 100% CPU load.

Attempt to contribute to #7075

### CODE REVIEW

**Comment by sergey-tihon** [comment]
@forki can you please suggest the fastest way to execute this particular test suite on Win? How do you run this?

**Comment by TIHan** [comment]
Thank you all for converting tests over. It's great!

Also, be sure to give feedback on the test framework API that you all have been using. I'd say I need to clean a few things up, but if you all have any suggestions, let us know!

**Comment by sergey-tihon** [comment]
This PR is ready for review. There is only one strange thing, I have to change error message from

> The type 'Hidden' is less accessible than the value, member or type 'Exported' it is used in

to

> This construct is deprecated. The type 'Hidden' is less accessible than the value, member or type 'Exported' it is used in.
As of F# 4.1, the accessibility of type abbreviations is checked at compile-time. Consider changing the accessibility of the type abbreviation. Ignoring this warning might lead to runtime errors.

**Comment by forki** [comment]
The new API does not match infixes. So the whole text is needed. So changing text is expected.

Regarding running the test. I do that from VS test runner

**Comment by KevinRansom** [comment]
Thanks

**Pull request merged**
