### PR TITLE
Fix #5729

### LINKED ISSUE #5729: Invalid binary and octal literals for 64-bit integers are accepted
When using binary or octal literals for 64-bit integers (both signed and unsigned) the compiler doesn't check for overflows and accepts more than 64 bits.

This also applies to `LanguagePrimitives.ParseInt64` and `LanguagePrimitives.ParseUInt64`.

I noticed that after I ported that portion of the code from the F# compiler to an app of mine.

This is the code in the compiler:

https://github.com/Microsoft/visualfsharp/blob/fead0aac540485683f694524eadad79983ec28d9/src/fsharp/lex.fsl#L69-L75

This is the code in FSharp.Core:

https://github.com/Microsoft/visualfsharp/blob/92247b886e4c3f8e637948de84b6d10f97b2b894/src/fsharp/FSharp.Core/prim-types.fs#L2363-L2369

#### Repro steps

``` fsharp
let N = 0b1111_1111_1111_1111_1111_1111_1111_1111_1111_1111_1111_1111_1111_1111_1111_1111_1L
// Actually 65 bits
// ---------------------------------------------------------------------------------------^
```

I prepared a repro project here: [repro.zip](https://github.com/Microsoft/visualfsharp/files/2441822/repro.zip)

#### Expected behavior

The compiler should emit `FS1149` and `FS1150` for signed and unsigned long integers, respectively. The `ParseInt64` and `ParseUInt64` functions should fail with an `OverflowException`.

#### Actual behavior

The compiler accepts more than 64 bits in binary and octal literals. The numbers end up being equal to `-1` for `int64` and `UInt64.MaxValue` for `uint64`.

#### Known workarounds

Use decimal or hexadecimal literals.

#### Related information 

I can reproduce that on Windows 10 with VS 2017 and on macOS with the .NET Core SDK 2.1.402.

### PR DESCRIPTION
**Pull request by gdziadkiewicz**

### CODE REVIEW

**Comment by dsyme** [comment]
Great! Link to the bug: https://github.com/Microsoft/visualfsharp/issues/5729

**Comment by cartermp** [comment]
@gdziadkiewicz Are you seeking a review? If so, if you could:

* Sign the .NET CLA
* Mark this PR as ready for review

Then we can take a loko.

**Comment by gdziadkiewicz** [comment]
@cartermp It is still work in progress. I was recently busy and even managed to forget about this PR, but I will make it review ready this week.

**Comment by cartermp** [comment]
@gdziadkiewicz No rush!

**Comment by realvictorprm** [comment]
You pushed 0 commits? Github bug lol

**Comment by realvictorprm** [comment]
> @gdziadkiewicz pushed 0 commits.

**Comment by cartermp** [comment]
@realvictorprm It's possible to push empty commits, which will re-trigger CI.

**Comment by gdziadkiewicz** [comment]
@cartermp Are there any plans to fix this CI error? It seems to be also present on master ATM 
image

**Comment by KevinRansom** [comment]
@brettfo

**Comment by cartermp** [comment]
@gdziadkiewicz Yes, we have an internal email thread going with infrastructure folks. It doesn't appear to be related to our codebase.

**Comment by brettfo** [comment]
@gdziadkiewicz The issue is present on all Windows jobs trying to restore FSharp.Core 4.6.2.  There is no issue if it's trying to restore 4.7.0 (like in the `release/dev16.3` branch) nor is there an issue on non-Windows machines.  I'm having some internal conversations to try and figure out why this package isn't getting restored.

I have a temporary workaround that I'll be creating a PR for soon

**Comment by brettfo** [comment]
#7424 should fix the issue.  I'll watch and merge that one as soon as it's ready.

Once that's in you may need to rebase or close/open this PR to trigger a new merge and build.

**Comment by brettfo** [comment]
#7424 is now in; you should be able to rebase (or otherwise force a re-merge) and get the tests to do something sane.

**Comment by gdziadkiewicz** [comment]
Thanks @brettfo , now it builds fine on the build server. @cartermp From my perspective this is ready to be reviewed.

**Comment by cartermp** [comment]
Give that FSharp.Core 4.7 is locked, this will be in F# vNext

**Pull request merged**
