### PR TITLE
Add `FSharpWorkspace` to FCS

### PR DESCRIPTION
**Pull request by 0101**
## Description

Adding `FSharpWorkspace` experimental API. 

Also some updates on `FSharpProjectSnapshot` to reflect that we need to be able to efficiently swap referenced projects and files when they change.

## Checklist

- [x] Do we need more `[<Experimental>]` attributes or is the top level one enough? _Should be enough._
- [x] Test cases added
- ~[ ] Performance benchmarks added in case of performance changes~
- ~[ ] Release notes entry updated~

### CODE REVIEW

**Review by vzarytovskii — APPROVED** [review]

**Comment by edgarfgp** [comment]
Thank you for this 👍🏻

**Comment by nojaf** [comment]
Thanks @0101 and team!

**Comment by 0101** [comment]
@nojaf don't get too excited, this is a pretty early version and didn't go through much testing yet 😅 But do try it out and let us know what needs to be fixed and added!

**Comment by nojaf** [comment]
Well, true, but at least it is out there.

**Pull request merged**
