### PR TITLE
Tinkering with allocations

### PR DESCRIPTION
**Pull request by vzarytovskii**
Probably need to have some benchmarks.
Also to check whether order matters for semantic classifications.

### CODE REVIEW

**Comment by baronfel** [comment]
For LSP order does matter - overlapping also matters. In FSAC we break up overlapping ranges into non-overlapping sub-ranges, but ordering would be a much bigger change to adapt to.

**Comment by En3Tho** [comment]
Is SortedSet<T> not an option?

**Comment by vzarytovskii** [comment]
> Is `SortedSet<T>` not an option?

No, range does not support equality out of the box.

**Comment by vzarytovskii** [comment]
Since we need to preserve ordering (hence the custom ordered set), the change didn't affect allocations much:

|                               Method                   |        Mean |     Error |     StdDev |    Gen0 |   Gen1 |  Allocated |
|------------------------------------------------------- |------------:|----------:|-----------:|--------:|-------:|-----------:|
|  GetSemanticClassificationsWholeFile_BEFORE            | 3,459.65 us | 68.591 us | 116.474 us | 19.5313 | 3.9063 | 3963.96 KB |
|  GetSemanticClassificationsWholeFile_AFTER_OrderedSet  | 3,503.58 us | 68.680 us | 67.453 us  | 19.5313 | 3.9063 | 3970.66 KB |
|  GetSemanticClassificationsWholeFile_AFTER_HashSet     | 3,422.14 us | 65.381 us | 67.141 us  | 19.5313 |      - | 3892.37 KB |
| GetSemanticClassificationsPartOfFile_BEFORE            |    28.88 us |  0.415 us | 0.368 us   |  0.0916 |      - |   22.77 KB |
| GetSemanticClassificationsPartOfFile_AFTER_OrderedSet  |    30.51 us |  0.605 us | 0.594 us   |  0.1221 |      - |   26.54 KB |
| GetSemanticClassificationsPartOfFile_AFTER_HashSet     |    29.30 us |  0.467 us | 0.414 us   |  0.1221 |      - |   25.38 KB |


I know @cartermp was trying to refactor it earlier as well.

So, doesn't make sense to pursue it further, closing.

**Comment by 0101** [comment]
Would changing `array` to `seq` here make any difference? It seems like a bunch of allocations and the result is only iterated once.

```fsharp
                    let resolutions =
                        match range with
                        | Some range ->
                            sResolutions.CapturedNameResolutions.ToArray()
                            |> Array.filter (fun cnr -> rangeContainsPos range cnr.Range.Start || rangeContainsPos range cnr.Range.End)
                            |> Array.groupBy (fun cnr -> cnr.Range)
                            |> Array.map (fun (_, cnrs) -> takeCustomBuilder cnrs)
                            |> Array.concat
                        | None -> sResolutions.CapturedNameResolutions.ToArray()
```

**Comment by vzarytovskii** [comment]
> Would changing `array` to `seq` here make any difference? It seems like a bunch of allocations and the result is only iterated once.
> 
> ```fsharp
>                     let resolutions =
>                         match range with
>                         | Some range ->
>                             sResolutions.CapturedNameResolutions.ToArray()
>                             |> Array.filter (fun cnr -> rangeContainsPos range cnr.Range.Start || rangeContainsPos range cnr.Range.End)
>                             |> Array.groupBy (fun cnr -> cnr.Range)
>                             |> Array.map (fun (_, cnrs) -> takeCustomBuilder cnrs)
>                             |> Array.concat
>                         | None -> sResolutions.CapturedNameResolutions.ToArray()
> ```

no

**Pull request closed without merging**
