### PR TITLE
AS constrPattern

### PR DESCRIPTION
**Pull request by xp44mm**
* trimed the whitespaces at the end of each lines.
* The `AS constrPattern` can only be applied once per node？

### CODE REVIEW

**Review by vzarytovskii — CHANGES_REQUESTED** [review]
Can whitespace changes be reverted please? It is very hard to see real changes.

Can you please also add more detailed description what the change is about?

**Comment by auduchinok** [comment]
@vzarytovskii JFYI it's possible to hide the whitespace changes, though, I agree, they should be cleaned up before merging.

Screenshot 2021-08-05 at 18 29 28

**Comment by vzarytovskii** [comment]
@auduchinok Yeah, i have it on, it just may mess up with blame.

**Comment by xp44mm** [comment]
> @auduchinok Yeah, i have it on, it just may mess up with blame.

Are your `Requested changes` still addressed?

**Comment by WhiteBlackGoose** [comment]
> Do your Requested changes still must be addressed?

But the whitespaces are still not reverted, right? 😅

**Comment by vzarytovskii** [comment]
> > @auduchinok Yeah, i have it on, it just may mess up with blame.
> 
> 
> 
> Do your `Requested changes` still must be addressed?

Sorry, missed it. Could you please revert whitespace changes? It will be hard to look at blame otherwise. 

Also, some tests are failing, could you please take a look?

**Comment by dsyme** [comment]
Closing this 

@xp44mm - we'd need a language suggestion filed at https://github.com/fsharp/fslang-suggestions/ before we can change the parser like this, thanks

**Pull request closed without merging**
