### PR TITLE
fix implicit load directory for script execution for package load scripts

### PR DESCRIPTION
**Pull request by dsyme**
This fixes https://github.com/dotnet/fsharp/issues/10865

For scripts generated via package load resolution we do *not* change the implicit include directory,
as doing so would, for example, change the ResolutionFolder for type provider instantiations.

This is consistent with the treatment of these scripts in ScriptClosure.fs for analysis

If scripts generated via package load resolution want to load resources relative to the 
the script then they can always use absolute paths in the generated script.

### CODE REVIEW

**Comment by dsyme** [comment]
@KevinRansom I've tested this manually

I'm not very familiar with what testing we have set up in this area. Adding a basic FSharp.Data `fsi` execution test would be sufficient, but there may be a better test to add at the level of FSHarp.DependencyManager

Could you add the testing, or determine if it's needed?

**Review by KevinRansom — COMMENTED** [review]
@dsyme ,

I need to think on this a bit, but I think this is probably the wrong approach.  Thhe dependency manager vreturns a collection files, which may or may not be code generated.  The nuget package can contain scripts. for example initialization scripts.  I expect those scripts will assume that they are in place in the nuget package folders.

Anyway, can we hold off on a fix for now ... the work around:

**Review by KevinRansom — CHANGES_REQUESTED** [review]
@dsyme ,

I need to think on this a bit, but I think this is probably the wrong approach.  Thhe dependency manager vreturns a collection files, which may or may not be code generated.  The nuget package can contain scripts. for example initialization scripts.  I expect those scripts will assume that they are in place in the nuget package folders.

Anyway, can we hold off on a fix for now ... the work around is not horrific.
````
type Stocks = CsvProvider<"data/MSFT.csv", ResolutionFolder= __SOURCE_DIRECTORY__ >
````

**Comment by dsyme** [comment]
The workaround is ok for FSharp.Data but is not obvious (no one spotted it except me) and there is no guarantee that other type provders will implement a ResolutionFolder override at all.

Getting ResolutionFolder right is important - it is critical information for the behaviour of type providers and part of the spec of how type providers function - we randomly mess up type providers by providing them with incorrect ResolutionFolder for the compilation they are used in.

Today the behaviour is very inconsistent:

1. For editing the provided script content is loaded with correct resolution folder 
2. For FSI execution the provided script content is loaded with resolution folder wherever they exist on disk.

Which spec is correct?  Well, spec (2) doesn't propagate the ResoutionFolder information correctly at all and so is clearly incorrect.  It's just a bug, especially since we have no other current option for how to propagate the resolution folder (without changing the TP architecture/API, which would mean breaking every type provider).

> The dependency manager vreturns a collection files, which may or may not be code generated. The nuget package can contain scripts. for example initialization scripts.  I expect those scripts will assume that they are in place in the nuget package folders.

In practice we only need allow code generated scripts, which can in turn #load on other scripts (indeed, in retrospect we could have only allowed script content, not script files)

**Comment by dsyme** [comment]
If you like I can adjust the PR to keep track of resolutionFolder separately from implicitIncludeDir for loaded scripts.  Indeed resolutionFolder should always be the same across the whole compilation - it's possible it's being set incorrectly for transitively `#load` scripts in any case.

**Pull request closed without merging**
