### PR TITLE
add ci step to do a plain `dotnet build`

### PR DESCRIPTION
**Pull request by brettfo**
While investigating #10151 I decided it would be a good idea to ensure that `dotnet build ./FSharp.sln` always works following an initial `./build.sh`.

### CODE REVIEW

**Review by KevinRansom — APPROVED** [review]

**Comment by auduchinok** [comment]
@brettfo Could it also have a Windows build, in addition to Linux and macOS ones, please?

**Comment by KevinRansom** [comment]
@auduchinok , it doesn't work on Windows ... I have to make some changes ....: https://github.com/dotnet/fsharp/issues/10151#issuecomment-713317687

**Comment by auduchinok** [comment]
@KevinRansom My suggestion is about having it in CI at least when we have a fix, so it doesn't accidentally get broken again. 🙂

**Comment by KevinRansom** [comment]
@auduchinok , when I submit the fix, I will include a ci leg for it :-)

**Comment by brettfo** [comment]
Since I'm already here I added a Windows version that can simply be un-commented when ready.

**Comment by KevinRansom** [comment]
@brettfo thanks mate.

**Review by cartermp — APPROVED** [review]
dope

**Pull request merged**
