### PR TITLE
Fix quickinfo text

### PR DESCRIPTION
**Pull request by KevinRansom**

### CODE REVIEW

**Comment by KevinRansom** [comment]
Passed
Failed

**Comment by majocha** [comment]
Probably it would be worth it to also test this case in FSharp.Compiler.Service.Tests.TooltipTests.

**Comment by KevinRansom** [comment]
> Probably it would be worth it to also test this case in FSharp.Compiler.Service.Tests.TooltipTests.

I just want the durned thing to work reliably again. :-)

**Review by vzarytovskii — APPROVED** [review]

**Review by T-Gro — APPROVED** [review]

**Pull request merged**
