### PR TITLE
Attribute targets on unions

### PR DESCRIPTION
**Pull request by edgarfgp**
Follow up: https://github.com/dotnet/fsharp/pull/17207

Unions compile down to a `class` or `struct`  [sharplab](https://sharplab.io/#v2:DYLgZgzgNAJiDUAfALgTwA4FMAEBVAdgJYD2+2AvALABQ2d2i2AwgIYSYCMN92NaWeIqQBMFbvUat2HbMTDYIyAE6F8Ac2wAqbKuTi6ktplFyFy1Wpo0A2gB4AysoCuAY2QA+ALp8MOR0tdkAhIyKloJZiMucLobB2c3Lx8Bf0DgkTEYhkjpWXkWEDMVdS0dfD0sw3YTeUVijW0AI0K6i31ean4cAEkYTFDsXqtqO1TE707fbDHkXv7kCkGYIA==).

This PR enforces the new rules on `unions`.

### Old rules
- AttributeTargets.Class
- AttributeTargets.Interface 
- AttributeTargets.Delegate 
- AttributeTargets.Struct 
- AttributeTargets.Enum

### New Rules
- AttributeTargets.Class
- AttributeTargets.Struct when using `[<Struct>]`

### Before [sharplab](https://sharplab.io/#v2:DYLgZgzgNAJiDUAfA9gBwKYDsAEBlAnhAC7oC2AsAFBUDaAPAIJFEBOAlgEYCuJAqhAEMA5ugAUTVpx7oAKgJYiiEAHQBhYAIgQAlAD4AulSL4M2dZohyF6IhPbcSo7dgC8VbB49tMAC3TsibDspR20qWkZme2l+YTFgh1l5RRUASUwSFjABAGN0PUNKY1N0zOy8q0UE6SdXd09sbz8AoKiQsTDqSnpqvkERcTbEypsVXFYuHKICoxN0PAmpkdshmuc3SgbG3382QN6O8O66Uv9ypOsiA2wAehvsABFkdAhsTGRA7LZgZWxUwIgPmQXGAMAi4xYkyIy2ud0ez1e70+Am+v3+2EBwNBEXMWhhhWK814mDYyBwGwaiDMmnQAEZ6h4IqcsrkLopYfcni83h9sF8fn8AUCQWDjhCofjbpyETzkajBRjhdjjrjLMkbAZZqZiaTMAAmOqbTxU1Q02nYZBgDGSTBCbAAKm2RAZ2BNNINlut7FtR3oqslcK5iN5/LRQqxovozPOAel3KRfJRAvRmJF4MWVwJcwWkKmOrJhsp1IgdPqOI0ePVmal8PjIaTYcVEaZGTOrNjteDcuT4bTYozmqK2fFeZJZINFONxbpFqtAhAXu8dsd3mdRo8bpLHqtxG9y+wHAXu6XQA===)

```fsharp
open System

[<AttributeUsage(AttributeTargets.Class)>]
type ClassTargetAttribute() =
     inherit Attribute()

[<AttributeUsage(AttributeTargets.Interface)>]
type InterfaceTargetAttribute() =
     inherit Attribute()

[<AttributeUsage(AttributeTargets.Struct)>]
type StructTargetAttribute() =
     inherit Attribute()

[<InterfaceTarget>] // Does not fail. It should
[<StructTarget>] // Does not fail. It should
[<ClassTarget>]
type Union =
    | Case1
    
[<InterfaceTarget>] // Does not fail. It should
[<StructTarget>] // Does not fail. It should
[<ClassTarget>]
type Union2 =
    | Case1 of string * int
    | Case2 of string

[<ClassTarget>] // Does not fail. It should
[<InterfaceTarget>] // Does not fail. It should
[<Struct>]
type StructUnion =
    | Case1
  
[<ClassTarget>] // Does not fail. It should
[<InterfaceTarget>] // Does not fail. It should
[<Struct>]
type StructUnion2 =
    | Case1 of a: string * int
    | Case2 of string * b: string
```

### After
```fsharp
open System

[<AttributeUsage(AttributeTargets.Class)>]
type ClassTargetAttribute() =
     inherit Attribute()

[<AttributeUsage(AttributeTargets.Interface)>]
type InterfaceTargetAttribute() =
     inherit Attribute()

[<AttributeUsage(AttributeTargets.Struct)>]
type StructTargetAttribute() =
     inherit Attribute()

[<InterfaceTarget>] // Fails as expected
[<StructTarget>]// Fails as expected
[<ClassTarget>]
type Union =
    | Case1
    
[<InterfaceTarget>] // Fails as expected
[<StructTarget>] // Fails as expected
[<ClassTarget>]
type Union2 =
    | Case1 of string * int
    | Case2 of string

[<ClassTarget>]// Fails as expected
[<InterfaceTarget>] // Fails as expected
[<Struct>]
type StructUnion =
    | Case1
  
[<ClassTarget>] // Fails as expected
[<InterfaceTarget>] // Fails as expected
[<Struct>]
type StructUnion2 =
    | Case1 of a: string * int
    | Case2 of string * b: string
```

## Checklist

- [x] Test cases added
- [x] Release notes entry updated

### CODE REVIEW

**Comment by edgarfgp** [comment]
This is ready.

**Review by psfinaki — APPROVED** [review]
Yeah I wish we had this proportion of added code and tests in all PRs :D

**Comment by edgarfgp** [comment]
Can I get another review please ?

**Review by vzarytovskii — APPROVED** [review]

**Comment by vzarytovskii** [comment]
Just a sanity check, `type E = A = 1 | B = 2` will still have target `enum`, right?

**Comment by edgarfgp** [comment]
> Just a sanity check, `type E = A = 1 | B = 2` will still have target `enum`, right?

@vzarytovskii Yes. There are dedicated tests that prove [that](https://github.com/dotnet/fsharp/blob/3125875f3bd39ef45a61f7fb759c517c88408d9f/tests/FSharp.Compiler.ComponentTests/Conformance/BasicGrammarElements/CustomAttributes/AttributeUsage/AttributeUsage.fs#L523)

**Comment by edgarfgp** [comment]
Any chance to get this merged before the nullable PR ?

**Comment by vzarytovskii** [comment]
> Any chance to get this merged before the nullable PR ? 

Uh oh, I didn't notice the comment before I've pressed merge button, but I sorry :(

**Comment by edgarfgp** [comment]
Ok,this is green again

**Comment by psfinaki** [comment]
Thanks @edgarfgp, merging now :)

**Pull request merged**
