### PR TITLE
Add ConvertToSingleEqualsEqualityExpression code fix

### PR DESCRIPTION
**Pull request by cartermp**
Addresses a super common beginner mistake.

image

The quick fix is also correct if the types are both `Nullable`, at least as of F# 5.

There are several other places where FS00043 can trigger, but this guards on the range of the error only being equal to `==`, so it should be safe. A generalized fixer for FS00043 could be interesting, but the errors are rather wide ranging so that is out of scope for now.

### CODE REVIEW

**Comment by cartermp** [comment]
This is ready for review

**Comment by abelbraaksma** [comment]
Nice!
For Google and Github search to find this, it's FS0043 ;)

**Review by KevinRansom — APPROVED** [review]

**Comment by TIHan** [comment]
What happens if you define ` val (==)` and try to use it?

**Review by TIHan — APPROVED** [review]

**Comment by cartermp** [comment]
I'm a clever boy.

**Pull request merged**
