### PR TITLE
Diagnostics logger: remove exception rethrow during recovery

### PR DESCRIPTION
**Pull request by auduchinok**
Partially fixes https://github.com/dotnet/fsharp/issues/15905. Removes rethrowing exceptions in `DiagnosticsLoggerExtensions.ErrorRecovery`, which was making the error recovery non-existent for many exceptions other than `InternalError`. System exceptions like `ArgumentException` or `NullReferenceException` were never recovered because of this call, breaking analysis for the whole file in many cases.

With this change the analysis recovery properly continues but the internal error isn't reported anymore, I'm still looking into it.

### CODE REVIEW

**Comment by auduchinok** [comment]
> Have you found the reason why this was put there initially?

I goes beyond the initial Git commit in this repo, so can't say for sure. Our guess was the authors wanted the process to crash to analyse the crash. We never want an IDE crash because of an error during analysis. 🙂

**Comment by vzarytovskii** [comment]
> > Have you found the reason why this was put there initially?
> 
> I goes beyond the initial Git commit in this repo, so can't say for sure. Our guess was the authors wanted the process to crash to analyse the crash. We never want an IDE crash because of an error during analysis. 🙂

That's exactly the reason. The idea is - we want to crash if we can't recover/repair it. In VS it won't crash the whole IDE, but only extension.

**Comment by auduchinok** [comment]
> That's exactly the reason. The idea is - we want to crash if we can't recover/repair it. 

The problem is it's called in `ErrorRecovery`, effectively breaking the recovery. Analysis continues just fine if this code is removed, both in the current file and in subsequent ones, because `ErrorRecovery` is called in places where we can actually continue.

**Comment by ForNeVeR** [comment]
> In VS it won't crash the whole IDE, but only extension.

I think we observed the whole VS process crashing because of an uncaught exception (see #15906 for the fix of that).

**Comment by vzarytovskii** [comment]
> > That's exactly the reason. The idea is - we want to crash if we can't recover/repair it. 
> 
> The problem is it's called in `ErrorRecovery`, effectively breaking the recovery. Analysis continues just fine if this code is removed, both in the current file and in subsequent ones, because `ErrorRecovery` is called in places where we can actually continue.

What I meant by that, if we hit something truly irrecoverable. Like, we can't read pickled data, or some critical issue, we want to crash. I'm not sure why is it in the diagnostic logged.

**Comment by auduchinok** [comment]
> Controlled report is preferable, but it doesn't allow to collect nearly as much info as watson allows. Also, we can't really collect much from the compiler itself.

So, what should we do here? Prior to this PR, this code would just break error recovery in the type checker in many cases and in addition to that it would also crash the process. It all happened in cases where we expect errors to be recoverable, because the only place where this rethrow is happening is during error recovery.

What short-term options I see:

* Log exception stacktrace via `Debug.Assert` instead of throwing again
  That would usually be enough for us to investigate the issue and may significantly improve user experience when an exception happens.

* Add a setting to FCS, to either rethrow (i.e. break the recovery) or to do the logging, as suggested above
  This would allow to crash VS process if that's actually needed for investigations

**Comment by auduchinok** [comment]
I've rechecked this fix without https://github.com/dotnet/fsharp/pull/15909 applied, and it turns out the errors aren't hidden and are properly reported via a diagnostic:

Screenshot 2023-09-01 at 10 14 18

Please note, that the rest of the analysis has also managed to finish, as can be seen from the highlighted identifiers.

With this info, I'd vote for a better exception logging (so the stacktraces are available somewhere) and not rethrowing the exception, at least by default. @vzarytovskii Please let me know how I should proceed here.

**Comment by vzarytovskii** [comment]
> I've rechecked this fix without https://github.com/dotnet/fsharp/pull/15909 applied, and it turns out the errors aren't hidden and are properly reported via a diagnostic:
> 
> Screenshot 2023-09-01 at 10 14 18
> 
> Please note, that the rest of the analysis has also managed to finish, as can be seen from the highlighted identifiers.
> 
> With this info, I'd vote for a better exception logging (so the stacktraces are available somewhere) and not rethrowing the exception, at least by default. @vzarytovskii Please let me know how I should proceed here.

Yeah, not rethrowing is correct thing to do.

**Review by abonie — APPROVED** [review]

**Comment by auduchinok** [comment]
I've added `InternalException` for wrapping a system exceptions and capturing their stacktraces. These exceptions get logged via `Debug.Trace` and show tooltip with the 'internal error' and exception message in both Release/Debug.

**Review by psfinaki — APPROVED** [review]

**Review by T-Gro — APPROVED** [review]

**Pull request merged**
