### PR TITLE
move BuildGraph to Facilities

### PR DESCRIPTION
**Pull request by dsyme**
Identified in the cleanup session last night, this is a more logical place for this - it's compiler specific but quite independent of most of the logic of the compiler

### CODE REVIEW

**Comment by dsyme** [comment]
@dotnet-bot test Build EndToEndBuildTests please

**Comment by dsyme** [comment]
@dotnet-bot test fsharp-ci (Build EndToEndBuildTests)  please

**Comment by dsyme** [comment]
Something very strange is going on with CI - I can't seem to get it to re-run cleanly after a transient failure

@vzarytovskii @KevinRansom @brettfo  Do we have a "dotnet-bot" or anything to use to re-run CI jobs?

**Comment by dsyme** [comment]
cool, thanks @brettfo!  Are there docs for that somewhere?

**Comment by brettfo** [comment]
Not that I'm aware of, I got lucky and remembered it from somewhere else.

**Review by vzarytovskii — APPROVED** [review]

**Pull request merged**
