### PR TITLE
Minor feature cleanup

### PR DESCRIPTION
**Pull request by brianrourkeboll**
## Description

#17067 removed the calls to `Array.map` and `List.map` added in #16948 and replaced them with direct emission of loops.

- Rename `LowerSimpleMappingsInComprehensionsToDirectCallsToMap` → `LowerSimpleMappingsInComprehensionsToFastLoops`.
- Remove the values added in #16948 to support calling `List.map` and `Array.map`.

## Checklist

- Release notes entry (N/A).

### CODE REVIEW

**Review by KevinRansom — APPROVED** [review]

**Review by edgarfgp — APPROVED** [review]

**Comment by psfinaki** [comment]
@brianrourkeboll thanks for keeping things tidy. You can probably remove the release notes here since those are internal changes, I added the label to suppress the release note gate.

**Review by psfinaki — APPROVED** [review]
Thanks. We'll merge this once .NET9 update is in.

**Comment by brianrourkeboll** [comment]
@psfinaki It looks like the CI stalled again :(

**Pull request merged**
