### PR TITLE
Revert parameterized product version and update version numbers

### PR DESCRIPTION
**Pull request by brettfo**
PR #8031 broke `VisualFSharpFull.vsix` in two ways:

  - `RegisterFsharpPackage.pkgdef` is no longer in the VSIX.
  - `manifest.json` contains an invalid path to the expected `.pkgdef`.

Given that we're close to shutting down the `release/dev16.5` branch I've reverted the original PR and updated the hard-coded version numbers to be correct.  Once we're not in a time crunch this change can be revisited.

### CODE REVIEW

**Comment by KevinRansom** [comment]
I am confused about registerpackagedef though

**Comment by KevinRansom** [comment]
@brettfo, I just built master on my machine, and it was correct.
RegisterPackage.pkgdef was there
and the manifest.json was correctly specified.
Would you mind if I took a look at the issue where you see it?

Thanks

Kevin

**Comment by KevinRansom** [comment]
Okay I see it, I'll work on a fix in parallel.

**Comment by KevinRansom** [comment]
@brettfo , I have a fix here: https://github.com/dotnet/fsharp/pull/8126

**Comment by brettfo** [comment]
Closing in favor of #8126.

**Pull request closed without merging**
