### PR TITLE
LOC CHECKING 20200709

### PR DESCRIPTION
**Pull request by cristianosuzuki77**

### CODE REVIEW

**Comment by wli3** [comment]
@cartermp could you help me merge it and make sure it will be part of a later insertion to 16.7?

**Comment by cartermp** [comment]
cc @brettfo @jonsequitur 

This is now merged, but I'm not sure how this finds its way into VS

**Comment by wli3** [comment]
@brettfo @jonsequitur ?

**Comment by brettfo** [comment]
Created #9673 which will ensure it gets into VS.

**Pull request merged**
