### PR TITLE
Get rid of couple more tryFind

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by KevinRansom** [comment]
@TIHan , when this code was originally written ValueOption wasn't available to the author.  There is a decent chance that if it had been available the author would have used it.   Certainly a fair amount of new code uses ValueOption rather than option.  I can't prove that this code is an improvement my intuition is that any improvement is slight.  However, one of the Jit developers once told me that  "if you are going do performance you are going to have learn to accept that any improvement you make is likely to be tiny, and only over time are they really noticeable.".

To the best of my ability I believe these changes don't break anything, and they may have a small positive benefit, so I would prefer to take the change rather than leave it on the table.

**Comment by KevinRansom** [comment]
> The TryFind are ok, but I don't see any value in peppering the codebase with `ValueSome`

@dsyme,
Having a non allocating Option type is quite Valuable for examples like this where creating an object, to immediately throw it away again one or two stack frames later.  Are you suggesting that it is not helpful to liberally use ValueOption in these circumstances?

And as an aside, this pattern of use of TryGetValue, is so much nicer than the C# use, that it looks as if TryGetValue was designed for F#, not C#, where it is hideously ugly.

**Comment by dsyme** [comment]
> Having a non allocating Option type is quite Valuable for examples like this where creating an object, to immediately throw it away again one or two stack frames later. Are you suggesting that it is not helpful to liberally use ValueOption in these circumstances?

I tend to look around and think "hey, are there many allocations around about, and is this high perf code, and if so don't bother with ValueSome and ValueNone"

As I scanned on code review I looked at the code and there are just zillions of tuples, lists, arrays, whatever around about.

**Comment by KevinRansom** [comment]
> As I scanned on code review I looked at the code and there are just zillions of tuples, lists, arrays, whatever around about.

I agree that is a good heuristic, however.  Is your objection to ValueSome because it is not "Some" or is it because a reference return is the right thing to do?  If it is because it is not the "good name" would it be useful to think about how we might fix that, I have no suggestions for how to fix it, but is it even useful to try?

**Comment by KevinRansom** [comment]
@forki , @dsyme , @TIHan , Don has great point about the ValueSome, but that places us in a tricky situation.
I almost never use ValueOption or struct tuples in real code because I also prefer "the good name".  However, opportunistic teeny tiny pickups like those represented by Steffen's two PR's are going to push us into having to re-decide this every time.  I'm going to raise a Language suggestion that will encourage us to look for a solution to this issue.

However, in the mean time we still have the pressure to reduce allocations, and yet right idiomatic non confusing code.

How are we going to resolve this?
1.  Stop accepting struct tuples and ValueOptions on high allocation code paths until we have a syntax that makes them less ugly?
2.  Continue to accept minor ValueOption and struct tuple improvements with the expectation that we may be able to improve and correct the syntax in the future?

I am particularly keen to here what Steffen has to say about this, given that he is the most active on these kind of opportunistic 'improvements'.

**Comment by KevinRansom** [comment]
FYI: https://github.com/fsharp/fslang-suggestions/issues/874

**Comment by KevinRansom** [comment]
@dsyme ,

should I close this PR, and also #9273.  It doesn't seem as if we can currently benefit from eliminating the allocations and yet not "pepperthe code with ValueSome" and should we also now consider a coding / reviewing guideline to ensure that "use of valueoption be limited to where it is necessary.  For some subjective definition of necessary?

**Comment by KevinRansom** [comment]
@forki ,
thanks for this PR, I am closing this because despite the probable benefit of eliminating a few allocations, it does sit in an allocation heavy part of the codebase and so the benefits will likely be drowned out by other allocation noise.  I think once we have added some sugar to make value options less jarring to use we can revisit these types of opportunistic optimizations.

Thanks again for this and all of your other work that benefits F#

Kevin

**Pull request closed without merging**
