### PR TITLE
Deploy FSharp.Core.xml in our IDE package

### PR DESCRIPTION
**Pull request by cartermp**
fixes https://github.com/dotnet/fsharp/issues/2926 hopefully?

### CODE REVIEW

**Review by KevinRansom — APPROVED** [review]

**Comment by cartermp** [comment]
Just to clarify, if I move the xml file in the directory that I _think_ does setup definitions for, I get XML docs for FSharp.Core. So I know that works, it's just a question of if this is the correct fix

**Comment by brettfo** [comment]
This change is the same as placing that XML file locally at `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\FSharp\FSharp.Core.xml`, so if that manual step does what you want, then this will do what you want, too.

**Comment by cartermp** [comment]
Yep, that's totes what I want. Here's the difference.

Before:

image


After:

image

My font is larger and different than the default btw

**Comment by dsyme** [comment]
Thank you for fixing this!

**Pull request merged**
