### PR TITLE
Adding ValRepInfoForDisplay for quick info for functions defined in expressions

### LINKED ISSUE #7080: Intellisense tooltip for local functions should show argument names
**Is your feature request related to a problem? Please describe.**
A function defined globally has its argument names shown in Intellisense tooltip, but not for functions in functions.

image
image

**Describe the solution you'd like**
Argument names should appear for functions in functions.

**Describe alternatives you've considered**
Nah

**Additional context**
Nope

### PR DESCRIPTION
**Pull request by psfinaki**
fixes #7080 

So this address the final set of cases with let binding tooltips, like this one:
image

### CODE REVIEW

**Comment by psfinaki** [comment]
@auduchinok please also take a look, for some reason cannot request a review from you.

**Review by KevinRansom — APPROVED** [review]

**Comment by auduchinok** [comment]
> @auduchinok please also take a look

Done. :)

> for some reason cannot request a review from you.

It's likely it's because I'm not in the dotnet organization, but feel free to ping me, I'm happy to take a look or to help where possible.

**Comment by dsyme** [comment]
> @psfinaki Could [FSharpMemberOrFunctionOrValue.CurriedParameterGroups](https://github.com/dotnet/fsharp/blob/main/src/Compiler/Symbols/Symbols.fs#L2017) also use this info? FSharpSymbol API is what editor tools use when they work with symbols directly.
 It could probably be good to add some tests for CurriedParameterGroups and https://github.com/dotnet/fsharp/pull/13429#issuecomment-1172384926 too?

I think do this in a separate PR - this is partly a learning exercise for @psfinaki and will be good to get the specific improvement in the bag.

I don't think there will be any downsides to doing it but might be tricky to make sure it doesn't have other effects.

**Comment by psfinaki** [comment]
@KevinRansom @auduchinok alright, so I'll merge this and will do a followup for your suggestions.

**Comment by auduchinok** [comment]
@psfinaki It's in [SignatureHelp.fs](https://github.com/dotnet/fsharp/blob/main/vsintegration/src/FSharp.Editor/Completion/SignatureHelp.fs). Btw, it has examples of how `CurriedParameterGroups` property is used in features.

**Comment by auduchinok** [comment]
@psfinaki Hi, are you still going to work on `CurriedParameterGroups`?

**Pull request merged**
