### PR TITLE
Fcs.38.0.2 -- include nuget package manager in fcs

### PR DESCRIPTION
**Pull request by KevinRansom**
Cherry pick the nuget pm pr into fcs branch

### CODE REVIEW

**Comment by cartermp** [comment]
@baronfel does this loom like the right package layout?

**Comment by baronfel** [comment]
Looks good to me, yeah. One thing I note that is slightly concerning is the change in listed dependencies for .net standard 2.0 between 38 (https://www.nuget.org/packages/FSharp.Compiler.Service/38.0.0) and 38.0.1 (https://www.nuget.org/packages/FSharp.Compiler.Service/38.0.1).  Is that concerning to either of you?

**Comment by cartermp** [comment]
I believe this is to account for the references that FSi needs for .NET 5 as per @dsyme's work to allow unblocking fsharp.formatting

**Comment by KevinRansom** [comment]
We got the dependencies wrong in 38.0.0, if you recall, msbuild was a dependency issue the change beween 38.0.0 and 38.0.1 was to specify the correct dependencies per what we use to build.
These were the dependencies for netstandard2.0 in 37.0.0  Which are broadly speaking similar to the dependencies in 38.0.1
````
      <group targetFramework=".NETStandard2.0">
        <dependency id="FSharp.Core" version="4.6.2" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Build.Framework" version="16.6.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Build.Tasks.Core" version="16.6.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Build.Utilities.Core" version="16.6.0" exclude="Build,Analyzers" />
        <dependency id="System.Buffers" version="4.5.0" exclude="Build,Analyzers" />
        <dependency id="System.Collections.Immutable" version="1.5.0" exclude="Build,Analyzers" />
        <dependency id="System.Memory" version="4.5.3" exclude="Build,Analyzers" />
        <dependency id="System.Reflection.Emit" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Reflection.Metadata" version="1.6.0" exclude="Build,Analyzers" />
        <dependency id="System.Reflection.TypeExtensions" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Runtime.Loader" version="4.0.0" exclude="Build,Analyzers" />
      </group>
````
38.0.1
````
      <group targetFramework=".NETStandard2.0">
        <dependency id="FSharp.Core" version="[5.0.0, 5.0.0]" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Build.Framework" version="16.6.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Build.Tasks.Core" version="16.6.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Build.Utilities.Core" version="16.6.0" exclude="Build,Analyzers" />
        <dependency id="System.Buffers" version="4.5.1" exclude="Build,Analyzers" />
        <dependency id="System.Collections.Immutable" version="1.5.0" exclude="Build,Analyzers" />
        <dependency id="System.Diagnostics.Process" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Diagnostics.TraceSource" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Linq.Expressions" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Linq.Queryable" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Memory" version="4.5.4" exclude="Build,Analyzers" />
        <dependency id="System.Net.Requests" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Net.Security" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Reflection.Emit" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Reflection.Metadata" version="1.6.0" exclude="Build,Analyzers" />
        <dependency id="System.Reflection.TypeExtensions" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Runtime" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Runtime.InteropServices" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Runtime.Loader" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Security.Claims" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Security.Cryptography.Algorithms" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Security.Principal" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Threading.Tasks.Parallel" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Threading.Thread" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Threading.ThreadPool" version="4.3.0" exclude="Build,Analyzers" />
      </group>
````
I will review the dependencies in main to see if any are not actually necessary, which is possible, but I am satisfied this is correct enough.  I hope that helps.

**Comment by baronfel** [comment]
Thanks for checking :)

**Review by cartermp — APPROVED** [review]
Approved pending your check to make sure the dependencies are right relative to `main`

**Comment by KevinRansom** [comment]
If I tell the build to generate a nuspec this is what I get: the only difference being:
    FSharp.DependencyManager.Nuget, which is of course deployed within the package in our manual nuspec build.
````
    <dependencies>
      <group targetFramework=".NETStandard2.0">
        <dependency id="FSharp.Core" version="[5.0.0, 5.0.0]" exclude="Build,Analyzers" />
        <dependency id="FSharp.DependencyManager.Nuget" version="5.0.0-dev" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Build.Framework" version="16.6.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Build.Tasks.Core" version="16.6.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Build.Utilities.Core" version="16.6.0" exclude="Build,Analyzers" />
        <dependency id="System.Buffers" version="4.5.1" exclude="Build,Analyzers" />
        <dependency id="System.Collections.Immutable" version="1.5.0" exclude="Build,Analyzers" />
        <dependency id="System.Diagnostics.Process" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Diagnostics.TraceSource" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Linq.Expressions" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Linq.Queryable" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Memory" version="4.5.4" exclude="Build,Analyzers" />
        <dependency id="System.Net.Requests" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Net.Security" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Reflection.Emit" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Reflection.Metadata" version="1.6.0" exclude="Build,Analyzers" />
        <dependency id="System.Reflection.TypeExtensions" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Runtime" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Runtime.InteropServices" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Runtime.Loader" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Security.Claims" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Security.Cryptography.Algorithms" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Security.Principal" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Threading.Tasks.Parallel" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Threading.Thread" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Threading.ThreadPool" version="4.3.0" exclude="Build,Analyzers" />
      </group>
    </dependencies>
````

**Comment by KevinRansom** [comment]
Published:  https://www.nuget.org/packages/FSharp.Compiler.Service/38.0.2

**Comment by cartermp** [comment]
Yeet

**Pull request merged**
