### PR TITLE
Updated documentation link to Parallel.For

### PR DESCRIPTION
**Pull request by nikofeyn**
See #10652.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=10655) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=10655) before we can accept your contribution.<br/><br/>:x: nikofeyn [sign now](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=10655)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/fsharp?pullRequest=10655) it.</sub>

**Review by KevinRansom — APPROVED** [review]
Thank you for taking care of this.

Kevin

**Comment by KevinRansom** [comment]
@nikofeyn , please could you take a look at and if you agree sign the [ Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=10655)

**Review by cartermp — APPROVED** [review]
Thanks!

**Pull request merged**
