### PR TITLE
Update to new inline rename Roslyn APIs

### PR DESCRIPTION
**Pull request by tmat**
Depends on 
- [x] https://github.com/dotnet/roslyn/pull/58381.

### CODE REVIEW

**Review by KevinRansom — APPROVED** [review]
Looks good.

**Comment by KevinRansom** [comment]
I will cherry pick this back into main too.

**Comment by tmat** [comment]
When do you plan the next insertion to VS?

**Comment by KevinRansom** [comment]
Not going back to main: [1:38 PM] Kevin Ransom
No I won't it relies on updated Visual Studio contracts.  It can wait until we release 17.2 to come back down.

**Comment by KevinRansom** [comment]
They are automatic, unless there is a build or test issue.

**Pull request merged**
