### PR TITLE
Remove unnecessary info from enum in FSI

### LINKED ISSUE #12127: F# Interactive displays enums unnecessarily verbosely.
On .NET 6 SDK Preview 7, .NET SDK 5.0.400 and .NET Core SDK 3.1.412, writing something like

```
System.Char.GetUnicodeCategory 'a';;
```

will display

```
val it : System.Globalization.UnicodeCategory = LowercaseLetter {value__ = 1;}
```

while it could display

```
val it : System.Globalization.UnicodeCategory = LowercaseLetter
```

I persume it is a side-effect of #5002. It does not happen when using `sprintf "%A"`.

### PR DESCRIPTION
**Pull request by joshuapassos**
Resolves #12127

### CODE REVIEW

**Comment by dsyme** [comment]
Looks good.  Can you add a test? Add it in `tests\fsharp\core\printing` - add it at the end, and you will need to update the baselines.  Just evaluating `System.DayOfWeek.Monday` should do

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=12321) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=12321) before we can accept your contribution.<br/><br/>:x: joshuapassos [sign now](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=12321)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/fsharp?pullRequest=12321) it.</sub>

**Comment by joshuapassos** [comment]
> Looks good.  Can you add a test please? Add it in `tests\fsharp\core\printing` - add it at the end, and you will need to update the baselines.  Just evaluating `System.DayOfWeek.Monday` should do

Done

**Review by dsyme — APPROVED** [review]

**Comment by dsyme** [comment]
Thank you for your contribution!

**Pull request merged**
