### PR TITLE
Use static field to avoid reallocating closures with empty environments

### PR DESCRIPTION
**Pull request by dsyme**
This is a long standing request to use a static field to avoid reallocating closures that have empty environments.  It honestly should have been done in F# 0.1 Some perf tests should be done but it's hard to see this being problematic

Test baselines will need updating

The change only applies to function closures and not delegates, object expressions nor sequence closures, nor async expressions (which the programmer may think of as a single closure object).

### CODE REVIEW

**Comment by dsyme** [comment]
Relates to https://github.com/fsharp/fslang-suggestions/issues/917 though that also covers some other sins

**Comment by dsyme** [comment]
If anyone has a benchmark that has suffered from the problem please let me know.  Micro-benchmarks are easy enough to create.

**Comment by dsyme** [comment]
To take a pathalogical case, this runs 2x as fast now:
```
let mutable a = 0
let mutable res = 0

let f () = a <- a + 1; (fun x -> x + 1)

let g() = 
   for i in 0 .. 10000 do
      for j in 0 .. i do
        res <- f() res

let sw = System.Diagnostics.Stopwatch()
sw.Start()
g()
sw.Stop()

printfn "a = {%A}, res = {%A}, time = %A" a res sw.Elapsed
```

**Comment by dsyme** [comment]
This is ready

**Review by TIHan — APPROVED** [review]
Fantastic

**Review by vzarytovskii — APPROVED** [review]

**Comment by cartermp** [comment]
@dsyme should there be an RFC for this? Since it's technically an optimization I think it's not necessary. But it might be good to document some of the behavior in the compiler guide: https://github.com/dotnet/fsharp/blob/main/docs/compiler-guide.md

**Comment by cartermp** [comment]
Specifically, the guide refers to some things that may need to be checked now, such as this: https://github.com/dotnet/fsharp/blob/main/docs/compiler-guide.md#potential-future-optimizations-better-inlining

**Comment by kerams** [comment]
> The change only applies to function closures and not delegates, object expressions nor sequence closures, nor async expressions

> Relates to fsharp/fslang-suggestions#917 though that also covers some other sins

https://github.com/fsharp/fslang-suggestions/issues/910 requested this exact thing though, right?

**Comment by kerams** [comment]
Thinking wildly here, would it be safe to also use a static instance for closures WITH free variables provided that they're all immutable **module** let-bound values (i.e. the references stay the same during the lifetime of the process)? A trivial example:

```fsharp
module CompositionRoot =
    let getEmptySpacesInRoom id = 2

let isAnyRoomNotFull: HttpHandler =
    fun (next: HttpFunc) (ctx: HttpContext) ->
        let! ids = ctx.BindModelAsync<int list>()
        let res = ids |> List.exists (fun x -> getEmptySpacesInRoom x > 0) // <-- no need to instantiate this closure every time
        return! json res next ctx
```

If there's no glaring flaw allowing you to shoot this down immediatelly, I could create an fslang suggestion.

**Pull request merged**
