### PR TITLE
Printing updates

### PR DESCRIPTION
**Pull request by dsyme**
This updates signature printing to print in ways that are consistent with [the F# style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/)

* [x] https://github.com/dotnet/fsharp/issues/12090

* [x] https://github.com/dotnet/fsharp/issues/12089

* [x] https://github.com/dotnet/fsharp/issues/12088

* [x] https://github.com/dotnet/fsharp/issues/12091

* [x] https://github.com/dotnet/fsharp/issues/12092

* [x] https://github.com/dotnet/fsharp/issues/12093

* [x] https://github.com/dotnet/fsharp/issues/12094

* [x] Format multi-line curried signatures according to the preferred style guide proposal https://github.com/dotnet/docs/issues/25917

* [x] This part of https://github.com/dotnet/fsharp/issues/393#issuecomment-640220707

* [x] Another part of https://github.com/dotnet/fsharp/issues/393#issuecomment-848890987

* [x] https://github.com/dotnet/fsharp/issues/11523 (see [sample for System.Char generation](https://gist.github.com/dsyme/cc9ec431222e7a12f6813f180bf06cc9))

  
* [x] https://github.com/dotnet/fsharp/issues/11524

FCS change:

* `symbol.DisplayName` will now include backticks when they are necessary to make the name a valid identifier. For example previously a symbol with logical name `A-B` would give `( A-B )` as the display name, which is not valid F# identifier text. Instead ``` ``A-B`` ``` will be returned by `symbol.DisplayName`.  

Also cleanup:

* [x] Rename some things internally `TRecdRepr` --> `TFSharpRecdRepr` etc. to make it clear they only apply to F#-declared things.  This can help when reading code, and also as we increase interop with C# records etc.

Some tests to update but all routine.

* [x] get it green

### CODE REVIEW

**Comment by dsyme** [comment]
@KevinRansom @TIHan @vzarytovskii This is ready

However we should first get https://github.com/dotnet/fsharp/pull/12047 in and then I'll integrate (it will take a bit of work)

**Comment by dsyme** [comment]
This needs one fix - the Declaration lists now contain ``ABC DEF`` entries, which is not what we want, e.g.

Before:  

image

After:

image

**Comment by dsyme** [comment]
@TIHan This is ready (assuming it goes green)

**Comment by dsyme** [comment]
@TIHan ready! :)

**Review by TIHan — APPROVED** [review]
This is a large change right before imminent release, but the changes here are really just printing improvements and other minor refactorings. Looks good and excited to see how signature generation has improved :) , as well as tooltips.

**Pull request merged**
