### PR TITLE
Enable warnings for FS1178

### PR DESCRIPTION
**Pull request by nojaf**
## Description

Turns out a lot of things aren't Comparable or support Equality when turning on `FS1178`.

Fixes # (issue, if applicable)

## Checklist

- [ ] Test cases added
- [ ] Performance benchmarks added in case of performance changes
- [ ] Release notes entry updated:
    > Please make sure to add an entry with short succint description of the change as well as link to this pull request to the respective release notes file, if applicable.
    >
    > Release notes files:
    > - If anything under `src/Compiler` has been changed, please make sure to make an entry in `docs/release-notes/FSharp.Compiler.Service/<version>.md`, where `<version>` is usually "highest" one, e.g. `42.8.200`
    > - If language feature was added (i.e. `LanguageFeatures.fsi` was changed), please add it to `docs/releae-notes/Language/preview.md`
    > - If a change to `FSharp.Core` was made, please make sure to edit `docs/release-notes/FSharp.Core/<version>.md` where version is "highest" one, e.g. `8.0.200`.

    > Examples of release notes entries:
    > - Respect line limit in quick info popup - https://github.com/dotnet/fsharp/pull/16208
    > - More inlines for Result module - https://github.com/dotnet/fsharp/pull/16106
    > - Miscellaneous fixes to parens analysis - https://github.com/dotnet/fsharp/pull/16262
    >

    > **If you believe that release notes are not necessary for this PR, please add `NO_RELEASE_NOTES` label to the pull request.**

### CODE REVIEW

**Comment by psfinaki** [comment]
That looks promising! :) Why not keep WarnOn in the project files btw?

**Comment by nojaf** [comment]
The `pars.fsy` files generate a type which also requires the attributes. 
This made the build fail because of warnings as errors.
FsYacc would need to support the generation of the attributes first.

**Review by edgarfgp — APPROVED** [review]

**Comment by vzarytovskii** [comment]
@T-Gro will this interfere with your nullable work a lot? Shall we postpone it?

**Comment by T-Gro** [comment]
I do not see this creating bugs, rather syntactical pain.

@nojaf : Did you use any tooling/scripting to make this PR?
This will need to be re-applied when merging this into the feature/nullness branch.

**Comment by nojaf** [comment]
> @nojaf : Did you use any tooling/scripting to make this PR?

No, I just enabled the flag and followed the warnings generated by the IDE.
You technically won't need to do this in the nullness branch, as the flag was removed.
The reason for that is that `lex/yacc` generated files contain generated types where the attribute is missing.

**Pull request closed without merging**
