### PR TITLE
Add note on .NET Core 3 SDK version

### PR DESCRIPTION
**Pull request by realvictorprm**

### CODE REVIEW

**Comment by realvictorprm** [comment]
I think by any means it shouldn't be a big deal to be a couple minor versions above the SDK version currently in there.

@cartermp any comments?

**Comment by KevinRansom** [comment]
@cartermp is correct.  It is actually pretty rubbish that the user may have to install any dotnet cli to make things work.  But that is how the current engineering build system works.  Hopefully that will get fixed.

**Comment by forki** [comment]
@kevinransom the build already downloads the correct version - it just doesn't use it and requires the additional global install

**Comment by cartermp** [comment]
> But that is how the current engineering build system works. Hopefully that will get fixed.

This I think we really ought to clarify. If there's something in the build system that regresses developer experiences like requiring a global install (which is weird given how the SDK works), we need to push to get that fixed.

**Comment by forki** [comment]
I reported that behavior a month ago.
https://github.com/dotnet/fsharp/issues/6819 - there were other issues
reported there as well. But since then I reinstalled windows and everything
from scratch so that I can build again. Only thing left is that we need
global installation.

Phillip Carter <notifications@github.com> schrieb am Mo., 1. Juli 2019,
08:09:

**Pull request closed without merging**
