### PR TITLE
Additional intrinsics for the NativePtr module

### PR DESCRIPTION
**Pull request by Happypig375**
RFC https://github.com/fsharp/fslang-design/blob/main/RFCs/FS-1109-Additional-intrinsics-for-the-NativePtr-module.md

https://github.com/fsharp/fslang-suggestions/issues/200

### CODE REVIEW

**Comment by dsyme** [comment]
@Happypig375 Where is this at w.r.t. completness, and the RFC?

**Comment by Happypig375** [comment]
Just missing the RFC, writing now.

**Comment by Happypig375** [comment]
https://github.com/fsharp/fslang-design/pull/604

**Comment by dsyme** [comment]
@KevinRansom This looks good to me.  Do we want "Experimental this is preview" attributes on the additions to FSharp.Core? Thanks

**Review by dsyme — APPROVED** [review]

**Comment by dsyme** [comment]
@vzarytovskii Approved subject to @KevinRansom 's opinion on whether we need the "this is in preview" library attributes.

**Comment by KevinRansom** [comment]
No I think the preview attributes are not necessary.  The APIs are not likely to change, they don't support a specific language feature and Dev 17.0 is the target for main anyway.

**Review by KevinRansom — APPROVED** [review]
This looks great

**Comment by dsyme** [comment]
Cool thank you!  So we have our first F# 5.1 (or F# 6.0 or whatever) feature :)

**Comment by dsyme** [comment]
Thank you @Happypig375 :)

**Comment by KevinRansom** [comment]
5.1 I think.

**Pull request merged**
