### PR TITLE
Removing CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by cartermp**
I think this document is outdated and duplicating too much information at this point. I also think most people don't read it or know it even exists. In an effort to simplify the amount of documents we either explicitly or implicitly expect people to read, I think this can be removed.

### CODE REVIEW

**Comment by tannergooding** [comment]
@cartermp, this should be fine provided the guidelines are in the `README.md` instead.

I can send you a link to the guidance (which is internal), but it currently states the following as being "required".
> The process for contributing is clearly documented in the README.md or CONTRIBUTING.md.

**Comment by cartermp** [comment]
@tannergooding We provide a quickstart in the README and link to the DEVGUIDE.md file that contains all the relevant information about developing various parts of the repo.

**Comment by voronoipotato** [comment]
I propose renaming DEVGUIDE.md to CONTRIBUTING.md as Contributing.md is a pattern across many repos, and devguide is a not so great name.

**Comment by voronoipotato** [comment]
Contributing.md seems to be a much more consistent pattern in development repos, perhaps we should rename DEVGUIDE.md to CONTRIBUTING.md

**Comment by voronoipotato** [comment]
### CLA	

 Contributors are required to sign a [Contribution License Agreement](https://cla.microsoft.com/) (CLA) before any pull requests will be considered. After submitting a request via the provided form, electronically sign the CLA when you receive the email containing the link to the document. This only needs to be done once for each Microsoft OSS project you contribute to.	

### Coding guidelines	

 Although there is currently no strict set of coding or style guidelines, use common sense when contributing code - make an effort to use a similar style to nearby existing code. If you have a passion for helping us develop a set of coding guidelines that we can roll out and apply within this project, get involved and start a discussion issue.

https://github.com/adriennefriend/imposter-syndrome-disclaimer

may also be valuable.

**Pull request merged**
