### PR TITLE
Remove SynSimplePats.Typed

### PR DESCRIPTION
**Pull request by nojaf**
I don't really see how `SynSimplePats.Typed` can ever be created, so I'd like to see what happens if it were gone.

### CODE REVIEW

**Comment by kerams** [comment]
https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWTwCuyYAFImwoALgEowAWgB8YciAC%2BQA

**Comment by nojaf** [comment]
I don't think so, that is a `SynSimplePats.SimplePats(SynSimplePat.Typed _, _)`

**Comment by auduchinok** [comment]
I may be mistaken, but I thought it was created here:

https://github.com/dotnet/fsharp/blob/beffcf6be077441df2550de3a580a9e3bdb6264a/src/Compiler/SyntaxTree/SyntaxTreeOps.fs#L300-L306

**Review by auduchinok — APPROVED** [review]

**Review by T-Gro — APPROVED** [review]

**Comment by vzarytovskii** [comment]
Did you also look at the possibility of `let (i: int: int: int) = 4`?

**Review by 0101 — APPROVED** [review]

**Review by edgarfgp — APPROVED** [review]

**Pull request merged**
