### PR TITLE
Arcade update + changes that should allow the "release/devXY.Z"  branches

### PR DESCRIPTION
**Pull request by MattGal**
Part of https://github.com/dotnet/arcade/issues/10578.  This should be integrate-able to branches like release/dev17**.x** and cause it to pick the correct pool provider automatically.

### CODE REVIEW

**Comment by vzarytovskii** [comment]
@MattGal do we need to backport it further to 17.2 and lower?

**Comment by vzarytovskii** [comment]
Ok, it seems it's not as easy.

**Review by T-Gro — APPROVED** [review]

**Review by vzarytovskii — APPROVED** [review]

**Pull request merged**
