### PR TITLE
Include range of parameter names and attributes in topTupleType SynType.Tuple

### PR DESCRIPTION
**Pull request by nojaf**
Fixes https://github.com/dotnet/fsharp/issues/13848

### CODE REVIEW

**Review by dsyme — APPROVED** [review]

**Comment by nojaf** [comment]
This is still fixed after taking in https://github.com/dotnet/fsharp/pull/13879

**Comment by dsyme** [comment]
@nojaf So we take these tests?  That's fine, thanks!

**Comment by nojaf** [comment]
Yes, please 😊.

**Review by T-Gro — APPROVED** [review]

**Review by T-Gro — DISMISSED** [review]

**Review by vzarytovskii — APPROVED** [review]

**Review by psfinaki — APPROVED** [review]

**Pull request merged**
