### PR TITLE
Infer isreadonly from structs ("readonly struct" in C#) to avoid struct-copies just like we do with readonly methods

### PR DESCRIPTION
**Pull request by T-Gro**
In C#, [Readonly]can be applied both on method level as well as struct level.
When [Readonly] is on entire struct, typically via "readonly struct" definition, semantically it is equivalent to having [Readonly] on every method. However, F# only reads [Readonly] at method level at the moment.

This PR changes the behaviour of IlMethodyInfo.IsReadOnly to also detect [Readonly] on struct level.
That way, the MethodCall will be understood by F# compiler as 'NeverMutates' and therefore enable performance optimization by avoiding copies.

### CODE REVIEW

**Comment by vzarytovskii** [comment]
Wondering if this has to go under a feature flag, since technically it may change the codegen.

**Comment by T-Gro** [comment]
> 

I consider it more of a fix. Basically the current way does not fully understand what Roslyn can do with respect to the "readonly" keyword and possible placement of [ReadOnly] attribute.

See example here - even placement of readonly keyword at the method level (which existing code is supposed to support) gets overriden by readonly on struct level, and therefore method does not get the [ReadOnly] by Roslyn.

image

**Comment by kerams** [comment]
Wouldn't IL tests be more reliable? The warning could theoretically be broken, independent of whether or not the defense copy is emitted.

**Comment by T-Gro** [comment]
> 

This was the only part of the test suite that failed when adding this feature, that is why considered it.
You mean searching IL output and scanning that there was no copy instruction at all?
Or comparing strict equality of the entire generated IL?

**Comment by kerams** [comment]
Just something simple like https://github.com/dotnet/fsharp/blob/main/tests/FSharp.Compiler.ComponentTests/EmittedIL/EmptyArray.fs, to show the instruction is present when expected, and missing when dealing with readonly structs.

**Comment by T-Gro** [comment]
> Just something simple like https://github.com/dotnet/fsharp/blob/main/tests/FSharp.Compiler.ComponentTests/EmittedIL/EmptyArray.fs, to show the instruction is present when expected, and missing when dealing with readonly structs.

Thanks, this is the way.

**Review by dsyme — APPROVED** [review]

**Comment by dsyme** [comment]
I do agree this can count as a bug fix

Could you add test cases for extension methods on readonly structs please?

**Review by vzarytovskii — APPROVED** [review]

**Pull request merged**
