### PR TITLE
Fix test discovery in VS for this repo

### PR DESCRIPTION
**Pull request by majocha**
Fix the problem #16280, [as advised](https://developercommunity.visualstudio.com/t/Test-discovery-aborted-Could-not-find-t/10512939#T-N10516182)
Thanks to Jakub Jares from MSFT.

### CODE REVIEW

**Review by T-Gro — APPROVED** [review]

**Review by 0101 — APPROVED** [review]

**Comment by psfinaki** [comment]
Hmm @brianrourkeboll looks like one of the recent parens tests is failing here - do you have any idea what can be happening? I can just temporarily disable it if you don't have time.

**Comment by brianrourkeboll** [comment]
Hmm @psfinaki I'll take a look. You can go ahead and disable it if you want to merge this now.

**Comment by brianrourkeboll** [comment]
@psfinaki #16285.

**Comment by psfinaki** [comment]
Thanks @brianrourkeboll :) merged, I will update the PRs with failing CI now.

**Pull request merged**
