### PR TITLE
[BLOCKED] Visual Studio implementation of Inline Hints

### PR DESCRIPTION
**Pull request by baronfel**
This is the second PR for the Inline Hints feature (the first is [here](https://github.com/dotnet/fsharp/pull/12927)). It contains only the Visual Studio changes, updated to the latest compiler main branch.  No other changes have been made.

Per https://github.com/dotnet/fsharp/pull/10295, the following changes still need to be made:

* [ ] Setting to respect key binding
* [ ] Setting for colors
* [ ] Setting for type hints
* [ ] Setting for parameter name hints

### CODE REVIEW

**Comment by dsyme** [comment]
What are the ergonomics of this?  Is there a key combination to show the hints?  Or are they on by default?

Thanks!

**Comment by dsyme** [comment]
I merged in main so reduce the apparent diff

**Comment by baronfel** [comment]
We'd need to hook up options - maybe something from [Roslyn](https://github.com/dotnet/roslyn/tree/bab9471d4b0dc3ec9dbcb5695c967b5fd7f563f9/src/EditorFeatures/Core.Wpf/InlineHints) would help as a pattern?

**Comment by vzarytovskii** [comment]
@baronfel we, perhaps, can take care of this as part of our lens work by @psfinaki 
I will, for the time being, convert it to draft.

**Comment by psfinaki** [comment]
@vzarytovskii this is a good start and the right way to go. But I'll rather somewhat incorporate this into my changes I'm working on, then will probably close this one.

**Pull request closed without merging**
