### PR TITLE
Implement feature #6783: new --version option

### PR DESCRIPTION
**Pull request by VTJDailey**
Issue #6783 

* Removed deprecated --version option on fsc.exe
* Added shared --version option for fsc.exe and fsi.exe
* Added English output for the new option on --help

All of the .xlf file changes were done by the build.

Never really done a pull request before, so please let me know if I've done something wrong.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=10099) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=10099) before we can accept your contribution.<br/><br/>:x: VTJDailey [sign now](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=10099)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/fsharp?pullRequest=10099) it.</sub>

**Review by KevinRansom — CHANGES_REQUESTED** [review]
Thank you for this contribution and welcome to the team :-)

1.  Please don't remove the deprecated version.
     The ability to specify a new version with a quick command line switch rather than attributes is useful.  It is deprecated to direct people to the "preferred mechanism" not because it is a bad mechanism.
2.  Please add a description that will show up in when we do fsc --help
     Of course once you do, then you will in a world of hurt, because some baselines will need updating, and the tests are horriffic.
     I think the important ones are here:
         https://github.com/dotnet/fsharp/tree/main/tests/fsharpqa/Source/CompilerOptions/fsc/help
         https://github.com/dotnet/fsharp/tree/main/tests/fsharpqa/Source/CompilerOptions/fsi/help
3. Please ensure that fsi.exe also supports the version switch

A few of the tests rely on --version existing and taking a value.

I believe it is possible to have --version and --version:some value.

I hope this helps

Kevin

**Comment by VTJDailey** [comment]
Hi @KevinRansom thanks for the help.  In the related issue #6783, @cartermp did ask to have the old meaning of the --version removed and just do the new behavior.  I'm not sure what the process is for resolving decisions like that but I'll let you two hash it out  :-)

Once I see the result, I'll get those tests updated.

-John

**Comment by KevinRansom** [comment]
@VTJDailey , put it back please.

**Comment by KevinRansom** [comment]
@VTJDailey , hey do you still want to pursue this change, or should we close it?

**Comment by VTJDailey** [comment]
I would say you can just close it.  I wasn't getting clean running tests
when I did a fresh project clone, and fiddled around with it for a while,
but I don't really have time to pursue it further.  The original use case
where I wanted the new feature has long passed anyway.

-John

**Comment by KevinRansom** [comment]
@VTJDailey , 

- I reverted the deprecated version switch, which will have got rid of a couple of the failures you saw, because we still use it in tests.
- I also updated the fsc and fsi baselines, which will fix the failures in the CompilerOptions test.
- I fixed the merge conflicts

Once the tests have passed this will be ready to merge.

Thanks for your work on this feature.

Kevin

**Review by KevinRansom — APPROVED** [review]
This is good, 
@VTJDailey thanks for the work

Kevin

**Comment by KevinRansom** [comment]
@VTJDailey, somehow I messed up your attribution when resolving the merge issues, can you commit a small change, so that I can fix it.

Thanks

Kevin

**Review by KevinRansom — CHANGES_REQUESTED** [review]
@VTJDailey, somehow I messed up your attribution when resolving the merge issues, can you commit a small non-functional change, so that I can fix that.

Thanks

Kevin

**Review by KevinRansom — APPROVED** [review]
Thanks for this.

**Pull request merged**
