### PR TITLE
I'm shy test. Please don't ignore me

### PR DESCRIPTION
**Pull request by kant2002**
My older brother just join your club. I'm want to be part of the test suite too.

### CODE REVIEW

**Review by KevinRansom — APPROVED** [review]

**Review by KevinRansom — CHANGES_REQUESTED** [review]
@vzarytovskii --- can you take a look.

**Comment by T-Gro** [comment]
Mismatch in error message, expected '"The type 'float<potato>' is not compatible with the type 'ITrigonometricFunctions<float<potato>>'"' was not found during compilation

**Comment by vzarytovskii** [comment]
I'll take a look at it, we're likely just didn't use correct interfaces from bcl.

**Comment by vzarytovskii** [comment]
Ok, I've re-enabled those as part of https://github.com/dotnet/fsharp/pull/14294, and fixed them there.

**Pull request closed without merging**
