### PR TITLE
New attempt to fix 'not' function

### LINKED ISSUE #9433: `not(isNull x)` leads to very odd and partially unreachable IL code that performace 5x slower than redefining `not` yourself
I noticed this while doing timings for https://github.com/dotnet/fsharp/issues/9390, where sometimes using `not` gave an unexpected performance degradation. This boiled down to `not` sometimes leading to very unexpected IL.

## Repro steps

Take the following code snippet:

```f#
let useNotIsNull (str:string) =
    if not(isNull str) then str.Length
    else 0
```

Because `not` [is coded to return a single `IL` instruction](https://github.com/dotnet/fsharp/blob/ed9b9b7df908bbc2b90e46de27dc05678a6d787a/src/fsharp/FSharp.Core/prim-types.fs#L3795) with `ceq`, and `isNull`, [while coded with `match`](https://github.com/dotnet/fsharp/blob/ed9b9b7df908bbc2b90e46de27dc05678a6d787a/src/fsharp/FSharp.Core/prim-types.fs#L3775), also leads to basically a single `ceq` instruction, that we'd end up with two instructions, or, after optimization, a single one. However, it blows up:

        IL_0000: ldarg.0
        IL_0001: brfalse.s IL_0006

        IL_0003: ldc.i4.0
        IL_0004: br.s IL_0007

        IL_0006: ldc.i4.1

        IL_0007: brtrue.s IL_0010

        IL_0009: ldarg.0
        IL_000a: callvirt instance int32 [System.Private.CoreLib]System.String::get_Length()
        IL_000f: ret

        IL_0010: ldc.i4.0
        IL_0011: ret

Which gets translated in C# as:

    public static int useNotIsNull(string str)
    {
        if (str != null || 1 == 0)
        {
            return str.Length;
        }
        return 0;
    }

If you were to recreate the `not` function as follows:

```f#
let not x = match x with true -> false | _ -> true
```

The same code above would now be encoded in IL as:

        IL_0000: ldarg.0
        IL_0001: brfalse.s IL_000a

        IL_0003: ldarg.0
        IL_0004: callvirt instance int32 [System.Private.CoreLib]System.String::get_Length()
        IL_0009: ret

        IL_000a: ldc.i4.0
        IL_000b: ret

And here is the real killer, if we encode `not` as itself, the problem _also_ disappears, regardless of whether it is marked as `inline` (the original) or not:

```f#
let justLikeNot x = not x

let useJustLikeNot (str:string) =
    if justLikeNot(isNull str) then str.Length
    else 0
```

Resulting IL:

        IL_0000: ldarg.0
        IL_0001: brfalse.s IL_000a

        IL_0003: ldarg.0
        IL_0004: callvirt instance int32 [System.Private.CoreLib]System.String::get_Length()
        IL_0009: ret

        IL_000a: ldc.i4.0
        IL_000b: ret

Strangely, the `not` function itself looks exactly the same as the `justLikeNot` function above:

        IL_0000: ldarg.0
        IL_0001: ldc.i4.0
        IL_0002: ceq
        IL_0004: ret

Though in one case (with `isNull`) it leads to strange opcodes. In most other cases, it leads to the expected folding of the `ceq` into a `brfalse` or `brtrue` respectively.

More examples of coding this and their surprising translations can be found in [this SharpLab.io snippet](https://sharplab.io/#v2:DYLgZgzgNALiCWwoBMQGoA+wCmMAEAdgK7DADyBwAnngBQQwBOIDj8BA5gJR4C8AsACg8IvPDBiIAORLA8rPDAAW2AngAMQ0XmzAI2eUwB0AGVUdlQq4Jz4i+qQHsYASWmy6rFk3bc+W0XFCZ1p4d1JDRh5lVUjTc0thUV19DQCRIVsxMCd8ADcAQ2AiA3ombzZOHgEkkSCCZzxC4oMYtVZ4zkTtFINNWrxM3GzcgEEAB3HgeGxkPAky5lZfavTs4JhaMFouaJV24zMupTXetMEh/AaYGVIAJWwFr2Wq/wH6kMcAIwArIwewNhGKoAMbYACiAEciEUIIsoIRZLtFPs4kcLCcBmd+tpLiNnBMpjNkAAmeaecovPw1bQfTYSVh7WIddHdZJ6PprPHXPAADz4eAAtgUYCClHy8AB3eDKRSMEp4AC0AD55rCDBg8AB9JWqpglaxZa5uW7kcb4RYVFZvWkSa6hcJyRko5mHBKYnoc854n72GAmeAAa2wuQlvA2fMNw3s2AAUn6A8HQ5aqat3hJfQxEyGQmFTZEmQdGJ0Macvf0uYIgA==).

**Expected behavior**

**Actual behavior**

See above for the _actual_ behavior. In terms of performance, the different `not` versions in the code perform all as expected, since they are ultimately folded into optimized x64 assembly, **except for the `not(isNull x)` version**. The `notIsNull` below uses `not(isNull x)`, the others all use a different way of coding `not` than the default:

image

_(These timings were made by ensuring the function returns and is not optimized away (hence the `str.Length` call) and repeated 10_000x in a close for-loop to erase timing inefficiencies for micro-benchmarks with BDN.)_

This is ultimatedly caused by the final assembly, which looks as follows (note the popping and extra call):

```assembly
; FSharp.Perf.BenchLength.notIsNull()
       push      rdi
       push      rsi
       sub       rsp,28
       mov       ecx,[rcx+8]
       call      FSharp.Perf.Data.get(Int32)
       mov       rsi,rax
       xor       edi,edi
M00_L00:                      ; start of for-loop body
       mov       rcx,rsi
       call      FSharp.Perf.StringLength.notIsNull(System.String)
       inc       edi
       cmp       edi,2711       ; loop 10_000 times
       jl        short M00_L00
       add       rsp,28
       pop       rsi
       pop       rdi
       ret
; Total bytes of code 44
```

```assembly
; FSharp.Perf.StringLength.notIsNull(System.String)
       test      rcx,rcx
       je        short M02_L00
       mov       eax,[rcx+8]
       ret
M02_L00:
       xor       eax,eax
       ret
; Total bytes of code 12
```

Compare that to using one of the `not` redefinitions, which, with the same code, gives:

```assembly
; FSharp.Perf.BenchLength.newNot()
       sub       rsp,28
       mov       ecx,[rcx+8]
       call      FSharp.Perf.Data.get(Int32)
       xor       edx,edx
M00_L00:                      ; start of for-loop body
       test      rax,rax
       je        short M00_L01
       mov       ecx,[rax+8]
M00_L01:
       inc       edx
       cmp       edx,2711       ; loop 10_000 times
       jl        short M00_L00
       add       rsp,28
       ret
; Total bytes of code 37
```

That is: no push/pop of `rdi` and `rsi`, that is, no new stackframe.

**Known workarounds**

Redefine `not` yourself and the problem seems to disappear.

**Related information**

I've only tested this on the latest VS + FSC (with optimizations on, of course), but the Sharplab decoding showed the same results.

I discussed this with @baronfel yesterday and neither of us could come up with a reasonable explanation, even more so since re-defining `not` as itself leads to optimized code, so I'm not sure why the combination `not(isNull x)` leads to such IL. The Sharplab.io link shows that using something else than `isNull` in the brackets _does not lead to the same weird IL opcodes_.

### PR DESCRIPTION
**Pull request by abelbraaksma**
Fixes #9433
Depends on #9622 (I really like to merge that one, as more and more are depending on it, making reviews harder, @KevinRansom could you check that one please?)

This resurrects #9434 by trying a different approach:

* I noticed that many optimizations depend on inline IL (see `mkAssemblyCodeValueInfo`), by leaving this behavior in place for comparison and logic functions, this makes less changes to baseline tests and FCS tests (like ExprTests)
* This moves the public function down in `prim-types.fs`, so that the "basic inlined operation" comes into scope, and changes it to use normal syntax.

The main benefit is: better optimized IL in user code, esp wrt `not(isNull x)`, which is currently broken, see linked issue. 

Relevant commit after #9622: https://github.com/dotnet/fsharp/pull/9715/commits/f2a9e2c0e429ee9859af6978e046c56f80bb2915

Let's see what tests are still complaining (impossible to run all locally).

### CODE REVIEW

**Comment by abelbraaksma** [comment]
Failing build, but build runner shows :laughing::

image

**Comment by abelbraaksma** [comment]
Strange stuff, a test clearly failed but CI doesn't consider it a fail (see above), but reports the run as failed :thinking: 

image

**Comment by abelbraaksma** [comment]
And a few minutes after that it said "all checks have passed" :thinking:  :thinking:  :thinking: ??? (no new commits)

Anyway, this may fix this (note that I don't seem to be able to run these tests locally with `build -testFSharpQA`, a bunch always fail and after some time it just hangs (no CPU, can see some perl jobs in task mgr) after this:

> Optimizations\Inlining (StructUnion01.fs) -- passed

**Comment by abelbraaksma** [comment]
This is ready, @cartermp can you review? Though it would be nice if #9622 gets merged first, to limit the diff.

**Comment by cartermp** [comment]
https://github.com/dotnet/fsharp/pull/9622 is now merged. For some reason GitHub still shows a large diff that includes its changes. Would it be possible to rebase this atop the latest master to make it a cleaner diff?

**Comment by abelbraaksma** [comment]
> Would it be possible to rebase this atop the latest master to make it a cleaner diff?

@cartermp, done (well, without the rebase, it appeared that just a merge from 'master' was fine). The "changed list" shows only the relevant changes now.

I'll do the same for the other PRs that depend on #9622.

**Comment by abelbraaksma** [comment]
With Kevin OOO, can I kindly ask other jedis to do the 2nd review? @tihan, @dsyme perhaps?

**Comment by abelbraaksma** [comment]
Never mind, looks like this one only needed one review? Great :+1:

**Comment by cartermp** [comment]
Yeah, this is implemented exactly as suggested and the changes look good. Thanks!

**Comment by cartermp** [comment]
@KevinRansom I definitely disagree here. We should _not_ be in the business of emitting IL directly anymore unless it is absolutely necessary. This is the right approach for FSharp.Core.

**Comment by KevinRansom** [comment]
@cartermp , 
We are a compiler, emitting il is what we do.  ceq is used a fair amount in our code generation pipeline.  Of course if we want to eliminate "ceq" support from the compiler, then a PR doing that would be welcome.

Kevin

**Comment by cartermp** [comment]
We should have a chat. I don't think you are right. This is not the compiler, this is a public API function in the F# core library for flipping a boolean expression.

The fact that raw IL emission is was done historically is just history and not at all related to emitting IL as a part of compilation. We should not be in the business of this stuff unless it's necessary for bootstrapping purposes. This function is definitely _not_ involved in any kind of bootstrapping.

**Comment by cartermp** [comment]
Please refer to the discussion here for what led to this change: https://github.com/dotnet/fsharp/issues/9433

**Comment by KevinRansom** [comment]
These types of PR's are always the most difficult for me.  Because the fix itself is a no-brainer ... sure the new one line is easier to parse and clearly better than the old one line.

However,  there are plenty of other places in the compiler that still generate the equivalent of the old one line.  They don't benefit from the change, and this PR does not even attempt to fix them.   I would prefer to understand and perhaps fix the actual problem rather than just avoid it in the places developers notice it.

**Comment by abelbraaksma** [comment]
@KevinRansom, @cartermp, When working with this fix I noticed some other cases where incorrect boolean optimizations are done. I'm still analyzing that, but this fix produces better IL for the majority of cases.

The optimizer is split in optimizing inline IL and normal code. When it is mixed, esp wrt booleans, it goes wrong and dead IL code is created. What's worse, when combined with null checks, the code didn't eliminate the `not`, but created code that was many times slower.

This simple fix takes care of all that. Yes, there are now other cases, but the way this fix was done ensures that the new cases are very limited, and that existing optimizations with comparison operators continue to work.

I intend to investigate further for optimizations of boolean expressions, esp boolean negation. But that should go in its own issue. I'll report that separately, as it's a much wider issue than this one (and may end up being wip for some time).

**Comment by abelbraaksma** [comment]
> They don't benefit from the change, and this PR does not even attempt to fix them

@KevinRansom No, this is misunderstanding what I'm doing here. The code using the old version **gets optimized**. The wrong assumption in the previous PR was that just changing `not` would lead to optimized code everywhere. It doesn't.

* the inline IL version leads to optimized code when paired with other inline IL function or operator. 
* the normal function (the new `not`) leads to optimized IL in most cases when paired with another normal function (like `isNull`).
* this doesn't fix the problem if the optimizer when encountering a mix of inline IL and normal code, nor does it fix certain rare cases where negation always leads to bad IL.

**Comment by KevinRansom** [comment]
@abelbraaksma the baseline that changed was built non-optimized, when that test case is built optimized no change in il happens.

**Comment by KevinRansom** [comment]
As I said before, this PR is tricky.  I am prepared to approve it, since there is a clear benefit, however, the underlying issue remains.  We should address that too at some point.

**Comment by abelbraaksma** [comment]
> the baseline that changed was built non-optimized, when that test case is built optimized no change in il happens

This came as a big surprise to me and basically set me on a tour to review my earlier assessments. 

After quite a bit experimenting I finally got a nice setup to compare before & after IL for different fsc arguments. I now come to the same conclusion as you, except that I need to verify some more optimized code. 

It is indeed as you say that many lines of somewhat weirdly looking, and partially dead IL in debug builds end up being a single IL instruction as it should (plus `ret`) for the offending case.

This makes one wonder, though, why we compare so many IL cases for debug builds, where the more interesting case is clearly the release build here. 

@kevinransom, I apologize for coming so strongly to the wrong conclusion, I misunderstood how these bsl files were generated. 

Some of the code I see in the debug build that's clearly redundant, may be part of the cause that you need to hit "next step" multiple times in certain cases when debugging, where there isn't such extra step in the code (not even if you desugar things). That'll be a research for another day. 

I'll create the relevant issue for improving the boolean negation further, but that'll be a much larger task given that it changes all the IL for the negated comparison operators. 

Thanks for reviewing this, @KevinRansom.

**Comment by KevinRansom** [comment]
@abelbraaksma , no problem mate, and thanks for this pr.

**Comment by abelbraaksma** [comment]
Follow-up issue: https://github.com/dotnet/fsharp/issues/9753.

**Pull request merged**
