### PR TITLE
Do not add PropInfos and MethInfos to NameRes if we don't know the type

### PR DESCRIPTION
**Pull request by forki**
references #4825

### CODE REVIEW

**Comment by forki** [comment]
@dsyme and @KevinRansom I think this is the correct fix for #4825. We added methinfos to the name resolution without knowing the type.

**Comment by forki** [comment]
but it brekas the following snippet.

    (struct (1,2)).ToTuple()

**Comment by KevinRansom** [comment]
@forki, It's been a while, what do you want to do with this?

Thanks

Kevin

**Comment by forki** [comment]
Dunno. Someone else wants to fix it?

Kevin Ransom (msft) <notifications@github.com> schrieb am So., 8. März
2020, 03:51:

**Comment by KevinRansom** [comment]
@ forki,

Thanks for this, I will close for now.  Please, reopen if you want to take this forward.

Kevin

**Pull request closed without merging**
