### PR TITLE
Update .gitattributes

### PR DESCRIPTION
**Pull request by houstonhaynes**
adding entries for F#, fsx/csx/cshtml

### CODE REVIEW

**Comment by cartermp** [comment]
Hmm, this PR seems to have affected a tiny set of test cases. Do you feel comfortable looking into them?

**Comment by houstonhaynes** [comment]
I was expecting this to be relatively benign. Maybe a formatting issue? I'll dig in and take a look.

**Comment by houstonhaynes** [comment]
I don't understand why these tests are failing in areas unrelated to the commit. There have been other PRs were I forgot to add the obligatory Windows blank line at the end of the config file. But the complaint here has nothing to do with the .gitattributes file so I'm mystified as to why this change is breaking the build.

**Comment by cartermp** [comment]
Yeah, I think there might be something awry with this change here. The "unicode" test that you can see in CI failed in both runs, and the fsharpQA logs (under the artifacts page) show these failures:

```
+++ Conformance\Expressions\DataExpressions\QueryExpressions (UppercaseIdentifier04.fs) +++
--------------------------------------------------------
Results from hosted compiler
msg: Compiling
cmd: fsc   -a --warnaserror UppercaseIdentifier04.fs 
Exit code: 1
Error:     0
Microsoft (R) F# Compiler version 11.3.1.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.
(1,38): error FS0010: Unexpected character '?' in implementation file
(1,38): error FS0222: Files in libraries or multiple-file applications must begin with a namespace or module declaration, e.g. 'namespace SomeNamespace.SubNamespace' or 'module SomeNamespace.SomeModule'. Only the last source file of an application may omit such a declaration.
--------------------------------------------------------
Compiling: [fsc   -a --warnaserror UppercaseIdentifier04.fs ]
Microsoft (R) F# Compiler version 11.3.1.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

UppercaseIdentifier04.fs(1,38): error FS0010: Unexpected character '਍' in implementation file

UppercaseIdentifier04.fs(1,38): error FS0222: Files in libraries or multiple-file applications must begin with a namespace or module declaration, e.g. 'namespace SomeNamespace.SubNamespace' or 'module SomeNamespace.SomeModule'. Only the last source file of an application may omit such a declaration.
Compile Unexpectedly Failed: 256 
FAIL

+++ Conformance\LexicalAnalysis\StringsAndCharacters (ByteChars02.fs) +++
--------------------------------------------------------
Results from hosted compiler
msg: Compiling
cmd: fsc   --codepage:1252 ByteChars02.fs 
Exit code: 1
Error:     0
Microsoft (R) F# Compiler version 11.3.1.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.
(1,35): error FS0010: Unexpected character '?' in implementation file
--------------------------------------------------------
Compiling: [fsc   --codepage:1252 ByteChars02.fs ]
Microsoft (R) F# Compiler version 11.3.1.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

ByteChars02.fs(1,35): error FS0010: Unexpected character '਍' in implementation file
Compile Unexpectedly Failed: 256 
FAIL

+++ Conformance\LexicalAnalysis\StringsAndCharacters (TripleQuoteString02.fs) +++
--------------------------------------------------------
Results from hosted compiler
msg: Compiling
cmd: fsc    TripleQuoteString02.fs 
Exit code: 1
Error:     0
Microsoft (R) F# Compiler version 11.3.1.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.
(1,35): error FS0010: Unexpected character '?' in implementation file
--------------------------------------------------------
Compiling: [fsc    TripleQuoteString02.fs ]
Microsoft (R) F# Compiler version 11.3.1.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

TripleQuoteString02.fs(1,35): error FS0010: Unexpected character '਍' in implementation file
Compile Unexpectedly Failed: 256 
FAIL

**Comment by houstonhaynes** [comment]
My question is - what does this have to do with the price of UTF16 in Japan? I'm really mystified how a .gitattributes change can cause an unaltered file to fail validation. My commit had nothing to do with it. (Obviously it has *something* to do with it, but you get my rhetorical point) If I changed those files then it would be understandable. 

On the broader point - I had done other .gitattributes to other repos and thought "OK while I'm at it..." and made some updates to the repo that builds gitattribute templates for various languages - at https://gittattributes.io - which had a CSharp template but not an FSharp sibling. So for course I started to do the rounds with others - and honestly this site doesn't really "need" it as it has a proliferation of native fs file types that seem to instruct linguist to "know" how to list it in GitHub meta searches. 

So in this case it would seem the juice may not be worth the squeeze - unless it's to inform Houston on how UTF16 gets messed up when the .gitattributes file causes a cascade read problem - maybe it's just a bug in linguist/gitattributes. Either way, I'm fine with this being sidelined. There were a handful of F# repos showing up as "javascript" which were fixed with some direct .gitattributes entries - and that's good enough. It would be great if the fsharp library had a canonical entry so that other folks "inside the beltway" would have a good example, but it's not the hassle if it distracts from the real work.

**Comment by cartermp** [comment]
Makes sense! I suspect it has something to do with how the compiler itself is built, and how it interprets the source files given the presence of the .gitattributes file. Unicode stuff is quirky as heck.

**Pull request closed without merging**
