### PR TITLE
Import FCS release notes and reorganize the release notes file

### PR DESCRIPTION
**Pull request by cartermp**
it's a big chungus

### CODE REVIEW

**Comment by cartermp** [comment]
cc @baronfel I imported the stuff

**Comment by baronfel** [comment]
Looks good! Brief note that the WIP FCS version is 38 right now, but other than :+1:

**Comment by cartermp** [comment]
Doneski

**Comment by cartermp** [comment]
This is now complete

**Review by KevinRansom — APPROVED** [review]

**Pull request merged**
