### PR TITLE
Add trivia for SynMemberFlags.

### LINKED ISSUE #11508: Keep track of used keywords in AbstractSlot/SynMemberFlags
Given the following code:
```fsharp
type Foo =
    abstract Bar1 : int
    abstract member Bar2 : int
```
and matching AST
```fsharp
AbstractSlot
  (ValSpfn
     ([], Bar1, SynValTyparDecls ([], true, []),
      LongIdent (LongIdentWithDots ([int], [])),
      SynValInfo ([], SynArgInfo ([], false, None)), false,
      false,
      PreXmlDoc ((2,12), FSharp.Compiler.XmlDoc+XmlDocCollector),
      None, None, tmp.fsx (2,4--2,23) IsSynthetic=false),
   { IsInstance = true
     IsDispatchSlot = true
     IsOverrideOrExplicitImpl = false
     IsFinal = false
     MemberKind = PropertyGet },
   tmp.fsx (2,4--2,23) IsSynthetic=false);
AbstractSlot
  (ValSpfn
     ([], Bar2, SynValTyparDecls ([], true, []),
      LongIdent (LongIdentWithDots ([int], [])),
      SynValInfo ([], SynArgInfo ([], false, None)), false,
      false,
      PreXmlDoc ((3,19), FSharp.Compiler.XmlDoc+XmlDocCollector),
      None, None, tmp.fsx (3,4--3,30) IsSynthetic=false),
   { IsInstance = true
     IsDispatchSlot = true
     IsOverrideOrExplicitImpl = false
     IsFinal = false
     MemberKind = PropertyGet },
   tmp.fsx (3,4--3,30) IsSynthetic=false)
```
there is currently no way of knowing what keywords were used in the original source.
I'd like to store this information in `SynMemberDefn.AbstractSlot` or maybe `SynMemberFlags`.

Would this be ok to have and how would you want to see this implemented?

### PR DESCRIPTION
**Pull request by nojaf**
Especially enjoy this one, what a treasure of information 🤑
Fixes #11508

### CODE REVIEW

**Review by vzarytovskii — APPROVED** [review]
Oh, that's nice.

**Review by KevinRansom — APPROVED** [review]

**Comment by KevinRansom** [comment]
@nojaf , could you take care of the conflicts please, and we will get this merged.

Thanks

Kevin

**Comment by nojaf** [comment]
Done, thanks Kevin!

**Comment by KevinRansom** [comment]
Thank you my friend

Kevin

**Pull request merged**
