### PR TITLE
Moved CodeGen/EmittedIL/Mutation over to NUnit 

### PR DESCRIPTION
**Pull request by sergey-tihon**
part of #7075

TODO:
- [x] Allow to  use snippets with  warnings
- [x] Make assemblyname stable (`<StartupCode$Mutation02>`  vs `<StartupCode$tmpF1A6>` )
- [x] Support .NET Core (`expected IL` in test should be runtime independent,`[mscorlib]System.Object` vs `[System.Runtime]System.Object` )

### CODE REVIEW

**Comment by sergey-tihon** [comment]
Before merging this keep in mind that I've changed `expected IL` vs old baseline IL.
Not sure how current tests pass ... but hope that change is expected.

### Mutation 2

bsl
```
    IL_0000:  ldsfld     valuetype [mscorlib]System.TimeSpan [mscorlib]System.TimeSpan::MinValue
    IL_0005:  dup
    IL_0006:  stsfld     valuetype [mscorlib]System.TimeSpan '<StartupCode$Mutation02>'.$Mutation02::x@4
    IL_000b:  stloc.0
    IL_000c:  call       valuetype [mscorlib]System.TimeSpan Mutation02::get_x()
    IL_0011:  stloc.1
    IL_0012:  ldloca.s   V_1
    IL_0014:  constrained. [mscorlib]System.TimeSpan
    IL_001a:  callvirt   instance string [mscorlib]System.Object::ToString()
    IL_001f:  pop
    IL_0020:  ret
```
new
```
    IL_0000:  ldsfld     valuetype [mscorlib]System.TimeSpan [mscorlib]System.TimeSpan::MinValue
    IL_0005:  stsfld     valuetype [mscorlib]System.TimeSpan '<StartupCode$asmName>'.$Mutation02::x@3
    IL_000a:  call       valuetype [mscorlib]System.TimeSpan Mutation02::get_x()
    IL_000f:  stsfld     valuetype [mscorlib]System.TimeSpan '<StartupCode$asmName>'.$Mutation02::copyOfStruct@4
    IL_0014:  ldsflda    valuetype [mscorlib]System.TimeSpan '<StartupCode$asmName>'.$Mutation02::copyOfStruct@4
    IL_0019:  constrained. [mscorlib]System.TimeSpan
    IL_001f:  callvirt   instance string [mscorlib]System.Object::ToString()
    IL_0024:  pop
    IL_0025:  ret
```

### Mutation 3

bsl
```
    IL_0000:  call       valuetype [mscorlib]System.DateTime [mscorlib]System.DateTime::get_Now()
    IL_0005:  dup
    IL_0006:  stsfld     valuetype [mscorlib]System.DateTime '<StartupCode$Mutation03>'.$Mutation03::'x@4-2'
    IL_000b:  stloc.0
    IL_000c:  call       valuetype [mscorlib]System.DateTime Mutation03::get_x()
    IL_0011:  stloc.1
    IL_0012:  ldloca.s   V_1
    IL_0014:  call       instance int32 [mscorlib]System.DateTime::get_Day()
    IL_0019:  pop
    IL_001a:  ret
```
new
```
    IL_0000:  call       valuetype [mscorlib]System.DateTime [mscorlib]System.DateTime::get_Now()
    IL_0005:  stsfld     valuetype [mscorlib]System.DateTime '<StartupCode$asmName>'.$Mutation03::x@3
    IL_000a:  call       valuetype [mscorlib]System.DateTime Mutation03::get_x()
    IL_000f:  stsfld     valuetype [mscorlib]System.DateTime '<StartupCode$asmName>'.$Mutation03::copyOfStruct@4
    IL_0014:  ldsflda    valuetype [mscorlib]System.DateTime '<StartupCode$asmName>'.$Mutation03::copyOfStruct@4
    IL_0019:  call       instance int32 [mscorlib]System.DateTime::get_Day()
    IL_001e:  pop
    IL_001f:  ret
```

### Mutation 4

bsl
```
    IL_0000:  ldsfld     valuetype [mscorlib]System.Decimal [mscorlib]System.Decimal::MaxValue
    IL_0005:  dup
    IL_0006:  stsfld     valuetype [mscorlib]System.Decimal '<StartupCode$Mutation04>'.$Mutation04::'x@4-4'
    IL_000b:  stloc.0
    IL_000c:  call       valuetype [mscorlib]System.Decimal Mutation04::get_x()
    IL_0011:  stloc.1
    IL_0012:  ldloca.s   V_1
    IL_0014:  constrained. [mscorlib]System.Decimal
    IL_001a:  callvirt   instance string [mscorlib]System.Object::ToString()
    IL_001f:  pop
    IL_0020:  ret
```
new
```
    IL_0000:  ldsfld     valuetype [mscorlib]System.Decimal [mscorlib]System.Decimal::MaxValue
    IL_0005:  stsfld     valuetype [mscorlib]System.Decimal '<StartupCode$asmName>'.$Mutation04::x@3
    IL_000a:  call       valuetype [mscorlib]System.Decimal Mutation04::get_x()
    IL_000f:  stsfld     valuetype [mscorlib]System.Decimal '<StartupCode$asmName>'.$Mutation04::copyOfStruct@4
    IL_0014:  ldsflda    valuetype [mscorlib]System.Decimal '<StartupCode$asmName>'.$Mutation04::copyOfStruct@4
    IL_0019:  constrained. [mscorlib]System.Decimal
    IL_001f:  callvirt   instance string [mscorlib]System.Object::ToString()
    IL_0024:  pop
    IL_0025:  ret
```

### Mutation 5

bsl
```
      IL_0000:  volatile.
      IL_0002:  ldsfld     int32 Mutation05/StaticC::init@9
      IL_0007:  ldc.i4.1
      IL_0008:  bge.s      IL_000c

      IL_000a:  br.s       IL_000e

      IL_000c:  br.s       IL_0017

      IL_000e:  call       void [FSharp.Core]Microsoft.FSharp.Core.LanguagePrimitives/IntrinsicFunctions::FailStaticInit()
      IL_0013:  nop
      IL_0014:  nop
      IL_0015:  br.s       IL_0018

      IL_0017:  nop
      IL_0018:  volatile.
      IL_001a:  ldsfld     int32 Mutation05/StaticC::x
      IL_001f:  ret
```
new
```
      IL_0000:  volatile.
      IL_0002:  ldsfld     int32 Mutation05/StaticC::init@10
      IL_0007:  ldc.i4.1
      IL_0008:  bge.s      IL_0011

      IL_000a:  call       void [FSharp.Core]Microsoft.FSharp.Core.LanguagePrimitives/IntrinsicFunctions::FailStaticInit()
      IL_000f:  br.s       IL_0011

      IL_0011:  volatile.
      IL_0013:  ldsfld     int32 Mutation05/StaticC::x
      IL_0018:  ret
```

bsl
```
      IL_0000:  volatile.
      IL_0002:  ldsfld     int32 Mutation05/StaticC::init@9
      IL_0007:  ldc.i4.1
      IL_0008:  bge.s      IL_000c

      IL_000a:  br.s       IL_000e

      IL_000c:  br.s       IL_0017

      IL_000e:  call       void [FSharp.Core]Microsoft.FSharp.Core.LanguagePrimitives/IntrinsicFunctions::FailStaticInit()
      IL_0013:  nop
      IL_0014:  nop
      IL_0015:  br.s       IL_0018

      IL_0017:  nop
      IL_0018:  ldarg.0
      IL_0019:  volatile.
      IL_001b:  stsfld     int32 Mutation05/StaticC::x
      IL_0020:  ret
```
new
```
      IL_0000:  volatile.
      IL_0002:  ldsfld     int32 Mutation05/StaticC::init@10
      IL_0007:  ldc.i4.1
      IL_0008:  bge.s      IL_0011

      IL_000a:  call       void [FSharp.Core]Microsoft.FSharp.Core.LanguagePrimitives/IntrinsicFunctions::FailStaticInit()
      IL_000f:  br.s       IL_0011

      IL_0011:  ldarg.0
      IL_0012:  volatile.
      IL_0014:  stsfld     int32 Mutation05/StaticC::x
      IL_0019:  ret
```

**Comment by sergey-tihon** [comment]
This PR is ready for review.
Anything I can do to help merge it?

**Comment by KevinRansom** [comment]
@sergey-tihon the difference in the il between the original and your port is because, the original tests were compiled with optimization disabled.  Whereas the 
You can tell what the original compile switches were from the scflags in the env.lst file:
````
	SOURCE=Mutation01.fs   SCFLAGS="-g --test:EmitFeeFeeAs100001 --optimize-" COMPILE_ONLY=1 POSTCMD="..\\CompareIL.cmd Mutation01.exe"		# Mutation01.fs -

	SOURCE=Mutation02.fs   SCFLAGS="-g --test:EmitFeeFeeAs100001 --optimize-" COMPILE_ONLY=1 POSTCMD="..\\CompareIL.cmd Mutation02.exe"		# Mutation02.fs
	SOURCE=Mutation03.fs   SCFLAGS="-g --test:EmitFeeFeeAs100001 --optimize-" COMPILE_ONLY=1 POSTCMD="..\\CompareIL.cmd Mutation03.exe"		# Mutation03.fs
	SOURCE=Mutation04.fs   SCFLAGS="-g --test:EmitFeeFeeAs100001 --optimize-" COMPILE_ONLY=1 POSTCMD="..\\CompareIL.cmd Mutation04.exe"		# Mutation04.fs
	SOURCE=Mutation05.fs   SCFLAGS="-g --test:EmitFeeFeeAs100001 --optimize-" COMPILE_ONLY=1 POSTCMD="..\\CompareIL.cmd Mutation05.exe"		# Mutation05.fs

````

**Comment by sergey-tihon** [comment]
Thank you @KevinRansom I'll take a look how to do `--optimize-` inside test framework

**Comment by KevinRansom** [comment]
@sergey-tihon probably just add a func:
CompilerAssert.CompileLibraryAndVerifyILWithOptions
and then pass in [| "--optimize-"|]

**Comment by sergey-tihon** [comment]
I've added `CompilerAssert.CompileLibraryAndVerifyILWithOptions` function converted tests to be compiled with `--optimize-` option, but new IL still differ from the `bsl`

Please look at my previous comment `bsl vs new`, it it updated based on output from `--optimize-`

**Comment by KevinRansom** [comment]
@sergey-tihon :  
so apparently it's
````
[|"-g"; "--optimize-"; |]
````

````
  //fsc Program.fs -g --optimize-
  {
    .entrypoint
    // Code size       33 (0x21)
    .maxstack  4
    .locals init ([0] valuetype [mscorlib]System.TimeSpan x,
             [1] valuetype [mscorlib]System.TimeSpan V_1)
    IL_0000:  ldsfld     valuetype [mscorlib]System.TimeSpan [mscorlib]System.TimeSpan::MinValue
    IL_0005:  dup
    IL_0006:  stsfld     valuetype [mscorlib]System.TimeSpan '<StartupCode$Program>'.$Mutation02::x@2
    IL_000b:  stloc.0
    IL_000c:  call       valuetype [mscorlib]System.TimeSpan Mutation02::get_x()
    IL_0011:  stloc.1
    IL_0012:  ldloca.s   V_1
    IL_0014:  constrained. [mscorlib]System.TimeSpan
    IL_001a:  callvirt   instance string [mscorlib]System.Object::ToString()
    IL_001f:  pop
    IL_0020:  ret
  } // end of method $Mutation02::main@
````

````
  // fsc Program.fs
  {
    .entrypoint
    // Code size       38 (0x26)
    .maxstack  8
    IL_0000:  ldsfld     valuetype [mscorlib]System.TimeSpan [mscorlib]System.TimeSpan::MinValue
    IL_0005:  stsfld     valuetype [mscorlib]System.TimeSpan '<StartupCode$Program>'.$Mutation02::x@2
    IL_000a:  call       valuetype [mscorlib]System.TimeSpan Mutation02::get_x()
    IL_000f:  stsfld     valuetype [mscorlib]System.TimeSpan '<StartupCode$Program>'.$Mutation02::copyOfStruct@3
    IL_0014:  ldsflda    valuetype [mscorlib]System.TimeSpan '<StartupCode$Program>'.$Mutation02::copyOfStruct@3
    IL_0019:  constrained. [mscorlib]System.TimeSpan
    IL_001f:  callvirt   instance string [mscorlib]System.Object::ToString()
    IL_0024:  pop
    IL_0025:  ret
  } // end of method $Mutation02::main@
````

**Comment by sergey-tihon** [comment]
@KevinRansom  Thank you, my bad. I have tried `-g` for `Mutation 1` test it did not affect IL and decided that irrelevant, but it really works for others.

The only question is the IL from first test, I've updated original comment with new IL.

**Comment by sergey-tihon** [comment]
I found the issue, IL was different because I changed
```
member t.setV v = t.v <- 0
```
to 
```
member t.setV _ = t.v <- 0
```
when was not able to compile source  with warnings.

Everything should be OK now. Expected IL should match IL from `bsl`.

**Comment by cartermp** [comment]
Thanks!

**Pull request merged**
