### PR TITLE
Create the benchmark solution 

### PR DESCRIPTION
**Pull request by psfinaki**
The benchmark solution once existed but then was removed in [this PR](https://github.com/dotnet/fsharp/pull/11619/files#diff-ed4b0a1445bac061d480cb8fe95607dc85bbc1da55495d3749e5d5679f380870) since at that point there was little code there.

Now we have quite a few benchmark related projects so for the convenience I am reviving all we have there.

Note: this doesn't do any fixes, cleanups, refactorings and so on. That stuff will be in followups / parallel PRs.

### CODE REVIEW

**Review by abonie — APPROVED** [review]

**Comment by T-Gro** [comment]
General question, what is it good for?
As in what developer scenarios should it support?

**Comment by psfinaki** [comment]
Well this is for whoever wants to deep dive in F# benchmarks with as little distraction as possible - e.g. me, this month.
Same idea as `FSharp.Editor.sln` is the minimal solution for working with the editor.

In the future, I want to utilize this solution for doing some CI checks, e.g. it should at least compile.

**Comment by T-Gro** [comment]
"Working with the Editor" makes sense from actual feature delivery perspective.
I fail to see "working with the benchmarks" as a useful independent scenario, the existing benchmarks are single-purpose temporary code artefacts anyway.

(except helper code to facilitate creation of certain kinds of benchmarks, e.g. helpers to mimic tooling operations)


==> I would rather approve deletion of those projects

**Comment by psfinaki** [comment]
I don't want to delete these projects. They can serve as benchmark examples for similar tasks. As in, there is no need to run these particular benchmarks in the CI, however if someone wants to bench a similar functionality - we have something to easily copy-paste and use as a starting point.

For this reason, I think it's important to keep those in shape - at least compiling, maybe also doing some smoke testing.

That said, this is a somewhat orthogonal discussion - I just want to have a solution with the overview of all the benchmarks that we have. We can add and remove projects later as we wish. A solution file doesn't cost us much.

Helper code also applies, the bench infra also has some common parts and I am thinking to do some further refactoring in the near future.

**Review by T-Gro — APPROVED** [review]

**Pull request merged**
