### PR TITLE
[RFC FS-1046] Wildcard self identifier. Allow single underscore in members.

### PR DESCRIPTION
**Pull request by gusty**
This allows writing a single underscore in member definitions, ie `member _.DoSomething()`.

### CODE REVIEW

**Comment by cartermp** [comment]
@gusty is there a language suggestion change that maps to this? Generally I'm in favor.

Another interesting one (if you're digging around in there) is `for __ in do`:

image

Error message kinda sucks, and the resolution is a double `_`.

**Comment by gusty** [comment]
Yes, it's approved in principle, see https://github.com/fsharp/fslang-suggestions/issues/333

I've never thought about the `for _ in`, I will dig into it, in a separate PR.

**Comment by cartermp** [comment]
@gusty Thanks!

**Comment by matthid** [comment]
Thanks a lot for trying to take care of this wart ;)

**Comment by cartermp** [comment]
Note: this code fixer can also be changed with this PR: https://github.com/dotnet/fsharp/blob/master/vsintegration/src/FSharp.Editor/CodeFix/RenameUnusedValue.fs#L73

**Comment by gusty** [comment]
@cartermp Yes, we can adjust the rules for unused values. The only thing I'm concerned is whether it would become a sort-of breaking change, specifically when using the warnings as errors flag.

**Comment by gusty** [comment]
@cartermp  Actually for the renamer you suggested it won't cause problems. I was thinking in the warning mechanisms. For the identifiers starting with underscore it won't be a problem, but for existing `member x.` we could issue a warning once this feature is added, but as I said it would be sort of a breaking change.

**Comment by gusty** [comment]
@cartermp I adjusted the renamer, as you suggested.

**Comment by KevinRansom** [comment]
targeting fsharp47

**Comment by pauldorehill** [comment]
Love this update, however I noticed that it doesn't work with an accessibility modifier:
```
type MyType =
    { Hello : string }
    member private __.WorldOk = "World ok"
    member private _.WorldOhNo = "World not ok"
```
Do you want me to open a separate issue?

**Comment by gusty** [comment]
Good catch !

I've just added a PR (#7631) that will cover that case.

**Pull request merged**
