### PR TITLE
Module functions for `'T option` ↔ `'T voption`

### PR DESCRIPTION
**Pull request by brianrourkeboll**
## Description

- Add module functions for converting between `'T option` and `'T voption`.
- ~~Remove the multiple existing internal copies of these functions in this repo and replace their usage with the FSharp.Core ones.~~ See https://github.com/dotnet/fsharp/pull/17436#issuecomment-2245921263.

```fsi
module Option =
    val inline ofValueOption : voption : 'T voption -> 'T option
    val inline toValueOption : option  : 'T option  -> 'T voption
```

```fsi
module ValueOption =
    val inline ofOption : option  : 'T option  -> 'T voption
    val inline toOption : voption : 'T voption -> 'T option
```

## Checklist

- [x] Test cases added.
- [x] Release notes entry updated.

## Notes

It seems to me like this ought to have been part of https://github.com/fsharp/fslang-suggestions/issues/703, as @Thorium pointed out in https://github.com/fsharp/fslang-suggestions/issues/703#issuecomment-1165336456.

I can open a new language suggestion and RFC for this if needed — but perhaps we could just update [RFC FS-1065](https://github.com/fsharp/fslang-design/blob/b44bf9d714dd15c3c68f082283c5da537f910537/FSharp.Core-4.6.0/FS-1065-valueoption-parity.md) instead?

### CODE REVIEW

**Comment by brianrourkeboll** [comment]
It looks like this bit of the CI

https://github.com/dotnet/fsharp/blob/2eab49c1e3befb40eb11034ea878f66a95685c6e/azure-pipelines-PR.yml#L636

means that f4ca9f4 might need to go in a separate PR?

**Comment by psfinaki** [comment]
@brianrourkeboll, I don't see how the CI stuff can be directly related here... can you maybe rerevert the changes so that we can investigate a bit? It would be nice to get rid of all those dupes of this. And yeah, our CI is quite flaky recently.

**Comment by brianrourkeboll** [comment]
@psfinaki The CI failed when it was directly invoking `dotnet build` on FSharp.Compiler.Service.sln (the "Regular rebuild of FSharp.Compiler.Service.sln" step in the Plain_Build_* runs), which meant that it wasn't using the modified version of FSharp.Core.

Since https://github.com/dotnet/fsharp/commit/f4ca9f4827718a2f595c19477ec28b73c98eb58d replaced the internal functions with calls to the new ones in FSharp.Core, but the new version of FSharp.Core wasn't being used, it wouldn't compile.

**Comment by psfinaki** [comment]
Right, yeah I was looking at the wrong results then. 
That's clear, I think we can remove the dupe in a followup then.

**Review by psfinaki — APPROVED** [review]
@vzarytovskii @abelbraaksma should we update the RFC (before or after the merge)?

**Review by T-Gro — APPROVED** [review]

**Comment by T-Gro** [comment]
Thanks for this addition.
I will merge this in. @brianrourkeboll : Could you please update the existing RFC FS-1065 with the added signatures?

**Comment by psfinaki** [comment]
Thanks for the RFC as well @brianrourkeboll. Would be cool to remove all the dupes from the codebase now. If you don't have time for this, I can probably create a PR from the commit with those changes that you had in this PR.

**Comment by brianrourkeboll** [comment]
@psfinaki All right, I opened #17457.

If the CI step mentioned in https://github.com/dotnet/fsharp/pull/17436#issuecomment-2245921263 is using a shipped version of FSharp.Core, though, then this change may need to wait (or we may need to modify that step, depending on its intent).

**Pull request merged**
