### PR TITLE
38.0.2.amieres

### PR DESCRIPTION
**Pull request by amieres**
I would like to introduce this verification when `runningOnMono` to avoid `MemoryMappedFiles` which do not seem to work on Mono.

There are similar verifications in other places like: 

https://github.com/dotnet/fsharp/blob/6b1af129b798d0b3b7c296b27e8c2a5ad4f1dad8/src/fsharp/absil/bytes.fs#L304

https://github.com/dotnet/fsharp/blob/6b1af129b798d0b3b7c296b27e8c2a5ad4f1dad8/src/fsharp/absil/bytes.fs#L337

### CODE REVIEW

**Comment by cartermp** [comment]
@amieres there are several conflicts here, likely due to an out of date branch. Could you resolve them?

**Comment by nosami** [comment]
There is another `MemoryMappedFile` usage [here](https://github.com/dotnet/fsharp/blob/11c9e3b364344928f043d29a469ba506ae79476f/src/fsharp/service/ItemKey.fs#L426) that is causing VSMac to crash with the latest FCS

**Comment by amieres** [comment]
@cartermp 
I was able to remove 2 of the conflicting files. The remaining one `ilread.fs` is the one with the key changes in just 2 lines.
Github says the conflicts are too complex to resolve in the web editor. I do not know hot to resolve that conflict.

@nosami 
The `ItemKeyStore` is fully dependant on `MappedMemoryFile` for some reason it didn't affect my usage. Changing this would require a redefinition of `ItemKeyStore`.

**Comment by nosami** [comment]
> The ItemKeyStore is fully dependant on MappedMemoryFile for some reason it didn't affect my usage. Changing this would require a redefinition of ItemKeyStore or not allowing to use it in case of runningOnMono.

@amieres It's used by syntax highlighting, so if you aren't using that, you won't be affected

**Comment by amieres** [comment]
@nosami 
I do want to use that, do you know if there is an alternative?
maybe like they do here: https://github.com/dotnet/fsharp/blob/6b1af129b798d0b3b7c296b27e8c2a5ad4f1dad8/src/fsharp/absil/bytes.fs#L337

**Comment by nosami** [comment]
> I do want to use that, do you know if there is an alternative?

I think that MemoryMappedFiles _can_ be used with Mono, although the behaviour is slightly different than .Net Framework or CoreCLR on Windows.
I can investigate over the coming days if you want, as I need this to work too and it would be nice to have MMF used in all the other places to boost performance.

**Comment by amieres** [comment]
It would be nice!
In particular I'm running FCS in WebAssembly (WASM), which is still in development. I'm not sure if mmf will work in Mono WASM anytime soon.

If you find out the necessary changes I can add them here or in another PR.
No rush though.

**Comment by nosami** [comment]
I have no idea how filesystem access works on WASM, but I would guess that file access would only work within a sandbox?

**Comment by amieres** [comment]
Yes, it is a sandboxed FileSystem that is preloaded on startup.

You can still create/remove/... and I imagine download files from the server.

**Comment by cartermp** [comment]
@amieres I think you'll have to rebase the branch you're starting from to proceed.

**Comment by amieres** [comment]
I created another PR using a clean repo:

https://github.com/dotnet/fsharp/pull/11086

**Comment by cartermp** [comment]
Thanks, let's close this one and work from there

**Pull request closed without merging**
