### PR TITLE
Add extra space when first type argument is a statically resolved type parameter

### LINKED ISSUE #13760: Signature file generation does not handle statically resolved type parameter
When generating a signature file from a function with statically resolved type parameters, the generated code requires an additional space.

**Repro steps**

```fsharp

module MyApp.GoodStuff

let inline toString< ^revision when ^revision: (static member GetCommitHash: ^revision -> string)>
    (p: System.Threading.Tasks.Task< ^revision >)
    : string =
    ""
```

leads to

```fsharp
module MyApp.GoodStuff

val inline toString:
  p: System.Threading.Tasks.Task<^revision> -> string
    when ^revision: (static member GetCommitHash: ^revision -> string)
```

**Expected behaviour**

The generated signature should be considered equivalent to the backing source file.

**Actual behaviour**

The generated code isn't valid:

image

**Known workarounds**

Edit signature file by hand.

### PR DESCRIPTION
**Pull request by nojaf**
Fixes #13760.

### CODE REVIEW

**Comment by abelbraaksma** [comment]
It should be noted that with the PR for static interfaces, the space is no longer required. If this could be merged in a point release it’s still beneficial. But if the next release is going to include that PR (by @vzarytovskii, iirc, but I forgot the link), this one would become moot.

Alternatively, we could cherry pick the parts of that PR that fixes the parsing of static generic types.

**Comment by vzarytovskii** [comment]
The PR should be in main already. Also, ' can now be used instead of ^.

**Comment by nojaf** [comment]
Hmm, if there are still dotnet 6.0.x releases coming, I'd still like to have this fix in.
The whole static interfaces thing is dotnet 7 right?

**Comment by vzarytovskii** [comment]
> Hmm, if there are still dotnet 6.0.x releases coming, I'd still like to have this fix in.

Only servicing, which means high bar, pretty much only bugfixes. Probably the only thing we will be able to get in there is the fix for attribute checking compiler error.

> The whole static interfaces thing is dotnet 7 right?

Yep, it is tied to runtime feature.

**Pull request closed without merging**
