### PR TITLE
Change format + fix for `--richerrors`

### PR DESCRIPTION
**Pull request by vzarytovskii**
For some reason, I didn't include the `--richerrors` flag when committing yesterday.

Also, changed format to use ASCII characters + look a bit more different, in the format:
```
error FSXXXX: <Error message>
  --> /path/to/file.fsx
  1 | let context = error
					^^^^^
```

image

### CODE REVIEW

**Review by psfinaki — APPROVED** [review]
Bubbles are gone, I'm happy

**Comment by edgarfgp** [comment]
What are your thoughts on having something similar to `Gleam` compiler errors. 

Screenshot 2024-08-27 at 14 39 55

**Comment by vzarytovskii** [comment]
> What are your thoughts on having something similar to `Gleam` compiler errors. ?
> 
> 
> 
> Screenshot 2024-08-27 at 14 39 55
> 
> 
> 
> Source: https://gleam.run/news/fault-tolerant-gleam/
> 
> 

This is what we having pretty much, except simpler presentation.

**Comment by edgarfgp** [comment]
> > What are your thoughts on having something similar to `Gleam` compiler errors. ?
> > Screenshot 2024-08-27 at 14 39 55
> > Source: https://gleam.run/news/fault-tolerant-gleam/
> 
> This is what we having pretty much, except simpler presentation. Can change it in further PRs. And as for messaging - we don't have that information at this point. We currently only have number, message and context.

@vzarytovskii 
I guess we could 
- Replace the absolute path with a relative path
- Replace  `-> |`  with `「` to simply this.

Regarding `we don't have that information at this point` 👍 
- Would `ExtendedData to FSharpDiagnostic` help here https://github.com/dotnet/fsharp/pull/15840 ?

**Comment by vzarytovskii** [comment]
> > > What are your thoughts on having something similar to `Gleam` compiler errors. ?
> 
> > > Screenshot 2024-08-27 at 14 39 55
> 
> > > Source: https://gleam.run/news/fault-tolerant-gleam/
> 
> > 
> 
> > This is what we having pretty much, except simpler presentation. Can change it in further PRs. And as for messaging - we don't have that information at this point. We currently only have number, message and context.
> 
> 
> 
> @vzarytovskii 
> 
> I guess we could 
> 
> - Replace the absolute path with a relative path
> 

I can do that where possible.

> - Replace  `-> |`  with `「` to simply this.
> 
> 

I personally think that standard easily typeable symbols read better, but we can try and see how it looks.

> 
> Regarding `we don't have that information at this point` 
> 
> - Would `ExtendedData to FSharpDiagnostic` help here https://github.com/dotnet/fsharp/pull/15840 ? 

I will and it won't at the same time, info from it can be used, but it needs to be plumbed there, and it'll either need to be processed case by case where to put it or provide pairs of range-message to automatically print. In other words there needs to be a new mechanism introduced which will be responsible for providing additional contextual info, which can be printed without the need to know how it's structured.

**Pull request merged**
