### PR TITLE
fix 12142

### PR DESCRIPTION
**Pull request by dsyme**
Second part of fix for https://github.com/dotnet/fsharp/issues/12142

cc @auduchinok

### CODE REVIEW

**Comment by auduchinok** [comment]
@dsyme Shouldn't reference the preview package version, since FCS actually relies on it?

**Comment by auduchinok** [comment]
Yay, the errors finally appear on the CI!

**Comment by auduchinok** [comment]
Ugh, it seems FCS is not compatible with the published FSharp.Core preview either:
Screenshot 2021-09-22 at 15 17 20

I've changed FSharp.Core reference manually to
```
<PackageReference Include="FSharp.Core" Version="5.0.3-beta.21352.5" />
```

**Comment by auduchinok** [comment]
@KevinRansom Could you publish another FSharp.Core preview, please? It's not possible to use a locally built FCS with the published/Microsoft-signed FSharp.Core right now.

**Comment by dsyme** [comment]
@auduchinok We should adjust the compiler code using `#if` to ensure it always builds against a latest published FSharp.Core.

**Comment by dsyme** [comment]
@TIHan @vzarytovskii @brettfo @KevinRansom this is ready

**Review by TIHan — APPROVED** [review]

**Pull request merged**
