### PR TITLE
Update error message of parsMultipleAccessibilitiesForGetSet

### PR DESCRIPTION
**Pull request by nojaf**
Fixes https://github.com/dotnet/fsharp/issues/15423

### CODE REVIEW

**Comment by vzarytovskii** [comment]
I don't think that's right.
Private setter, public getter scenario is very common one. Or am I missing something (looking from my phone)?

**Comment by KevinRansom** [comment]
@nojaf - I believe this is not the correct fix.  
````F#
type Foo() =
    member f.X with internal get (key1, key2) = true and private set (key1, key2) value = ()
    member internal f.Y with get (key1, key2) = true and private set (key1, key2) value = ()
````
If you do not specify the visibility of the property F# allows you specify individual visibilities for the getter and setter, as shown in the X property of the repro.

The reason F# needs this behaviour is for C# interop which also allows, distinct visibilities for the getter or setter, 
E.g.
````C#
        public string ShowSomething { set; private get; } = "Some text value";
````

The Y property has an error because if you specify the visibility of the property, then you are not allowed to specify the visibility of the getters and setters.

I think improving the error message would have been better.  Something like, "When the visibility for a property is specified, setting the visibility of the set or get method is not allowed."

**Review by KevinRansom — COMMENTED** [review]
@nojaf - I believe this is not the correct fix.

type Foo() =
    member f.X with internal get (key1, key2) = true and private set (key1, key2) value = ()
    member internal f.Y with get (key1, key2) = true and private set (key1, key2) value = ()
If you do not specify the visibility of the property F# allows you specify individual visibilities for the getter and setter, as shown in the X property of the repro.

The reason F# needs this behaviour is for C# interop which also allows, distinct visibilities for the getter or setter,
E.g.

        public string ShowSomething { set; private get; } = "Some text value";
The Y property has an error because if you specify the visibility of the property, then you are not allowed to specify the visibility of the getters and setters.

I think improving the error message would have been better. Something like, "When the visibility for a property is specified, setting the visibility of the set or get method is not allowed."

**Review by KevinRansom — CHANGES_REQUESTED** [review]
@nojaf - I believe this is not the correct fix.

type Foo() =
    member f.X with internal get (key1, key2) = true and private set (key1, key2) value = ()
    member internal f.Y with get (key1, key2) = true and private set (key1, key2) value = ()
If you do not specify the visibility of the property F# allows you specify individual visibilities for the getter and setter, as shown in the X property of the repro.

The reason F# needs this behaviour is for C# interop which also allows, distinct visibilities for the getter or setter,
E.g.

        public string ShowSomething { set; private get; } = "Some text value";
The Y property has an error because if you specify the visibility of the property, then you are not allowed to specify the visibility of the getters and setters.

I think improving the error message would have been better. Something like, "When the visibility for a property is specified, setting the visibility of the set or get method is not allowed."

**Comment by nojaf** [comment]
Thanks everyone, I was indeed confused about all of this.
I've updated the error message as @KevinRansom suggested.

**Review by T-Gro — APPROVED** [review]

**Pull request merged**
