### PR TITLE
Some diff minimization for RFC FS-1060

### PR DESCRIPTION
**Pull request by dsyme**

### CODE REVIEW

**Comment by dsyme** [comment]
Does anyone understand the error?
```
D:\a\_work\1\s\vsintegration\ItemTemplates\CodeFile\CodeFile.csproj : error NU1301: Failed to verify the root directory of local source 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json'. [D:\a\_work\1\s\VisualFSharp.sln]
D:\a\_work\1\s\vsintegration\ItemTemplates\AppConfig\AppConfig.csproj : error NU1301: Failed to verify the root directory of local source 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json'. [D:\a\_work\1\s\VisualFSharp.sln]
D:\a\_work\1\s\vsintegration\ItemTemplates\ResourceFile\ResourceFile.csproj : error NU1301: Failed to verify the root directory of local source 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json'. [D:\a\_work\1\s\VisualFSharp.sln]

```

**Review by KevinRansom — APPROVED** [review]

**Comment by T-Gro** [comment]
Am I missing any major change-category apart from this list?

- usage of MaybeNull type alias
- usage of Null / NonNull active patterns , and 'nonNull' conversion func
- where possible, replacing Unchecked.defaultOf with 'null'
- cosmetics in array and list declaration style

**Review by T-Gro — APPROVED** [review]

**Comment by dsyme** [comment]
> Am I missing any major change-category apart from this list?

That's about it I think!

**Comment by dsyme** [comment]
Another odd error, only on Mac, is this a heisenerror?

```
2023-04-29T00:00:15.3506910Z System.Exception: Failed: 1
2023-04-29T00:00:15.3507600Z    at <StartupCode$AssemblyVersion03>.$AssemblyVersion03.main@()
2023-04-29T00:00:15.3508330Z    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
2023-04-29T00:00:15.3509080Z    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
2023-04-29T00:00:15.3509820Z -------
2023-04-29T00:00:15.3604960Z [xUnit.net 00:01:14.68]     FSharp.Compiler.ComponentTests.Conformance.DeclarationElements.CustomAttributes.AttributeUsage.AssemblyVersion03_fs(compilation: AssemblyVersion03.fs) [FAIL]
```

**Pull request merged**
