### PR TITLE
fix boxing promotion for locally mutable values

### PR DESCRIPTION
**Pull request by dsyme**
Should prevent us doing the reversion in https://github.com/dotnet/fsharp/pull/11686 and instead address the issue noted with the PR

### CODE REVIEW

**Comment by dsyme** [comment]
@kerams This contains some other cleanup to your PR which will change generated names etc.

**Comment by dsyme** [comment]
@kerams I was very surprised to see that changing


```fsharp
let [<Literal>] suffixForTupleElementAssignmentTarget = "tupleElem"
```
to my preferred
```fsharp
let [<Literal>] suffixForTupleElementAssignmentTarget = "$tupleElem"
```

causes the `Branching let binding rhs does not prevent tuple elimination` test to fail.  Do you have any idea why that might be the case? I'd really rather we have a `$` in that generated name

**Comment by dsyme** [comment]
@kerams I worked out the thing I just mentioned, was difference between DisplayName and LogicalName.  Best to use LogicalName in anything related to optimiziation

**Review by brettfo — APPROVED** [review]

**Comment by vzarytovskii** [comment]
Some of the changes (in tests) may be conflicting when https://github.com/dotnet/fsharp/pull/11690 is merged.

**Pull request merged**
