### PR TITLE
Language Service prefers original parse results

### LINKED ISSUE #14269: Type hints break for some tuple cases
Yaay, first F# hints bug!

**Repro steps**

Here is the code leading to crashes.
```fsharp
module Test =
    let test() =
        fun (a, (b, c)) -> (a, b, c)
```

**Expected behavior**

At least no crash, at best the actual hints.

**Actual behavior**

Crash.

**Known workarounds**

Turn off type hints.

### PR DESCRIPTION
**Pull request by psfinaki**
See @dsyme's comment down below.

### CODE REVIEW

**Comment by psfinaki** [comment]
@dotnet/fsharp-team-msft and maybe @dsyme, please see the description and look carefully :) either I have identified some useless code deep down in the repo, or this is actually some corner case that might be useful for some other scenarios.

I mean, either way, `assert false` is not the best thing to do in code, but we might want to adjust things here instead of just deleting the logic.

**Comment by kerams** [comment]
The error message would indicate some unexpected weirdness with node ranges. [`fun ((a, b), c) -> ()`](https://sharplab.io/#v2:DYLgZgzgNALiCGEZQCYgNQB8wFcB2ABABRHxQEBGAlOQMZUEC0AfMVUA) AST is not what I would have expected for instance.

**Comment by dsyme** [comment]
Yeah the problem is that `fun ((a, b), c) -> ...` "pushes" the `(a,b)` pattern to the right hand side of the `fun` during parsing, rather than during checking. Giving

    fun (_arg1, c) -> match _arg1 with (a, b) -> ...

When this happens the ranges associated with the synthetic `_arg1` and/or the `match` are then both claiming a position.

OK so for `SynExpr.Lambda` the original parse information is held in `parsedData` holding the original (`args`, `body`) before the above is done.  See https://github.com/dotnet/fsharp/blob/main/src/Compiler/SyntaxTree/SyntaxTree.fsi#L646

So @psfinaki I think the solution is to systematically have **all** the non-typechecking SyntaxTree traversals work over the `parsedData` rather than the `args`/``body`.   

That is, we should go through all the SyntaxTree travels walking over SynExpr.Lambda and adjust them to do sub-tree traversals on `parsedData` rather than the immediately available `args` and `body`.

I think this will then make the trees look OK and you should be able to keep the assert I think

Add a comment to the assert point out that you can analyse parse trees using sharplab.io or the Fantomas tools, and that the problem may be to do with some synthetic transfomation happening after parsing.

**Comment by kerams** [comment]
Out of curiousity, what's the rationale behind such a transformation?

**Comment by nojaf** [comment]
A bit of a heads up here, the `body` or `parsedData` isn't perfect.
Some [examples](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWTwCuyYAFAGUUAcxqwALqz5UATiICUYALQA%2BAQoA6szcm26effv264wANwXZ%2BKCWABUYWwqVqN%2BvTuSGwwMAElkOAAPMABeJzAAXxV1fgVIECigA) where you still have `_arg` in `Match` expressions.

**Comment by dsyme** [comment]
@nojaf looks like we should address those too, whether as part of this PR or separate

**Pull request closed without merging**
