### PR TITLE
Add trimming XML files to FSharp.Core.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**
Contributes to #12819.

This PR adds two XML files as embedded resources in `FSharp.Core` that when trimming instruct the linker to:

* Remove the optimization and signature info blobs from the assembly, yielding an easy 1.2 MB size reduction.
* Remove instances of all attributes declared in `FSharp.Core` if the [`_AggressiveAttributeTrimming` feature switch](https://github.com/dotnet/runtime/blob/main/docs/workflow/trimming/feature-switches.md#:~:text=_AggressiveAttributeTrimming) is enabled. Only four of the fifty one attributes are accessed at runtime by `FSharp.Core`, and by removing them we might observe different behavior ([or maybe not](https://github.com/dotnet/runtime/blob/main/docs/workflow/trimming/ILLink-files.md#:~:text=However%2C%20if%20the%20trimming%20tool%20encounters%20code%20that%20is%20trying%20to%20read%20the%20attribute%20at%20runtime%2C%20it%20doesn%27t%20trim%20the%20attribute%20instances.)), but the feature switch's documentation allows them.

### CODE REVIEW

**Comment by vzarytovskii** [comment]
@teo-tsirpanis question - trimming is opt-in now, right?

**Review by vzarytovskii — APPROVED** [review]

**Comment by teo-tsirpanis** [comment]
Yes, it can be enabled only on self-contained deployments, but [since .NET 7 all assemblies are trimmed by default](https://docs.microsoft.com/en-us/dotnet/core/compatibility/deployment/7.0/trim-all-assemblies) if we enable trimming.

**Comment by vzarytovskii** [comment]
@teo-tsirpanis so, what would be a default behaviour now for the app which packages FSharp.Core in .NET7? Will it be trimming resources and attributes if it's an aggressive mode?

**Comment by dsyme** [comment]
@teo-tsirpanis What automated testing can we have for this?

**Comment by teo-tsirpanis** [comment]
@vzarytovskii yes, the resources will be trimmed away always if trimming is enabled; [these resource files are used only by the compiler](https://grep.app/search?q=FSharpOptimizationInfo&filter[lang][0]=F%23).

@dsyme no, the repository doesn't seem to have any tests related to trimmability at all.

**Comment by vzarytovskii** [comment]
> @vzarytovskii yes, the resources will be trimmed away always if trimming is enabled; [these resource files are used only by the compiler](https://grep.app/search?q=FSharpOptimizationInfo&filter%5Blang%5D%5B0%5D=F%23).
> 

Yeah, I understand that. What about annotating library itself - can we somehow put some attribute on types/members to mark them safe/unsafe to trim?

**Comment by teo-tsirpanis** [comment]
> What about annotating library itself

This is part 2 of #12819. I started doing it and will submit it in a separate PR. Can't do 100% of it though, it gets extremely tedious after one point with no clear cost-to-benefit ratio.

Trimming away the resources and paving the way to remove the attributes is the trimming enhancement I am more interested in.

**Review by KevinRansom — CHANGES_REQUESTED** [review]
There is the ability to compress the sig and optdata files, the names are different, we will be moving over to compressed metadata for FSharp.Core shortly.

````
    <resource name="FSharpOptimizationInfo.FSharp.Core" action="remove" />
    <resource name="FSharpSignatureInfo.FSharp.Core" action="remove" />
````
Also include:
````
    <resource name="FSharpOptimizationCompressedData.FSharp.Core" action="remove" />
    <resource name="FSharpSignatureCompressedData.FSharp.Core" action="remove" />
````

**Comment by teo-tsirpanis** [comment]
Done.

**Review by KevinRansom — APPROVED** [review]
Thanks

**Comment by dsyme** [comment]
> [@dsyme](https://github.com/dsyme) no, the repository doesn't seem to have any tests related to trimmability at all.

@vzarytovskii Can we have them added please? :))

**Comment by vzarytovskii** [comment]
> > [@dsyme](https://github.com/dsyme) no, the repository doesn't seem to have any tests related to trimmability at all.
> 
> @vzarytovskii Can we have them added please? :))

We can, I'm not entirely sure what we would like test though. Just the lack of resources and types in resulting assembly after trimming? I guess it will make more sense to add such tests to trimmer instead.

This will also involve the whole SDK (as oppose to just running fsc most of the times).

**Comment by dsyme** [comment]
> We can, I'm not entirely sure what we would like test though. Just the lack of resources and types in resulting assembly after trimming? I guess it will make more sense to add such tests to trimmer instead.

I guess, we would test whether a trim of a simple app compiles, runs and the binary size is below some threshold.  If it goes above, we should fail the test, forcing us to adjust a baseline if we regress

It would be ok to use the SDK we're compiling with to do this, as long as it's compiling with our compiler and using our FSHarp.Core.

**Comment by vzarytovskii** [comment]
@teo-tsirpanis @dsyme I've added a new leg which will use locally built compiler and FSharp.Core in the project, and will publish and check trimmed build. @teo-tsirpanis can you please take a look if it makes sense.

Let's see if it passes the CI, since I've probably broken something in yml.

The program itself is just a hello world, please feel free to add more FSharp.Core functions.

**Comment by vzarytovskii** [comment]
On a second thought, we should probably test for exact size of the FSharp Core, and not <=

**Comment by teo-tsirpanis** [comment]
Exact size? That sounds super brittle. What I had in mind was to check if the optimization and signature data resources are present in the FSharp.Core assembly (which is in the strictest sense what we want to check in this PR).

A more complex idea I thought of is to somehow monitor the ~~trimmed size (less objective; what constitutes an average F# app?)~~ number of trimming warnings on FSharp.Core and alert us if they increased.

**Comment by vzarytovskii** [comment]
> Exact size? That sounds super brittle. 

I would like us to check for exact size it because we would like understand why the change (either codegen change, or framework upgrade) caused the trimming size change.

> What I had in mind was to check if the optimization and signature data resources are present in the FSharp.Core assembly (which is in the strictest sense what we want to check in this PR).

This will be implicit, I've checked that optimization and signature data are not in the resources. If this will ever change, the size check will fail. I will also add matrix to check both compressed and uncompressed resources.

> A more complex idea I thought of is to somehow monitor the ~trimmed size (less objective; what constitutes an average F# app?)~ number of trimming warnings on FSharp.Core and alert us if they increased.

I did not see any trimming warnings for this particular test yet, I can enable warnings as errors, and as we evolve this particular test suite, we can see if we hit any.

I will make the check explicit - check for exact size, let's see if it's too painful for us. We can change it any moment.

**Comment by vzarytovskii** [comment]
Ok, I think I know why.
My local build was rolled forward to rc1, and remote one was on p6

**Pull request merged**
