### PR TITLE
string interpolation tests

### PR DESCRIPTION
**Pull request by yatli**
Ramping up. This is work-in-progress, and I'll try to work on general interpolation tests, negative cases, and the performance.

@dsyme @catermp it would be great if you can give me some guidance:

- ~~How to run specific tests on Linux? `build.sh --help` doesn't reveal the correct knob to tweak.~~
- ~~There's one case that I'm sure it'll fail, but running `build.sh --test` gives me 100% pass. The new test isn't run?~~ 
- Edit: test on Windows.

Thanks!

### CODE REVIEW

**Comment by yatli** [comment]
The case I referred to that should not pass:

image

**Comment by yatli** [comment]
hmm the tests are indeed triggered in CI.
https://dev.azure.com/dnceng/public/_build/results?buildId=603685&view=ms.vss-test-web.build-test-results-tab&runId=18985580&resultId=100585&paneView=debug

**Comment by dsyme** [comment]
> The case I referred to that should not pass:

Ah yes, thank you.  Hmm....

**Comment by yatli** [comment]
Tests all good except `sprintf $""` produces null

**Comment by dsyme** [comment]
Thanks!!

**Pull request merged**
