### PR TITLE
Yeet FCS folder

### PR DESCRIPTION
**Pull request by KevinRansom**
Now that build and testing for FCS is incorporated into the main repo, there is no longer any requirement for the fcs folder.

### CODE REVIEW

**Comment by baronfel** [comment]
The FCS samples (which need to be updated for non-WCF communication methods) are called out in several of the FCS docs, so we'd need to rewrite those docs or update those samples before I'd feel ok just yeeting them.

**Comment by baronfel** [comment]
It would also be good to bring in the ReleaseNotes from this directory to serve as the core of the release notes mechanism that @cartermp spoke about on our shared call.

**Comment by KevinRansom** [comment]
@baronfel I am working on the release notes as we speak.

**Comment by KevinRansom** [comment]
@cartermp , @brettfo , @vzarytovskii Can we get an approve on this pls.

Thanks

**Comment by auduchinok** [comment]
@KevinRansom The FCS solution is the one we work with and we cannot currently work with the other ones.

@cartermp approved bringing it back in DM, but I'm not sure where to place it at. Having the `fcs` folder would allow using `Directory.Build.props` file to set `FSHARPCORE_USE_PACKAGE` in this solution without affecting FSharp.sln and VisualFSharp.sln. Do you have any other ideas of how it could be achieved?

**Comment by KevinRansom** [comment]
What do you mean work with?  What is the trouble with the one found here:  https://github.com/dotnet/fsharp/tree/main/src/fsharp/FSharp.Compiler.Service

I for sure don't want to go back to having a separate build for the fcs that is idiosyncratic and fails a lot.  So what is it about the replacement project that you can't "work with"?

**Comment by auduchinok** [comment]
@KevinRansom Thanks for your reply!

> What do you mean work with?

We've been working with fcs/FSharp.Compiler.Service.sln solution exclusively, and there were few issues with FSharp.sln and VisualFSharp.sln for us.

> What is the trouble with the one found here:
> https://github.com/dotnet/fsharp/tree/main/src/fsharp/FSharp.Compiler.Service

No trouble with the FCS project itself, it's about the solutions with extra projects and FSharp.Core project reference instead of a package one.

> I for sure don't want to go back to having a separate build for the fcs that is idiosyncratic and fails a lot.

I'm not suggesting a separate build at all. It's only about having a minimal solution to work on FCS without FSharp.Core back.

**Comment by KevinRansom** [comment]
@auduchinok --- does this not work for you:  https://github.com/dotnet/fsharp/blob/main/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj#L737

````
  <ItemGroup Condition="'$(FSHARPCORE_USE_PACKAGE)' != 'true'">
    <ProjectReference Include="$(MSBuildThisFileDirectory)..\FSharp.Core\FSharp.Core.fsproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(FSHARPCORE_USE_PACKAGE)' == 'true'">
    <PackageReference Include="FSharp.Core" Version="$(FSharpCorePreviewPackageVersion)" />
  </ItemGroup>
````
If you want to add an fcs solution, with just the fcs project and tests in it, then put it alongside fsharp.sln and visualfsharp.sln.  should be fine.

Kevin

**Comment by auduchinok** [comment]
@KevinRansom Thanks. I might me missing something but how do I make this property set for FCS solution only?

**Pull request merged**
