### PR TITLE
Parens: tweak sensitive indentation handling

### PR DESCRIPTION
**Pull request by brianrourkeboll**
Another followup to #16079.

- Dedent by one space in certain scenarios.

There are certain cases where we must consider both the context outside of a pair of parentheses as well as the inside in order to reintegrate the inner construct into the outer context after removing the parentheses. That is, sometimes we cannot simply remove the parentheses in place, but we must instead shift the entire parenthesized multiline expression left by one space.

For example:

```fsharp
let _ =
    1,
    (true
     || false
     || true),
    1
```

must become

```fsharp
let _ =
    1,
    true
    || false
    || true,
    1
```

not

```fsharp
let _ =
    1,
     true
     || false
     || true,
    1
```

Or here's a real-world example from FSharp.Core:

https://github.com/dotnet/fsharp/blob/9e7ec64cb62e93cde77cbd33b6ec79e4d9e18cb2/src/Compiler/Utilities/sformat.fs#L891-L901

### CODE REVIEW

**Review by psfinaki — APPROVED** [review]
Cool, thanks!

**Comment by brianrourkeboll** [comment]
Hmm, I think I see one bug... Let me fix that.

**Comment by brianrourkeboll** [comment]
Tricky, tricky:

https://github.com/dotnet/fsharp/blob/9a0b9bfeecc6cd248887ba26753cf0fba96bbc40/src/FSharp.Core/eventmodule.fs#L74-L79

**Comment by brianrourkeboll** [comment]
Expect some more PRs after this one, unfortunately—running fix-all on FSharp.Core is surfacing some other oddities I hadn't thought of, like the fact that parens aren't needed after `new` in this:

```fsharp
type T (x, y) =
    new (x) = T (x, 3) // Can remove parens: `new x = T (x, 3)`.
```

or in this:

```fsharp
type T (x, y) =
    new (x, y, z) = T (x, y)
    new (x) = T (x, 3) // Can remove parens: `new x = T (x, 3)`.
```

but they _are_ required if there's another constructor and it comes _after_:

```fsharp
type T (x, y) =
    new (x) = T (x, 3) // Cannot remove; removing the parens causes parse errors below.
    new (x, y, _z) = T (x, y)
```

Or the fact that this is fine:

```fsharp
type C = abstract M : unit -> unit
let _ = { new C with override _.M () = () } // I.e., `override _.M (())` can be simplified to `override _.M ()`
```

but this requires `(())` for the override:

```fsharp
type C<'T> = abstract M : 'T -> unit
let _ = { new C<unit> with override _.M (()) = () }
```

Real example:

https://github.com/dotnet/fsharp/blob/9a0b9bfeecc6cd248887ba26753cf0fba96bbc40/src/FSharp.Core/printf.fs#L1074-L1078

**Comment by psfinaki** [comment]
We are totally ready for the followups :) 
Yeah looks like you are facing more and more inconsistencies in the compiler... Feel free to create issues about those, we might do something with the parser to eliminate some root causes.

**Comment by psfinaki** [comment]
@brianrourkeboll this LGTM - is there anything else you plan to add here?

**Review by T-Gro — APPROVED** [review]

**Comment by brianrourkeboll** [comment]
> @brianrourkeboll this LGTM - is there anything else you plan to add here?

Nope, this one should be all set.

**Comment by majocha** [comment]
It seems this test case started to fail at some point:

https://github.com/dotnet/fsharp/blob/9e357ca5f82f5e800b259cbda7d91507b41d2e9a/vsintegration/tests/FSharp.Editor.Tests/CodeFixes/RemoveUnnecessaryParenthesesTests.fs#L784-L790


Apparently because it's not being caught by the diagnostics.

**Pull request merged**
