### PR TITLE
Report merged identifiers in copy-and-update to the sink

### PR DESCRIPTION
**Pull request by kerams**
Fixes https://github.com/dotnet/fsharp/issues/15696.

### CODE REVIEW

**Comment by psfinaki** [comment]
@kerams you are breaking GitHub with the name of your branch :D

image

**Comment by edgarfgp** [comment]
It would be good to add some tests to [Symbols.fs](https://github.com/dotnet/fsharp/blob/6ed38fcb360a0015828973b1f32cd2ea6b58c6ad/tests/service/Symbols.fs) ?

**Comment by kerams** [comment]
The current preview also can't handle

```fsharp
type RecordA<'a> = { Foo: 'a; Bar: int; Zoo: RecordA<'a> }

let fz (a: RecordA<int>) = { a with Zoo.Foo = 21; Zoo.Zoo.Bar = 33; Zoo.Bar = 22 }
```

and doesn't show completions for

```fsharp
let g (a: RecordA<RecordA<int>>) = { a with Foo.F| }
```

These issues have been taken care of too. I suggest we keep the feature in preview for .NET 8 as there might be further subtle problems.

**Comment by vzarytovskii** [comment]
> The current preview also can't handle
> 
> ```fsharp
> type RecordA<'a> = { Foo: 'a; Bar: int; Zoo: RecordA<'a> }
> 
> let fz (a: RecordA<int>) = { a with Zoo.Foo = 21; Zoo.Zoo.Bar = 33; Zoo.Bar = 22 }
> ```
> 
> and doesn't show completions for
> 
> ```fsharp
> let g (a: RecordA<RecordA<int>>) = { a with Foo.F| }
> ```
> 
> These issues have been taken care of too. I suggest we keep the feature in preview for .NET 8 as there might be further subtle problems.

I think it's fine if we put it under 8, it will motivate us to use it and we'll uncover issues faster.

**Comment by kerams** [comment]
It's your call whether the quality meets the bar ;).

**Pull request merged**
