### PR TITLE
Fix crash in DOTNET_SYSTEM_GLOBALIZATION_INVARIANT mode

### LINKED ISSUE #16272: ERROR: First Error Message: Error MSB6006. "dotnet.exe" exited with code -532462766.
I've had no clue what's the problem is until I found this in event viewer.
```
Application: dotnet.exe
CoreCLR Version: 8.0.23.47906
.NET Version: 8.0.0-rc.2.23479.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
en-US is an invalid culture identifier.
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at FSharp.Compiler.Driver.main1(CompilationThreadToken ctok, String[] argv, LegacyReferenceResolver legacyReferenceResolver, Boolean bannerAlreadyPrinted, ReduceMemoryFlag reduceMemoryUsage, CopyFSharpCoreFlag defaultCopyFSharpCore, Exiter exiter, IDiagnosticsLoggerProvider diagnosticsLoggerProvider, DisposablesTracker disposables) in C:\MSBFU\visualfsharp\src\Compiler\Driver\fsc.fs:line 490
   at FSharp.Compiler.Driver.CompileFromCommandLineArguments(CompilationThreadToken ctok, String[] argv, LegacyReferenceResolver legacyReferenceResolver, Boolean bannerAlreadyPrinted, ReduceMemoryFlag reduceMemoryUsage, CopyFSharpCoreFlag defaultCopyFSharpCore, Exiter exiter, IDiagnosticsLoggerProvider loggerProvider, FSharpOption`1 tcImportsCapture, FSharpOption`1 dynamicAssemblyCreator) in C:\MSBFU\visualfsharp\src\Compiler\Driver\fsc.fs:line 1197
   at FSharp.Compiler.CommandLineMain.main(String[] argv) in C:\MSBFU\visualfsharp\src\fsc\fscmain.fs:line 84
   at FSharp.Compiler.DiagnosticsLogger.DiagnosticsLoggerExtensions.ReraiseIfWatsonable(Exception exn) in C:\MSBFU\visualfsharp\src\Compiler\Facilities\DiagnosticsLogger.fs:line 419
   at FSharp.Compiler.DiagnosticsLogger.DiagnosticsLoggerExtensions.DiagnosticsLogger.ErrorRecovery(DiagnosticsLogger x, Exception exn, Range m) in C:\MSBFU\visualfsharp\src\Compiler\Facilities\DiagnosticsLogger.fs:line 470
   at FSharp.Compiler.DiagnosticsLogger.errorRecovery(Exception exn, Range m) in C:\MSBFU\visualfsharp\src\Compiler\Facilities\DiagnosticsLogger.fs:line 571
   at FSharp.Compiler.CommandLineMain.main(String[] argv) in C:\MSBFU\visualfsharp\src\fsc\fscmain.fs:line 101
```
While it's dotnet problem FSC should be less error-prone and do not crash randomly.
But catch exceptions at the highest level and report them clearly.

### PR DESCRIPTION
**Pull request by auduchinok**
Fixes #16272.

Applies the same fix as in https://github.com/dotnet/msbuild/pull/8738 to prevent crashing when `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT` is set.

### CODE REVIEW

**Comment by vzarytovskii** [comment]
Can this be auto-tested somehow?

**Comment by auduchinok** [comment]
> Can this be auto-tested somehow?

Calling the `fsc` on Windows with `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT` and non-ASCI locale should throw the exception from https://github.com/dotnet/msbuild/pull/8738. I'm not sure what is the easiest way to add a test for it in the compiler repo. Could help me with that, please?

**Comment by vzarytovskii** [comment]
> > Can this be auto-tested somehow?
> 
> Calling the `fsc` on Windows with `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT` and non-ASCI locale should throw the exception from [dotnet/msbuild#8738](https://github.com/dotnet/msbuild/pull/8738). I'm not sure what is the easiest way to add a test for it in the compiler repo. Could help me with that, please?

Not entirely sure tbh. The only tests we invoke with FSC are F#QA. And we don't really want to add anything to the suite.

**Review by T-Gro — APPROVED** [review]

**Comment by T-Gro** [comment]
Can we get a standalone proof please?
Automatic test not needed in my opinion, just a proof of manual testing .

**Comment by auduchinok** [comment]
> Can we get a standalone proof please?

Hm, I wasn't able to reproduce it myself. I'll ask @mfilippov (i.e. the author of the original MSBuild fix) later if there's a simple repro when he's back from vacation.

**Comment by mfilippov** [comment]
Yes, it is easy to reproduce. Just set locale for Unicode program different from US.
image

**Comment by 0101** [comment]
@auduchinok were you able to confirm the fix works using the repro steps?

**Comment by auduchinok** [comment]
AFAIK it helps, yes.

**Review by 0101 — APPROVED** [review]

**Comment by psfinaki** [comment]
@auduchinok please move the release notes to the next version 👀

**Pull request merged**
