### PR TITLE
Possible fix for 9962

### PR DESCRIPTION
**Pull request by dsyme**
Possible fix for https://github.com/dotnet/fsharp/issues/9702 and https://github.com/dotnet/fsharp/issues/9962

TODO: 

* [ ] add tests

### CODE REVIEW

**Comment by dsyme** [comment]
Yes this fixes  #9962 and I'd expect #9702 as well

I'm on 80% vacation tis week so not really rev'ving to do the hard work to submit tests for this as well.  Does anyone want to check if #9702 is fixed and add tests to this PR?   Otherwise I'll do it when back at work

**Comment by cartermp** [comment]
@dsyme probably unrelated but might be worth looking into as well: https://github.com/dotnet/fsharp/issues/6411

**Comment by dsyme** [comment]
@cartermp 

> @dsyme probably unrelated but might be worth looking into as well: #6411

yes  - I've confirmed this is a different issue

**Review by cartermp — APPROVED** [review]
We'll need to develop a good way to test this "generate in release mode" kind of stuff. Given that this fixes the issue i'd rather get this in now and we can address the testing issue separately as we work to modernize our tests.

**Pull request merged**
