### PR TITLE
Remove unnecessary .NET Standard 1.x packages.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**
A continuation of #8898 (which was subsequently reverted for some reason) but on the entire repository, this PR removes references to NuGet packages from the .NET Standard 1.x era, reducing the amount of transitive dependencies of projects. I also updated two packages to versions that bring less of them, and a notice to `Versions.props` that discourages adding more of these legacy packages.

### CODE REVIEW

**Review by KevinRansom — APPROVED** [review]
I think these were all necessary when we still built netstandard 1.6.  But probably serve no useful purpose now.

Thanks

**Comment by teo-tsirpanis** [comment]
CI currently fails because of some version conflicts caused by the removed packages. They will be fixed by updating dependencies to versions that target .NET Standard 2.0 which I will do later (couldn't catch it earlier, building fails on my machine with compiler errors).

**Comment by vzarytovskii** [comment]
We will likely have to roll this one back, it causes build issues when merging yo 17.4

**Comment by teo-tsirpanis** [comment]
What fails? Is there a log publicly available?

**Comment by vzarytovskii** [comment]
@teo-tsirpanis 
> What fails? Is there a log publicly available?

Yeah, this is the merge PR:
https://github.com/dotnet/fsharp/pull/13917
Here's run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=20083&view=results

I will need to take a closer look at it. I think our packages diverge in main and 17.4.

**Comment by teo-tsirpanis** [comment]
I don't think this PR is to blame. That PR fails because the property `$(MicrosoftCodeAnalysisWorkspacesCommonVersion)` is not defined.

**Comment by vzarytovskii** [comment]
> I don't think this PR is to blame. That PR fails because the property `$(MicrosoftCodeAnalysisWorkspacesCommonVersion)` is not defined.

Yeah, it seems just a weird merge resolution across multiple PRs

**Pull request merged**
