### PR TITLE
Reduce optData scope in case of <Optimize>false</>

### PR DESCRIPTION
**Pull request by T-Gro**
This PR is a natural follow-up on https://github.com/dotnet/fsharp/pull/15325, especially a resolution to this comment https://github.com/dotnet/fsharp/pull/15325#issuecomment-1609427389 .

Since F# Optimizer is capable of inlining across assembly boundaries, it means that dependent assemblies must be up to date even at build time, not just runtime.
This does make sense for things which are a must have for inlining - SRTP constraints or in general bindings marked with the `inline` keyword.

However, most of the other bindings in F# have an inlining flag of `ValInline.Optional`, leaving it to the F# optimizer whether to inline them or not. Which means that all regular bindings are part of optimization data, and can in theory be inlined across assembly boundaries.

That would however mean that except for places where inlining is not allowed (externs, constructors, virtual calls,..), even the smallest change of a function body would lead to a different reference assembly and therefore a full rebuild of the dependency graph. => the ref assembly feature usefulness would drastically reduce for F#.

This PR proposes to keep the optimization data used for cross-assembly inlining to a minimum (= Vals which must get inlined)  **only if** optimizations are turned off (which is also the default when debugging).

The natural disadvantage is that in case of depending on cross-assembly-inlined bindings (which were not marked as inline), the runtime will probably be slower.
That is why this setting is explicitly restricted to the  Optimize=false configuration.

### CODE REVIEW

**Comment by baronfel** [comment]
How does this change impact the debug stepping experience? Based on what you wrote I'd expect to see more 'normal' calls between methods, which the debugger is good about following. There would be less compiler-emitted 'patch up' debug stepping due to less overall inclining I'd expect - is that an accurate statement?

**Comment by T-Gro** [comment]
> How does this change impact the debug stepping experience? Based on what you wrote I'd expect to see more 'normal' calls between methods, which the debugger is good about following. There would be less compiler-emitted 'patch up' debug stepping due to less overall inclining I'd expect - is that an accurate statement?


That is true, as the inlining (in Debug) would not happen unless the binding is explicitly marked as "inline".
Important to manage expectations for this PR - the change here only affects cross-assembly inlining.

**Comment by KevinRansom** [comment]
I think I prefer for us to be able to test optimization data generation in debug builds.

I find the fsharp.core exception a bit tricky:  '$(PackageId)' != 'FSharp.Core' given that the edited target file is in the shipped SDK rather than a specific modification in our own build, which is where we care about building fsharp.core.

The metadata in the reference assemblies must be the same as the metadata in the implementation assemblies, otherwise the ref assemblies are not 'accurate ref assemblies'.  And I believe that developers may want to ship debug build packages that support the additional performance benefits of cross assembly inlining.  We apparently want that for 'FSharp.Core' hence the build exception.

All in all this optimization of not rebuilding assemblies because of edits to private implementation, which makes perfect sense in C# which relies on the JIT for inlining and has the visibility of private values encoded in the IL seems a bit of a stretch for F#.

The additional complexity that implementing these PRs have caused is somewhat disquieting to me.

**Review by KevinRansom — CHANGES_REQUESTED** [review]
We should discuss this further.

**Comment by T-Gro** [comment]
Even with this change, the optimization data is still being computed and used to full extend within a single assembly.
What this switch does is a plain filter after the generation is finished, to reduce what goes into the IlResource for cross-assembly generation.

It is obviously a tradeoff for starting run/test/debug session faster, but not having F#-provided-cross-assembly-inlining, and only having the one JIT can do.


And **yes**, this change (assuming the conditions are met) affects both implementation and ref assemblies the same way- they are created in a single pass together given the current defaults.

**Review by vzarytovskii — APPROVED** [review]

**Review by 0101 — APPROVED** [review]

**Pull request merged**
