### PR TITLE
Nullness - SDK prop alignment with C# - <Nullable> 

### PR DESCRIPTION
**Pull request by T-Gro**
This aligns the project setting needed to turn on nullability analysis and warnings.
Possible values are `<Nullable>enable,/>` and `<Nullable>disable</>`.

This first needs https://github.com/dotnet/fsharp/pull/15310#pullrequestreview-2212600397 to be merged in order to suceed, since that PR adds "bootstrapped Fsharp.Build" to the proto mechanism.

### CODE REVIEW

**Review by baronfel — APPROVED** [review]
Lovely! Thank you for aligning this to the existing values.

**Comment by baronfel** [comment]
Related question - for the F# new project templates in the SDK, do you want to default `<Nullable>enable</Nullable>`? If so that would need to be done ASAP.

**Comment by T-Gro** [comment]
> Related question - for the F# new project templates in the SDK, do you want to default `<Nullable>enable</Nullable>`? If so that would need to be done ASAP.

Thanks for reminding, but I think we should wait for more stabilization + bug fixing first.

@vzarytovskii : Agree?

**Comment by baronfel** [comment]
It's late enough in the cycle that you could definitely wait and make the change for the .NET 10 release, no worries :)

**Comment by vzarytovskii** [comment]
> > Related question - for the F# new project templates in the SDK, do you want to default `<Nullable>enable</Nullable>`? If so that would need to be done ASAP.
> 
> 
> 
> Thanks for reminding, but I think we should wait for more stabilization + bug fixing first.
> 
> 
> 
> @vzarytovskii : Agree?
> 
> 

Yep, let's not default it just yet

**Review by abonie — APPROVED** [review]

**Pull request merged**
