### PR TITLE
Add section about compiler tools.

### PR DESCRIPTION
**Pull request by nojaf**
Added some links to useful online tools when working on the compiler.
Let me know if you want to see anything differently.

### CODE REVIEW

**Review by cartermp — APPROVED** [review]

**Comment by abelbraaksma** [comment]
Good addition! You could add that you can configure fsi as well to output the syntax tree.

**Comment by cartermp** [comment]
image

🙃

**Comment by abelbraaksma** [comment]
@cartermp, maybe we can set a filter on the build server to skip running all builds and tests for changes to MD files?

**Comment by cartermp** [comment]
Yes, I think that would be good. I don't know how to do that though. @brettfo ?

**Comment by brettfo** [comment]
Reading the docs there is a way to skip pr builds if only certain files were changed, but it only supports wildcards in the path, not in the file name.  E.g., we could add a skip on `docs/*`, but not `**/*.md`, which is what we really want.

**Comment by abelbraaksma** [comment]
@brettfo, interesting, as I remember changes to `*.md` in the runtime repo where the build doesn't kick in, but perhaps these were indeed in some docs directory. 

But: there's only a handful of `*.md` files here, wouldn't it work if we specify the exact filenames? If this itself goes into a config file, we can always add new ones there, or start placing things in a `docs` dir.

**Comment by abelbraaksma** [comment]
Just found that for the `runtime` repo they've included root `*.md` files to **not trigger** a build, here's an example of such PR with 0 checks: https://github.com/dotnet/runtime/pull/37322.

**Comment by brettfo** [comment]
@abelbraaksma Thanks for the digging.  I looked at their internal build definition to see what `.yml` file they're using and created #10189.

**Comment by brettfo** [comment]
@cartermp Are we just waiting on the broken CI to merge this?  If so feel free to bring it in, or if you don't have admin powers I'll fix that (so you can merge with failing checks).

**Comment by cartermp** [comment]
image

**Comment by cartermp** [comment]
:)

**Pull request merged**
