### PR TITLE
fix records in multiemit

### PR DESCRIPTION
**Pull request by dsyme**
Fixes the regression here: https://github.com/dotnet/fsharp/issues/12886

Also deletes tests/fsharp/core/printing/*.txt files which should never have been added

### CODE REVIEW

**Comment by dsyme** [comment]
Heisen failure:
```
Processing D:\a\_work\1\s\global.json
Move-Item : Access to the path 'C:\Users\cloudtest\.netcoreeng\native\bin\perl\5.32.1.1.tmp' is denied.
At D:\a\_work\1\s\eng\common\native\CommonLibrary.psm1:382 char:5
+     Move-Item -Path $TempOutputDirectory -Destination $OutputDirector ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\cloudt...rl\5.32.1.1.tmp:DirectoryInfo) [Move-Item], IOException
    + FullyQualifiedErrorId : MoveDirectoryItemIOError,Microsoft.PowerShell.Commands.MoveItemCommand
 
at <ScriptBlock>, D:\a\_work\1\s\eng\common\native\install-tool.ps1: line 103
at <ScriptBlock>, D:\a\_work\1\s\eng\common\init-tools-native.ps1: line 103
at <ScriptBlock>, D:\a\_work\1\s\eng\common\init-tools-native.ps1: line 80
at InitializeNativeTools, D:\a\_work\1\s\eng\common\tools.ps1: line 638
at <ScriptBlock>, D:\a\_work\1\s\eng\build.ps1: line 446
at <ScriptBlock>, <No file>: line 1
Cannot find path 'C:\Users\cloudtest\.netcoreeng\native\bin\perl\5' because it does not exist.
perl installation failed
Native tools: 
Cannot bind argument to parameter 'Path' because it is an empty string.
System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Path' because it is an empty string.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
```

**Comment by dsyme** [comment]
@vzarytovskii @KevinRansom This is ready

**Comment by dsyme** [comment]
@vzarytovskii @KevinRansom approve on this please?  And we should make sure it gets into 17.2 (I think the integrations are still automatic, but please double check)

**Review by vzarytovskii — APPROVED** [review]

**Comment by vzarytovskii** [comment]
> @vzarytovskii @KevinRansom approve on this please?  And we should make sure it gets into 17.2 (I think the integrations are still automatic, but please double check)

I recall @brettfo disabling automatic merges yesterday, not sure it got merged already.

**Pull request merged**
