### PR TITLE
Enable xlf for dotnet build by adding reference to XliffTasks package

### PR DESCRIPTION
**Pull request by Martin521**
Fix for #16311

It seems what is missing is just a reference to the XliffTasks package.

I am not sure about the version though (and was not able to list available versions).

### CODE REVIEW

**Comment by vzarytovskii** [comment]
Version should be declared in xml file like with other package versions (Versions.prop under eng). Also, that should be guarded to only run when not under arcade (to avoid conflicts with arcade itself).

**Comment by Martin521** [comment]
Ok, I added the guard, will move the version

**Comment by vzarytovskii** [comment]
Version should likely be `1.0.0-beta.23426.1` as it is now in dependencies.

**Comment by vzarytovskii** [comment]
CoreCLR issue is transient, it happens sometimes, should go away once we update on stable .NET8

**Review by T-Gro — APPROVED** [review]

**Review by edgarfgp — APPROVED** [review]

**Review by psfinaki — APPROVED** [review]
Thank you Martin.

**Pull request merged**
