### PR TITLE
Enforce `AttributeTargets.Interface`

### PR DESCRIPTION
**Pull request by edgarfgp**
## Description

Enforce `AttributeTargets.Interface`

- `AttributeTargets.Interface` should only work on `interfaces`
- `AttributeTargets.Class` should only work on `classes`

```fsharp
open System

[<AttributeUsage(AttributeTargets.Interface)>]
type CustomInterfaceAttribute() =
    inherit Attribute()

[<AttributeUsage(AttributeTargets.Class)>]
type CustomClassAttribute() =
    inherit Attribute()

[<CustomClass>] // Should fail, but does not
type IFoo =
    abstract member Foo : string

[<CustomClass>] // Should fail, but does not
[<Interface>]
type IFoo2 =
    abstract member Foo : string
    
[<CustomInterface>] // Should fail, but does not
type Foo() = class end

[<Class; CustomInterface>] // Should fail, but does not
type Foo2() = class end
```
 
See C# version for reference [sharplab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFDINoEEAumBOBLAIwFdMBTAVQGcBDAc1IAotdCTSAVanezSgOgCSAOzI4AZtQDGpAJQBdZFADMAAlgqAwkUqYA9gFthoidOb5iZFSBVnWZZAG9kAX2RpbFijXpNs5tpzcpLx8GgA21JSU8oqq6lo6BuGRlB5sVjZ+dqSOLm5IqAl6hiKk4lKMMUjKajAqAGK6uipOSK4oBUVJEVEMVTV4peXSKgKNza3OQA=)
## Checklist

- [x] Test cases added
- [x] Release notes entry updated

### CODE REVIEW

**Comment by edgarfgp** [comment]
`AllowNullLiteralAttribute` needs updating

**Comment by edgarfgp** [comment]
Interesting. VS Integration is using `System.Runtime.InteropServices.ClassInterface` attribute [docs](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.classinterfaceattribute?view=net-8.0) which is meant to be used only on a `class` 

```csharp
  /// <summary>Indicates the type of class interface to be generated for a class exposed to COM, if an interface is generated at all.</summary>
  [AttributeUsage(AttributeTargets.Assembly | AttributeTargets.Class, Inherited = false)]
  public sealed class ClassInterfaceAttribute : Attribute
  {
    /// <summary>Initializes a new instance of the <see cref="T:System.Runtime.InteropServices.ClassInterfaceAttribute" /> class with the specified <see cref="T:System.Runtime.InteropServices.ClassInterfaceType" /> enumeration member.</summary>
    /// <param name="classInterfaceType">One of the <see cref="T:System.Runtime.InteropServices.ClassInterfaceType" /> values that describes the type of interface that is generated for a class.</param>
    public ClassInterfaceAttribute(ClassInterfaceType classInterfaceType)
    {
      this.Value = classInterfaceType;
    }
```
[sharplab](https://sharplab.io/#v2:DYLgZgzgNAJiDUAfA9gBwKYDsAEBlAnhAC7oC2AdAEoCumRAlqeuQJJ3oBOaunAbvQGN0EALAAocQG0APAWJkqtBk1bsuqHh35CI5AMLAAhhAhsSHMIaEAKA8dNrLQgCr4M5AHLJM6AJQA+AF1xIjd0bFRqACNgQWwWADUIAFlBLghkMCI2YkNgYHQYAAUuGGoBImwAXnFsOuxDKOIOK0qWGAAhUg1UIwgAC2TsEGwo/A50MGlqejoAZgAmf2wAWmXaeiJa7ClZQhIKGjpGZjNObj5BYX0+h3MndFtbs4srdFd3Lx8A4LFQjGwADFkMhrL5qtgBLdsFgYOIgA===)
```fsharp
[<System.Runtime.InteropServices.ClassInterface(ClassInterfaceType.None)>] // This is allowed but should not
type public IVsMicrosoftInstalledProduct =
    inherit IVsInstalledProduct
    abstract IdBmpSplashM : byref<uint32> -> unit

[<System.Runtime.InteropServices.ClassInterface(ClassInterfaceType.None)>]
type Foo() = class end
```

[sharplab](https://sharplab.io/#v2:CYLg1APgAgDABFAjAOgEoFcB2AXAlgWwFNkBJHQgJwHsAHAZUoDdcBjQgZwG4BYAKD4DaAYQA2AQ3bsy2SgDMxbABSiJU8hXlsAKgE8axAILpsVACK52NMdhYALAJQBdPlADMCAExwAsjpWS+AG8+AF8+QX81GQ0FQmVxSWk5WN19ZCMTc0trOycXd1x1TUI4EgAxKio4QLDeIA=)

```csharp
using System.Runtime.InteropServices;

[ClassInterface(ClassInterfaceType.AutoDispatch)]
public class MyClass
{
}

[ClassInterface(ClassInterfaceType.AutoDispatch)] // This raises an error in C#
public interface IFoo {}
```

cc @vzarytovskii seems like `System.Runtime.InteropServices.ClassInterface` has been wrongly used [here](https://github.com/edgarfgp/fsharp/blob/df3919d6940ca3ab63fa8f8fe7b1a511cf4cc96d/vsintegration/src/FSharp.ProjectSystem.FSharp/Project.fs#L167) ?

**Comment by vzarytovskii** [comment]
Not sure what to do with it, it'll probably need to be an abstract class. This is legacy project system, so won't be able to test it that easy, and we have to support it.

**Comment by edgarfgp** [comment]
> Not sure what to do with it, it'll probably need to be an abstract class. This is legacy project system, so won't be able to test it that easy, and we have to support it.

Yeah an `AbstractClass` will be ok here but it won't be able to inherit from an interface `IVsInstalledProduct`(seems to be a close source so I can't see the defined  members)

**Comment by majocha** [comment]
@edgarfgp it's just this https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.interop.ivsinstalledproduct?view=visualstudiosdk-2022

**Comment by edgarfgp** [comment]
> @edgarfgp it's just this https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.interop.ivsinstalledproduct?view=visualstudiosdk-2022

Ohh Thank my googling failed 😅

**Comment by majocha** [comment]
Yeah, we don't actually implement it, so it's not really used as the docs prescribe. This is some ancient COM trickery that worked long time ago but not necessarily still do.

In fact I just comment out that whole `IVsMicrosoftInstalledProduct` interface, started VS debug instance and things seem to work the same without it:
image

**Comment by edgarfgp** [comment]
> Yeah, we don't actually implement it, so it's not really used as the docs prescribe. This is some ancient COM trickery that worked long time ago but not necessarily still do.
> 
> In fact I just comment out that whole `IVsMicrosoftInstalledProduct` interface, started VS debug instance and things seem to work the same without it

If it is not longer used/needed we could just comment out / remove this code.

ideally enforcing the right attribute targets in the compiler should not depend on the use of this interface

**Comment by abelbraaksma** [comment]
I'd really like this change and for the compiler to enforce attribute targets, but technically this would be a backward incompatible change, right? Do we have a lang suggestion or bug or issue report (I believe this has come up several times)?

Ah, wait, found it: #8547.

And related are all these: #16692, #16764, #16845, #16790. I assume my point above has already been discussed before then ;).

And there's mention of an RFC, can we link that from the original post above, or is that TODO? https://github.com/dotnet/fsharp/issues/8547#issuecomment-1952063131

**Review by T-Gro — APPROVED** [review]

**Review by psfinaki — APPROVED** [review]
Thanks for your continuous work here, Edgar :)

Yeah so the VS change looks a bit risky, but since Jakub tested the related functionality, I don't think we should block the fix by that thing. Also, this is a well-isolated PR, so can be reverted quickly if needed.

**Pull request merged**
