### PR TITLE
Turn XML doc and Sig<->Impl mismatch warnings on by default

### PR DESCRIPTION
**Pull request by cartermp**
I think these should just be on by default.

1. Nobody actually _relies_ on malformed XML documentation, or documentation where things like parameter names are different in XML docs than their names in source.
2. Sig and Impl file parameter mismatches have less of a "nobody actually relies on this" factor, but like ... nobody actually _relies_ on parameter names differing between signature and implementation files.

This is technically a breaking change for anyone who has warnings set as errors, and should be treated like any circumstance where if we introduce a warning it will break people with that setting turned on.

That said, I think that these two checks move code towards being _more_ correct, and especially in the case of the XML doc thing can catch some bugs that they might otherwise not easily catch.

### CODE REVIEW

**Review by KevinRansom — APPROVED** [review]

**Comment by TIHan** [comment]
How likely is this to impact anyone from compiling their code?

**Comment by cartermp** [comment]
@tihan For the signature file mismatch one, highly unlikely. The likelihood that someone has warnings as errors, uses signature files, intentionally mismatches parameter names, and is blocked from changing things feels like it's pretty much zero.

For the XML doc one, it will likely impact more people because there are probably several libraries out there that have malformed or incorrect XML documentation. However, the likelihood that they would appreciate this warning is also quite high, because this fixes very real bugs for their consumers.

**Comment by cartermp** [comment]
Merging as per convo with @TIHan

**Comment by dsyme** [comment]
If we're turning these on, then unused variable warnings (in projects, not scripts) seem a good candidate too. These warnings catch so many bugs in real world code.

**Comment by cartermp** [comment]
I wouldn't mind doing that as well, we might as well just go for it and let feedback dictate if we back off.

**Pull request merged**
