### PR TITLE
Fix member declaration ranges

### PR DESCRIPTION
**Pull request by auduchinok**
Currently member declarations have their beginnings stripped, e.g. `static member` is not in the reported range, nor are attributes. This PR fixes these ranges.

AST viewer example: [jindraivanek.gitlab.io](https://jindraivanek.gitlab.io/ast-viewer/#?code=C4TwDgpgBAKlC8AoKKoFsJoEYQE5QA8A6ABQSgEYg&defines=Q&filename=Q).

### CODE REVIEW

**Comment by auduchinok** [comment]
Needs baseline update.

**Comment by auduchinok** [comment]
@brettfo I've noticed the macOS FCS build is green despite it clearly needs a baseline update and has errors in log. Could you please check why it didn't fail?

**Comment by auduchinok** [comment]
Is the Linux failure expected? The native crash report looks odd.

**Comment by cartermp** [comment]
Restarting it (since it seems to generally be fine after a restart).

**Comment by auduchinok** [comment]
It seems all recent PRs fail this way currently, so I don't think restarting it will actually help.

**Comment by cartermp** [comment]
Yep, doesn't look like some transient failure then :(

**Comment by brettfo** [comment]
For anyone following along at home, the Linux_FCS failures are unrelated and recently disabled via #7697.

**Comment by auduchinok** [comment]
This is ready.

**Comment by cartermp** [comment]
Is there an issue listed somewhere that this resolves?

**Comment by auduchinok** [comment]
Probably not. I've updated the PR description.

**Comment by cartermp** [comment]
@auduchinok Thanks, that's good to know.

**Comment by cartermp** [comment]
@TIHan can we get a review on this puppy? Although it doesn't fix a tooling bug on our end, it does fix a future one we'd have if we did a similar kind of thing in VS as described above

**Comment by TIHan** [comment]
Yes, I will try to get a review today.

**Comment by auduchinok** [comment]
Any news on it?

**Pull request merged**
