### PR TITLE
[WIP]Turn unused value warnings on by default

### PR DESCRIPTION
**Pull request by cartermp**
Based on comment from https://github.com/dotnet/fsharp/pull/10457

Also worth noting that a lot of F# developers turn this one on explicitly

### CODE REVIEW

**Comment by cartermp** [comment]
I'm terribly confused. Why is GitHub saying there is a conflict?

**Comment by cartermp** [comment]
Huh. So like, does `NoWarn` just like, not work?

**Comment by vzarytovskii** [comment]
@cartermp Apparently, if we have certain warning in WarningsAsErrors, it is ignored in NoWarn, I need to confirm that though.
Do we want to change the behaviour? I would say NoWarn should be higher priority. Wdyt?

cc @KevinRansom

**Comment by vzarytovskii** [comment]
Some tests are failing, need to add some NoWarns to generated fsprojs (or fix unused vars).

**Comment by dsyme** [comment]
@vzarytovskii Let's discuss this 

- 1182 should not be on for F# scripts. It's too intrusive. So this would need to be adjusted for that

- However if we want it on by default I think a simpler option is to make it on in the default templates for new projects?  So much less intrusive, and then the user has control.  

- If we changed it in the compiler I think it should be protected by a langversion switch - the very many changes to tests in this PR indicates how intrusive it is in the language

**Comment by vzarytovskii** [comment]
> @vzarytovskii Let's discuss this
> 
> * 1182 should not be on for F# scripts. It's too intrusive. So this would need to be adjusted for that
> * However if we want it on by default I think a simpler option is to make it on in the default templates for new projects?  So much less intrusive, and then the user has control.
> * If we changed it in the compiler I think it should be protected by a langversion switch - the very many changes to tests in this PR indicates how intrusive it is in the language
> * I think we'd need to improve our error message to mention "you can add `_` if you want to suppress this"

Yeah, the more I try to fix tests, the more I think it may be not what we want to enforce via the compiler.

**Comment by dsyme** [comment]
> Yeah, the more tests I "fix", the more I think it may be not what we want to enforce via the compiler.

Right.  I mean I think it's ok for fresh project code.

**Comment by vzarytovskii** [comment]
> > Yeah, the more tests I "fix", the more I think it may be not what we want to enforce via the compiler.
> 
> Right. I mean I think it's ok for fresh project code.

Yeah, we can enable it in the templates by default, I guess.

**Comment by cartermp** [comment]
I'll just close this out since it was so long ago

**Pull request closed without merging**
