### PR TITLE
[<Struct>] DUs - eliminate dummy .ctor args, fix bug > 49 cases, simplify IL

### PR DESCRIPTION
**Pull request by T-Gro**
Fixes: https://github.com/dotnet/fsharp/issues/5342
Fixes: https://github.com/dotnet/fsharp/issues/9767  

Before:
https://sharplab.io/#v2:DYLgZgzgPgsAUAbQDwDkD2BhNBbADgQwCcBLCNAOwG50BRARwFd9hiAXAT0oGVXCGBjVgD4AuvA64ApgAIAKhAjSAvNOkBBaVGkAhTdIx6AInpp6AYnoDiegBJ6AknoBSegNJ6AMnoCyelPHggA=

Have a look at the generated constructors, artificial arguments were added to tell them apart.
This lead to unexpected runtime crashes when constructing a case from a DU with  > 49 cases.

After:
- Nullary cases created plain .ctor setting the _tag field (just like `new StructType(_tag = 13)`)
- Non-nullary cases created using "maker method", which:
    - initializes the struct to 0 ( I am open to suggestions about cases where we could in theory avoid it?)
    - assigns the constant _tag field for this case
    - assigns fields needed by the case

The public-API - mainly properties for creationg, "IsXXX" properties etc. all remain the same, as does the struct layout in memory (at least for this PR).

### CODE REVIEW

**Comment by T-Gro** [comment]
Missing - eliminate for single case DUs

**Review by 0101 — APPROVED** [review]

**Comment by vzarytovskii** [comment]
Important question - do we merge it, so it gets to 8, or is it too risky?

**Comment by T-Gro** [comment]
For me the risk outweighs the existing error `System.InvalidProgramException: Common Language Runtime detected an invalid program.` which this fixes.

A downside is that we are not dogfooding large struct DUs ourselves that much, only a few small ones in FSharp.Core.

**Review by psfinaki — APPROVED** [review]
LGTM, I guess this can go?

**Review by KevinRansom — APPROVED** [review]

**Pull request merged**
