### PR TITLE
[Experiment] net6.0

### PR DESCRIPTION
**Pull request by dsyme**
An experiment to update everything to net6.0, just to see what goes wrong, see #12733 

@KevinRansom @brettfo Do we have plans for this?  I presume these problems have been solved in some release branch?

### CODE REVIEW

**Comment by dsyme** [comment]
```
Test run for /Users/runner/work/1/s/artifacts/bin/FSharp.Compiler.ComponentTests/Release/net6.0/FSharp.Compiler.ComponentTests.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Failed to negotiate protocol, waiting for response timed out after 90 seconds. This may occur due to machine slowness, please set environment variable VSTEST_CONNECTION_TIMEOUT to increase timeout.
Results File: /Users/runner/work/1/s/artifacts/TestResults/Release/FSharp.Compiler.ComponentTests_net6.0.xml

```

**Comment by vzarytovskii** [comment]
> ```
> Test run for /Users/runner/work/1/s/artifacts/bin/FSharp.Compiler.ComponentTests/Release/net6.0/FSharp.Compiler.ComponentTests.dll (.NETCoreApp,Version=v6.0)
> Microsoft (R) Test Execution Command Line Tool Version 17.0.0
> Copyright (c) Microsoft Corporation.  All rights reserved.
> 
> Starting test execution, please wait...
> A total of 1 test files matched the specified pattern.
> Failed to negotiate protocol, waiting for response timed out after 90 seconds. This may occur due to machine slowness, please set environment variable VSTEST_CONNECTION_TIMEOUT to increase timeout.
> Results File: /Users/runner/work/1/s/artifacts/TestResults/Release/FSharp.Compiler.ComponentTests_net6.0.xml
> ```

We probably want to update `xunit.*` `Microsoft.NET.Test.Sdk` too

**Comment by dsyme** [comment]
> We probably want to update xunit.* Microsoft.NET.Test.Sdk too

Makes sense

**Comment by dsyme** [comment]
> We probably want to update xunit.* Microsoft.NET.Test.Sdk too

Hmmm these seem to be at latest versions, XUnitVersion is 2.4.1 and that's about as late as it gets.  I can't actually see where our master reference to Microsoft.NET.Test.Sdk is

**Comment by dsyme** [comment]
@vzarytovskii Is this something we would like to proceed with?  I think it needs to be looked at very carefully by @brettfo too?

If so please let push changes as you see fit or point me to which lines you think might be updated? Thanks :)

**Comment by vzarytovskii** [comment]
> @vzarytovskii Is this something we would like to proceed with?  I think it needs to be looked at very carefully by @brettfo too?
> 
> If so please let push changes as you see fit or point me to which lines you think might be updated? Thanks :)

I'll take a look at it.

**Comment by dsyme** [comment]
Might be NunitXml.TestLogger needs bumping

Note that we might also need to bump things like SystemMemoryVersion, not sure

**Comment by dsyme** [comment]
We also need to bump `build.windows.10.amd64.vs2019` to VS2022 by the look of it

**Comment by vzarytovskii** [comment]
> We also need to bump `build.windows.10.amd64.vs2019` to VS2022 by the look of it

This one is trickier, since it depends on dnceng pools.

 @brettfo knows more about it.

**Comment by KevinRansom** [comment]
Checked in net 6.0 update

**Pull request closed without merging**
