### PR TITLE
Don't crash when looking up XML docs for signature with apostrophe

### PR DESCRIPTION
**Pull request by 0101**
Fixes https://github.com/dotnet/fsharp/issues/13817

There seems to be no good way to escape `'` in XPath other than wrap the string with `"`. 

For sake of simplicity and since it didn't work before anyway, I propose to not look up the docs when you have a value with both `'` and `"` in its name (which would be a pretty strange thing to have).

### CODE REVIEW

**Review by T-Gro — DISMISSED** [review]

**Review by psfinaki — COMMENTED** [review]
Any testing possible here?

**Comment by 0101** [comment]
@psfinaki there should be... actually wonder if this is covered by any tests right now. I will find out.

**Comment by 0101** [comment]
@psfinaki Don't think this was tested directly (although plenty indirectly), so I added a test.

**Review by KevinRansom — APPROVED** [review]

**Comment by psfinaki** [comment]
@0101 too late to approve - but thanks!

**Pull request merged**
