### PR TITLE
Add optional width parameter to GetToolTip

### LINKED ISSUE #13772: Add optional width parameter for FSharpCheckFileResults.GetToolTip
**Is your feature request related to a problem? Please describe.**

When the IDE gets a tooltip via [FSharpCheckFileResults.GetToolTip](https://fsharp.github.io/fsharp-compiler-docs/reference/fsharp-compiler-codeanalysis-fsharpcheckfileresults.html#GetToolTip), it will eventually print a layout from NicePrint.

**Describe the solution you'd like**

https://github.com/dotnet/fsharp/blob/bdb64624f0ca220ca4433c83d02dd5822fe767a5/src/Compiler/Service/ServiceDeclarationLists.fs#L150-L183

To a certain degree, it is possible to control the width of a layout before it gets transformed into a tooltip.
Using `Display.squashTo 80` after `NicePrint.layoutType denv unionTy` for example.

I'd like to be able to pass in an option width that when present squashes the layout to get a better tooltip view.

**Describe alternatives you've considered**

I'm not really sure what the alternatives could be here.

### PR DESCRIPTION
**Pull request by dawedawe**
fixes #13772
with help of @nojaf 

If provided, use the given width to call Display.squashTo on the layout of the ToolTip.

We were able to demonstrate the effects this would have in Rider:

Default behaviour with no width provided:

Screenshot 2023-03-14 111939

With width 20 for demo purposes:
Screenshot 2023-03-14 111732

### CODE REVIEW

**Comment by vzarytovskii** [comment]
It doesn't change the default current behaviour, right?

**Comment by dawedawe** [comment]
No, if no width is provided, the layout isn't modified in any way.

**Review by nojaf — APPROVED** [review]

**Comment by majocha** [comment]
Will it squash doc comments, too?

**Comment by dawedawe** [comment]
No, but you might see them rendered in a window with a smaller width. But that depends on the caller of the API.
Here's the current rendering of Rider without the width given:

Screenshot 2023-03-14 152936

Here with a width given:

Screenshot 2023-03-14 152742

You can get the same change in the rendering of the doc comment if you drag the tooltip window with your mouse to a smaller width. But this PR dosn't add newlines to doc comments.

**Comment by dawedawe** [comment]
First, you'll get an Ehrenmitgliedschaft in some German language club 😜 
Second, the word is honored and not broken. The breaks only happen between words.

Screenshot 2023-03-14 200603

**Comment by psfinaki** [comment]
@dawedawe alright, now I can sleep peacefully :D thanks for checking that!

**Review by 0101 — APPROVED** [review]

**Pull request merged**
