### PR TITLE
Disable UpdateXlfOnBuild for VMR builds

### PR DESCRIPTION
**Pull request by T-Gro**
This changes the condition set for UpdateXlfOnBuild.

Right now, net9 builds are occasionally failing with "The target "UpdateXlf" does not exist in the project".

However, updating localization files happens locally before contribution (see guidelines), it is not needed as a CI step.

### CODE REVIEW

**Comment by vzarytovskii** [comment]
I will be more interested in why are they failing.

**Comment by T-Gro** [comment]
> I will be more interested in why are they failing.

The target is not correctly imported in case of net9, it is an issue within the UpdateXlf task.
Alex will follow on that.

image

**Review by akoeplinger — APPROVED** [review]

**Comment by akoeplinger** [comment]
Looks like the xlf files need to be updated now since CI is no longer inadvertently regenerating them.

You can also remove the SKIP_NETCURRENT_FSC_BUILD workaround from https://github.com/dotnet/fsharp/blob/6a9747eb086aee8c7218145d90237da5f15d3a07/src/Compiler/FSharp.Compiler.Service.fsproj#L22-L24

**Comment by T-Gro** [comment]
> Looks like the xlf files need to be updated now since CI is no longer inadvertently regenerating them.
> 
> You can also remove the SKIP_NETCURRENT_FSC_BUILD workaround from
> 
> https://github.com/dotnet/fsharp/blob/6a9747eb086aee8c7218145d90237da5f15d3a07/src/Compiler/FSharp.Compiler.Service.fsproj#L22-L24

I can remove the workaround for CI steps, I have to keep the option to disable it for local MacOs/Linux contributors.
@vzarytovskii experienced the error when building on MacOs locally as well IIRC.

**Review by psfinaki — APPROVED** [review]
Hope it helps, thanks!

**Review by abonie — APPROVED** [review]

**Comment by akoeplinger** [comment]
> I can remove the workaround for CI steps, I have to keep the option to disable it for local MacOs/Linux contributors.
@vzarytovskii experienced the error when building on MacOs locally as well IIRC.

Thanks, @ViktorHofer was also able to reproduce the issue locally and is looking into it. It currently looks like it is somehow related to project.assets.json being used from the `Proto` Configuration and that one doesn't contain net9.0

**Comment by akoeplinger** [comment]
This is a good change regardless since we shouldn't be setting UpdateXlfOnBuild=true in CI builds.

**Comment by ViktorHofer** [comment]
Isn't the Arcade default sufficient? I don't recall other repos setting this.

**Comment by akoeplinger** [comment]
Yes the default should work too.

**Comment by T-Gro** [comment]
Ok, will see if the default works as well here.

**Pull request merged**
