### PR TITLE
Bugfix - underscore dot lambda conversion to Func<> in LINQ

### LINKED ISSUE #16305: Unexpected type inference error in shorthand lambda
Possibly because of lambda to Func<> conversion
```fsharp
open System.Linq

let _ = [""; ""; ""].Select(fun x -> x.Length)
let _ = [""; ""; ""].Select(_.Length)
```

image

Minimal repro:
```fsharp
open System

type A =
    static member M(x: Func<int, string>) = ()

A.M(fun x -> x.ToString())
A.M(_.ToString())
```

### PR DESCRIPTION
**Pull request by T-Gro**
Fixes #16305 

This changes how dot lambda is being recognized for type inference, making sure it is treated like a function type.
With that, it will be detected in method call scenarios for a possible conversion between function type to `Func<,>`.

The following three now work (before, only the first did):
```fsharp
open System.Linq
let _ = [""; ""; ""].Select(fun x -> x.Length)
let _ = [""; ""; ""].Select(_.Length)
let _ = [""; ""; ""].Select _.Length
```

### CODE REVIEW

**Comment by DedSec256** [comment]
Will this also work for `System.Linq.Expressions.Expression<Func<...>>`?

**Comment by DedSec256** [comment]
Wouldn't this fix also allow conversion between a short lambda and `System.Linq.Expressions.Expression<Func<...>>`?

**Comment by T-Gro** [comment]
It should, let me add a simple test for that as well.

**Comment by auduchinok** [comment]
> Wouldn't this fix also allow conversion between a short lambda and System.Linq.Expressions.Expression<Func<...>>?

@DedSec256 Do you have a sample to add a test?

**Comment by DedSec256** [comment]
```fsharp
open System
open System.Linq.Expressions

type A = static member M(x: Expression<Func<string, int>>) = ()

A.M(fun x -> x.Length)
A.M(_.Length)

```

Should we allow such a conversion? Will it be able to convert the F# expression into a tree at runtime?

**Comment by auduchinok** [comment]
> Should we allow such a conversion? 

It should be the same as the existing behaviour for the existing lambda expressions. 🙂

**Comment by T-Gro** [comment]
Confirmed, it works.

**Comment by T-Gro** [comment]
Also it works without parens when using underscore dot lambda.

**Review by 0101 — APPROVED** [review]

**Review by vzarytovskii — APPROVED** [review]

**Comment by Tarmil** [comment]
I've done some testing with SDK 8.0.101, and while it works with `Func<_, _>`, it doesn't seem to be fully working with `Expression<Func<_, _>>`. It's quite weird actually.

* `[1].AsQueryable().Select(_.ToString())` works and does call the `Expression` version of `Select`.
* `["1"].AsQueryable().Select(_.Length)` gives "Error FS0072 : Lookup on object of indeterminate type based on information prior to this program point."
* @DedSec256's snippet (calling a custom method that takes an `Expression`) gives "Error FS0002 : This function takes too many arguments, or is used in a context where a function is not expected".

**Pull request merged**
