### PR TITLE
TryRemove List Function

### PR DESCRIPTION
**Pull request by aaron-jack-manning**
A new list function for removing the first instance of an element within a list.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=12353) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=12353) before we can accept your contribution.<br/><br/>:x: aaron-jack-manning [sign now](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=12353)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/fsharp?pullRequest=12353) it.</sub>

**Comment by Happypig375** [comment]
Tests?

**Comment by aaron-jack-manning** [comment]
> Tests?

Sorry, first time contributor to this project. Can you be a bit more specific?

**Comment by Happypig375** [comment]
All additions should have tests like in https://github.com/dotnet/fsharp/pull/11888/files#diff-6873fcbba3dc702964b3a078300823c8de856634e3c154801d912b3e3fab8706 and surface area updated as in https://github.com/dotnet/fsharp/pull/11888/files#diff-574d04bc8fc18b9df28a993836a12465a26efed6612c366bac121923f3d4efc1

**Comment by aaron-jack-manning** [comment]
Thank you. Will fix my changes and create a new request.

**Comment by Happypig375** [comment]
Well, you can push to the same branch and new commits will appear in this PR

**Comment by dsyme** [comment]
Hello @aaron-jack-manning .  Thank you for your submission - it's really great to have new contributors.

For additions to FSharp.Core we need to go through the F# design process.  Could you submit a suggestion at https://github.com/fsharp/fslang-suggestions and we can discuss there?  Thank you

**Comment by vzarytovskii** [comment]
Suggestion: https://github.com/fsharp/fslang-suggestions/issues/1093#issuecomment-963047945

**Comment by aaron-jack-manning** [comment]
@dsyme Yes thank you. I didn't realise that as a new contributor but I have created an issue for it there. Thanks for your help.

**Pull request closed without merging**
