### PR TITLE
[Test] test enabling preview features

### PR DESCRIPTION
**Pull request by dsyme**
This is just to test the bootstrap when enabling all preview features.

### CODE REVIEW

**Comment by dsyme** [comment]
This failed so we have something to fix
```
tests/service/data/TestTP/ProvidedTypes.fs(13811,123): error FS0001: (NETCORE_ENGINEERING_TELEMETRY=Build) This expression was expected to have type    'ILTypeDef'    but here has type    'ILExportedTypeOrForwarder'
```

**Comment by dsyme** [comment]
Failed with just these enabled:
```
            LanguageFeature.AdditionalTypeDirectedConversions, languageVersion50
            LanguageFeature.RelaxWhitespace2, languageVersion50
            LanguageFeature.OverloadsForCustomOperations, languageVersion50
            LanguageFeature.ExpandedMeasurables, languageVersion50
            LanguageFeature.FromEndSlicing, languageVersion50
            LanguageFeature.ResumableStateMachines, languageVersion50
```

**Comment by vzarytovskii** [comment]
Same issues, it sounds like AdditionalTypeDirectedConversions is the cause.

**Comment by dsyme** [comment]
> Same issues, it sounds like AdditionalTypeDirectedConversions is the cause.

Thanks, yes, likely, verifying that now

**Comment by auduchinok** [comment]
Could we have a separate CI configuration that would have the preview features enabled?

**Comment by vzarytovskii** [comment]
> Could we have a separate CI configuration that would have the preview features enabled?

Good idea, let me poke around a bit.

**Comment by dsyme** [comment]
> Good idea, let me poke around a bit.

I think it's tricky, because we would expect tests to fail (since there are tests checking errors etc.)

So we would only want to build, not test

**Comment by dsyme** [comment]
* [x] The bug with AdditionalTypeDirectedConversions is fixed
* [x] Bootstrap build completes with all other features enabled
* [ ] Now checking AdditionalTypeDirectedConversions with fix integrated

**Pull request closed without merging**
