### PR TITLE
[WIP] Roslyn file ordering for legacy projects

### PR DESCRIPTION
**Pull request by TIHan**
This is for when Roslyn merges project document ordering: https://github.com/dotnet/roslyn/pull/31462

Here we take advantage of using the Roslyn API to order documents so when we compute `FSharpProjectOptions`, we can just use `Project.Documents` instead of relying on the `ProjectSite`.

### CODE REVIEW

**Comment by TIHan** [comment]
A lot has changed in FSharpProjectOptionsManager that will affect the work that was done here, but the LegacyWorkspaceMap work can be re-used.

**Comment by KevinRansom** [comment]
@TIHan is this still necessary, do we plan on finishing it up?

**Comment by cartermp** [comment]
Unfortunately this works against diverged tooling code that is going to be difficult to pick up. I'll close this out. We may want to pursue this in the future for existing projects, but since VS 16.7 and future updates will no longer ship the legacy templates and all new projects will use SDK-style projects, this has bumped down a bit in priority.

**Comment by Happypig375** [comment]
@cartermp What about Xamarin projects? They still use the legacy format.

**Pull request closed without merging**
