### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by dsyme**
Cleanup work:

* Rename `ErrorLogger` --> `DiagnosticsLogger`

* Split out part of `infos.fs` --> `TypeHierarchy.fs` 

* Split out part of `SymbolHelpers.fs`  --> `FSharpDiagnostic.fs` 

* Split `LowerCallsAndSeqs.fs` into the three independent logical parts that it is

* The exception type `Error(...)` --> `SRDiagnostic`.  This is because this is the exception that carries diagnostics derived from SR text.  Note the use of the name `Error` is misleading as these are also use for warnings, however it remains in the codebase as it is 1000 lines of churn.  Also `errorLogger` remains for now, we will rename to `diagsLogger` in due course.

* Rename `block` --> `ImmutableArray`.  In retrospect I'm just not liking this abbreviation and it's not sufficiently helping readability.  Will revisit the relevant suggestion.

### CODE REVIEW

**Comment by dsyme** [comment]
@KevinRansom @vzarytovskii This is ready

**Comment by auduchinok** [comment]
I think `SRDiagnostic` name may be hard to understand. Looking at the change after contributing to this repo for some time I don't think I know what SR stands for.

**Comment by dsyme** [comment]
> I think SRDiagnostic name may be hard to understand. Looking at the change after contributing to this repo for some time I don't think I know what SR stands for.

True.  Not sure what to call it otherwise.  It is the primary way for diagnostics and we should really get rid of the RESX and various exception types.  Maybe DiganosticWithText.

**Review by vzarytovskii — APPROVED** [review]

**Comment by auduchinok** [comment]
> True. Not sure what to call it otherwise. 

Could it be `Diagnostic`, `GeneratedDiagnostic`, or something like that?

**Comment by vzarytovskii** [comment]
Maybe something like `LocalizedDiagnostic`? Or is it used not only with localized strings?

**Comment by vzarytovskii** [comment]
Maybe something like `LocalizedDiagnostic`? Or is it used not only with localized strings?

**Comment by dsyme** [comment]
>  Maybe something like LocalizedDiagnostic? Or is it used not only with localized strings?

Hmmmm the FSStrings.resx resources are also localized I think - there is content under "src/fsharp/xlf".  Historically we started localising via the FSStrings resx approach then switched

I've renamed to DiagnosticWithText for now which is pretty accurate.

**Comment by dsyme** [comment]
> Could it be Diagnostic, GeneratedDiagnostic, or something like that?

There are multiple uses of "Diagnostic" - summary below

* The public "FSharpDiagnostic", that's ok

* The internal "PhasedDiagnostic". This contains an exception-valued field in `Diagnostic`, of which one kind is this `exception DiagnosticWithText`. Note exceptions are generally only being used as a cheap-shot way of getting objects to store in the "Diagnostic" field of "PhasedDiagnostic", they aren't necessarily being raised.  Arbitrary exceptions can however be caught and turned into PhasedDiagnostic

* There is also a legacy "Diagnostic" used internally in CompilerDiagnostics.fs and also as part of the LegacyHostedCompilerForTesting (used only by fsharpqa suite). I've now renamed this to `FormattedDiagnostic`.

I think we should use `DiagnosticWithText` as the actual name of the exception type to make sure it's not confused with `FSharpDiagnostic`.

**Pull request merged**
