### PR TITLE
Add FSharpType.IsMeasureType

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**
It looks there are some measure types that don't have type definition, like `Measure.Var` or `Measure.RationalPower`. This makes it impossible to know if the type is a measure from the FCS public API, so this PR exposes a new member for that.

### CODE REVIEW

**Review by T-Gro — APPROVED** [review]
Approved, just SurfaceArea for FCS needs to be updated.

**Comment by alfonsogarciacaro** [comment]
Thanks @T-Gro! How the SurfaceArea is updated?

**Comment by psfinaki** [comment]
@alfonsogarciacaro thanks Alfonso :)
You can see an example of baseline update in this [recent PR](https://github.com/dotnet/fsharp/pull/14916/files#diff-09b004be1be3034c0ddf117b1b291743a34cfb57fc50995b6b9b2fd2c8b559dd). 

See also [this PR](https://github.com/dotnet/fsharp/pull/14929), the contributor was confused just like you are :) Last commits in that PRs do the right thing though.

**Comment by T-Gro** [comment]
> Thanks @T-Gro! How the SurfaceArea is updated?

Either manually in the respective surfacearea text file (a text description of the public API).
Or, an environment variable can be set, which sets the surface area when the test is run:


```powershell
    $env:TEST_UPDATE_BSL=1 
    dotnet test tests/FSharp.Compiler.Service.Tests/FSharp.Compiler.Service.Tests.fsproj --filter "SurfaceAreaTest"
    dotnet test tests/FSharp.Compiler.Service.Tests/FSharp.Compiler.Service.Tests.fsproj --filter "SurfaceAreaTest" -c Release

```

**Review by psfinaki — APPROVED** [review]

**Comment by alfonsogarciacaro** [comment]
Thanks for merging and sorry for not updating the surface area myself 😅

**Pull request merged**
