### PR TITLE
Starting point for thorough testing of AsyncLocal impact

### PR DESCRIPTION
**Pull request by majocha**
This keeps a shadow diagnostics async state in AsyncLocals, and compare it with the current implementation, failing whenever they diverge.

The idea is to find out when and why it happens and to bring the behavior to some unification, so we can be sure AsyncLocal is a valid and safe replacement for current ThreadStatics + NodeCode.

It's useful to run some tests in debug, with the setting to break on `System.Exception`.
Then we can not only observe what diverged:
image

but also view the log of changes:
image

with some, not often useful, call stacks:
image

### CODE REVIEW

**Comment by majocha** [comment]
At the moment I'm not sure how to continue with this in light of #16712.

**Comment by 0101** [comment]
> At the moment I'm not sure how to continue with this in light of #16712.

I guess disregard anything Transparent Compiler related in the testing? Since that possibly doesn't work correctly now it's not something we can compare against. 

But presumably what was there before does work, so we could just check if that stays the same.

**Comment by majocha** [comment]
I'm afraid this is impossible task. I think threadstatics behavior is not 100% deterministic in tests, I even see different results depending on how many tests I run simultaneously.  Nothing is fully reproducible here, it just kind of eventually converges on some final state.
There is always potential for one task picking up threadstatics of a different one, whenever it happens to be started on or switched to the same thread, see https://github.com/dotnet/fsharp/pull/16712
With some careful massaging of the code in BuildGraph.fs we can make it almost fully deterministic, but then it's not the same code anymore that we want to test for.

**Comment by auduchinok** [comment]
> I think threadstatics behavior is not 100% deterministic in tests, I even see different results depending on how many tests I run simultaneously. Nothing is fully reproducible here, it just kind of eventually converges on some final state.

I think it should be possible to have more (lots of? 🙂) asserts in tests, maybe? They would check that, for example, we don't have diagnostics without logger or in a wrong phase.

**Comment by majocha** [comment]
Yes, one thing we had was the `AssertFalseDiagnosticsLogger`, but it was disabled for as long as this repo exists.
I think now I have some better idea what's going on: #16778

**Pull request closed without merging**
