### PR TITLE
move FCS to netstandard2.0 and purge old net461 related code

### PR DESCRIPTION
**Pull request by baronfel**
This moves FCS to NS2.0 only.

The ProjectCracker, ProjectCrackerTool, and MsBuild.v12 projects have been removed, as those were net461 only.  In addition, the FscExe and FsiExe samples have been removed, as they relied on .Net Framework Remoting, which has no nice analog in a .Net Standard/.Net Core world.

The netfx.props were removed as well, because nothing else was using them.

### CODE REVIEW

**Comment by auduchinok** [comment]
We currently still target `net461` and there might be some issues with `netstandard2.0` assemblies according to discussion with @cartermp.

**Comment by baronfel** [comment]
I wondered about that. If the timing's not right that's cool, this took like half an hour so it'd be easy to do later.

**Comment by cartermp** [comment]
@auduchinok If you wouldn't mind testing a nupkg of this to see if everything works that'd be good. There may be runtime errors for the net461 target but there may not; unfortunately there's no way to analyze that

**Comment by auduchinok** [comment]
Rider 2020.1 EAP2 uses the `netstandard2.0` FCS build. We're still looking if there are any problems with it and if something bad is found or reported I'll let you know.

**Comment by cartermp** [comment]
Thanks @auduchinok - tentatively, let's see if we can take this in once that build ends up shipping outside of EAP.

**Comment by cartermp** [comment]
linking https://github.com/dotnet/fsharp/pull/8722

**Comment by cartermp** [comment]
Unfortunately the codebase has diverged a lot. We want to take this in, but only once we can confirm it doesn't hose Rider will we continue with it. I'll close this out for now, since picking this up again will involve merging conflicts that could end up being about the same amount of time spent doing this in the first place.

**Comment by auduchinok** [comment]
We've been using the netstandard2.0 build for some time now and with the dependency manager fixes it currently works fine. There are some issues when running on Mono but it's likely we won't be using Mono in 2020.2 even as a fallback runtime anymore.
I'm going to grab a newer FCS build soon to test it all again, but now it seems it's more or less safe to go netstandard2.0 FCS for us.

**Comment by cartermp** [comment]
will close this out in favor of https://github.com/dotnet/fsharp/pull/10135 on account of _everything being different now_

**Pull request closed without merging**
