### PR TITLE
Improve type error ranges in computed collections

### LINKED ISSUE #7670: Adding a let binding in list gives the wrong error and increases the error range to the whole list
**Repro steps, Actual Behavior**

image

**Expected behavior**

image

**Known workarounds**

Moving the let binding out of the list

**Related information**

Provide any related information (optional):

* Operating system Win10 1809
* .NET Runtime kind (.NET Core, .NET Framework, Mono) .NETFramework4.8
* Editing Tools (e.g. Visual Studio Version, Visual Studio) VS16.3.1

### LINKED ISSUE #15361: Incorrect error range in mixed lists with yield!
This issue is particularly painful when writing Fable UI where lists are often generated from data sequences using yield!

**Repro steps**

Provide the steps required to reproduce the problem:
Here is the code:
```fsharp
module Test =
    let f (): int list =
        [
            1
            "wrong"
            2
            yield! [3; 4]
        ]
```

**Expected behavior**

I expect the error to be highlighted only on `"wrong"` like when there is no `yield!`

image

**Actual behavior**

Whole list is highlighted with red

image

Provide a description of the actual behaviour observed. 

**Known workarounds**

Not applicable

**Related information**

Provide any related information (optional):

dotnet 7.0.200

### PR DESCRIPTION
**Pull request by kerams**
Fixes #15361, fixes #7670.

Before and after

devenv_rh3jLBLjPb devenv_U7W79EhJHt

### CODE REVIEW

**Comment by baronfel** [comment]
Why does f2 error on the string, but f3 errors on the int list? Naively I expect the first element to 'fix' the element type of the seq CE.

**Comment by kerams** [comment]
`f2` has a type annotation.

**Review by vzarytovskii — APPROVED** [review]

**Review by edgarfgp — APPROVED** [review]

**Comment by kerams** [comment]
On an unrelated note, not sure if this is an inherent limitation of implicit yields or just an oversight:

```fsharp
> let y = [ yield 1L; if true then yield 2 ];;
val y: int64 list = [1L; 2L]

> let y = [ 1L; if true then 2 ];;

  let y = [ 1L; if true then 2 ];;
  --------^^^^^^^^^^^^^^^^^^^^^^

stdin(6,9): error FS0193: Type constraint mismatch. The type
    'int'
is not compatible with type
    'int64'
```

**Review by 0101 — APPROVED** [review]

**Review by T-Gro — APPROVED** [review]

**Comment by psfinaki** [comment]
Thanks @kerams, with PRs like this it really feels like we are cutting off all the rough edges in the language and it's nearing perfection :)

**Comment by vzarytovskii** [comment]
> On an unrelated note, not sure if this is an inherent limitation of implicit yields or just an oversight:
> 
> ```fsharp
> > let y = [ yield 1L; if true then yield 2 ];;
> val y: int64 list = [1L; 2L]
> 
> > let y = [ 1L; if true then 2 ];;
> 
>   let y = [ 1L; if true then 2 ];;
>   --------^^^^^^^^^^^^^^^^^^^^^^
> 
> stdin(6,9): error FS0193: Type constraint mismatch. The type
>     'int'
> is not compatible with type
>     'int64'
> ```

I think it's an oversight when we were doing implicit conversions.

**Pull request merged**
