### PR TITLE
Infer string type when using nameof pattern

### PR DESCRIPTION
**Pull request by ntovas**
Most likely there is a better way to do this, any comment appreciated 

Fixes: #13377

PS: I am a c# dev, it's my first time with f#, I would like to implement better `(SynConst.String(c.ToString(), SynStringKind.Regular, m))` but I dont know how

### CODE REVIEW

**Comment by T-Gro** [comment]
Hi, had a look at the failing checks:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=46781&view=logs&j=966222a4-f29d-5ec0-88cc-1b798728906e&t=052eabf8-67e2-5f29-745c-00cc34aa0e02 is hinting two failing tests related to this change:

at FSharp.Tests.Core.VersionTests.nameof-fsi() in D:\a\_work\1\s\tests\fsharp\tests.fs:line 2102

and

at FSharp.Tests.Core.VersionTests.nameof-execute() in D:\a\_work\1\s\tests\fsharp\tests.fs:line 2099

This should bring you to test cases where a new regression was introduced, please try to untackle this.
If it does not work, let me know and I can have a look later.

**Comment by ntovas** [comment]
@T-Gro 
The tests seem to fail at `PatternMatchingWithNameof`, more specifically on the function:
```
let deserialize (e: RecordedEvent) : MyEvent =
        match e.EventType with
        | nameof A -> A e.Data
        | nameof B -> B e.Data
        | t -> failwithf "Invalid EventType: %s" t
```

Unfortunately, when I am running the same code with `VisualFSharpDebug` with targets: `.net 7.0 - .net 4.7.2` it works as expected.
Am I missing something?

**Comment by T-Gro** [comment]
> 

How did you run the same code please?
Depending on the test project, there might be "special" ways of launching the test suite - best to follow the readme.md in the /tests folder.

Or, alternatively, run Build.cmd with respective -test*** switch, this is what CI does.
(each CI report contains the cmd arguments used to launch it)

**Comment by ntovas** [comment]
Yes, I did that and in my local env it also fails. 
I copied the same code in order to debug it and find the issue, so my main question is, how can I debug this case to find what is going wrong? I found no way to debug these test cases.

**Comment by T-Gro** [comment]
> Yes, I did that and in my local env it also fails. I copied the same code in order to debug it and find the issue, so my main question is, how can I debug this case to find what is going wrong? I found no way to debug these test cases.

This specific is calling dotnet.exe with `build /t:RunFSharpScript ` arguments => running a .fsx file.

**Comment by ntovas** [comment]
Ok, thanks, I look into this.

**Comment by T-Gro** [comment]
I think I got the issue now, will submit soon.

The Const.ToString() is a debug-oriented view, and therefore adds quotes around the string when rendering it.
That meant that within patterns, a nameof A was actually replaced with  "A" , incl. the quotes in the string itself.

Which then meant that the pattern did not match.

I have also replaced the code to be more strict and insist on Const.String, since nameof should not produce any other constant type besides a string.

**Review by T-Gro — APPROVED** [review]

**Review by psfinaki — APPROVED** [review]
@ntovas thanks for the great first contribution :)
(and @T-Gro thanks for help)

**Pull request merged**
