### PR TITLE
Change ty1.Equals(ty2) to call static op_Equality

### PR DESCRIPTION
**Pull request by rstm-sf**
Closes https://github.com/dotnet/fsharp/issues/8447

### CODE REVIEW

**Comment by dsyme** [comment]
@rstm-sf This needs to be merged with main, can you do that please?  Thank you

**Comment by edgarfgp** [comment]
@vzarytovskii This would a good improvement to have merged to main ?

**Review by T-Gro — DISMISSED** [review]

**Comment by T-Gro** [comment]
> @vzarytovskii This would a good improvement to have merged to main ?

Would be good (uses a more fitting overload, skipping type checks when they are known).
It has some conflicts since creation...

**Comment by tannergooding** [comment]
It's worth noting that for `float`, `double`, `System.Half`, and potentially other types `==` and `Equals` are not the same.

In the case of the IEEE 754 floating-point types, `==` follows IEEE 754 semantics and so `NaN != NaN`, even for bitwise equivalent values. However, `Equals` follows .NET semantics and fits the needs around using a type in dictionaries, sets, and other collection types and so `NaN.Equals(NaN)`, even for NaNs of differing signs or payloads.

**Review by T-Gro — APPROVED** [review]

**Pull request merged**
