### PR TITLE
[WIP] Try to use @gerardtoconnor MaxBuffer

### PR DESCRIPTION
**Pull request by forki**
/cc @gerardtoconnor

### CODE REVIEW

**Comment by gerardtoconnor** [comment]
@forki apologies, I posted benchmarked better code in main PR, this is slower and no go

**Comment by forki** [comment]
@gerardtoconnor can you please take a look?

**Comment by forki** [comment]
@gerardtoconnor there is a off-by-1 error:

        let buffer = SuggestionBuffer("abcd")
        buffer.Add("abce")
        buffer.Add("somethingcompletelyunrelated")

        -> [|"abce"; null|]

**Comment by gerardtoconnor** [comment]
> @gerardtoconnor there is a off-by-1 error:
>     let buffer = SuggestionBuffer("abcd")
>     buffer.Add("abce")
>     buffer.Add("somethingcompletelyunrelated")
> 
>     -> [|"abce"; null|]

😳 thanks ... checking now ...

**Comment by gerardtoconnor** [comment]
My overly aggressive algo comes with some compromises, the tail resets back on itself making a small logic gap on entries (maxSuggestions - 1 -> maxSuggestions)

The following `MoveNext` code adds fallback for this edge case, and only runs null check on final tail position when current = tail on full buffer
```fsharp
member x.MoveNext() = 
    current <- current - 1
    current > tail || (current = tail && data.[current] <> Unchecked.defaultof<_>) //<< update this LOC
```

**Comment by forki** [comment]
Closing in favor of #7060 - changes have been applied over there.

**Pull request closed without merging**
