### PR TITLE
Fix #13686 by upgrading the FsCheck version to next alpha version (stable version is not available on dotnet-public)

### LINKED ISSUE #13686: build.cmd -testFSharpCore for .NET Framework throws: System.InvalidCastException : Unable to cast object of type 'Arrow@249-1[Int32,FSharpFunc'2[FsCheck.Property]]' to type 'Testable'1[FSharpFunc'2......
Running `build.cmd -testFSharpCore` gives a bunch of the following exceptions:

> System.InvalidCastException : Unable to cast object of type 'Arrow@249-1[System.Int32,Microsoft.FSharp.Core.FSharpFunc`2[System.Int32,FsCheck.Property]]' to type 'Testable`1[Microsoft.FSharp.Core.FSharpFunc`2[System.Int32,Microsoft.FSharp.Core.FSharpFunc`2[System.Int32,FsCheck.Property]]]'.

## Repro steps

On a Windows machine with a fresh checkout of the current `main` branch of FSharp:

* run `git clean -xdf`
* run `build.cmd -testFSharpCore`

## Expected behavior

No errors expected

## Actual behavior

A few dozen of the follow errors appear (they are all `InvalidCastException` and all have something like `Arrow@999` in the name, suggesting it's failing a cast of a compiler-generated function type).

It turns out that **every test that uses `Check.QuickThrowOnFailure` exhibits this behavior**. These errors muddled the analysis of #13557. After a long while I finally realized this only happened on .NET Framework 4.72 tests. The normal `net6.0` run didn't raise this exception.

Why CI doesn't also expose these issues, I don't know. I can only imagine that there are slight differences in the systems leading to a different JIT, leading to a (slightly) different type resolution. But I'm just theorizing.

```
 FSharp.Core.UnitTests.DiscriminatedUnionTypes+UnionsFSCheckTests.struct unions are comparable
   Source: DiscriminatedUnionType.fs line 141
   Duration: 96 ms

  Message: 
    System.InvalidCastException : Unable to cast object of type 'Arrow@249-1[System.Int32,Microsoft.FSharp.Core.FSharpFunc`2[System.Int32,FsCheck.Property]]' to type 'Testable`1[Microsoft.FSharp.Core.FSharpFunc`2[System.Int32,Microsoft.FSharp.Core.FSharpFunc`2[System.Int32,FsCheck.Property]]]'.

  Stack Trace: 
    IntrinsicFunctions.UnboxGeneric[T](Object source)
    Runner.check[a](Config config, a p)
    Check.QuickThrowOnFailure[Testable](Testable property)
```

Example of a test that fails:

```f#
[<Fact>]
member _.``struct unions are comparable`` () =
    Check.QuickThrowOnFailure <|
    fun (i1:int) (i2:int) ->
        i1 <> i2 ==>
        let sr1 = SU (i1, i2)
        let sr2 = SU (i1, i2)
        let sr3 = SU (i2, i1)
        (sr1 = sr2)                    |@ "sr1 = sr2" .&.
        (sr1 <> sr3)                    |@ "sr1 <> sr3" .&.
        (sr1.Equals sr2)               |@ "sr1.Equals sr2"
```

## Known workarounds

Don't run tests. Just commit and wait a few hours for CI, which isn't really a workaround, but was my go-to method for a while.

## Cause

After many sessions on Slack with @vzarytovskii (thanks!) and today writing a new analysis to him about what I had found so far, I noticed that **the FsCheck library, while a 3.0 alpha release, is 4 years old!**.

I already saw a bunch of these errors, for instance: https://github.com/Microsoft/fsharplu/issues/14. But I dismissed them as I figured "hey, we have a 3.0x version, must be hot of the press!".

But noooooo 😮 

image

Still, I have no idea why these tests pass on other people's machines, or why CI passes them. Anyway, testing one by one showed:

| Version      | Release | Used by FSharp | Exhibits this problem |
|--------------|---------|----------------|-----------------------|
| 3.0.0-beta2  | 2022-01 |                | Probably not*         |
| 3.0.0-beta1  | 2021-09 |                | Probably not*         |
| 3.0.0-alpha5 | 2020-12 |                | No                    |
| 3.0.0-alpha4 | 2018-06 | YES            | YES                   |
| 3.0.0-alpha3 | 2017-12 |                | YES                   |
| 3.0.0-alpha2 | 2017-10 |                | No                    |
| 3.0.0-alpha1 | 2017-09 |                | No                    |
| 2.16.5 | 2022-06 |                | No**                    |

\* I couldn't use this because these are not in the NuGet sources used by FSharp, they seem to be quite far behind with only having the 2020 version
\** I only tested this stable version with the FSharp.Core tests for .NET Framework, it works

## Proposal

* Create some mechanism that we can clearly see what platform (Framework/Core) a test is failing for. Unless you suspect this, it is _very_ hard to find. Just knowing that all tests are run twice would already be helpful (and I should've known!), I guess.
* Upgrade `FsCheck` to at least `3.0.0-alpha5`, or downgrade to `2.16.5` until the 3.x versions become stable. A lot of 3.x features have been backported into 2.x anyway.

### PR DESCRIPTION
**Pull request by abelbraaksma**
Fixes #13686.
Unblocks: #13558
Related to: #13557 (part of the cause of that mess)

As explained in that issue, on certain platforms (in this case Windows), the very old (2018!) version of FsCheck, which is an alpha release (`3.0.0-alpha4` to be exact) can raise `InvalidCastException` on invocation of the `Check.QuickThrowOnFailure` methods.

This aims to solve that.

EDIT 2: going for `2.16.5`, see discussion below, it was added to the available MS packages.

**Ready for review.**

### Overview of versions that exhibit `InvalidCastException`:

| Version      | Release | Used by FSharp | Throws on `QuickThrowOnFailure`  |
|--------------|---------|----------------|-----------------------|
| 3.0.0-beta2  | 2022-01 |                | Probably not*         |
| 3.0.0-beta1  | 2021-09 |                | Probably not*         |
| 3.0.0-alpha5 | 2020-12 |                | No                    |
| 3.0.0-alpha4 | 2018-06 | YES            | YES                   |
| 3.0.0-alpha3 | 2017-12 |                | YES                   |
| 3.0.0-alpha2 | 2017-10 |                | No                    |
| 3.0.0-alpha1 | 2017-09 |                | No                    |
| 2.16.5 | 2022-06 |                | No**                    |

\* Not available in MS's nuget feed, not known whether it exhibits this issue, probably not
\*\* Not available in MS's nuget feed, but I've locally checked that it solves the problem

### CODE REVIEW

**Comment by abelbraaksma** [comment]
[Odd, as this wasn't an issue](https://dev.azure.com/dnceng/public/_build/results?buildId=1942268&view=logs&j=21ffccb3-dd24-5c7d-bf5b-5230b6605867&t=3052aa15-d19e-578e-4f82-9dc8afbd1ff5&l=984) locally, which used the same `nuget.config`:

```
FSharp.Core.UnitTests.fsproj : error NU1103: Unable to find a stable package FsCheck with version (>= 2.16.5) [/Users/runner/work/1/s/FSharp.sln]
FSharp.Core.UnitTests.fsproj : error NU1103:   - Found 78 version(s) in dotnet-public [ Nearest version: 3.0.0-alpha1 ] [/Users/runner/work/1/s/FSharp.sln]
```

Let's try the latest alpha then.

**Comment by KevinRansom** [comment]
@abelbraaksma , if you let us know what version to prop to our nuget feed, we will ensure it gets added.

thanks

KEvin

**Comment by abelbraaksma** [comment]
@KevinRansom, from the referred issue, that would be stable FsCheck `2.16.5`, and from the 3.x branch, that would be `3.0.0-beta2`.

I tested locally with the stable branch, I think that, if we can, we should use that, and no alpha or beta branches.

**Comment by abelbraaksma** [comment]
This is ready for review, unless the nuget feed gets updated (not sure how long that normally takes, ie, is there some formal process or not?), in which case we could use the latest version instead.

**Comment by abelbraaksma** [comment]
@KevinRansom and/or @vzarytovskii I'm not sure about what's needed to change the MS nuget feed, please advice. Otherwise, the current PR solves the problems with running these tests on Windows machines.

**Comment by vzarytovskii** [comment]
2.6.15 should be in dotnet-public

**Comment by abelbraaksma** [comment]
@vzarytovskii, see https://github.com/dotnet/fsharp/pull/13687#issuecomment-1214252389. It isn't picked up. Re-quoting the error:

```
FSharp.Core.UnitTests.fsproj : error NU1103: Unable to find a stable package FsCheck with version (>= 2.16.5) [/Users/runner/work/1/s/FSharp.sln]
FSharp.Core.UnitTests.fsproj : error NU1103:   - Found 78 version(s) in dotnet-public [ Nearest version: 3.0.0-alpha1 ] [/Users/runner/work/1/s/FSharp.sln]
```

**Comment by vzarytovskii** [comment]
> @vzarytovskii Vlad Zarytovskii FTE, see [#13687 (comment)](https://github.com/dotnet/fsharp/pull/13687#issuecomment-1214252389). It isn't picked up. Re-quoting the error:
> 
> ```
> FSharp.Core.UnitTests.fsproj : error NU1103: Unable to find a stable package FsCheck with version (>= 2.16.5) [/Users/runner/work/1/s/FSharp.sln]
> FSharp.Core.UnitTests.fsproj : error NU1103:   - Found 78 version(s) in dotnet-public [ Nearest version: 3.0.0-alpha1 ] [/Users/runner/work/1/s/FSharp.sln]
> ```

I can see it in the feed:
https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-public/NuGet/FsCheck/overview/2.16.5

**Comment by abelbraaksma** [comment]
@vzarytovskii localky that works, but CI fails. See this commit, it was my first try, I don’t know how to solve that: https://github.com/dotnet/fsharp/pull/13687/commits/8d0df9afbd20e83e8cbf715b3767e9c5b2a4c5ec

**Comment by abelbraaksma** [comment]
@vzarytovskii thanks, I wasn't aware, indeed. Trying with stable `2.16.5` now.

**Comment by abelbraaksma** [comment]
@vzarytovskii, or @dsyme this very small PR is ready, can you review and/or merge? It unblocks other work.

**Review by vzarytovskii — APPROVED** [review]

**Comment by abelbraaksma** [comment]
Thanks! Small change solves a lot of issues!

**Pull request merged**
