### PR TITLE
Refactor CE checking

### PR DESCRIPTION
**Pull request by vzarytovskii**
1. Move CE checking functions out of `TcComputationExpression`.
2. Pass all arguments explicitly (before they were captured inside) - not the prettiest, but makes it possible to argue about perf and optimizations.
3. Perf **is not a goal** now, benchmarks show no degradation, slight improvement if anything in hyperfine:
> Before:
  Time (mean ± σ):      2.215 s ±  0.071 s    [User: 2.266 s, System: 0.269 s]
  Range (min … max):    2.119 s …  2.332 s    100 runs

> This PR:
  Time (mean ± σ):      2.151 s ±  0.048 s    [User: 2.222 s, System: 0.251 s]
  Range (min … max):    2.081 s …  2.224 s    100 runs
  
This PR is **only a refactoring** and is a prerequisite before I will start tinkering with CE checking.

Test file:
[testcode.fs.zip](https://github.com/user-attachments/files/16428166/testcode.fs.zip)

### CODE REVIEW

**Review by T-Gro — APPROVED** [review]

**Review by edgarfgp — APPROVED** [review]

**Comment by vzarytovskii** [comment]
So, good news is that it's not this pr causes proto build crash. Bad news is that I don't know what causes it or what are the consequences. I am going to build it in loop on devbox until postmortem debugger kicks in

**Comment by vzarytovskii** [comment]
It seems that the reason for this crash is the issue in p6 runtime has (there are a bunch of crashes in Rosyln have been reported). It seems it doesn't crash on p4 or p7. I will proceed with this PR (I have some change to introduce a wrapper type to pass into all functions, and do it one-by-one).

**Comment by edgarfgp** [comment]
One thing to consider is that this PR might put back some removed code in previous PRs due to refactor nature

**Review by psfinaki — APPROVED** [review]

**Comment by vzarytovskii** [comment]
That's ready as soon as tests are passing.

**Review by edgarfgp — APPROVED** [review]

**Comment by vzarytovskii** [comment]
Oh, Azure DevOps seems to be not feeling very well now. Might take a bit before CI passes :|

**Pull request merged**
