### PR TITLE
update xlf files

### PR DESCRIPTION
**Pull request by brettfo**
Building from a clean state shows new/changed LOC strings, probably from the 16.6 LOC checkin last week.

### CODE REVIEW

**Comment by KevinRansom** [comment]
Lol ... https://github.com/dotnet/fsharp/pull/9023 ... you could approve a merge this one it's ready :-)

**Comment by KevinRansom** [comment]
What was wrong with mine from earlier?

**Comment by brettfo** [comment]
> What was wrong with mine from earlier?

I simply didn't see it :)

**Comment by KevinRansom** [comment]
@brettfo , I realize that, I just wanted to be whiney, I hang around with michael all day :-)

**Pull request closed without merging**
