### PR TITLE
WIP: Change generic "This value is not a function and cannot be applied" error message.

### PR DESCRIPTION
**Pull request by isaacabraham**
In an attempt to make some progress on #5475, here's a sample error message that I think is more usable for newcomers to the language. As always, it's also more verbose and I suspect can be trimmed down.

The biggest problem is that I don't know all the cases when this error message can be generated, so there may be situations where it's not appropriate.

### CODE REVIEW

**Comment by cartermp** [comment]
I think part of the confusion with this message that I saw in user studies was the "this value is not a function" bit, but the message itself didn't say what the value or assumed argument are. Additionally, I'm not sure of where this could trigger in places where you need to disambiguate with parentheses. At least in my experience it's always a type mismatch error unless it's a value and not a function.

Splicing in the value and argument (first arg is probably fine) like this and expanding the message similar to what you did could work:

`'%value%' is not a function but you are treating it like one by passing '%arg%' as an argument to it. Did you intend to treat '%value%' as a function here?`.

**Comment by cartermp** [comment]
cc @forki since he's got valuable opinions as well :)

**Comment by matthid** [comment]
I agree with @cartermp, we shouldn't be guessing to much about the error. Personalization can already drastically improve the scenario. We can give a better error like suggested here when we are sure about the scenario and when we can personalize the message. We shouldn't list a bunch of generic examples as it might increase the confusion imho...

**Comment by isaacabraham** [comment]
@matthid Agreed - my original thought was that a "phase 1" would be to simply improve the basic message, without needing to get a handle to the context / personalisation capabilities. And then a subsequent improvement with context.

**Comment by isaacabraham** [comment]
Would anyone be willing to work with me (or one of my colleagues) - potentially with screenshare - to work through this? I've done basically PRs to the compiler but nothing that involved this sort of enhancement i.e. bringing in a richer context of information in order to improve an error message.

**Comment by KevinRansom** [comment]
@isaacabraham --- is this still something you wish to pursue?

**Comment by isaacabraham** [comment]
@KevinRansom yes, I'm happy to invest time into this - as long as I know what should actually be done :-) It sounds like the original idea I had (relatively cheap to do) won't work as the original error is too generic and occurs in too many places?

@cartermp are there any examples of how to "splice" in the arguments? Like, will what you have done "just work"? Where does `%value%` come from?

**Comment by cartermp** [comment]
On second thought, this would be fine without splicing in any info. It's possible to do by modifying the core error type in the typechecker to contain some information about the name of the expression, and possible go further by pretty-printing its signature like in OCAML. But this gives a much better indication of the example in the bug than before.

**Comment by cartermp** [comment]
@isaacabraham I think this would be good to take as-is. Are you still interested in pursuing it? Might need to do a hard rebase here

**Comment by cartermp** [comment]
Closing out old PR. @isaacabraham please ping if you'd like to re-open.

**Comment by isaacabraham** [comment]
Hi. Sorry for tardy response here. I'll try to resurrect this branch - worst case I'll just do it again.

**Comment by isaacabraham** [comment]
@cartermp I've merged master into this so it should be good to merge into master, if you like. I'm still happy to look into rewording or doing some screenshare to learn how to do the magic context stuff.

As an aside - on the F# training course that we ran last month, the two main issues that I had to personally get involved to help people with were:

1. Precedence - why does `add 1 add 2 3` not work but `add 1 (add 2 3)` work? (This was *after* having to explain to them what the error message was about in the first place, as they couldn't grok it). Also around pipelining there was a little bit of handholding needed but generally that wasn't too bad.
1. Missing else branches on if / elif i.e. #6873

**Comment by isaacabraham** [comment]
@cartermp I've tested this out and it seems to still be working e.g.

```fsharp
let add x y = x + y
let z = add 1 add 1 2 // triggers new error message

let aValue = add 1 0
let shouldFail = aValue 10 // triggers new error message

let shouldAlsoFail = add 1 2 3 // triggers new error message
```

**Comment by abelbraaksma** [comment]
Great improvement! Could you share how the message looks when the parameters are filled in?

**Comment by isaacabraham** [comment]
@abelbraaksma by "filled in", what do you mean?

**Comment by cartermp** [comment]
@isaacabraham cool! definitely feel-free to re-open this one, or just do a new PR. I'll review from there

**Comment by isaacabraham** [comment]
@cartermp I can't reopen this one, but that would seem to be the best thing to do as we can keep the history.

**Comment by abelbraaksma** [comment]
@isaacAbraham, I meant:

> '%value%' is not a function but you are treating it like one by passing '%arg%' as an argument to it. Did you intend to treat '%value%' as a function here?.

 I wondered what went where in the examples above with `add`, esp where you have the the `add` function twice. I'm just not sure what comes for value and what for arg (as either could be a function).

**Comment by isaacabraham** [comment]
@abelbraaksma at the moment this is using the "hard coded" message variant, not the one which is parameterised :-( Sorry.

**Comment by isaacabraham** [comment]
Not sure why the build failed on those three since it worked on 10 others.

**Comment by cartermp** [comment]
It's not a build failure, it's test failures. You can inspect which tests failed by diving into the details of CI runs.

**Comment by isaacabraham** [comment]
Whoops. I assumed since some passed and some failed there was some transient issue.

**Comment by cartermp** [comment]
Nope. Not all CI runs are the same here, since many of the tests we have rely on environmental dependencies.

**Comment by abelbraaksma** [comment]
@isaacAbraham, I recently discovered that some CI build run the same test set on Core and Framework, but report only once, even if two tests fail (I mean, same test, different framework or core). I doubt that is the issue here, but you can run in the same test failing without knowing that you only fixed it for one framework.

I've an issue open where I'm trying to collect that info to make life a little easier. It appears that little is known about the exact configs atm.

(ideally, I'd dump the meta info on each failing test, to make this more easily discoverable, and CI should report the real number of failing tests, eventually)

**Comment by KevinRansom** [comment]
I'm closing this it's over a year old.  Perhaps we can revisit this in the future.

**Pull request closed without merging**
