### PR TITLE
Use InlineIfLambda in core collections

### PR DESCRIPTION
**Pull request by pirrmann**
More uses of `InlineIfLambda`, matching the pre-approved RFC (https://github.com/fsharp/fslang-design/blob/main/RFCs/FS-1115-InlineIfLambda-in-FSharp-Core.md) following the rule "systematically use it on every inlined function that takes a lambda which is only applied once".

I haven't inlined more functions in core here, so this should not be a controversial PR, but I also think that more core functions could benefit from being inlined.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=12756) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=12756) before we can accept your contribution.<br/><br/>:x: pirrmann [sign now](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=12756)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/fsharp?pullRequest=12756) it.</sub>

**Comment by pirrmann** [comment]
I'll soon review all the tests failures.

**Comment by teo-tsirpanis** [comment]
Failures are:

* https://github.com/dotnet/fsharp/blob/1477ca5102ca74c52ead84b6d076dbf4b1b35b8e/tests/FSharp.Core.UnitTests/FSharp.Core/Microsoft.FSharp.Collections/ArrayModule2.fs#L850-L853

* And this codegen test https://github.com/dotnet/fsharp/blob/a31c18e4f21e802571b1f9fd3bf59f364650b27f/tests/fsharp/Compiler/CodeGen/EmittedIL/BooleanLogic.fs#L64

**Comment by pirrmann** [comment]
I'm surprised that I don't have the `[ArrayModule2.fs` test error when running the tests locally, and I'm a bit puzzled as to how this test could fail. If anyone has an idea I'm happy to read about it.

**Comment by dsyme** [comment]
> [](https://github.com/pirrmann)I'm surprised that I don't have the ArrayModule2.fs test error when running the tests locally, and I'm a bit puzzled as to how this test could fail. If anyone has an idea I'm happy to read about it.

Is it release v. debug?

**Comment by pirrmann** [comment]
> Is it release v. debug?

Yes, I only get the test to fail in Release build. From the [produced IL](https://sharplab.io/#v2:DYLgZgzgNALiCWwA+B7ADgUwHYAIDKAnhDBgLYCwAUFcBjDvFsIxjhAK6kBCBOAFAG0APAEkmLEWAAyAQ1IAjACYyAfAF0caAE4oAVhgDGMeCiwgcAcgAqOALQqcAPQCqASn4ytWmQXPWBau7mLjgAvDhUOFE4tPSk7DAy8rQ4MgYGYTiyWADm7DI5GAAKWvCk8MYAbhgQAHQA4tgYpQYAWs0oQk7OKpHRYChaDJkADDgwKKlePrVS2DkwABZ2OACMOIoofdHRaRlCtjgAwouGANYYirV8ANTue/zaeobGplPeBLUC8IHbqelUKgwAiYY58dyhQGUHakMjyZo4AD6tSsNRgq3BYT+O1iODAwBQMhgAEFpr42DBSrkApkBEgcAAiVa1ABMDIA3AyAMy1ACsHIZADZagB2Bk4JBqbHRUkfWocbi8fGEmBcll4glE2U+aVRP6whQI5Go4gszGQ6E7aK45VasnmYhUnI08J0xnMtmcnn8znCsUSqWWq1sTg8fhgdi4CB2By21XqiDuOPaghAA===), I can see that `float32` is inlined as well, which in turn inlines `ParseSingle`. Although everything should produce the same output, there is a slight difference.

**Comment by pirrmann** [comment]
From my point of view this is ready, please let me know if there's anything to change.

**Comment by vzarytovskii** [comment]
It looks good to me, I wonder if we want more ILgen tests to verify correct inlining.
We have them in the other modules, and we have `[<InlineIfLambda>]` verified in general though.

**Review by vzarytovskii — APPROVED** [review]

**Comment by abelbraaksma** [comment]
> but I also think that more core functions could benefit from being inlined.

About that, quite a while back I looked into that (before `InlineIfLambda` was a thing), wondering the same thing. In most cases though, the functions were small enough to be inlined by the JIT, so there wouldn't be a runtime benefit to inline them.

There's also the case that sometimes the JIT can optimize better when it knows the body of the functions/methods, as opposed to them being IL'ed inside bodies of other functions which then in turn cannot be optimized well. But that's hard to measure except for some individual cases.

This observation doesn't apply to inlined lambdas, that's a whole different thing. This PR is perfect in that respect :).

Just my 2p.

**Comment by smoothdeveloper** [comment]
Just my cheaper .02e as well :), I quickly tried to apply the new optimization to replace a single member DU that wraps a function, and the few places, resulting in much more inlined code, and it performed slower.

I think the matter should be evaluated carefully (and @matthewcrews reminded me once more, benchmarking is trickier than tricky), despite for this PR, it seems it is deterministic what will occur, should be the same, IIUC.

I'd personally be eager to see a performance profile of compiling the compiler before / after the optimization, to see if it has any measurable impact on the compiler itself.

@KevinRansom / @brettfo is there any chance, we would integrate a "under profiling profiler" compilation of compiler report into the CI process, if the tooling is available as part of dotnet sdk?

**Comment by pirrmann** [comment]
> > but I also think that more core functions could benefit from being inlined.
> 
> About that, quite a while back I looked into that (before `InlineIfLambda` was a thing), wondering the same thing. In most cases though, the functions were small enough to be inlined by the JIT, so there wouldn't be a runtime benefit to inline them.
> 
> There's also the case that sometimes the JIT can optimize better when it knows the body of the functions/methods, as opposed to them being IL'ed inside bodies of other functions which then in turn cannot be optimized well. But that's hard to measure except for some individual cases.
> 
> This observation doesn't apply to inlined lambdas, that's a whole different thing. This PR is perfect in that respect :).
> 
> Just my 2p.

That's why I didn't want to add anything else to the scope of this PR, and not start a debate here!

My own 2 cents, though: one benefit that I can see, when considering inlining more functions, is that it opens the case for using InlineIfLambda in more places. My goal here was to remove the allocation of closures where they can be avoided, without having to write loops by hand, and for that, inline functions + InlineIfLambda are just a perfect combination.

**Review by KevinRansom — APPROVED** [review]

**Comment by vzarytovskii** [comment]
@smoothdeveloper 
> @KevinRansom / @brettfo is there any chance, we would integrate a "under profiling profiler" compilation of compiler report into the CI process, if the tooling is available as part of dotnet sdk?

Just adding it to CI won't really make much sense, since the environment (i.e. agent we're running our CI builds) is not stable/reproducible, and we can be getting different VMs every time, so, we won't be able to compare results of profiling.

However we should probably add it as part of https://github.com/dotnet/performance at some point.

**Comment by KevinRansom** [comment]
@smoothdeveloper, I saw your comment, we will have a chat to figure out if there is something we can do about perf examination with the CI.

**Pull request merged**
