### PR TITLE
Update the default fsharp language version to 5.0

### LINKED ISSUE #10144: Default LangVersion for .NET 5 is still F# 4.7
You cannot use any F# 5 features unless you explicitly set LangVersion to `preview` or `5.0`.

### PR DESCRIPTION
**Pull request by KevinRansom**
Fixes #10144

mea culpa  ... throw big sticks at me over this, I completely missed it.

### CODE REVIEW

**Comment by cartermp** [comment]
`LanguageFeature.OverloadsForCustomOperations` should also be lifted to 50. It works great. Otherwise, this is good

**Review by cartermp — APPROVED** [review]

**Comment by KevinRansom** [comment]
@cartermp , I will submit a seperate PR for overloads for custom operators.  I know it seems silly but revert and bisect for failures is easier.  And I expect that will require some test updating too.

**Comment by dsyme** [comment]
All of these are still listed as preview is that right??
```
            LanguageFeature.FromEndSlicing, previewVersion
            LanguageFeature.OpenTypeDeclaration, previewVersion
            LanguageFeature.PackageManagement, previewVersion
            LanguageFeature.WitnessPassing, previewVersion
            LanguageFeature.InterfacesWithMultipleGenericInstantiation, previewVersion
            LanguageFeature.NameOf, previewVersion
            LanguageFeature.StringInterpolation, previewVersion
```

**Comment by cartermp** [comment]
No, only in `main`. I have no idea why `main` isn't showing this though.

https://github.com/dotnet/fsharp/blob/release/dev16.8/src/fsharp/LanguageFeatures.fs#L63

**Comment by KevinRansom** [comment]
Once dev16.8 branch has rtm'd we will integrate the changes back into master.  We make version changes like this only in the release branches like dev16.8.  Once the release branches have rtmd they are integrated back into master.  It's just the process we use and it works out fine.

**Pull request merged**
