### PR TITLE
[RFC FS-1114] Make long-established deprecation warning messages into errors

### PR DESCRIPTION
**Pull request by dsyme**
Implements https://github.com/fsharp/fslang-design/blob/main/RFCs/FS-1114-ml-compat-revisions.md

* [ ] get it green

### CODE REVIEW

**Comment by dsyme** [comment]
@KevinRansom This is now ready (though I know you're prioritizing the F# 6.0 labelling, that comes first). 

The revisions go into preview with this PR. These don't have to be part of F# 6.0, happy for you to decide when to integrate

The PR also adds LangVersion to LexBuffer and this simplifies the many places we pass functions through.  FCS now respects the language version for ParseFile operations, e.g. if one comes in explicitly via the ParsingOptions (which will stem from project options). This is correct API behaviour and the tests have been adjusted for it, though it won't change any actual IDE behaviour since no IDEs just parse files, they always ParseAndCheck files.

**Comment by auduchinok** [comment]
> though it won't change any actual IDE behaviour since no IDEs just parse files, they always ParseAndCheck files

Just for the record, we use ParseFile a lot in Rider.

**Comment by dsyme** [comment]
> Just for the record, we use ParseFile a lot in Rider.

Right, I'm assuming you still collect diagnostics from CheckFile (of course).  

Anyway either way it's still right that ParseFile respect language version.

**Comment by dsyme** [comment]
> We currently report parse and type check errors separately, and the parse ones come from ParseFile. It was implemented this way before the LangVersion was introduced, and I didn't know ParseFile worked differently these days.

Today, ParseFile effectively uses preview language version 

* FSharpParsingOptions doesn't have any langversion info.

* When parsing "lexbuf.SupportsFeature" is implemented as a lambda returning `true`, meaning all features are considered supported

In practice this doesn't matter today.  However with this PR we start to emit errors for the long-deprecated features, but that depends on langversion, so it's important to pass the right langversion through.

**Review by KevinRansom — APPROVED** [review]
Thanks for this

**Pull request merged**
