### PR TITLE
Revert 16348

### PR DESCRIPTION
**Pull request by 0101**
This reverts https://github.com/dotnet/fsharp/pull/16348 Cancellable: set token from node/async in features code 

It seems it was generating some random cancellations in tests and I couldn't figure out why. It's likely that this can also occur in regular FCS usage outside tests.

There are also fixes for some unrelated test flakiness.

### CODE REVIEW

**Comment by 0101** [comment]
@auduchinok I think we should revert unless you have any ideas on how to fix it.

**Comment by auduchinok** [comment]
> @auduchinok I think we should revert unless you have any ideas on how to fix it.

Yes, sure, the tests stability is much more important. We can also try to reiterate on it once more later, e.g. after the Node/Cancellable builders refactoring, if needed.

**Review by psfinaki — APPROVED** [review]

**Comment by majocha** [comment]
I encountered this errors while typing in the editor:
Might be of interest, but, fwiw I'm no longer sure what vsix I'm using, probably built from main.

```
System.AggregateException : One or more errors occurred. ---> Index was outside the bounds of the array.
   at <StartupCode$FSharp-Compiler-Service>.$AsyncMemoize.Get@494-13.Invoke(Exception _arg17)
   at FSharp.Compiler.BuildGraph.TryWith@72-2.Invoke(Exception x)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallFilterThenInvoke[T](AsyncActivation`1 ctxt,FSharpFunc`2 filterFunction,ExceptionDispatchInfo edi)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.VisualStudio.FSharp.Editor.WorkspaceExtensions.CheckerExtensions.FSharpChecker-ParseAndCheckDocumentUsingTransparentCompiler@355(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.VisualStudio.FSharp.Editor.WorkspaceExtensions.CheckerExtensions.FSharpChecker-ParseAndCheckDocument@448(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.VisualStudio.FSharp.Editor.WorkspaceExtensions.Document-GetFSharpParseAndCheckResultsAsync@538(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async StartupCode$FSharp-Editor(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.<>c__DisplayClass12_0.<GetRefactoringFromProviderAsync>b__0(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
---> (Inner Exception #0) System.IndexOutOfRangeException : Index was outside the bounds of the array.
   at System.Collections.Generic.List`1.Add(T item)
   at Internal.Utilities.Collections.CachingDiagnosticsLogger.DiagnosticSink(PhasedDiagnostic diagnostic,FSharpDiagnosticSeverity severity)
   at FSharp.Compiler.ParseAndCheckInputs.CheckOneInputWithCallback@1588-13.Invoke(TcState tcState)
   at <StartupCode$FSharp-Compiler-Service>.$TransparentCompiler.clo@1178-619.Invoke(TcInfo tcInfo)
   at FSharp.Compiler.CodeAnalysis.TransparentCompiler.TypeCheckingGraphProcessing.processTypeCheckingGraph@253-6.Invoke(Tuple`2 tupledArg)
   at Microsoft.FSharp.Collections.ArrayModule.Fold[T,TState](FSharpFunc`2 folder,TState state,T[] array)
   at FSharp.Compiler.CodeAnalysis.TransparentCompiler.TypeCheckingGraphProcessing.processTypeCheckingGraph@246-4.Invoke(Tuple`2[] results)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt,b result1,FSharpFunc`2 userCode)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) <--- 
```

also:

```
System.AggregateException : One or more errors occurred. ---> Index was outside the bounds of the array.
   at <StartupCode$FSharp-Compiler-Service>.$AsyncMemoize.Get@494-13.Invoke(Exception _arg17)
   at FSharp.Compiler.BuildGraph.TryWith@72-2.Invoke(Exception x)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallFilterThenInvoke[T](AsyncActivation`1 ctxt,FSharpFunc`2 filterFunction,ExceptionDispatchInfo edi)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.VisualStudio.FSharp.Editor.WorkspaceExtensions.CheckerExtensions.FSharpChecker-ParseAndCheckDocumentUsingTransparentCompiler@355(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.VisualStudio.FSharp.Editor.WorkspaceExtensions.CheckerExtensions.FSharpChecker-ParseAndCheckDocument@448(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.VisualStudio.FSharp.Editor.WorkspaceExtensions.Document-GetFSharpParseAndCheckResultsAsync@538(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async StartupCode$FSharp-Editor(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async StartupCode$FSharp-Editor(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
---> (Inner Exception #0) System.IndexOutOfRangeException : Index was outside the bounds of the array.
   at System.Collections.Generic.List`1.Add(T item)
   at FSharp.Compiler.ParseAndCheckInputs.CheckOneInputWithCallback@1588-13.Invoke(TcState tcState)
   at <StartupCode$FSharp-Compiler-Service>.$TransparentCompiler.clo@1178-619.Invoke(TcInfo tcInfo)
   at FSharp.Compiler.CodeAnalysis.TransparentCompiler.TypeCheckingGraphProcessing.processTypeCheckingGraph@253-6.Invoke(Tuple`2 tupledArg)
   at Microsoft.FSharp.Collections.ArrayModule.Fold[T,TState](FSharpFunc`2 folder,TState state,T[] array)
   at FSharp.Compiler.CodeAnalysis.TransparentCompiler.TypeCheckingGraphProcessing.processTypeCheckingGraph@246-4.Invoke(Tuple`2[] results)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt,b result1,FSharpFunc`2 userCode)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) <--- 

```
image

**Comment by 0101** [comment]
Yeah that does look interesting, thanks for the report. 

Wonder if [`CachingDiagnosticsLogger`](https://github.com/dotnet/fsharp/blob/09ac4000040c3204c03c469bfb9c1f3df0fd0af0/src/Compiler/Facilities/AsyncMemoize.fs#L129) needs to be made thread safe. It probably does!

**Comment by 0101** [comment]
@majocha actually it would be good to know if you saw those exceptions with VSIX from `main` - because then I'd replace that `List` with `ConcurrentQueue`. But if it was with some of your experimental changes then maybe it's not necessary. I imagine there's some performance penalty for it.

I have personally not seen that exception.

**Comment by majocha** [comment]
@0101 I'm now on current main, with this PR (revert) merged. The concurrency problem is gone and things seem to run really smooth.


The only thing I still see is exceptions surfacing in VS, like the screenshot above, whenever I enable Transparent Compiler. Simple repro: 
Open a file and type
```
module A

module B
```

**Comment by majocha** [comment]
@0101 oops, just now on main:

>System.AggregateException : One or more errors occurred. ---> One or more errors occurred. ---> One or more errors occurred. ---> The input must be non-negative.
count = -1
Parameter name: count
   at <StartupCode$FSharp-Compiler-Service>.$AsyncMemoize.Get@493-12.Invoke(Exception _arg15)
   at FSharp.Compiler.BuildGraph.TryWith@70-2.Invoke(Exception x)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallFilterThenInvoke[T](AsyncActivation`1 ctxt,FSharpFunc`2 filterFunction,ExceptionDispatchInfo edi)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.VisualStudio.FSharp.Editor.WorkspaceExtensions.CheckerExtensions.FSharpChecker-ParseAndCheckDocumentUsingTransparentCompiler@355(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.VisualStudio.FSharp.Editor.WorkspaceExtensions.CheckerExtensions.FSharpChecker-ParseAndCheckDocument@448(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.VisualStudio.FSharp.Editor.WorkspaceExtensions.Document-GetFSharpParseAndCheckResultsAsync@538(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async StartupCode$FSharp-Editor(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.<>c__DisplayClass12_0.<GetRefactoringFromProviderAsync>b__0(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
---> (Inner Exception #0) System.AggregateException : One or more errors occurred. ---> One or more errors occurred. ---> The input must be non-negative.
count = -1
Parameter name: count
   at <StartupCode$FSharp-Compiler-Service>.$AsyncMemoize.Get@493-12.Invoke(Exception _arg15)
   at FSharp.Compiler.BuildGraph.TryWith@70-2.Invoke(Exception x)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallFilterThenInvoke[T](AsyncActivation`1 ctxt,FSharpFunc`2 filterFunction,ExceptionDispatchInfo edi)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
---> (Inner Exception #0) System.AggregateException : One or more errors occurred. ---> The input must be non-negative.
count = -1
Parameter name: count
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive,Int32 toExclusive,ParallelOptions parallelOptions,Action`1 body,Action`2 bodyWithState,Func`4 bodyWithLocal,Func`1 localInit,Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive,Int32 toExclusive,Action`1 body)
   at Microsoft.FSharp.Collections.ArrayModule.Parallel.Map[T,TResult](FSharpFunc`2 mapping,T[] array)
   at FSharp.Compiler.GraphChecking.DependencyResolution.mkGraph(FilePairMap filePairs,FileInProject[] files)
   at <StartupCode$FSharp-Compiler-Service>.$TransparentCompiler.clo@929-597.Invoke(IDisposable _arg19)
   at FSharp.Compiler.BuildGraph.Using@114-6.Invoke(IDisposable _arg6)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt,TResult result1,FSharpFunc`2 part2)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
---> (Inner Exception #0) System.ArgumentException : The input must be non-negative.
count = -1
Parameter name: count
   at Microsoft.FSharp.Primitives.Basics.List.take[T](Int32 n,FSharpList`1 l)
   at FSharp.Compiler.GraphChecking.FileContentMapping.longIdentToPath(Boolean skipLast,FSharpList`1 longId)
   at FSharp.Compiler.GraphChecking.FileContentMapping.mkFileContent(FileInProject f)
   at Microsoft.FSharp.Collections.ArrayModule.Parallel.Map@2063-2.Invoke(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>) <--- 
 <--- 
 <--- 

image


I'm positive I built and installed VSIX from current main.

**Comment by majocha** [comment]
on top of existing will do

**Comment by 0101** [comment]
The exception seems to point here
https://github.com/dotnet/fsharp/blob/3af3d4182ea5284f37cc85f408f392070eb1ee8c/src/Compiler/Driver/GraphChecking/FileContentMapping.fs#L11-L14

And `longId` being empty.

**Comment by 0101** [comment]
Ok, I've been able to reproduce it by just typing `mo` on top a file which starts with `module`. 

With an extra one from `FSharpCompletionProvider`:

<details><summary>A nested module cannot have multiple identifiers</summary>

```fsharp
System.AggregateException : One or more errors occurred. ---> One or more errors occurred. ---> One or more errors occurred. ---> A nested module cannot have multiple identifiers
   at <StartupCode$FSharp-Compiler-Service>.$AsyncMemoize.Get@488-13.Invoke(Exception _arg17)
   at FSharp.Compiler.BuildGraph.TryWith@72-2.Invoke(Exception x)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallFilterThenInvoke[T](AsyncActivation`1 ctxt,FSharpFunc`2 filterFunction,ExceptionDispatchInfo edi)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.VisualStudio.FSharp.Editor.WorkspaceExtensions.CheckerExtensions.FSharpChecker-ParseAndCheckDocumentUsingTransparentCompiler@355(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.VisualStudio.FSharp.Editor.WorkspaceExtensions.CheckerExtensions.FSharpChecker-ParseAndCheckDocument@448(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.VisualStudio.FSharp.Editor.WorkspaceExtensions.Document-GetFSharpParseAndCheckResultsAsync@538(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async StartupCode$FSharp-Editor(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async StartupCode$FSharp-Editor(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
---> (Inner Exception #0) System.AggregateException : One or more errors occurred. ---> One or more errors occurred. ---> A nested module cannot have multiple identifiers
   at <StartupCode$FSharp-Compiler-Service>.$AsyncMemoize.Get@488-13.Invoke(Exception _arg17)
   at FSharp.Compiler.BuildGraph.TryWith@72-2.Invoke(Exception x)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallFilterThenInvoke[T](AsyncActivation`1 ctxt,FSharpFunc`2 filterFunction,ExceptionDispatchInfo edi)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
---> (Inner Exception #0) System.AggregateException : One or more errors occurred. ---> A nested module cannot have multiple identifiers
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive,Int32 toExclusive,ParallelOptions parallelOptions,Action`1 body,Action`2 bodyWithState,Func`4 bodyWithLocal,Func`1 localInit,Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive,Int32 toExclusive,Action`1 body)
   at Microsoft.FSharp.Collections.ArrayModule.Parallel.Map[T,TResult](FSharpFunc`2 mapping,T[] array)
   at FSharp.Compiler.GraphChecking.DependencyResolution.mkGraph(FilePairMap filePairs,FileInProject[] files)
   at <StartupCode$FSharp-Compiler-Service>.$TransparentCompiler.clo@917-598.Invoke(IDisposable _arg19)
   at FSharp.Compiler.BuildGraph.Using@116-6.Invoke(IDisposable _arg6)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt,TResult result1,FSharpFunc`2 part2)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
---> (Inner Exception #0) System.Exception : A nested module cannot have multiple identifiers
   at FSharp.Compiler.GraphChecking.FileContentMapping.visitSynModuleDecl(SynModuleDecl decl)
   at Microsoft.FSharp.Primitives.Basics.List.collectToFreshConsTail[T,TResult](FSharpFunc`2 f,FSharpList`1 list,FSharpList`1 cons)
   at Microsoft.FSharp.Primitives.Basics.List.collect[T,TResult](FSharpFunc`2 f,FSharpList`1 list)
   at FSharp.Compiler.GraphChecking.FileContentMapping.mkFileContent(FileInProject f)
   at Microsoft.FSharp.Collections.ArrayModule.Parallel.Map@2060-2.Invoke(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>) <--- 
 <--- 
 <--- 
```
</details>

**Comment by majocha** [comment]
> The exception seems to point here
> 
> https://github.com/dotnet/fsharp/blob/3af3d4182ea5284f37cc85f408f392070eb1ee8c/src/Compiler/Driver/GraphChecking/FileContentMapping.fs#L11-L14
> 
> And `longId` being empty.

Yeah, this is not concurrency related, just something in the code fix?

**Comment by 0101** [comment]
Both of them are coming from the graph processing stuff (which I didn't touch). 

They just somehow bubble all the way to VS.

It could be concurrency related if they end up in a wrong ThreadStatic DiagnosticsLogger which doesn't handle them correctly.

Or maybe we're just missing a try/with somewhere to deal with these and gracefully abort the checking. 

Or there's some other issue which makes the input for constructing the graph somehow wrong.

**Comment by majocha** [comment]
>It could be concurrency related if they end up in a wrong ThreadStatic DiagnosticsLogger which doesn't handle them correctly.

Yes, unfortunately this could be the case.
Looking at this:

https://github.com/dotnet/fsharp/blob/276fc42fa8004a1d3c3e26080e964bac9bc14e04/src/Compiler/Facilities/BuildGraph.fs#L16-L26

There is assumption the code after `finally` runs on the same thread as the code before 'try'? I'm not sure think this is correct.

**Comment by 0101** [comment]
Yeah that would be bad. But most likely `async` makes sure that it does run on the same thread. This code has been there forever :) 

What we're seeing here is most likely all symptoms of Graph-based checking not expecting invalid (recovered) syntax trees as input, because it was only intended for a command line compiler where that was not an issue. ([Example #1](https://github.com/dotnet/fsharp/pull/16575))

So we'll have to find and fix those and probably add some guard for when it fails for whatever reason and try to recover it somehow or at least just not crash.

**Comment by vzarytovskii** [comment]
> > It could be concurrency related if they end up in a wrong ThreadStatic DiagnosticsLogger which doesn't handle them correctly.
> 
> Yes, unfortunately this could be the case. Looking at this:
> 
> https://github.com/dotnet/fsharp/blob/276fc42fa8004a1d3c3e26080e964bac9bc14e04/src/Compiler/Facilities/BuildGraph.fs#L16-L26
> 
> There is assumption the code after `finally` runs on the same thread as the code before `try`? I'm not sure this is correct.

It for sure is not explicitly launched on different thread. It will pretty much launch on the same thread async was in the moment when exception/completion happened.

**Comment by majocha** [comment]
> It will pretty much launch on the same thread async was in the moment when exception/completion happened.
But after a few continuations in between it's not necessarily the same thread on which we saved the threadstatics initially?

**Comment by vzarytovskii** [comment]
> > It will pretty much launch on the same thread async was in the moment when exception/completion happened.
> 
> But after a few continuations in between it's not necessarily the same thread on which we saved the threadstatics initially?

Yeah, we technically can end up on different thread, so ideally `finally` should somehow "capture" threadstatics of the thread it was saving those from and restore them.

**Unless** the intent is to always restore threadstatics on the thread continuation is running. Which likely be the case @0101. I am still wrapping my head around this.

**Comment by 0101** [comment]
> Yeah, we technically can end up on different thread, so ideally `finally` should somehow "capture" threadstatics of the thread it was saving those from and restore them.

That's may not be possible in this model (?). So instead we need to make sure we copy them over from the previous thread whenever there's a chance we could have jumped to a new one.

> **Unless** the intent is to always restore threadstatics on the thread continuation is running. Which is likely the case (cc @0101). I am still wrapping my head around this.

Yeah that makes sense. The code that will run afterwards needs to have the same thread statics. It doesn't need to be back on the same thread.

Still this test should be passing: https://github.com/dotnet/fsharp/pull/16576

So there must be a place where we don't copy over the phase when jumping on a new thread.

**Comment by 0101** [comment]
> So there must be a place where we don't copy over the phase when jumping on a new thread.

Well I guess it's here. `NodeCode.Parallel` doesn't do anything about thread statics. 

https://github.com/dotnet/fsharp/blob/641d0ee179755ba700c3ac780a347f916d740472/src/Compiler/Facilities/BuildGraph.fs#L195-L196

**Pull request merged**
