### PR TITLE
Simplification of #2867

### PR DESCRIPTION
**Pull request by dsyme**
This is trialling a simplification of https://github.com/dotnet/fsharp/pull/2867

### CODE REVIEW

**Comment by KevinRansom** [comment]
@dsyme , hello mate, just for my education, what was the simplification?  Most of the complicated bit still seems to be there?

**Comment by forki** [comment]
https://tse1.mm.bing.net/th?id=OGC.fcbb1e7d74dac5260c19e23daf6ff7ac&pid=Api&rurl=https%3a%2f%2fmedia.tenor.co%2fimages%2ffcbb1e7d74dac5260c19e23daf6ff7ac%2fraw&ehk=BqkycxzWH5tMzyuQ5N8tqjiUVRBi%2bUcM8bu0nPaFO2A%3d

**Comment by forki** [comment]
Lol. Love that comment

**Comment by KevinRansom** [comment]
@dsyme is this ready, the comment says trialing?

**Comment by dsyme** [comment]
> @dsyme , hello mate, just for my education, what was the simplification? Most of the complicated bit still seems to be there?

Basically this: https://github.com/dotnet/fsharp/pull/9446/commits/c5345f8b8831b60e9ab26c624c4825605f7dfa4b

**Comment by dsyme** [comment]
Integrated this into #2867

**Pull request closed without merging**
