### PR TITLE
Make Event's AddHandler/RemoveHandler atomic

### PR DESCRIPTION
**Pull request by gsomix**
Implementation for corresponding [suggestion](https://github.com/fsharp/fslang-suggestions/issues/992).

### CODE REVIEW

**Comment by ForNeVeR** [comment]
I would just try adding and removing some event handler to the same event from, say, 100 threads in a loop of 100 iterations, something like that. It's still possible for such test to accidentally pass for the unsafe implementation, but the probability is miniscule. Hopefully.

**Comment by vzarytovskii** [comment]
> I would just try adding and removing some event handler to the same event from, say, 100 threads in a loop of 100 iterations, something like that. It's still possible for such test to accidentally pass for the unsafe implementation, but the probability is miniscule. Hopefully.

Ideally, we would like to avoid such tests, which rely on timings, it has been a pain in the past, especially when running in the CI :(

**Comment by baronfel** [comment]
It's very possible to do some reflection spelunking on the event and related classes to get the underlying delegates and do assertions on the subscribers to the delegates:

```fsharp
open System.Reflection

let x = new Event<int>()

let getMulticastFor (x: Event<'t>) =
  let t = x.GetType() // Event<'t>
  let v = t.GetField("multicast", BindingFlags.NonPublic ||| BindingFlags.Instance).GetValue x :?> Handler<'t>
  if isNull v then None, typeof<Handler<'t>> else Some v, typeof<Handler<'t>>

let handler, handlerTy = getMulticastFor x
let getInvocationListFor (t: Handler<'t>) =
  let multicastD = handlerTy.BaseType // MulticaseDelegate
  let getListeners = multicastD.GetMethod("GetInvocationList")
  getListeners.Invoke(t, [||]) :?> System.Delegate []

let listenersFor x =
  match getMulticastFor x with
  | None, _ -> None
  | Some m, mTy ->
    getInvocationListFor m |> Some

let xListenersBefore = listenersFor x
printfn $"No listeners before: {xListenersBefore = None}"

x.Publish.Add (fun x -> printfn $"%d{x * 2}")
let xListenersAfter = listenersFor x
printfn $"One listener after: {(xListenersAfter |> Option.map Array.length) = Some 1}"
```

I could see a test using this to assert on the number of subscribers in different threaded-ness environments.

**Comment by gsomix** [comment]
I've added tests (thanks @ForNeVeR and @baronfel!) and rebased against `main`. CI is happy, ready to review. Tests successfully fail on current implementation from `main` branch.

@dsyme @cartermp @vzarytovskii

**Review by cartermp — APPROVED** [review]
Looks reasonable to me!

**Comment by Happypig375** [comment]
Bump @dsyme @vzarytovskii

**Review by vzarytovskii — APPROVED** [review]

**Comment by vzarytovskii** [comment]
Thanks!

**Comment by gsomix** [comment]
Yay! My first merged PR in this repo. Thanks!

**Pull request merged**
