### PR TITLE
Add Expr.NewStructTuple constructor and active pattern

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
Addresses #7914

### CODE REVIEW

**Comment by eiriktsarpalis** [comment]
Should be good now.

**Comment by cartermp** [comment]
@dsyme we'll need your review on this one as well.

**Comment by KevinRansom** [comment]
@cartermp, should this be Fsharp 5?

**Comment by cartermp** [comment]
Nah, this can just be master. I don't see value in gating this one until November since it's just an incremental addition and not tied to any new language change.

**Pull request merged**
