### PR TITLE
Fix adding attribute to both property and getter/setter when AllowMultiple=false

### LINKED ISSUE #11304: AllowMultiple=false prevents adding attribute to both property and getter/setter
C# allows adding an attribute with `AllowMultiple=false` to both a property and its getter and/or setter. F# allows adding the attribute to either the property or its getter/setter, but not both.

**Repro steps**

```fsharp
open System

[<AttributeUsage(AttributeTargets.Property ||| AttributeTargets.Method, AllowMultiple=false)>]
type FooAttribute() = inherit Attribute()

type C() =
    [<Foo>]
    member _.Foo
        with [<Foo>] get () = "bar"
```

**Expected behavior**

Should compile.

**Actual behavior**

`error FS0429: The attribute type 'FooAttribute' has 'AllowMultiple=false'. Multiple instances of this attribute cannot be attached to a single language element.`

**Known workarounds**

Unknown.

**Related information**

Provide any related information (optional):

* Operating system: Mac OS X 10.15.7
* .NET Runtime kind:  .NET Core
* Editing Tools (e.g. Visual Studio Version, Visual Studio): N/A

### PR DESCRIPTION
**Pull request by chkn**
Fixes #11304

### CODE REVIEW

**Comment by cartermp** [comment]
Test failure here:

```
+++ Misc (E_CompiledName.fs) +++
--------------------------------------------------------
Results from hosted compiler
msg: Compiling
cmd: fsc   -a --test:ErrorRanges --flaterrors E_CompiledName.fs 
Exit code: 0
Error:     2
Microsoft (R) F# Compiler version 11.3.1.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.
--------------------------------------------------------
Microsoft (R) F# Compiler version 11.3.1.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

*** The following necessary lines were never matched:
***	\(29,16-29,28\):.+error FS0429:.+The attribute type 'CompiledNameAttribute' has 'AllowMultiple=false'\. Multiple instances of this attribute cannot be attached to a single language element\.$
***	\(30,15-30,27\):.+error FS0429:.+The attribute type 'CompiledNameAttribute' has 'AllowMultiple=false'\. Multiple instances of this attribute cannot be attached to a single language element\.$


*** The following necessary lines were incorrectly matched:

Unexpected Compiler Output 
FAIL
```

If you could also add a test here, that'd be great! https://github.com/dotnet/fsharp/tree/main/tests/FSharp.Compiler.ComponentTests

This is probably a good place: https://github.com/dotnet/fsharp/blob/main/tests/FSharp.Compiler.ComponentTests/Language/AttributeCheckingTests.fs

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=11307) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=11307) before we can accept your contribution.<br/><br/>:x: chkn [sign now](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=11307)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/fsharp?pullRequest=11307) it.</sub>

**Comment by chkn** [comment]
@cartermp Thanks for the pointers! Fixed the failure and added a test.

**Review by cartermp — APPROVED** [review]
Thank you!

**Pull request merged**
