### PR TITLE
FSharpQA tests migration to xUnit suite - Part 1/?

### PR DESCRIPTION
**Pull request by vzarytovskii**
This is a (semi-)automatic migration of F#QA tests to xUnit suite. 

This is pretty much second try of https://github.com/dotnet/fsharp/pull/10415, in previous one, remaining fshsarpqa tests weren't discovered by runner. In this PR, we don't modify tests.lst much.

This PR is migrating only small fraction of simpler tests, which do not require running, IL comparison, or linking other libs - to test the migration script.

After this one is passing, I will start migrating other batches.

### CODE REVIEW

**Comment by dsyme** [comment]
Is there any automatic way to update all IL baselines after a change that affects multiple ones?  Currently I use

    set TEST_UPDATE_BSL=1

**Comment by vzarytovskii** [comment]
> Is there any automatic way to update all IL baselines after a change that affects multiple ones? Currently I use
> 
> ```
> set TEST_UPDATE_BSL=1
> ```

Good question, I don't think it's currently easily possible in the new framework. You can delete baseline files, and they will be re-generated, however with different extension. 
I will look into better way of doing it.

**Comment by KevinRansom** [comment]
I don't automatically do it, so that I can at least eyeball the changes.

**Review by KevinRansom — APPROVED** [review]
The only thing I don't really like is the source being in external files, however, this way is probably much better in practice.

**Review by cartermp — APPROVED** [review]

**Pull request merged**
