### PR TITLE
Add const keyword to completion info

### PR DESCRIPTION
**Pull request by DedSec256**
- Added const keyword to completion info

### CODE REVIEW

**Comment by DedSec256** [comment]
Can you help with the wording of the description text?

**Review by cartermp — APPROVED** [review]

**Comment by cartermp** [comment]
The description text is  good.  Thanks!

**Comment by auduchinok** [comment]
It seems localization files would need an update? What's the proper process of handling this?

**Comment by cartermp** [comment]
These get handled by a localization team leading up to every VS and .NET release. Every once in a while they come back with questions about certain terms but it's usually automatic from our perspective.

**Comment by cartermp** [comment]
I think it's possible to add a custom localization though, if that's preferred.

**Review by KevinRansom — APPROVED** [review]

**Pull request merged**
