### PR TITLE
Updates README with new non-vs-dependent build switch

### PR DESCRIPTION
**Pull request by ChrSteinert**
Related: #7056

### CODE REVIEW

**Comment by auduchinok** [comment]
It'd be really great to fix the build and not to suggest this workaround in the readme. :(

**Comment by forki** [comment]
tbh noVS should be the default

**Comment by ChrSteinert** [comment]
I agree on both points. Though this is not the intention of this PR ;)

**Comment by realvictorprm** [comment]
I completely oversaw this 😂 I'll close my PR

**Pull request merged**
