### PR TITLE
Remove unnecessary DotNetBuildOffline switches

### PR DESCRIPTION
**Pull request by ViktorHofer**
DotNetBuildOffline is set in two test projects in the fsharp repo. Test projects are already filtered out when building from source, so those switches are unnecessary.

We plan to overhaul the source build control switches and remove this one completely. FSharp was the only repo that was still using it.

### CODE REVIEW

**Review by T-Gro — APPROVED** [review]

**Comment by vzarytovskii** [comment]
@ViktorHofer these are not typical test projects, they are "normal" projects which we use to test trimming of freshly built FSharp core. We use those to correctly restore packages, so some more work will be needed to remove those. I can say now what changes are required

**Comment by ViktorHofer** [comment]
> so some more work will be needed to remove those

Everything under "/tests" is already excluded in a source build today: https://github.com/dotnet/fsharp/blob/97923c9a3207784feb7c24b7c2c75a80c080a315/tests/Directory.Build.props#L6

As the `DotNetBuildOffline` switch is only respected when building from source, the properties are just dead code and don't impact other kinds of builds.

**Comment by ViktorHofer** [comment]
This PR depends on https://github.com/dotnet/fsharp/pull/16488

**Comment by ViktorHofer** [comment]
@T-Gro / @vzarytovskii can you please merge this PR in?

**Pull request merged**
