### PR TITLE
build net472 specific dependency manager to make ngen happy

### PR DESCRIPTION
**Pull request by brettfo**
Internal RPS looks clean.  Subsequent VS insertion will require binding redirects for `Interactive.DependencyManager.dll` added to vsn.exe.config.

### CODE REVIEW

**Comment by brettfo** [comment]
@KevinRansom Updated PR to include that line, it was missing from `master`.

**Comment by KevinRansom** [comment]
@brettfo , yes I know, I had to go looking for it, because, I was sure it must be there :-)

**Comment by brettfo** [comment]
Also, confirmed that with this change `VisualFSharpFull.vsix` contains the `net472` variant, and loading up that in ILSpy shows the offending types/methods as not present, but they are in the `netstandard2.0` one.

**Comment by brettfo** [comment]
After much pain, the NGEN logs are clean and internal RPS test doesn't list FSharp.Compiler.Private or Interactive.DependencyManager.  Once green I'll merge this so it can eventually flow into VS branches.

**Pull request merged**
