### PR TITLE
Use 1-based column numbers in tests

### PR DESCRIPTION
**Pull request by forki**
This will make it easier to port tests from fsharpqa over to NUnit

### CODE REVIEW

**Comment by KevinRansom** [comment]
@forki,  I'm not at all sure I understand why adding 1 to the compiler output for the error range is beneficial.  Can you explain please?

**Comment by forki** [comment]
Sure. Before this change the reported ranges in the error message and the expected range differ since the internal compiler ranges are 0-based and the reported errors are 1-based. So if you develop new tests or convert tests from fsharpqa you would always have to convert to the 0-based system. This is confusing.

After the change all expected error ranges are given as you would see them in compiler output or IDE

**Comment by dsyme** [comment]
> Sure. Before this change the reported ranges in the error message and the expected range differ since the internal compiler ranges are 0-based and the reported errors are 1-based. So if you develop new tests or convert tests from fsharpqa you would always have to convert to the 0-based system. This is confusing.

I'm not sure about this - I thought we only had this kind of discrepancy for line nubers, not column numbers?

**Comment by forki** [comment]
I can only say: I had to shift by 1 in order to make tests use the same column numbers as the compiler output in the error message

**Comment by forki** [comment]
@dsyme https://github.com/dotnet/fsharp/blob/master/src/fsharp/CompileOps.fs#L1663 looks like the place in the compiler which changes to 1-based. The comment reads:

    // We're adjusting the columns here to be 1-based - both for parity with C# and for MSBuild, which assumes 1-based columns for error output


Interestingly it's done in all cases of the pattern match except for `ErrorStyle.EmacsErrors` ;-)

**Comment by forki** [comment]
@kevinransom any chance we can get this in as well? Thanks

**Comment by KevinRansom** [comment]
@forki, looks like it needs resolving.

**Comment by forki** [comment]
@KevinRansom done

**Comment by KevinRansom** [comment]
thx

**Comment by forki** [comment]
@KevinRansom it's green

**Comment by cartermp** [comment]
🥗

**Pull request merged**
