### PR TITLE
VS: Use IViewElementFactory as intended

### PR DESCRIPTION
**Pull request by majocha**
Alternative approach to styling QuickInfo, to address the issue with our `IViewElementFactory` being picked up by other packages in  VS.
Now we provide content using the cross platform objects (`ClassifiedTextElement` at al.) and let VS render them. Custom visuals are provided by our internal `FSharpStyle` so the type conversion should never be available to other VS inhabitants.
To make the links look nicer we imperatively touch up the visual tree created by VS. Maybe not a standard, but still a legit way to do this.

`FSharpStyle` overrides `ToString` to render paragraphs and separators cross platform. (To see this in action in VS on Windows just comment out `[<Export(typeof<IViewElementFactory>)>]`)

### CODE REVIEW

**Comment by T-Gro** [comment]
Thanks for the quick turnaround @majocha .

Since the original regression happened as a perf regression for CPlusPlus coding tooltips, could we test that it isn't happening again? As in F# MEF-registered service is not being loaded in non-F# context.

**Review by T-Gro — APPROVED** [review]

**Comment by vzarytovskii** [comment]
I have re-targeted it to 17.7, so we don't wait for bot to merge it.

**Comment by majocha** [comment]
Does it need to be merged into main also?

**Comment by vzarytovskii** [comment]
> Does it need to be merged into main also?

Not necessary, I usually don't bother with such changes. It will get there once 17.7 is merged back, but if you'd like to, you can cherry pick and PR it

**Comment by vzarytovskii** [comment]
Reason for backporting - I want it in main and my branch, where I publish custom VSIX

**Pull request merged**
