### PR TITLE
Add IFileSystem.SourceFileReadShim returning char[]

### PR DESCRIPTION
**Pull request by auduchinok**
Adds API allowing to pass `char[]` to be used by lexer instead of returning `Stream` which is read to `string` which is then thrown away with `.ToCharArray()`.

PR continues work by @smoothdeveloper in #4882 but is aimed at the file system shim clients.

It would be great to use `ReadOnlySpan<char>` (and probably make this API return `string`) instead at some point.

### CODE REVIEW

**Comment by auduchinok** [comment]
Anything I should change?

**Comment by forki** [comment]
Ping

**Comment by smoothdeveloper** [comment]
I'm not sure I'm grasping the changes so I'll put few questions/points to try having better understanding:

* we remove member returning a Stream: Stream can be used in all kinds of wrong way, and need to be disposed, so it is probably good
* we pass char[] instead of string in several places: is it saving a roundtrip from char[] to string to char[] somewhere?
* in SourceFileReadShim, we use ReadToEnd (which gives a string) and then call ToCharArray on this, is this the only or best way? I guess reading to char directly isn't possible due to encoding, not knowing the array size, and we assume that String.ToCharArray is most efficient for that

**Comment by cartermp** [comment]
@auduchinok Unfortunately, to use spans here (which I agree would be great) would require us to figure out how to adopt them all-up in the compiler. They are only available in `System` for .NET Core 2.1+, with no current plans to bring them into .NET Standard or .NET Framework. There will likely be a NuGet package for .NET Framework consumers, but it's not clear if it will actually be a benefit for those consumers since the desktop CLR does not have the runtime changes that were required for Span.

Given this, I think we should take this PR as-is (assuming it is approved) and then open a discussion about how to start using spans once F# 4.5 is fully released.

Based on benchmarking we've done, there are places where copying can be reduced quite a bit, which implies that judicious use of Span could help. But as it stands, the majority of F# users may not see those benefits.

**Comment by KevinRansom** [comment]
@auduchinok, I'm guessing we should close this, what do you think?

Kevin

**Comment by auduchinok** [comment]
It's OK to close it, since APIs are changed a bit since then, thank you. I'll probably open another one if ever continue this work.

**Pull request closed without merging**
