### PR TITLE
Update FSharp.Core to use array instead of []

### PR DESCRIPTION
**Pull request by edgarfgp**
Now that https://github.com/dotnet/fsharp/pull/13700 merged. As part of this PR we will update FSharp.Core

### CODE REVIEW

**Comment by edgarfgp** [comment]
@vzarytovskii I have updated for now only array.fs . Not sure if we want to update all of the instances where we use [] to use array ? . Happy to do it as part of another PR :)

**Comment by KevinRansom** [comment]
@edgarfgp - 
If we think this is the correct way to format array type definitions, wouldn't it be preferable to implement them using fantomas so that we can police it, rather than providing a thousand manually edited PR's?

**Comment by vzarytovskii** [comment]
Hm, to be completely honest, I'm not sure we should update everything now.

As per https://github.com/fsharp/fslang-suggestions/issues/635#issuecomment-913185688 - the most important places are tooling presentation (addressed in the original PR), API reference and docs.

**Comment by vzarytovskii** [comment]
> @edgarfgp - 
> If we think this is the correct way to format array type definitions, wouldn't it be preferable to implement them using fantomas so that we can police it, rather than providing a thousand manually edited PR's?
> 
> 

Yep, agree, I think if we want to unify it, we should enforce it.

**Comment by edgarfgp** [comment]
@vzarytovskii @KevinRansom Thanks for the feedback. Agreed Fantomas is a better approach to do this :) . happy to help either way . Closing this PR

**Pull request closed without merging**
