### PR TITLE
Wrapping prefix operator expressions with a paren expression

### PR DESCRIPTION
**Pull request by TIHan**
This is an alternative fix to @auduchinok 's [PR](https://github.com/dotnet/fsharp/pull/7239) where we wrap the prefix operator expression with the paren expression; resolves the incorrect ranges.

I'm not personally happy with this fix, but it does do the right thing.

### CODE REVIEW

**Comment by auduchinok** [comment]
@TIHan There's a fix for the failing tests in https://github.com/dotnet/fsharp/pull/7239/commits/a05bf64785cf54a8889d371b04e5e4b81e9e7742 which updates ranges to include the parens.

**Comment by TIHan** [comment]
Ok, I managed to cherry-pick

**Comment by TIHan** [comment]
Ok, we have two failling tests. They will be simple to fix. I will get to it when I get to it.

**Comment by KevinRansom** [comment]
@TIHan , what is the status of this?  do we want to continue with it?  it has been something over a year.

Thanks

Kevin

**Comment by auduchinok** [comment]
@KevinRansom I'll look into it.

**Comment by auduchinok** [comment]
@KevinRansom I've rebased it to current `master`, fixed the 2 tests failing here and opened #9374. I hope it helps, feel free to choose the PR to stay alive. 🙂 

@TIHan Thank you for the parser fix!

**Comment by TIHan** [comment]
Closing in favor of @auduchinok 's PR.

**Pull request closed without merging**
