### PR TITLE
Support `ldelem.u8`, `ldelem.u` opcode aliases

### LINKED ISSUE #18066: error FS0192: internal error: Error in pass3 for some F# code.
**Repro steps**

Copy/paste the following program in F# interactive:

```
type A = {
    F: uint64  
}

type B = {
    C: uint64[]
}

let g x =
    let c = 
        [|
            for d in x.C do
                {
                    F = d
                }
        |]
    c
```

It produces the following error:

error FS0192: internal error: Error in pass3 for type FSI_0003, error: ldelem

**Expected behavior**

I think it should build fine.

**Actual behavior**

internal error

**Known workarounds**
changing the uint64 to int64 fixes it.

**Related information**

It used to work, it stopped working after upgrading to latest VS.

* Operating system
Windows 11

* .NET Runtime kind (.NET Core, .NET Framework, Mono)

.NET 9

* Editing Tools (e.g. Visual Studio Version, Visual Studio)
Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.12.1

### PR DESCRIPTION
**Pull request by brianrourkeboll**
## Description

Fixes #18066.

Followup to #17067, etc.

- Support `ldelem.u8`, `ldelem.u` opcode aliases.

## Checklist

- [x] Test cases added.
- [x] Release notes entry updated.

### CODE REVIEW

**Comment by T-Gro** [comment]
This matches the translations which we have elsewhere. I would prefer if we made ldelem.u8 work (as an alias to the same bytecode which ldelem.i8 uses), but I cannot asses where else this could resurface.
It is supported in the ASCII representation of IL as well as the mapping in the compiler codebase:

https://github.com/dotnet/fsharp/blob/7526d75870d6cab3e6e94da7b913f126191dd62f/src/Compiler/AbstractIL/ilascii.fs?plain=1#L95C13-L95C46

https://en.wikipedia.org/wiki/List_of_CIL_instructions


We also do support this aliasing for stelem, just missing for ldelem:
https://github.com/dotnet/fsharp/blob/7526d75870d6cab3e6e94da7b913f126191dd62f/src/Compiler/AbstractIL/ilwrite.fs?plain=1#L2020C24-L2020C28
Maybe that's a better way to fix it?
(so that future contributors emitting I_ldelem DT_U8 will not experience the same problem?)

**Comment by brianrourkeboll** [comment]
> Maybe that's a better way to fix it?
> (so that future contributors emitting I_ldelem DT_U8 will not experience the same problem?)

Good idea.

**Review by T-Gro — APPROVED** [review]

**Review by 0101 — APPROVED** [review]

**Review by psfinaki — APPROVED** [review]
Thanks for the quick fix!

**Pull request merged**
