### PR TITLE
Remove CompactFramework references

### PR DESCRIPTION
**Pull request by charlesroddie**
Remove CompactFramework references and supporting implementations, since CompactFramework is not supported.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=9865) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=9865) before we can accept your contribution.<br/><br/>:x: charlesroddie [sign now](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=9865)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/fsharp?pullRequest=9865) it.</sub>

**Comment by cartermp** [comment]
@charlesroddie I think so, yes.

**Comment by cartermp** [comment]
Perhaps that branch was indeed needed for other circumstances :)

**Comment by charlesroddie** [comment]
This is failing some of the online builds and I can't reproduce the test failures locally. It's too minor to be worth a lot of effort to diagnose so I'll close and reopen later when the online builds change.

**Pull request closed without merging**
