### PR TITLE
Make test projects use the local FSharp.Core

### PR DESCRIPTION
**Pull request by Martin521**
Set FSHARPCORE_USE_PACKAGE for the test projects so they use the local core lib.
(Currently, for a fresh setup, tests with new functionality fail)

(BTW FSharpCoreShippedPackageVersionValue is still set to 7.0.0 in Versions.props, should this be changed to 8.0.100?)

### CODE REVIEW

**Comment by Martin521** [comment]
I would be interested to hear why.
It is only for the tests. And currently, test fail when not using the local one.

**Comment by Martin521** [comment]
Actually, thinking about it, I wonder why it works for CI. 
Can there be anything wrong with my setup? (I am using dev container)

**Comment by vzarytovskii** [comment]
I think Eugene mentioned that he didn't want fslib to be built for service solution.

**Comment by vzarytovskii** [comment]
@auduchinok need a review from you

**Comment by auduchinok** [comment]
> I would be interested to understand why.

We need to align FSharp.Core used in Rider plugin, and we use the published packge version. The package is only used in FSharp.Compiler.Service solution. We can upgrade it in the service solution instead of starting to use a project reference, if particular symbols are needed from the newer lib.

**Comment by Martin521** [comment]
Thank you @auduchinok , I do understand that you need FSharp.Compiler.Service with FSharp.Core from the package.
That's why I made the change in tests/Directory.Build.props, not in the top-level one, so building FSharp.Compiler.Service should not be affected.

My problem is that currently (without this PR), `dotnet test tests/FSharp.Compiler.ComponentTests` (or UnitTests or Service.Tests) fails because of missing F#8 features. The same with the tests shown by the Ionide test explorer in VS Code.

**Comment by auduchinok** [comment]
> My problem is that currently (without this PR), dotnet test tests/FSharp.Compiler.ComponentTests (or UnitTests or Service.Tests) fails because of missing F#8 features. 

Let's then just bump the referenced FSharp.Core package? 🙂

**Comment by vzarytovskii** [comment]
> > My problem is that currently (without this PR), dotnet test tests/FSharp.Compiler.ComponentTests (or UnitTests or Service.Tests) fails because of missing F#8 features.
> 
> Let's then just bump the referenced FSharp.Core package? 🙂

We will, once .NET8 is working with our official builds (don't want to update to newer-than-compiler one). One thing which comes to mind, is that `FSharp.Core.UnitTest` should **always run** the project, since it makes sense (unit tests testing nuget package doesn't make much sense).

**Comment by Martin521** [comment]
Fine for me to wait for that release.

But I would still like to understand if changing `tests/Directory.Build.props` would create a problem for Rider.

**Comment by Martin521** [comment]
Understood.
Longer term, it would be nice to find a solution though. 
Once the next feature is added to FSharp.Core that needs unit testing ...
Perhaps a separate solution for testing, working with a different artifacts directory?
Or even the same solution, but making ArtifactsDir dependent on FSHARPCORE_USE_PACKAGE?

**Comment by Martin521** [comment]
Meanwhile, can we unset FSHARPCORE_USE_PACKAGE in the Dockerfile?

**Comment by Martin521** [comment]
I will close this for now and come back to it when/if it is needed for F# 9 Fsharp.Core features

**Pull request closed without merging**
