### PR TITLE
Fix analysis of conjunctive patterns for exhaustiveness

### PR DESCRIPTION
**Pull request by dsyme**
The analysis of conjunctive patterns `pat & pat` has problems.

* https://github.com/dotnet/fsharp/issues/1281
* https://github.com/dotnet/fsharp/issues/3294

This fixes these issues

### CODE REVIEW

**Comment by edgarfgp** [comment]
Improving the pattern matching in conjunction with AP would be really nice . I have hit some of above limitation, making hard to grasp for a newcomer

**Comment by edgarfgp** [comment]
> This probably needs a bunch of tests, from the linked issues.

I did add some unites locally and  it seems that only the second issue on the list is fixed.
The first one still show a warning "This rule will never be matched"

Happy to raise a PR to Don's fork with the unit tests :)

**Comment by dsyme** [comment]
@edgarfgp Thank you so much for checking!  I've checked too and it seems both are fixed - with the first issue, two warnings were being generated - one for incomplete matching, and one for "never matched".   The second is correct to emit, the first is not.

I've added testing for both test cases.

**Comment by dsyme** [comment]
@vzarytovskii This is ready

**Comment by edgarfgp** [comment]
@dsyme Thanks for fixing this . I use AP and this will make the experience much better

**Comment by edgarfgp** [comment]
@vzarytovskii This seems to be ready and the CI  timed out.  Would be awesome to have this in :)

**Review by vzarytovskii — APPROVED** [review]

**Pull request merged**
