### PR TITLE
FSharp.Compiler.Private -> .NET Standard 2.0

### PR DESCRIPTION
**Pull request by cartermp**

### CODE REVIEW

**Comment by cartermp** [comment]
Only a few thousand test failures, how hard could it be?

**Comment by NatElkins** [comment]
Seems like a ton of the errors are coming from here: https://github.com/dotnet/fsharp/blob/master/src/utils/reshapedmsbuild.fs#L822

**Comment by cartermp** [comment]
@NatElkins Yeah, it's the center of all of our woes, actually. This _wonderful_ system, built a long time ago, only executes on .NET Desktop with the desktop compiler. However...

* We must still build and test the desktop compiler
* Every FSharpQA test uses the desktop compiler to execute

So it is a significant investment involved to finally be rid of the .NET Framework target in this project.

**Comment by cartermp** [comment]
Gonna close this one out. We can do this, but I think it's going to depend on fsharpqa getting moved first.

**Pull request closed without merging**
