### PR TITLE
Add clear fsi command

### PR DESCRIPTION
**Pull request by jkone27**
would like to add clear screen capability to fsharp interactive

```cli
#clear;;
```

https://github.com/dotnet/fsharp/issues/12646

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=12858) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=12858) before we can accept your contribution.<br/><br/>:x: jkone27 [sign now](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=12858)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/fsharp?pullRequest=12858) it.</sub>

**Comment by baronfel** [comment]
@jkone27 the implementation looks fine to me, but some FSI tests are failing because they expect certain help output, which has changed: https://dev.azure.com/dnceng/public/_build/results?buildId=1672956&view=ms.vss-test-web.build-test-results-tab&runId=45913734&resultId=100074&paneView=debug

Can you update the expectations?

**Comment by jkone27** [comment]
yes i will take a look this week, thanks! thing i need some more time to setup the solution locally, so i was mostly making changes with vscode... 

ps. i already added this in the expectations but it fails..

```
"    #clear;;                                      // Clear screen";
```

i will try spot the failure..

**Comment by jkone27** [comment]
anyone can help troubleshoot the error? this is the extra token it seems..

```
["> "
```

on linux build pipeline I got this error yes
```
2022-04-01T14:31:19.9071102Z   Error Message:
2022-04-01T14:31:19.9071979Z    Expected to see error sentinel value written
2022-04-01T14:31:19.9072659Z expected:[|"  F# Interactive directives:"; "";
2022-04-01T14:31:19.9073123Z   "    #r "file.dll";;                               // Reference (dynamically load) the given DLL";
2022-04-01T14:31:19.9074036Z   "    #i "package source uri";;                     // Include package source uri when searching for packages";
2022-04-01T14:31:19.9086415Z   "    #I "path";;                                   // Add the given search path for referenced DLLs";
2022-04-01T14:31:19.9087464Z   "    #load "file.fs" ...;;                         // Load the given file(s) as if compiled and referenced";
2022-04-01T14:31:19.9088907Z   "    #time ["on"|"off"];;                          // Toggle timing on/off";
2022-04-01T14:31:19.9089376Z   "    #help;;                                       // Display help";
2022-04-01T14:31:19.9090787Z   "    #r "nuget:FSharp.Data, 3.1.2";;               // Load Nuget Package 'FSharp.Data' version '3.1.2'";
2022-04-01T14:31:19.9091998Z   "    #r "nuget:FSharp.Data";;                      // Load Nuget Package 'FSharp.Data' with the highest version";
2022-04-01T14:31:19.9092497Z   "    #clear;;                                      // Clear screen";
2022-04-01T14:31:19.9092890Z   "    #quit;;                                       // Exit"; "";
2022-04-01T14:31:19.9093491Z   "  F# Interactive command line options:"; ""; "--help' for options"; ""; ""|]
2022-04-01T14:31:19.9093920Z actual:seq
2022-04-01T14:31:19.9094290Z   ["> "; "  F# Interactive directives:"; "";
2022-04-01T14:31:19.9094716Z    "    #r "file.dll";;                               // Reference (dynamically load) the given DLL";
2022-04-01T14:31:19.9095125Z    ...]
2022-04-01T14:31:19.9095411Z Expected: True
2022-04-01T14:31:19.9095740Z Actual:   False
2022-04-01T14:31:19.9096037Z   Stack Trace:
2022-04-01T14:31:19.9096857Z      at FSharp.Compiler.Scripting.DependencyManager.UnitTests.DependencyManagerInteractiveTests.Verify that #help produces help text for fsi + dependency manager language version preview() in /home/vsts/work/1/s/tests/FSharp.Compiler.Private.Scripting.UnitTests/DependencyManagerInteractiveTests.fs:line 804
```

**Comment by vzarytovskii** [comment]
It's likely, not the extra token, but bad test error message. I think that amount of spaces between `;;` and `//` is wrong.
Let me try to fix both message and test.

**Comment by vzarytovskii** [comment]
@jkone27 see below:
image

**Comment by vzarytovskii** [comment]
Removing 1 space from each `#clear;;` and `#quit;;` _should_ fix tests. 
But we will need to improve error messages in the test framework.

**Review by vzarytovskii — APPROVED** [review]

**Comment by vzarytovskii** [comment]
Failing desktop tests are also missing the clear command in the baselines. Should be easy to fix, I can look at it on Monday, unless you fix it sooner :)

**Comment by jkone27** [comment]
Troubleshooting the test is a bit arcane for me at this time, I really appreciate your help thank you so much!
https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1695072/logs/128

```
2022-04-01T16:00:29.8188014Z System.Reflection.AssemblyConfigurationAttribute
2022-04-01T16:00:29.8200978Z System.Reflection.AssemblyConfigurationAttribute
2022-04-01T16:00:29.8241144Z Expected What's your configuration?; Actual: What's your configuration?
```

**Comment by dsyme** [comment]
Note that to update most baseline tests, you simply delete the baseline file and run the test.  The output will then be copied across, the test will succeed, and you can look at the diff using `git diff` and PRs.

**Comment by vzarytovskii** [comment]
> Note that to update most baseline tests, you simply delete the baseline file and run the test. The output will then be copied across, the test will succeed, and you can look at the diff using `git diff` and PRs.

Yeah, I forgot to add that functionality to the new framework. Probably should. :)

**Comment by vzarytovskii** [comment]
This looks good to me, @dsyme @KevinRansom if you don't have anything, I think, we can merge it.

**Review by dsyme — APPROVED** [review]

**Comment by dsyme** [comment]
@jkone27 - thanks for the contribution

**Comment by jkone27** [comment]
Thanks @vzarytovskii  @dsyme for your help with contributing and tests fixes!

**Pull request merged**
