### PR TITLE
Yeet fx_reshaped_msbuild

### PR DESCRIPTION
**Pull request by KevinRansom**
I have always been embarrassed by reshaped_msbuild.  However, now it is completely unnecessary, and so, it is with great joy that I consign it to the bit bucket in the sky.

Oh yeah and update the msbuild libraries to the latest bits.

### CODE REVIEW

**Comment by cartermp** [comment]
oh boy oh boy oh boy oh boy

looks like the fcs project needs updating as well

**Comment by cartermp** [comment]
oh man the magic reflection going on in here was a primary source of blocking this: https://github.com/dotnet/fsharp/pull/7959

**Comment by cartermp** [comment]
Just curious, what's the history of this thing

**Comment by KevinRansom** [comment]
It came into existence when I did the original coreclr port.  If you remember netstandard was at about 1.3 at that point, and I think it had not even been released then.  Anyway, the compiler had a huge dependency on msbuild, and the port to coreclr hadn't started then.  Because ... project.json.

Anyway, tons of the compiler and FSI did resolution using msbuild API's we needed some of that code in our compiler just to even compile it.

Over the years we have abstracted things, simplified things in the compiler, and msbuild got ported to the coreclr.  So ... I thought I would try to yeet it, and it worked.

In a future PR, will I will turn on the msbuildresolution resolver on the coreclr version of the compiler.  It should help with replacing the desktop compiler.

**Comment by cartermp** [comment]
Oh, our old friends project.json. I fondly recall my first PR here was involving that: https://github.com/dotnet/fsharp/pull/1225

Great to see this getting cleaned up!

**Pull request merged**
