### PR TITLE
 Name resolution: actually add reported item when trying to replace

### PR DESCRIPTION
**Pull request by auduchinok**
An experiment to see what happens with CI.

I'm not sure what is the intention of the original code here: the names imply that in some cases when we want to record an item we also want to replace (i.e. remove?) an existing one. But it seems like the code only tries to remove existing items and doesn't add the new one.

### CODE REVIEW

**Comment by vzarytovskii** [comment]
@auduchinok do you want to continue with this one, or shall we close it?

**Comment by auduchinok** [comment]
@vzarytovskii It seems it should be a correct change. We can probably merge it, and I'll let get back to it if I see any problems.

**Review by vzarytovskii — APPROVED** [review]

**Review by psfinaki — APPROVED** [review]
Thanks. Any testing possible here?

**Comment by auduchinok** [comment]
@psfinaki It should be possible, yes, but I haven't looked deeply into how this API is used. If this is really needed, I can look into creating a test, sure. Otherwise, I'd prefer not doing that right now.

**Comment by psfinaki** [comment]
@auduchinok we can merge it, <s>it's Friday evening,</s> but if you happen to go through this code again, please add some test, name resolution is a bit undertested now IMO.

**Comment by auduchinok** [comment]
@psfinaki Sure. I'm going to get back to https://github.com/dotnet/fsharp/pull/14773 in which I've discovered this API inconsistence, so there's a chance I'll be able to find an interesting case to test here. 🙂

**Pull request merged**
