### PR TITLE
Remove some asses from the codebase

### PR DESCRIPTION
**Pull request by cartermp**
Seeing as this is _highly_ unlikely to pass policheck, I figured it was worth doing.

One tiny problem, though: https://github.com/Microsoft/visualfsharp/blob/e709f52b21db479c198aa7a62e5fd941429df4be/src/absil/il.fsi#L1608

This can be changed in our own codebase, but I just want to make sure doing that doesn't break anything.

### CODE REVIEW

**Comment by KevinRansom** [comment]
@dsyme, I tend to use asm.

**Comment by forki** [comment]
I'm offended by the title of this PR and Microsoft even merging this. This is clearly a violation of the CoC. Why do you have policheck when you don't use it on PRs?


:P

**Comment by cartermp** [comment]
@forki I suppose I'll have to ban myself from the repo!

**Comment by KevinRansom** [comment]
@forki, I can ban him.

**Comment by ScottHutchinson** [comment]
I'm relieved. I thought this was removing me from the codebase.😉

**Pull request merged**
