### PR TITLE
Use latest .NET7 preview by default

### PR DESCRIPTION
**Pull request by vzarytovskii**

### CODE REVIEW

**Comment by auduchinok** [comment]
@vzarytovskii Do we really want to require every contributor to have a preview SDK? We've previously tried to require the latest stable SDK only.

**Comment by vzarytovskii** [comment]
> @vzarytovskii Do we really want to require every contributor to have a preview SDK? We've previously tried to require the latest stable SDK only.

For the `(Visual)FSharp.sln` we would like to, since it's the easiest way of testing latest SDKs before it's too late.

We don't want to update to unreleased/nightly versions (which arcade does now sometimes).

For the service solution, we would like to stick to latest released one.

**Comment by vzarytovskii** [comment]
We've actually been updating to .NET6 previews before for the compiler/visualfsharp solutions.

**Comment by vzarytovskii** [comment]
Let's put that on hold and instead, I will try to come up with additional CI leg which will be building and running tests on the latest SDK.

**Pull request closed without merging**
