### PR TITLE
Provided implementation for Set.exactlyOne and Set.tryExactlyOne

### PR DESCRIPTION
**Pull request by yreynhout**
I only had the following insight after submitting this PR - I probably can't just change / extend the api surface of FSharp.Core. Still, it felt like this was missing. Some guidance on how to proceed would be appreciated.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=9607) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=9607) before we can accept your contribution.<br/><br/>:x: yreynhout [sign now](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=9607)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/fsharp?pullRequest=9607) it.</sub>

**Comment by abelbraaksma** [comment]
I assume you're adding this for parity with lists, sequences etc, right? Or is there a language suggestion?

The reason tests fail is because if the surface area (the public functions) changes, they will fail. It's to protect against accidental additions of public functions, that would otherwise go unchecked.

**Comment by cartermp** [comment]
@yreynhout you can see the test failures here: https://dev.azure.com/dnceng/public/_build/results?buildId=712967&view=ms.vss-test-web.build-test-results-tab&runId=22108046&resultId=101213&paneView=debug

**Comment by yreynhout** [comment]
@abelbraaksma indeed, felt a bit weird that I had to either write custom functions or convert to a list to get the functionality.

**Comment by yreynhout** [comment]
@cartermp Thanks for the hint. Are you suggesting I simply change the surface area in the test file(s)?

**Comment by cartermp** [comment]
The surface area changes are necessary to make this mergeable. But I think that some new tests for the Set module are also in order here.

**Comment by abelbraaksma** [comment]
FYI, the related suggestion for `Seq` and friends was: https://github.com/fsharp/fslang-suggestions/issues/137. It should perhaps be paired with the suggestion to extend the surface area of `Set`: https://github.com/fsharp/fslang-suggestions/issues/803.

I don't know if it is needed, but if so, I can help write up a short RFC for this. Or we could perhaps extend this PR to the other functions mentioned in https://github.com/fsharp/fslang-suggestions/issues/803.

**Comment by yreynhout** [comment]
@cartermp I'm more than willing to add tests but failed to find a suitable place. Any pointers as to where you'd like me to add them would be useful - I'm a newbie in this codebase. I do hope I can confine the tests to cover only what I'm adding.

@abelbraaksma If there is protocol to be followed I'll take any suggestions on how to proceed. I can copy the `seq` related RFC for `tryExactlyOne` and work my way from there.

**Comment by abelbraaksma** [comment]
Sounds good, I'm not sure what the protocol is here, but my guess would be that changes to the API need an RFC, so that people are aware it exists, and/or can comment on the design.

**Comment by KevinRansom** [comment]
@yreynhout , there is supposed to be a test that fails when you change the surface area of FSharp.Core.  But yes, you can add api's to FSharp.Core, we just have to figure out if we want to make a change.

There is a Documented Change Request process here:https://github.com/fsharp/fslang-suggestions/issues

And here is an example: https://github.com/fsharp/fslang-suggestions/issues/873

**Comment by KevinRansom** [comment]
@yreynhout ,
I am closing this PR, because the API has not yet been approved in principle at:  https://github.com/fsharp/fslang-suggestions/issues

Please pursue the RFC process mentioned and above and then reactivate this PR for consideration once the API additions have been approved in principle.

Thanks

Kevin

**Comment by abelbraaksma** [comment]
This could be part of https://github.com/fsharp/fslang-suggestions/issues/1361. Linking for posterity ;).

**Pull request closed without merging**
