### PR TITLE
Set NonParallelizable on tests assembly

### PR DESCRIPTION
**Pull request by KevinRansom**
More investigation of disposed textwriter

### CODE REVIEW

**Comment by KevinRansom** [comment]
Log:
1.    Passed

**Comment by mandar1jn** [comment]
What happened here?

**Comment by vzarytovskii** [comment]
> What happened here?

It's just a PR for testing one bug we have in the testing framework.

**Comment by mandar1jn** [comment]
I mean: why all the close and re opens?

**Comment by vzarytovskii** [comment]
> I mean: why all the close and re opens?

To retrigger CI

**Comment by mandar1jn** [comment]
Ah. Ok

**Review by vzarytovskii — APPROVED** [review]

**Comment by KevinRansom** [comment]
fixes: https://github.com/dotnet/fsharp/issues/11800

**Pull request merged**
