### PR TITLE
Moving ElseBranchHasWrongTypeTests over to NUnit

### PR DESCRIPTION
**Pull request by forki**
This is a prototypical PR for showing how to move tests from fsharpqa over to NUnit (see #7075).

The idea is that the F# community can help to move all those tests over. With many small PRs we as a community should be able to accomplish this task easily. Everyone who ever wanted to work on the compiler base can now participate here and pick a couple of fsharpqa tests and move them over. This is a good way to get started with this project.

The big advantage is that tests are now runable and debuggable from within VS like people are used to.

If you want to help:

* pick a handful of tests (not more than 10) from `tests/fsharpqa/Source` and try to move them over like I did in this PR
* send a WIP PR (as early as possible so that others see which tests you picked)
* me and others will review and help you to get them merged!

------------

While moving the ElseBranchHasWrongType tests over to NUnit I noticed that `Else branch is a function that returns int while if branch is string` shows the same error twice.

I already reported this to ionide (see https://github.com/ionide/ionide-vscode-fsharp/issues/1122) and @Krzysztof-Cieslak "fixed" it by adding deduplication in FSAutocomplete (see https://github.com/fsharp/FsAutoComplete/commit/ee95c5c69e34459f420ab2b606326d5806ec1a9b).

Now I think we can repro directly in the compiler tests. /cc @dsyme

### CODE REVIEW

**Comment by cartermp** [comment]
Hooray! Thanks (yes, I know this is still WIP). Every little bit matters

**Comment by forki** [comment]
We need to figure out where the duplicate error message is coming from. I mean I could just dedupe, but I fear we detected a deeper issue and maybe the compiler is doing twice as much work. I really hope someone can take a deeper look

**Comment by cartermp** [comment]
@KevinRansom @dsyme can you take a look at this? @forki noticed something interesting here; reporting errors twice. But there doesn't seem to be anything fundamentally different about them. This is important if we're to move tests to NUnit, since we want to preserve the right behavior.

**Comment by dsyme** [comment]
I wrote this to @forki on twitter:

> I have a hunch about what's happening to give the duplicate error message but I recommend don't worry about it... When we have `f x y z` we kind of traverse twice, once to propagate known information from `f` (return type and arguments types, before processing the actual arguments) and then again processing the individual application/arguments.
> 
> That would cause this sort of thing. But it's not such a bad problem I think.

**Comment by cartermp** [comment]
@KevinRansom This is a great one to review

**Comment by KevinRansom** [comment]
@forki, @TIHan ---
This is an interesting start, certainly a good way to deal with the negative conformance tests.

Do you intend moving over more of the tests?

**Comment by KevinRansom** [comment]
Thanks, I hope more of the conformance tests move over.

**Comment by forki** [comment]
@kevinransom as written above in the description: the idea is to apply crowdsourcing and move all those tests over

**Pull request merged**
