### PR TITLE
Asorted tests improvements 

### PR DESCRIPTION
**Pull request by majocha**
Cherrypicked from #17662.

- replace or remove some of the flakiest hardcoded timeouts
- make sure there are no background tasks started with `Async.Start` etc. and not observed / awaited. They will escape the confinement of currently running test case and if they throw, they bring down the whole test host
- Enabled a few regression tests that were disabled for years because of trivial `exit 0` in the code
- named test runs in CI to make test summary easier to use
- added some rudimentary tests for `Mailbox.TryScan` because we had none outside of the core\controlMailbox script.

### CODE REVIEW

**Comment by majocha** [comment]
Another one:
https://dev.azure.com/dnceng-public/public/_build/results?buildId=829273&view=logs&j=966a6946-91f0-5397-81f4-d998467880f9&t=344839a9-08c6-5829-65fb-26f32c5a016f&l=5086

```
 Failed EmittedIL.TryCatch.Stackoverflow reproduction(compilation: StackOverflowRepro.fs) [30 s]
  Error Message:
   System.TimeoutException : Timeout executing command 'dotnet' 'D:\a\_work\1\s\artifacts\bin\FSharp.Compiler.ComponentTests\Release\net9.0\tests\EmittedIL\TryCatch\Stackoverflow_reproduction\StackOverflowRepro.exe'
```
  
This comes down to the timeout here being too tight for the CI occasionally:
https://github.com/dotnet/fsharp/blob/8eec34b024f4b09090189e5f6396beb691abbf6d/tests/FSharp.Test.Utilities/CompilerAssert.fs#L665-L666

Maybe it would make sense to get rid of such hardcoded timeouts altogether. In the IDE it's obvious when a test hangs and in the CI we can just use `--blame-hang-timeout`.

**Comment by majocha** [comment]
I used `CancellationTokenSource` to cancel `MailboxProcessors` on test end. Turns out Mailbox uses quite different code paths with and without cancellation, #17849, so this is not acceptable.

**Review by T-Gro — APPROVED** [review]

**Review by psfinaki — APPROVED** [review]
Thanks for applying proper testing practices, @majocha. This is a really solid effort. I have also learned some multithreading stuff from this :)

**Comment by majocha** [comment]
> Thanks for applying proper testing practices, @majocha. This is a really solid effort. I have also learned some multithreading stuff from this :)

They're still not perfect. Using just sync primitives often obfuscates the code. Now I think some sort of simulated time, Rx style, would make the code more clear. But at the cost of making the tests depend on yet another thing.

**Comment by psfinaki** [comment]
Well - we're leaving the playground in the better shape we've found it 👀

**Comment by Martin521** [comment]
Great improvement indeed

**Pull request merged**
