### PR TITLE
Don't emit IsReadOnlyAttribute if not available.

### LINKED ISSUE #14275: `IsReadOnlyAttribute` is generated on TFMs which do not have it.
https://github.com/JamesNK/Newtonsoft.Json/issues/2758
Caused by either https://github.com/dotnet/fsharp/pull/13413

We will need to emit it conditionally, based on TFM

### PR DESCRIPTION
**Pull request by nojaf**
Fixes #14275

I'm not sure how to add a test for this fix.
I believe [IsReadOnlyAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.isreadonlyattribute?view=netframework-4.7.2) is available for both `net472` and `net6.0`. Only when targeting `netstandard2.0` or lower can you come across the situation where it is not present.
I'm not sure how to add a test for that exact condition.

I was able to compile my [repro]
(https://github.com/nojaf/serialize-struct) with the local compiler and the test now passes.

### CODE REVIEW

**Review by T-Gro — APPROVED** [review]

**Review by 0101 — APPROVED** [review]

**Comment by NinoFloris** [comment]
@nojaf I don't think this is the right way to go. 

Roslyn instead synthesizes an internal attribute if the tfm does not have it. This allows compilers to still apply the same optimizations for apps that have dependencies compiled for high compatibility tfms like ns2.0

**Comment by vzarytovskii** [comment]
> @nojaf I don't think this is the right way to go.
> 
> Roslyn instead synthesizes an internal attribute if the tfm does not have it. This allows compilers to still apply the same optimizations for apps that have dependencies compiled for high compatibility tfms like ns2.0

I don't think we do that. We usually check for runtime presence instead.

**Comment by NinoFloris** [comment]
>I don't think we do that. We usually check for runtime presence instead.

Sure you'd only add the internal attribute if the presence check fails. 

I don't see why a ns2.0 library should have its consumers lose out on perf benefits just because its tfm lacks the attributes to convey the actual applicable semantics.

In the end it's just my opinion, do with the knowledge what you wish, but I at least wanted to mention the approach roslyn takes here.

**Comment by vzarytovskii** [comment]
@dsyme @KevinRansom wdyt about the codegen missing attributes here?

**Comment by NinoFloris** [comment]
To add a bit of extra context, Roslyn does this only in specific cases. It doesn't do so for features that are explicitly not supported on older tfms like non nullable reference types. There you have to manually add the attributes if you turn on the feature and use it, as it will produce a compiler error otherwise. 

C# 11 `SetsRequiredMembersAttribute` and `UnscopedRefAttribute` are good examples, as they fail to compile when you target net6.0 tfms as well. On the flip side C# 11 did start to add RefSafetyRulesAttribute by default. See https://github.com/dotnet/runtime/issues/76032#issuecomment-1255657942 for a bit of rationale when C# emits by default or not.

**Comment by NinoFloris** [comment]
Sounds good to me!

**Comment by SamuelBerger** [comment]
We cannot upgrade to .NET 7 because of emitted IsReadOnlyAttribute in netstandard2.0 projects, tried with latest VS preview containing SDK 7.0.200-preview.22628.1 and 7.0.300-preview.23106.2

The funny thing is: the attribute is only emitted when the package System.Collections.Immutable is referenced inside the project.

An updated version of @nojaf repro having the System.Collections.Immutable package referenced [https://github.com/SamuelBerger/serialize-struct](https://github.com/SamuelBerger/serialize-struct)

@vzarytovskii is this fixed included in 7.0.200-preview.22628.1 and/or 7.0.300-preview.23106.2?

**Comment by vzarytovskii** [comment]
> We cannot upgrade to .NET 7 because of emitted IsReadOnlyAttribute in netstandard2.0 projects, tried with latest VS preview containing SDK 7.0.200-preview.22628.1 and 7.0.300-preview.23106.2
> 
> The funny thing is: the attribute is only emitted when the package System.Collections.Immutable is referenced inside the project.
> 
> An updated version of @nojaf repro having the System.Collections.Immutable package referenced [SamuelBerger/serialize-struct](https://github.com/SamuelBerger/serialize-struct)
> 
> @vzarytovskii Vlad Zarytovskii FTE is this fixed included in 7.0.200-preview.22628.1 and/or 7.0.300-preview.23106.2?

Hm, this should be included in the 7.0.200 release and all previews release after Nov 14, 2022.
I am not sure when those preview were released.

**Comment by SamuelBerger** [comment]
But can you reproduce the issue? (System.TypeLoadException : Could not load type 'System.Runtime.CompilerServices.IsReadOnlyAttribute' from assembly 'System.Collections.Immutable, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')

Or is it a weirdness on my side?

**Comment by vzarytovskii** [comment]
Ok, it seems is is a separate bug, since System.Collections.Immutable inludes its own `IsReadOnlyAttribute`:
image
And we are checking it only by namespace, we decide to emit it but not generate attribute. 

I will revert generating it altogether, until proper fix is in place (with codegen).

**Comment by vzarytovskii** [comment]
A workaround would be to have it in your project (create a namespace S.R.CS with IsReadOnlyAttribute inside).

**Comment by vzarytovskii** [comment]
@0101 fyi, I will be reverting it alltogether

**Comment by SamuelBerger** [comment]
When adding:

```
namespace System.Runtime.CompilerServices 

[<System.AttributeUsage(System.AttributeTargets.All, Inherited=false)>]
[<Sealed>]
type IsReadOnlyAttribute() =
    inherit System.Attribute()
```
to the project containing the struct, it still picks up the one from System.Collections.Immutable:
  ```
.method public hidebysig specialname instance int32
    get_StartLine() cil managed
  {
    .custom instance void [System.Collections.Immutable]System.Runtime.CompilerServices.IsReadOnlyAttribute::.ctor()
      = (01 00 00 00 )
    .custom instance void [netstandard]System.Runtime.CompilerServices.CompilerGeneratedAttribute::.ctor()
      = (01 00 00 00 )
    .custom instance void [netstandard]System.Diagnostics.DebuggerNonUserCodeAttribute::.ctor()
      = (01 00 00 00 )
    .maxstack 8

    IL_0000: ldarg.0      // this
    IL_0001: ldfld        int32 FSharpLibrary.FRange::StartLine@
    IL_0006: ret

  } // end of method FRange::get_StartLine
```

But never mind, we will simply wait with the .NET 7 upgrade.

**Comment by vzarytovskii** [comment]
> When adding:
> 
> ```
> namespace System.Runtime.CompilerServices 
> 
> [<System.AttributeUsage(System.AttributeTargets.All, Inherited=false)>]
> [<Sealed>]
> type IsReadOnlyAttribute() =
>     inherit System.Attribute()
> ```
> 
> to the project containing the struct, it still picks up the one from System.Collections.Immutable:
> 
> ```
> .method public hidebysig specialname instance int32
>   get_StartLine() cil managed
> {
>   .custom instance void [System.Collections.Immutable]System.Runtime.CompilerServices.IsReadOnlyAttribute::.ctor()
>     = (01 00 00 00 )
>   .custom instance void [netstandard]System.Runtime.CompilerServices.CompilerGeneratedAttribute::.ctor()
>     = (01 00 00 00 )
>   .custom instance void [netstandard]System.Diagnostics.DebuggerNonUserCodeAttribute::.ctor()
>     = (01 00 00 00 )
>   .maxstack 8
> 
>   IL_0000: ldarg.0      // this
>   IL_0001: ldfld        int32 FSharpLibrary.FRange::StartLine@
>   IL_0006: ret
> 
> } // end of method FRange::get_StartLine
> ```
> 
> But never mind, we will simply wait with the .NET 7 upgrade.

Ugh, that's unexpected, it's probably starts searching from the "top" and references are going first. 
That's annoying,

**Pull request merged**
