### PR TITLE
Add NoEquality to range

### PR DESCRIPTION
**Pull request by cartermp**
This is to address #6052 

It's quite a bit of machinery that I think might actually be better served by having the compiler properly handle equality and comparison for structs with custom equality. But that could also be a breaking change IIRC - @TIHan @dsyme is that accurate?

Some notes:

* Lack of ability to pass in a custom comparer to List/Seq/Array combinators is why there is duplication going on here - should there be a core library change to support something like this? That would allow for far less code additions and open up doing the same for `List`, which is currently blocked because the actual implementation ultimately relies on inline IL which is only available in FSharp.Core.
* Some of this is pretty ugly; I imagine it could get cleaned up

### CODE REVIEW

**Comment by dsyme** [comment]
Given the amount of code and complexity being added I'd rather take a look at addressing the core problems here - it should be totally fine to use `CustomEquality` on a struct like `range` and void boxing.

I'm sure we can address this tactically for the actual allocations you're seeing once we have the relevant stacks.  But it shouldn't be as much code as this is.

@manofstick's PRs are also relevant here and fix the problem of boxing much more universally for structs.

**Comment by cartermp** [comment]
I agree, I'd definitely prefer that then have all of this machinery and two versions of standard combinators just to get around what should be considered a bug in the compiler.

@TIHan had some interesting thoughts about compatibility that are worth considering here, it sounds like something we'd have to be _very_ judicious with changing.

Separately, digging through illib.fs and lib.fs was kind of painful. illib.fs clearly has many more utilities than just what is needed for manipulating IL, and lib.fs just seems like a smaller version of library functions that might have just been abandoned at some point. There's clearly a need for a "compiler utility library" where things like additional `Seq` functions can live. What are your thoughts on factoring all of that out?

**Comment by dsyme** [comment]
> Separately, digging through illib.fs and lib.fs was kind of painful. illib.fs clearly has many more utilities than just what is needed for manipulating IL, and lib.fs just seems like a smaller version of library functions that might have just been abandoned at some point. There's clearly a need for a "compiler utility library" where things like additional Seq functions can live. What are your thoughts on factoring all of that out?

Factoring into a separate assembly would not be right.  Merging `lib.fs` into `illib.fs` and ensuring uniform design makes sense.  The split was historical.

I don't mind if `illib.fs` gets split into multiple files too though you always end up with a bucket-of-stuff file in the end.

**Comment by cartermp** [comment]
> Factoring into a separate assembly would not be right. 

What's the rationale? I understand having utilities specific to IL generation here, but there's so much generic utility code here - string utilities and active patterns, `Cancellable` computation expression, graph data structures, etc. I could imagine some of it being utilized by other projects. For example, `Extensions.fs` in FSharp.Editor also defines an equivalent `Option.attempt` function. There may be more, but I haven't exhaustively looked.

**Comment by dsyme** [comment]
> What's the rationale? I understand having utilities specific to IL generation here, but there's so much generic utility code here - string utilities and active patterns, Cancellable computation expression, graph data structures, etc. I could imagine some of it being utilized by other projects. For example, Extensions.fs in FSharp.Editor also defines an equivalent Option.attempt function. There may be more, but I haven't exhaustively looked.

People are welcome to copy it out to a separate project in `fsprojects` or elsewhere.  But the scope of `illib.fs`+`lib.fs` is precisely what's needed by the F# compiler - nothing more and nothing less - if a utility function is not needed, we will delete it, and if some random thing is needed, we will add it.  There is not a coherent, well-designed library here, it's just a bucket of utility code.

**Pull request closed without merging**
