### PR TITLE
Making inline type hints less intrusive

### LINKED ISSUE #14382: Make Type Hints less intrusive
So this is quite annoying:

https://user-images.githubusercontent.com/5451366/203621934-99ec33fb-d39d-4c38-9611-eb1684f79d21.mp4

Instead, I'd prefer the behavior like in C# on the right - show the type when we can provide useful information (e.g. when the equal sign is printed).

### PR DESCRIPTION
**Pull request by psfinaki**
Partially fixes #14382 
Fixes: #14393

Before:

https://user-images.githubusercontent.com/5451366/203825303-38c72324-df96-4cc8-ae39-32219c48f839.mp4

After:

https://user-images.githubusercontent.com/5451366/203825894-be4a297c-c4de-4aa3-b226-332bb915c677.mp4

I found this nearly unused properly which seems to do the trick.

Note this does **not** solve the issue completely:

https://user-images.githubusercontent.com/5451366/203826447-e54756ec-69a4-40d5-a11a-7e2fea87c1e2.mp4

### CODE REVIEW

**Comment by psfinaki** [comment]
Thanks @kerams for the suggestions btw.

**Review by vzarytovskii — CHANGES_REQUESTED** [review]
If the property is part of public surface API, it's a breaking change, then we will either need to bump major FCS version, or leave old one, mark it as obsolete and suggest using new one .

**Comment by psfinaki** [comment]
> If the property is part of public surface API, it's a breaking change, then we will either need to bump major FCS version, or leave old one, mark it as obsolete and suggest using new one.

Mhm I'm allergic to typos but alright let's revert the breaking change and then solve it separately

> Also, how does it work with SRTP, iwsams generic functions and methods? What does it display?

Will check it and add some extra tests maybe, stay tuned.

**Comment by vzarytovskii** [comment]
> > If the property is part of public surface API, it's a breaking change, then we will either need to bump major FCS version, or leave old one, mark it as obsolete and suggest using new one.
> 
> Mhm I'm allergic to typos but alright let's revert the breaking change and then solve it separately
> 

Understandable, but we should start being more careful with breaking changes in minor versions, it's a big pain point for community tooling

**Comment by psfinaki** [comment]
So @vzarytovskii IWSAM is working correctly (added a test), SRTP has a small issue, will deal with it separately [here](https://github.com/dotnet/fsharp/issues/14400).

**Review by T-Gro — APPROVED** [review]

**Review by vzarytovskii — APPROVED** [review]

**Pull request merged**
