### PR TITLE
improve build telemetry

### PR DESCRIPTION
**Pull request by brettfo**
Since our build uses a custom script, this PR adds an explicit call to the Arcade function `Write-PipelineTelemetryError` in the root `catch` block.  To handle the different stages of the build, two script-level variables are created, `$BuildCategory` and `$BuildMessage`, that get updated so that in the case of a failure, the contents are relevant.

### CODE REVIEW

**Comment by chcosta** [comment]
Is there a test job we can look at to validate this works as expected?  ie, have you tried forcing a failure or something?

**Comment by brettfo** [comment]
Good call, I just pushed a commit with a bad test that should catch on both Windows and Linux.  If the build telemetry gets classified appropriately I'll walk back that commit.

**Comment by brettfo** [comment]
Hijacked test resulted in the appropriate log lines and failure reasons:

Linux/Mac:
`##[error](NETCORE_ENGINEERING_TELEMETRY=Test) Error running tests (exit code '1').`

Windows:
`##[error](NETCORE_ENGINEERING_TELEMETRY=Test) Failure running tests`

I'll revert the bad test and this can be merged as soon as it's green.

**Comment by chcosta** [comment]
Looks good, thanks Brett

**Pull request merged**
