### PR TITLE
Check whether versions are already published

### PR DESCRIPTION
**Pull request by vzarytovskii**
Check whether package with current version has been published to nuget.org

We will try to restore both FSharp.Core and FCS and if restore is _successful_, package version needs to be bumped.

NOTE: This CI check should only run on the release branches.

### CODE REVIEW

**Review by KevinRansom — APPROVED** [review]

**Comment by KevinRansom** [comment]
Very lovely !!!

Thanks

**Comment by vzarytovskii** [comment]
So, check in this branch should fail, since we have it published already, after it fails, I will bump package version by 1 and rerun it, and then we're good to merge

**Comment by vzarytovskii** [comment]
Ok, check fails on 17.4 (released FCS and fscore), I have retargeted it for 17.5, it should be passing (since it's not released yet), good to merge as long as it's green

**Review by vzarytovskii — COMMENTED** [review]
This is ready now

**Pull request merged**
