### PR TITLE
Keep parsed range in SynExpr.Ident

### PR DESCRIPTION
**Pull request by auduchinok**
There're currently several hacks in the parser making some operator ident expressions have incorrect range. There're separate rules for parsing operators using their source names and producing incomplete structure. Here're examples for using an operator with its compiled and source names respectively:
```fsharp
(op_Addition)
(+)
```

```fsharp
[DoExpr
   (SequencePointAtBinding tmp.fsx (1,0--1,13) IsSynthetic=false,
    Paren
      (Ident op_Addition,tmp.fsx (1,0--1,1) IsSynthetic=false,
       Some tmp.fsx (1,12--1,13) IsSynthetic=false,
       tmp.fsx (1,0--1,13) IsSynthetic=false),
    tmp.fsx (1,0--1,13) IsSynthetic=false);
 DoExpr
   (SequencePointAtBinding tmp.fsx (2,1--2,2) IsSynthetic=false,
    Ident op_Addition,tmp.fsx (2,1--2,2) IsSynthetic=false)]
```

It's more difficult to get back the real parsed file structure when AST provides incomplete data and this structure is used by Rider, Fantomas and could be helpful for the Compilation PR.

Apart from the tooling issues, incorrect ranges are promoted up the tree (so containing expressions have incorrect ranges too) and lead to producing incorrect warning and error ranges ranges:
Screenshot 2019-07-15 at 14 35 36

This PR adds `range` back to `SynExpr.Ident` (which effectively removes one of previous optimisations) and fixes ranges for warnings/errors and makes it more-or-less possible to spot used parser rules by comparing ident and expression ranges:
Screenshot 2019-07-15 at 18 16 41

Probably the best way to solve this problem is to change the parser rules but it's more difficult way and it most likely will add more churn across the compiler. It's better to work on it more systematically in a separate PR later.

### CODE REVIEW

**Comment by auduchinok** [comment]
Expressions test also showed previously incorrect ranges where left paren wasn't included to the range.
```fsharp
let testByteEqualsOperator               (e1:byte) (e2:byte) = (=) e1 e2
let testByteNotEqualsOperator            (e1:byte) (e2:byte) = (<>) e1 e2
let testByteLessThanOperator             (e1:byte) (e2:byte) = (<) e1 e2
let testByteLessThanOrEqualsOperator     (e1:byte) (e2:byte) = (<=) e1 e2
let testByteGreaterThanOperator          (e1:byte) (e2:byte) = (>) e1 e2
let testByteGreaterThanOrEqualsOperator  (e1:byte) (e2:byte) = (>=) e1 e2
```

**Comment by auduchinok** [comment]
> Also, it should not include parenthesis ranges as they have nothing to do with the actual identifier text.

It's the range of the expression, not the identifier. Now the expression range is clearly wrong.

> We probably want to have a SynExpr.Paren around the SynExpr.Ident that uses the actual operator, +. That should resolve your issue with the ranges in this case.

Yes. I was thinking about it while writing the following:

> Probably the best way to solve this problem is to change the parser rules but it's more difficult way and it most likely will add more churn across the compiler. It's better to work on it more systematically in a separate PR later.

**Comment by TIHan** [comment]
> It's the range of the expression, not the identifier. Now the expression range is clearly wrong.

`SynExpr.Ident`'s range should only be the identifier's range, nothing more. I'd say the expression tree is incomplete without the `SynExpr.Paren`. which makes the overall `DoExpr`'s range wrong. You also need to consider `SynExpr.LongIdent`'s range too if we accept `SynExpr.Ident`'s change. `SynExpr.LongIdent` already has a range but it's supposed to be the computed range of the contained `LongIdentWithDots`.

I understand you would rather not change the parser rules. However, fixing it by adding the `SynExpr.Paren` is going to be the right thing to do here.

**Comment by auduchinok** [comment]
Closing due to a better approach is proposed in #7243.

**Pull request closed without merging**
