### PR TITLE
Make conditional directives collapsible

### PR DESCRIPTION
**Pull request by kerams**
urTCguw0g1 M8tVSVaKlx

### CODE REVIEW

**Comment by abelbraaksma** [comment]
Awesome stuff! I looked at this over a year ago, looking at your changes it appears ‘easier’ than I thought at the time (knowing where to look for IDE stuff was never my forte 😆).

**Comment by kerams** [comment]
I'm not sure this information was easily available in the past. The trivia types are relatively new.

**Comment by kerams** [comment]
I'm starting to wonder whether it wouldn't be better to deviate from the `if` expression collapsing behavior (one scope to collapse the entire expression), and use a scope for each branch so that you could collapse the branch which you don't care about. For obvious reasons there'd be no third scope covering the entire directive.

**Comment by T-Gro** [comment]
> I'm starting to wonder whether it wouldn't be better to deviate from the `if` expression collapsing behavior (one scope to collapse the entire expression), and use a scope for each branch so that you could collapse the branch which you don't care about. For obvious reasons there'd be no third scope covering the entire directive.

 
I must admit I like this idea
Even thinking of a GLOBAL rule, to auto-collapse all branches of directive #if that do not match the current profile.

**Review by vzarytovskii — DISMISSED** [review]

**Comment by kerams** [comment]
@vzarytovskii, would you prefer the change I described above?

**Review by T-Gro — APPROVED** [review]

**Comment by vzarytovskii** [comment]
> @vzarytovskii Vlad Zarytovskii FTE, would you prefer the change I described above?

I guess if it's not a big of a change, we can use different scopes.

**Comment by kerams** [comment]
Now we've got this:

5Vt4dcNTCC VGbJHp1qS4

**Review by T-Gro — DISMISSED** [review]

**Review by T-Gro — APPROVED** [review]

**Review by vzarytovskii — APPROVED** [review]

**Pull request merged**
