### PR TITLE
Fix signature help in lists

### LINKED ISSUE #12943: Signature Help shows tooltips for incorrect functions
**Repro steps**

devenv_4xyitGHGJR

When props for the button are non-empty, the reported position is even stranger.

devenv_lqybyIlvjk

I'm seeing this all the time when writing Fable code.
@cartermp, any idea off the top of your head what could be going wrong here?

**Expected behavior**

In both cases the tooltip should show this, and be similarly positioned with respect to the caret

devenv_C5VkNoTgDp

**Related information**

Provide any related information (optional):

* Win 10
* .NET 7.0.100-preview.4.22175.1
* VS 17.2 Preview 2.0

### PR DESCRIPTION
**Pull request by kerams**
Fixes #12943.

r2XiijXNgc

Thanks for the pointers, @cartermp, the fix is pretty straightforward.

### CODE REVIEW

**Comment by cartermp** [comment]
Just to test this, if you hit space inside of the list expression argument for `button`, does it trigger signature help for `button`?

**Comment by kerams** [comment]
Like this?

CoSiT3xe2f

**Comment by cartermp** [comment]
The manual test case I'd look for:

1. Space after `button` and within a list expr in the first argument slot --> sig help for `button` with first parameter highlighted
2. Space in function call inside list expr (2nd arg for funsies) --> sig help for that function call
3. Step (2), but for a function with two arguments to make sure the 2nd space invoked still shows signature help for that function
4. After step (3), after hitting `;` or on a newline or whatever, hitting space --> sig help for `button`, with 2nd argument highlighted

**Comment by kerams** [comment]
Good shout, semicolon + space does not show anything once you already have some item in the list. This is also fishy - the semicolon has to be on its own.

HLq6ciUfcV

**Comment by cartermp** [comment]
Yeah, it's a little finnicky :)

I think this is already a good improvement though

**Comment by kerams** [comment]
I've made that range check stricter, but a new issue has surfaced when the expression outside of the range falls through to other match clauses. Unless I'm reading this all wrong, given

```fsharp
let test () = div [] [
    str ""; | 
]
```

because `adjustedColumnInSource` is used, the walker reports that we're at the end of `str` application, but there are no more parameters left, so nothing is shown.

Given

```fsharp
let div a b [] = ()

let test () = div [] [
    str ""
    ; | 
]
```

the wrong argument index is computed (possibly because `curriedArgsInSource` is empty), so the tooltip shows `div` with `a` highlighted.

I'm afraid fixing this would involve further refactoring, which I don't want to dig into right now. Therefore no signatures are shown for these edge cases, which is better than showing the wrong thing as far as I am concerned. Whoever picks up the slack later will have tests ready for this. Even so, the changes should have a positive impact, especially in Fable.

**Review by cartermp — APPROVED** [review]
In the spirit of "not 100% complete but holy shit is this better", this is great and it should be merged once tests pass

**Review by KevinRansom — APPROVED** [review]

**Review by baronfel — APPROVED** [review]

**Pull request merged**
