### PR TITLE
Include attributes in ranges of signature nodes.

### LINKED ISSUE #11487: Attributes not included in the range of the parent node (signature files)
Following up on previous AST related issues.
I still found some constructs where the range of the attributes is not included in the parent node in signature files.

```fsharp
namespace SomeNamespace

[<Foo1>] // SynModuleSigDecl.Types / SynTypeDefnSig
type MyType =
    class
    end

type FooType =
    [<Foo2>] // ValSpfn
    abstract x : int
```

See [AST Viewer](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmAC4BOArrPhJAMYD2cFkyAhgLboAHbs1hgAyq34A5PoOGwAOtQXIlKgNoAeYq1YBGAHwBdMAHpT4gJ7IAsu1oAbWGMQBzACKxmDgHQAVSwF0MytkAKDPeGQXVzVkSkDRG0tw0QBeOIgIb240NEys2GRoOLiEoLAdVlSwDOVkLLAtKoAmYzMLADVuBzEBKIKIbgAjNBphSjAADzBsFEpIEABfIA)

**Expected behaviour**

Attributes are included.

**Actual behaviour**

They are not.

**Known workarounds**

Parse the tree to construct a correct range.

**Related information**

FCS 39.

### PR DESCRIPTION
**Pull request by nojaf**
Fixes #11487.

### CODE REVIEW

**Review by vzarytovskii — APPROVED** [review]

**Review by cartermp — APPROVED** [review]
Thanks!

**Comment by cartermp** [comment]
@nojaf some conflicts.

**Comment by nojaf** [comment]
Resolved!

**Comment by auduchinok** [comment]
This PR breaks ranges for type signatures that don't have attributes. For the following signature the range now starts at `R` instead of `type`:
```fsharp
type R =
    { F: int }
```

I'm working on a fix.

**Comment by nojaf** [comment]
Would that not be consist with the range you'd get when it is inside an implementation file?
I thought keywords were not supposed to be part of the range.

**Comment by auduchinok** [comment]
So you're suggesting that there should be this difference?

```fsharp
type R1 = // type is not included
    { F: int }

[<A>]
type R = // type is included
    { F: int }

```

It looks very wrong to me.

> Would that not be consist with the range you'd get when it is inside an implementation file?

IIRC implementation files should already contain them. If not, we should fix it.

**Comment by nojaf** [comment]
I'd be in favor of having them included, just wanted to point out that in FCS 39, the `type` keyword is not included in `TypeDefn`.
See [example](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQAuAngA6wwAJTABeMMDDFWrbCi5gAvpBCKgA).

**Comment by auduchinok** [comment]
Ah, I see where I wasn't clear.

We use `SynModuleDecl.Types.Range` for looking at where types groups starts, and this is the part where it has regressed, not individual type signature ranges. In your tree dump the group does indeed contain `type`.

**Comment by nojaf** [comment]
Ah ok, now I understand what regressed. Thanks for explaining.

**Pull request merged**
