### PR TITLE
Tests: clean-up unneeded code

### PR DESCRIPTION
**Pull request by majocha**
Since the tests run in temp directories by default, this code in `single-test.fs` should no longer be needed.

Let's see if it is.

### CODE REVIEW

**Comment by KevinRansom** [comment]
Yeah!!! the tests are probably not as consistent as you think.  Different tests, even within the ComponentTests suite have different strategies ... usually depending on how the test originally work.

**Comment by majocha** [comment]
I think I had that special case handled for that `helloworld` thing. I'll look into it, as this change works in my experiment PR.

**Comment by majocha** [comment]
Yes it's like geological strata, sediments upon sediments. But it seems this worked :)

**Comment by psfinaki** [comment]
Yeah. We are doing geological programming this week :)

Consider conducting some smoke testing from whatever applies in [this comment](https://github.com/dotnet/fsharp/pull/17709#pullrequestreview-2308736320) to a sibling PR - among other things, doing this will just help us "compile" some sanity checks for these sorts of PRs.

**Comment by majocha** [comment]
Subsumed by #17815

**Pull request closed without merging**
