### PR TITLE
Don't warn on lack of 'new' for disposables anymore

### PR DESCRIPTION
**Pull request by cartermp**
Chatted with @dsyme about this, came from recognizing how it's kind of annoying when working with PyTorch bindings and others where you mix and match classes and disposable classes. The lack of uniformity in syntax stuck out like a sore thumb.

The history of this warning is that it's from some old days of F#, where the warning was meant to exist as a means for developers to more easily distinguish between disposable and non-disposable types. But @dsyme and I agreed that this feels kind of outdated/not that useful anymore.

This removes the warning!

image

### CODE REVIEW

**Comment by auduchinok** [comment]
Should it be guarded with a language version?

**Comment by charlesroddie** [comment]
Would the idea be then to rely completely on color?
So reverting https://github.com/dotnet/fsharp/pull/10092 ?

**Comment by En3Tho** [comment]
I personally solved this problem by using a custom plugin build for JB Rider by adding many different highlightings for disposable/asyndisposable types, exceptions, parameters and so on. So I believe you're right and IDE should help with recognizing certain patterns or types.

**Comment by cartermp** [comment]
@charlesroddie https://github.com/dotnet/fsharp/pull/10092 isn't reverted at all, and coloring is orthogonal. This is just a very old warning back before any tooling considerations existed, and the thinking was that it would help distinguish between disposable and non-disposable values anymore. However, since we have `use` that argument is a little flimsy, and it ends up just being somewhat confusing.

**Comment by charlesroddie** [comment]
> it would help distinguish between disposable and non-disposable

This is very important. There are three ways to do this that are mentioned here:

- `new`. Better than nothing but only detects constructors, not other functions that return disposable.
- Color. This is a good solution but is off by default after the other PR.
- `use`. For this to identify disposables, programmers must start by typing `use ... = x` instead of `let ... = x` everywhere, replacing with `let` when they get an error that `x` is not `IDisposable`. This is not an efficient workflow.

> coloring is orthogonal

Since these are all suggested solutions to the problem we agree exists, they are not independent, since at least one solution is needed. Since `use` is not a solution, that means `Color` or `new` unless there is another proposal.

**Comment by cartermp** [comment]
I never said I agree to some problem you're claiming exists. Just that this PR merely removed a warning we agree never did much use, and that it doesn't revert another PR.

**Review by vzarytovskii — APPROVED** [review]

**Comment by auduchinok** [comment]
@cartermp I believe from the tooling standpoint we need to be able to know if there's the rule relaxation (and, say, don't suggest simplification when that would produce a warning on an older compiler), so let's make it a vNext version change without a long preview at least?

**Comment by piaste** [comment]
On the one side, I agree that it's ugly syntax to have some constructors be called with `new` and others without, especially when there's little intuitive connection between the keyword `new` and the IDisposable interface.

On the other side, although `new` was a poor marker, I do think that _some_ kind of explicit marker should be used when an `IDisposable` is instantiated without the `use` keyword (e.g. when it's part of the return value), because it's then doubly important to make sure it gets disposed properly at a later point. And at warning level 4 or 5, I would expect the compiler to pipe up with a yellow squiggle if you don't use that marker.

**Comment by charlesroddie** [comment]
> I never said I agree to some problem you're claiming exists. Just that this PR merely removed a warning we agree never did much use, and that it doesn't revert another PR.

Ok but the people who put the original `new` requirement in did and they are right. Since it is manifestly not obvious what is IDisposable without tooling help, and handling IDisposables is very important to avoid crashes and memory leaks and write correct code in general, one must conclude that it is important for tooling to notify users of `IDisposable`s.

> a warning we agree never did much use

Prior to color, the `new` requirement was the way to distinguish IDisposables. So it did have a lot of use and was very hard to live without.

**Comment by cartermp** [comment]
Okay, never mind then.

**Comment by kerams** [comment]
Removing the warning when `use` is present would still be appreciated as far as I am concerned.

**Comment by cartermp** [comment]
@kerams I agree, and furthermore, the warning was also of limited use for me because it is satisfied even without the `use` keyword:

```fsharp
// ...somewhere in some code
let x = new MyDisposable()
// ...somewhere later, did the resource get disposed at some point? I dunno
```

but it appears that folks like the warning. Feel free to submit a PR with this change and a more compelling argument than I could muster.

**Comment by seanamos** [comment]
I agree that `new` isn't the nicest way to do this. However, I rely on it quite a lot.
I've only ever written F# in VSCode and maybe I've got something not setup right, but until I saw this issue, I had no idea IDisposables were supposed to be colored differently.

The `new` warning is a nice reminder, without checking the docs or implementation for every type, that something is IDisposable.
I would even like something similar for IDisposables returned from functions!

**Comment by cartermp** [comment]
@seanamos disposables aren't colored differently by default.

**Comment by dsyme** [comment]
We could convert this to a level 5 opt-in warning

**Pull request closed without merging**
