### PR TITLE
remove internal from member UsesTransparentCompiler

### PR DESCRIPTION
**Pull request by dawedawe**
## Description

This makes the `UsesTransparentCompiler` member from `FSharpChecker` available to all interested parties (Rider, FSAC, etc.).

(No release notes needed)

## Checklist

- [ ] Test cases added
- [ ] Performance benchmarks added in case of performance changes
- [ ] Release notes entry updated:
    > Please make sure to add an entry with short succinct description of the change as well as link to this pull request to the respective release notes file, if applicable.
    >
    > Release notes files:
    > - If anything under `src/Compiler` has been changed, please make sure to make an entry in `docs/release-notes/.FSharp.Compiler.Service/<version>.md`, where `<version>` is usually "highest" one, e.g. `42.8.200`
    > - If language feature was added (i.e. `LanguageFeatures.fsi` was changed), please add it to `docs/releae-notes/.Language/preview.md`
    > - If a change to `FSharp.Core` was made, please make sure to edit `docs/release-notes/.FSharp.Core/<version>.md` where version is "highest" one, e.g. `8.0.200`.

    > Information about the release notes entries format can be found in the [documentation](https://fsharp.github.io/fsharp-compiler-docs/release-notes/About.html).
    > Example:
    > * More inlines for Result module. ([PR #16106](https://github.com/dotnet/fsharp/pull/16106))
    > * Correctly handle assembly imports with public key token of 0 length. ([Issue #16359](https://github.com/dotnet/fsharp/issues/16359), [PR #16363](https://github.com/dotnet/fsharp/pull/16363))
    > *`while!` ([Language suggestion #1038](https://github.com/fsharp/fslang-suggestions/issues/1038), [PR #14238](https://github.com/dotnet/fsharp/pull/14238))

    > **If you believe that release notes are not necessary for this PR, please add `NO_RELEASE_NOTES` label to the pull request.**

### CODE REVIEW

**Comment by vzarytovskii** [comment]
Why does this need to be in the public surface? It seems like it's an implementation detail. If we need to log it, we should just do it inside, otherwise caller always knows whether transparent compiler is used, because it needs to set it.

**Comment by dawedawe** [comment]
Mmh, isn't simple ergonomic stuff like [this](https://github.com/dotnet/fsharp/blob/15a6a64f92151782f409c0e500e572eaf63f6c76/vsintegration/src/FSharp.Editor/LanguageService/WorkspaceExtensions.fs#L451) only possible because of the privilige granted [here](https://github.com/dotnet/fsharp/blob/15a6a64f92151782f409c0e500e572eaf63f6c76/src/Compiler/FSharp.Compiler.Service.fsproj#L81)?

**Comment by vzarytovskii** [comment]
> Mmh, isn't simple ergonomic stuff like [this](https://github.com/dotnet/fsharp/blob/15a6a64f92151782f409c0e500e572eaf63f6c76/vsintegration/src/FSharp.Editor/LanguageService/WorkspaceExtensions.fs#L451) only possible because of the privilige granted [here](https://github.com/dotnet/fsharp/blob/15a6a64f92151782f409c0e500e572eaf63f6c76/src/Compiler/FSharp.Compiler.Service.fsproj#L81)?

This as well feels like exposing too much implementation details. We should hide it. But again, caller of the checker should know whatever transparent compiler is used or not.

**Review by vzarytovskii — APPROVED** [review]
On the second though, I think it's fine as long as we keep it experimental

**Comment by dawedawe** [comment]
> On the second though, I think it's fine as long as we keep it experimental

Thanks for giving this a second thought.

**Review by 0101 — APPROVED** [review]

**Pull request merged**
