### PR TITLE
Dependency manager/nuget: use enabled feeds only

### PR DESCRIPTION
**Pull request by auduchinok**
Prevents Nuget dependency manager trying to access disabled feeds, accessing which could cause errors.

### CODE REVIEW

**Review by vzarytovskii — APPROVED** [review]

**Review by KevinRansom — COMMENTED** [review]
Cool

thanks

**Comment by KevinRansom** [comment]
@auduchinok , looks like a formatting error mate.

**Comment by auduchinok** [comment]
> @auduchinok , looks like a formatting error mate.

This doesn't seem right to me, as the code was manually formatted in a way that is allowed by the official style guide.

It's good that the style guide allows variations that help to convey the meaning by emphasizing parts of the code that can be done by carefully placing new lines and empty lines, adding more indent or not and so on, at it may be very important on difficult parts of a codebase. It seems requiring all contributors to automatically format their changes in a way that often lose this formatting makes things a bit worse for both the codebase and the contributors who may have part of their work removed. Ideally, Fantomas should be a bit more flexible and keep the formatting where it's allowed by the style guide.

**Comment by auduchinok** [comment]
> @auduchinok , looks like a formatting error mate.

This doesn't seem right to me, as the code was manually formatted in a way that is allowed by the official style guide.

It's good that the style guide allows variations that help to convey the meaning by emphasizing parts of the code that can be done by carefully placing new lines and empty lines, adding more indent or not and so on, at it may be very important on difficult parts of a codebase. It seems requiring all contributors to automatically format their changes in a way that often lose this formatting makes things a bit worse for both the codebase and the contributors who may have part of their work removed. Ideally, Fantomas should be a bit more flexible and keep the formatting where it's allowed by the style guide.

cc @dsyme @nojaf @vzarytovskii

**Comment by smoothdeveloper** [comment]
To me, there is no one true formatting, and being over sensitive to it creates more waste than it improves codebase soundness.

Formatting tools and conventions are good guidance and of good help, but there are as many writing styles as there are authors, and reacting strongly against one or other is missing the point that the code can't fit taste of everyone.

If there are formatting comments to be made, the new formatting should be proposed, patching the PR, ideally.

If there is one standard to be enforced everywhere, it should be a CI failure.

We can't go from nothing to all, and we should strike right balance (all is not, the same as nothing is not), and rely on appreciation of contributors more than stringent rules.

The only way for having same consistency would be to take most efficient F# contributor, clone that person, and allow no one else to contribute 🙂.

Please ignore if this goes against better compiler and more contributions.

**Comment by dsyme** [comment]
@auduchinok We have quite a long setting for `fsharp_max_if_then_else_short_width` here: https://github.com/dotnet/fsharp/blob/main/.editorconfig#L8

I discussed with @nojaf about `if expr then expr` formatting on single line, see https://github.com/fsprojects/fantomas/issues/2299

**Comment by auduchinok** [comment]
A similar example was discussed here: https://github.com/fsprojects/fantomas/issues/2280#issuecomment-1137493834

It's not about assignment or `if` expressions in particular, it's about preventing a formatter from enforcing a single style in cases where different styles are possible and allowed and when some other style may be preferred in a particular situation (and was explicitly used by a user in the code being formatted).

**Comment by nojaf** [comment]
> as the code was manually formatted in a way that is allowed by the official style guide.

Your input isn't being checked against the style guide. It is being checked against how Fantomas would have formatted it, based on its understanding of the style guide.

On a side note, if the style guide changes, someone needs to update Fantomas as well in order for it to adhere to the new guide. People seem to think this happens automagically and overnight.

It takes a bit of getting used to.

**Comment by auduchinok** [comment]
> Your input isn't being checked against the style guide. It is being checked against how Fantomas would have formatted it, based on its understanding of the style guide.

The point is Fantomas should produce identical code if it's allowed by style guide and settings.

**Comment by nojaf** [comment]
That is how you would like the tool to work, but has never been the mission statement.

**Comment by dsyme** [comment]
@smoothdeveloper Yes, it's possible we will decide not to apply Fantomas to a few select files (ValFlags in TypedTree.fs being one example)

**Pull request merged**
