### PR TITLE
Expose the dependency graph in FSharpChecker via a new member

### PR DESCRIPTION
**Pull request by dawedawe**
This adds a new member function to the FSharpChecker to get the dependency graph.
The idea is to make use of the graph in IDE tooling to support performance work.

### CODE REVIEW

**Comment by vzarytovskii** [comment]
Graph is an implementation detail, I'm not convinced we want to expose it via public API as is.

What tooling scenarios do you have in mind, which will require that?

**Comment by dawedawe** [comment]
> Graph is an implementation detail, I'm not convinced we want to expose it via public API as is.
> 
> What tooling scenarios do you have in mind, which will require that?

We had the idea to introduce IDE tooling that would use a heuristic to tell people that they might profit from adding a signature file for certain critical impl files. That would help reducing the time spend in type checking without the need for going all in with signature files and have them for all impl files.

**Comment by dawedawe** [comment]
To give an example:
We were able to reduce the type checking time in Fantomas.Core.Tests by ~29% by adding a signature file for an impl file. We used the graph information to identify that file. (The time comparison was made with `--test:GraphBasedChecking` in both cases)

**Comment by auduchinok** [comment]
> This is a test and experimental feature, it does not feel correct to expand the public API with it.

We can mark it with some attribute which would say that it's experimental.

**Comment by dawedawe** [comment]
> This is a `test` and `experimental` feature, it does not feel correct to expand the public API with it. At the same time, the reasoning behind the request and the accomplished goal is good - that is, at least until graph based checking becomes the default.

I added the experimental attribute.

> 
> We alredy have a test flag that allows exporting the heuristical graph to a mermaid file. Wouldn't that work for the same use case?

Well, you're right, the mermaid file could be parsed to get the desired information but a full build with the flags would be required to get the file. In general, it would be pretty cumbersome to work with it compared to the API call and the data structure returned by it.

**Comment by T-Gro** [comment]
Exposing the dep. graph as it is isn't the right thing to do as of now, it would expose implementation detail.
This will be revisited at Analyzer SDK implementation, in order to expose similar level of information to analyzer.

**Pull request closed without merging**
