### PR TITLE
Better error reporting for `return, yield, return! and yield!`

### PR DESCRIPTION
**Pull request by edgarfgp**
## Description

Better error reporting for `return, yield, return! and yield!`

Continuation of https://github.com/dotnet/fsharp/pull/17779

### Before
Screenshot 2024-10-04 at 17 41 30

### After

```fsharp
let f1 = return [ 3; 4 ] 
         ^^^^^^
let f2 = return! [ 3; 4 ] 
         ^^^^^^^
```

### Before
Screenshot 2024-10-04 at 17 44 53

### After
```fsharp
let f3 =
    [
        if true then
            "a"
            "b"
        yield! [ 3; 4 ] 
               ^^^^^^^^
    ]
```

### Before
Screenshot 2024-10-04 at 17 46 23

### After
```fsharp
let f4 =
    async {
        if true then
            yield "a"
            ^^^^^
        else
            yield "b"
    }
```

### Before
Screenshot 2024-10-04 at 17 48 55

### After 
```fsharp
let maybeTask = task { return false }

let indexHandler (): Task<string> = 
    task {
        return! maybeTask
                ^^^^^^^^^
    }
```

## Checklist

- [x] Test cases added
- [x] Release notes entry updated:

### CODE REVIEW

**Comment by edgarfgp** [comment]
The failing tests in this PR are the `FSharp.Editor.Tests.CodeFixes.RemoveReturnOrYieldTests` which are VS specific. Unfortunately I no longer own a Windows machine.  @psfinaki would you able to help me with these failing test ?

**Comment by psfinaki** [comment]
Hmm looking at the tests, this change indeed breaks the code fix. Although the code fix itself is quite simple, shouldn't be a big deal, hope I'll get to it later today.

**Comment by psfinaki** [comment]
There you go, there is some change in range/span arithmetic there, added a few extra tests just to be sure :)

**Comment by edgarfgp** [comment]
> There you go, there is some change in range/span arithmetic there, added a few extra tests just to be sure :)

Thank you Sir. Enjoy the holidays :)

**Comment by edgarfgp** [comment]
This is ready

**Review by T-Gro — APPROVED** [review]

**Review by vzarytovskii — APPROVED** [review]

**Pull request merged**
