### PR TITLE
Add parser recovery for incomplete SynField

### PR DESCRIPTION
**Pull request by nojaf**

### CODE REVIEW

**Comment by auduchinok** [comment]
@nojaf Nice work, but this is already covered in https://github.com/dotnet/fsharp/pull/15042. 🙂

**Comment by kerams** [comment]
Vlad will send you an invoice for the CI run.

**Review by auduchinok — APPROVED** [review]
Let's merge these changes, I'm going to split https://github.com/dotnet/fsharp/pull/15042 and redo parts of it.

**Comment by psfinaki** [comment]
Alright, then @nojaf I guess there are some conflicts to fix here - ping if you need any help with them.

**Pull request merged**
