### PR TITLE
Fix lexing of words starting with #if/#else/#endif/#light

### PR DESCRIPTION
**Pull request by misonijnik**
`let t : #iftype` is lexed as
`LET, IDENT("t"), COLON, IF_HASH, IDENT("type")` 
but expected
`LET, IDENT("t"), COLON, HASH, IDENT("iftype")` .

I open this PR to run the tests.

Related to https://github.com/Microsoft/visualfsharp/issues/3487.

### CODE REVIEW

**Comment by cartermp** [comment]
@misonijnik have you had a chance to look over the CLA to sign?

**Comment by abelbraaksma** [comment]
By chance this gets merged? Seems a rain storm reasonable fix :)

**Comment by cartermp** [comment]
We'll need @misonijnik to sign the CLA to continue. It also seems like there were failures in CI.

**Comment by KevinRansom** [comment]
@abelbraaksma the bar is down for 16.0, but this will likely make 16.1

**Comment by KevinRansom** [comment]
@misonijnik ,

I am truly sorry for how long it took to get this.  I am afraid this PR got lost in the middle of the pack.  Thank you for making the time to fix this bug.  I am ready to approve this, but would like to see some testing.  If you get the chance to add some tests, please do so, failing that, I will probably revisit this at the weekend to knock up some tests for this PR.

nce again, my apologies and thank you for your contribution

Kevin

**Comment by abelbraaksma** [comment]
To add to that, I believe the CLA still needs to be signed, see https://github.com/dotnet/fsharp/pull/5498#issuecomment-413156025. Or is it legal if we just resurrect these changes in a new PR?

**Comment by KevinRansom** [comment]
@abelbraaksma  , it says the CLA conditions have been met, https://github.com/dotnet/fsharp/pull/5498#issuecomment-413156025

**Comment by abelbraaksma** [comment]
Interesting, before I posted it wasn't, and I hit the retry link just in case. Guess it's been done meanwhile, or my browser is playing me parts ;).

**Comment by KevinRansom** [comment]
@abelbraaksma , you should get new eyes mate, it says Aug 15th 2018 :-) 

As an FYI there is actually a CI task that fails the build and makes stuff unmergeable if the CLA is not signed.

**Comment by abelbraaksma** [comment]
> you should get new eyes mate, it says Aug 15th 2018 :-)

Haha, I actually do need to go to the optometrist (corona...), but I only posted because it said CLA signing was still needed. I've no idea why that particular part in this thread didn't refresh, and now does. Sorry for the noise.

**Comment by KevinRansom** [comment]
@abelbraaksma it's all good mate, just havin fun with ya :-)

**Comment by cartermp** [comment]
This is failing some tests - I think the code itself does look fine, but existing tests will have to be updated (provided this isn't regressing something)

**Comment by KevinRansom** [comment]
@cartermp I plan on looking at the failures.

**Comment by cartermp** [comment]
@KevinRansom i've assigned you to the pr

**Comment by cartermp** [comment]
Closing out old PR

**Pull request closed without merging**
