### PR TITLE
Enable Visualizer Support for F# in VS

### PR DESCRIPTION
**Pull request by mpeyrotc**
## Description

This PR addresses bug [361](https://github.com/microsoft/VSExtensibility/issues/361) from the VS Extensibility repo, where a customer is complaining about the lack of support of Custom Visualizers in VS for the F# language. I tested F#'s support of this scenario and did not notice any issues with it, so I feel it can be safely enabled for VS 2022. The only required change is to register the appropriate EE metric that gets consumed by VS to indicate the visualizers are supported. 

## Checklist

- [X] Test cases added *Not tests were added since there was no change to the language itself.*
- [X] Performance benchmarks added in case of performance changes. *This change should have 0 performance impact on the language.*
- [X] Release notes entry updated:

* Add Custom Visualizer support for F# in Visual Studio 2022 ([Issue #361](https://github.com/microsoft/VSExtensibility/issues/361), [PR #17239](https://github.com/dotnet/fsharp/pull/17239)).

### CODE REVIEW

**Review by KevinRansom — APPROVED** [review]
Nice, 

thank you

**Comment by abelbraaksma** [comment]
Even though it may look like a small change, the impact is massive! Thanks so much for this, and maybe you can update the release-notes anyway, so that people are aware this feature is coming their way? (or is there more that needs to be done here?)

**Comment by smoothdeveloper** [comment]
If the test/demo can confirm it works with a `System.Data.DataTable`, that would be great.

related issue: https://github.com/dotnet/fsharp/issues/13482

**Review by T-Gro — APPROVED** [review]

**Comment by mpeyrotc** [comment]
Hello [psfinaki](https://github.com/psfinaki), and [smoothdeveloper](https://github.com/smoothdeveloper)! Here is a .gif showcasing the IEnumerable and DataTable Visualizers for a simple F# project.

F#

**Comment by smoothdeveloper** [comment]
@mpeyrotc that rocks!

**Comment by abelbraaksma** [comment]
**this is awesome!!!**

**Review by abelbraaksma — APPROVED** [review]
**this is awesome!!**

**Pull request merged**
