### PR TITLE
Respect line limit in QuickInfo

### PR DESCRIPTION
**Pull request by majocha**
Fixes problem with the ellipsis as seen in #7783:

Before:
image

After:
image

### CODE REVIEW

**Comment by vzarytovskii** [comment]
Wondering if we should add `(+ X more)` instead of (or in addition to) ellipsis?

**Review by abonie — APPROVED** [review]

**Comment by psfinaki** [comment]
@majocha do you plan to add anything else here or do you want to have it as-is?

**Comment by majocha** [comment]
I'm fine with this as a simple improvement for now. We could revamp the whole thing in another PR.

At the moment I'm a bit blocked because test explorer doesn't work for me in the current VS preview. Larger refactoring probably would touch the tests. I guess I should reinstall VS.

**Comment by majocha** [comment]
I'm ok with this as a simple fix. We could further improve in another PR.

**Review by psfinaki — APPROVED** [review]

**Pull request merged**
