### PR TITLE
Remove inline IL for public 'not' function

### LINKED ISSUE #9433: `not(isNull x)` leads to very odd and partially unreachable IL code that performace 5x slower than redefining `not` yourself
I noticed this while doing timings for https://github.com/dotnet/fsharp/issues/9390, where sometimes using `not` gave an unexpected performance degradation. This boiled down to `not` sometimes leading to very unexpected IL.

## Repro steps

Take the following code snippet:

```f#
let useNotIsNull (str:string) =
    if not(isNull str) then str.Length
    else 0
```

Because `not` [is coded to return a single `IL` instruction](https://github.com/dotnet/fsharp/blob/ed9b9b7df908bbc2b90e46de27dc05678a6d787a/src/fsharp/FSharp.Core/prim-types.fs#L3795) with `ceq`, and `isNull`, [while coded with `match`](https://github.com/dotnet/fsharp/blob/ed9b9b7df908bbc2b90e46de27dc05678a6d787a/src/fsharp/FSharp.Core/prim-types.fs#L3775), also leads to basically a single `ceq` instruction, that we'd end up with two instructions, or, after optimization, a single one. However, it blows up:

        IL_0000: ldarg.0
        IL_0001: brfalse.s IL_0006

        IL_0003: ldc.i4.0
        IL_0004: br.s IL_0007

        IL_0006: ldc.i4.1

        IL_0007: brtrue.s IL_0010

        IL_0009: ldarg.0
        IL_000a: callvirt instance int32 [System.Private.CoreLib]System.String::get_Length()
        IL_000f: ret

        IL_0010: ldc.i4.0
        IL_0011: ret

Which gets translated in C# as:

    public static int useNotIsNull(string str)
    {
        if (str != null || 1 == 0)
        {
            return str.Length;
        }
        return 0;
    }

If you were to recreate the `not` function as follows:

```f#
let not x = match x with true -> false | _ -> true
```

The same code above would now be encoded in IL as:

        IL_0000: ldarg.0
        IL_0001: brfalse.s IL_000a

        IL_0003: ldarg.0
        IL_0004: callvirt instance int32 [System.Private.CoreLib]System.String::get_Length()
        IL_0009: ret

        IL_000a: ldc.i4.0
        IL_000b: ret

And here is the real killer, if we encode `not` as itself, the problem _also_ disappears, regardless of whether it is marked as `inline` (the original) or not:

```f#
let justLikeNot x = not x

let useJustLikeNot (str:string) =
    if justLikeNot(isNull str) then str.Length
    else 0
```

Resulting IL:

        IL_0000: ldarg.0
        IL_0001: brfalse.s IL_000a

        IL_0003: ldarg.0
        IL_0004: callvirt instance int32 [System.Private.CoreLib]System.String::get_Length()
        IL_0009: ret

        IL_000a: ldc.i4.0
        IL_000b: ret

Strangely, the `not` function itself looks exactly the same as the `justLikeNot` function above:

        IL_0000: ldarg.0
        IL_0001: ldc.i4.0
        IL_0002: ceq
        IL_0004: ret

Though in one case (with `isNull`) it leads to strange opcodes. In most other cases, it leads to the expected folding of the `ceq` into a `brfalse` or `brtrue` respectively.

More examples of coding this and their surprising translations can be found in [this SharpLab.io snippet](https://sharplab.io/#v2:DYLgZgzgNALiCWwoBMQGoA+wCmMAEAdgK7DADyBwAnngBQQwBOIDj8BA5gJR4C8AsACg8IvPDBiIAORLA8rPDAAW2AngAMQ0XmzAI2eUwB0AGVUdlQq4Jz4i+qQHsYASWmy6rFk3bc+W0XFCZ1p4d1JDRh5lVUjTc0thUV19DQCRIVsxMCd8ADcAQ2AiA3ombzZOHgEkkSCCZzxC4oMYtVZ4zkTtFINNWrxM3GzcgEEAB3HgeGxkPAky5lZfavTs4JhaMFouaJV24zMupTXetMEh/AaYGVIAJWwFr2Wq/wH6kMcAIwArIwewNhGKoAMbYACiAEciEUIIsoIRZLtFPs4kcLCcBmd+tpLiNnBMpjNkAAmeaecovPw1bQfTYSVh7WIddHdZJ6PprPHXPAADz4eAAtgUYCClHy8AB3eDKRSMEp4AC0AD55rCDBg8AB9JWqpglaxZa5uW7kcb4RYVFZvWkSa6hcJyRko5mHBKYnoc854n72GAmeAAa2wuQlvA2fMNw3s2AAUn6A8HQ5aqat3hJfQxEyGQmFTZEmQdGJ0Macvf0uYIgA==).

**Expected behavior**

**Actual behavior**

See above for the _actual_ behavior. In terms of performance, the different `not` versions in the code perform all as expected, since they are ultimately folded into optimized x64 assembly, **except for the `not(isNull x)` version**. The `notIsNull` below uses `not(isNull x)`, the others all use a different way of coding `not` than the default:

image

_(These timings were made by ensuring the function returns and is not optimized away (hence the `str.Length` call) and repeated 10_000x in a close for-loop to erase timing inefficiencies for micro-benchmarks with BDN.)_

This is ultimatedly caused by the final assembly, which looks as follows (note the popping and extra call):

```assembly
; FSharp.Perf.BenchLength.notIsNull()
       push      rdi
       push      rsi
       sub       rsp,28
       mov       ecx,[rcx+8]
       call      FSharp.Perf.Data.get(Int32)
       mov       rsi,rax
       xor       edi,edi
M00_L00:                      ; start of for-loop body
       mov       rcx,rsi
       call      FSharp.Perf.StringLength.notIsNull(System.String)
       inc       edi
       cmp       edi,2711       ; loop 10_000 times
       jl        short M00_L00
       add       rsp,28
       pop       rsi
       pop       rdi
       ret
; Total bytes of code 44
```

```assembly
; FSharp.Perf.StringLength.notIsNull(System.String)
       test      rcx,rcx
       je        short M02_L00
       mov       eax,[rcx+8]
       ret
M02_L00:
       xor       eax,eax
       ret
; Total bytes of code 12
```

Compare that to using one of the `not` redefinitions, which, with the same code, gives:

```assembly
; FSharp.Perf.BenchLength.newNot()
       sub       rsp,28
       mov       ecx,[rcx+8]
       call      FSharp.Perf.Data.get(Int32)
       xor       edx,edx
M00_L00:                      ; start of for-loop body
       test      rax,rax
       je        short M00_L01
       mov       ecx,[rax+8]
M00_L01:
       inc       edx
       cmp       edx,2711       ; loop 10_000 times
       jl        short M00_L00
       add       rsp,28
       ret
; Total bytes of code 37
```

That is: no push/pop of `rdi` and `rsi`, that is, no new stackframe.

**Known workarounds**

Redefine `not` yourself and the problem seems to disappear.

**Related information**

I've only tested this on the latest VS + FSC (with optimizations on, of course), but the Sharplab decoding showed the same results.

I discussed this with @baronfel yesterday and neither of us could come up with a reasonable explanation, even more so since re-defining `not` as itself leads to optimized code, so I'm not sure why the combination `not(isNull x)` leads to such IL. The Sharplab.io link shows that using something else than `isNull` in the brackets _does not lead to the same weird IL opcodes_.

### PR DESCRIPTION
**Pull request by cartermp**
Fixes #9433

The current implementation of `not` gets funky when you pass in a call to `isNull` for a reference type. Probably other quirks too. The following benchmark shows the effect:

```fsharp
module Op =
    let inline not' x = if x then false else true
    let inline not'' x = match x with true -> false | false -> true


[<MemoryDiagnoser>]
type NotBench() =
    let s = "hello"

    [<Benchmark(Baseline=true)>]
    member _.Not() = 
        let mutable b = false
        for i=0 to 1 do b <- not (isNull s)
        b

    [<Benchmark>]
    member _.NotWithIf() = 
        let mutable b = false
        for i=0 to 1 do b <- Op.not' (isNull s)
        b

    [<Benchmark>]
    member _.NotWithMatch() = 
        let mutable b = false
        for i=0 to 1 do b <- Op.not'' (isNull s)
        b
```

I get these timings against .NET 5:

|       Method |     Mean |     Error |    StdDev | Ratio | Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------- |---------:|----------:|----------:|------:|------:|------:|------:|----------:|
|          Not | 1.859 ns | 0.0224 ns | 0.0187 ns |  1.00 |     - |     - |     - |         - |
|    NotWithIf | 1.277 ns | 0.0178 ns | 0.0139 ns |  0.69 |     - |     - |     - |         - |
| NotWithMatch | 1.277 ns | 0.0188 ns | 0.0157 ns |  0.69 |     - |     - |     - |         - |

And these for net48:

|       Method |     Mean |     Error |    StdDev | Ratio | RatioSD | Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------- |---------:|----------:|----------:|------:|--------:|------:|------:|------:|----------:|
|          Not | 1.909 ns | 0.0448 ns | 0.0419 ns |  1.00 |    0.00 |     - |     - |     - |         - |
|    NotWithIf | 1.295 ns | 0.0357 ns | 0.0334 ns |  0.68 |    0.03 |     - |     - |     - |         - |
| NotWithMatch | 1.292 ns | 0.0126 ns | 0.0118 ns |  0.68 |    0.02 |     - |     - |     - |         - |

### CODE REVIEW

**Comment by abelbraaksma** [comment]
For my understanding, this looks like a giant change for one line of code, does this have something to do with specific IL tests, that are generated from time to time to prevent accidental IL regressions?

**Comment by cartermp** [comment]
Ugh, looks like getting these ExprTests to pass locally doesn't mean anything in a CI environment. These tests are so hard to understand

@abelbraaksma Yes, the huge changes are about IL that was generated many years ago and how it needs to change given that `not` has been changed to emit better IL. It's frustrating to deal with, unfortunately

**Comment by cartermp** [comment]
These FSharpQA tests are impossible to update or get to pass. I don't know how to progress with this PR.

**Comment by abelbraaksma** [comment]
Ouch, sounds painful. I doubt I can help, but since it was my report to begin with, I can give it a shot (likely to strand where you stranded, but then at least we're both frustrated :p)

**Comment by abelbraaksma** [comment]
From a cursory look at the tests, it appears it's the same set that I ran into for updating `string`. I start to understand why nobody dares attacking these basic functions: too much effort getting the tests updated.

**Comment by cartermp** [comment]
Given some other changes to these files, where similar seemingly unrelated changes had to go in just to get the tests to pass, I'm certain now that whatever the tool FSharpQA tests use to generate those baseline tools is very much out of date and shouldn't be considered to greatly.

@KevinRansom sorry to call upon you here, but I have absolutely no clue how to get this FSharpQA test to pass.

**Comment by KevinRansom** [comment]
@cartermp, will take a look.  I remember looking earlier and wondering if it was a real issue, which worried me cos I like the fix.

**Comment by abelbraaksma** [comment]
Oops, I forgot that you continued from https://github.com/dotnet/fsharp/pull/9434 here. 

I've meanwhile taken a slightly different approach which leaves the `not` optimizations used for generic comparisons in place as-is, and has the public `not` function compile as done here. Sorry for the hijack ;). 

@cartermp This new PR is green now: https://github.com/dotnet/fsharp/pull/9715, maybe close this in favor of that one?

About this:

> Ugh, looks like getting these ExprTests to pass locally doesn't mean anything in a CI environment. These tests are so hard to understand

Some of those problems are now alleviated with https://github.com/dotnet/fsharp/pull/9622. But some of the failures you see in CI but not locally are caused by the fact that CI runs some tests with old FSharp.Core.dll. I ran into something similar here (https://github.com/dotnet/fsharp/pull/9549) where I ultimately decided to disable some tests based on what FSharp.Core version is loaded. Once we go over this again with @vzarytovskii, I hope to come to a cleaner way of writing / running these.

**Comment by cartermp** [comment]
Closing in favor of https://github.com/dotnet/fsharp/pull/9715

**Pull request closed without merging**
