### PR TITLE
Distinguish signature files from non-signature files in NavigateToSearchService results

### PR DESCRIPTION
**Pull request by cartermp**
fixes https://github.com/dotnet/fsharp/issues/11317

image

### CODE REVIEW

**Comment by smoothdeveloper** [comment]
Does it address the seemingly non deterministic order as well?

**Comment by cartermp** [comment]
Not that I'm aware of, but we'll find out :)

**Comment by cartermp** [comment]
There's probably a much fancier way to separate string-based names/search keys and the presentation.

I experimented with taking string tokens from the data we compete and assigning an appropriate `TaggedText` for each "part" and rendering it all fancy-like. But that ended up being a little more difficult, and represents some feature creep when this solves the main issue at hand. So I decided not to bother with going that route right now. Might come in as a secondary PR if I'm feeling up for it some evening or weekend.

**Comment by smoothdeveloper** [comment]
@cartermp, this fixes the main issue that @kerams brought and that's honestly, outstanding turnaround.

I think once the results disambiguated, living with the nondeterministic order is more bearable, and concur with your reply to scope later/with other things.

I was trying to figure out if you stoned all the birds without groking the code changes myself 🙂

**Review by TIHan — APPROVED** [review]

**Pull request merged**
