### PR TITLE
Compiler tests cleanup, part 1

### PR DESCRIPTION
**Pull request by psfinaki**
This will be quite a journey.

The idea is to merge FSharp.Compiler.Service.Tests with FSharp.Compiler.UnitTests and move to xUnit altogether.

This will also remove some test duplication and save some CI time.

### CODE REVIEW

**Comment by vzarytovskii** [comment]
@auduchinok @nojaf  could you please take a look at it, if it works for you guys. I don't think that UnitTests are in the FCS solution, so it's pretty much removing tests from this solution.

**Comment by auduchinok** [comment]
> @auduchinok @nojaf could you please take a look at it, if it works for you guys. I don't think that UnitTests are in the FCS solution, so it's pretty much removing tests from this solution.

Removing the tests project from FCS solution would be really problematic, as we mostly work with this solution. Would it be possible to add `UnitTests` to that solution instead?

**Comment by psfinaki** [comment]
Uff that would be even harder - because FSharp.Compiler.Service.Tests is NUnit whereas we are converging things to xUnit, hence  to FSharp.Compiler.UnitTests which is xUnit already.

How about including both projects in the FCS solution until we eventually only have one?

**Comment by KevinRansom** [comment]
@psfinaki , hey mate, at first I was wondering why you wasn't merging unit tests into compiler service, because xunit has fewer files.  But I suppose the xunit translation may take a moment.

Anyway two thumbs for this, I like the goal.

**Review by T-Gro — APPROVED** [review]

**Review by vzarytovskii — CHANGES_REQUESTED** [review]
Both suites should be in the service solution.

**Comment by psfinaki** [comment]
> Both suites should be in the service solution.
Done

**Review by KevinRansom — APPROVED** [review]

**Pull request merged**
