### PR TITLE
Reconfigure Legacy MSBuildReferenceResolver to be API-driven

### PR DESCRIPTION
**Pull request by cartermp**
Another one of the ickies found by removing the IVT to FSharp.Editor.

Changes MSBuildReferenceResolver to have a single accessible entrypoint, a function that gives a `Resolver`. Calls this everywhere else. Also renames some files and moves stuff around.

### CODE REVIEW

**Comment by cartermp** [comment]
Dern, we keep this thingie around in VisualFSharp.sln but it's not a part of FCS proper

**Comment by cartermp** [comment]
This one sucks.

**Comment by cartermp** [comment]
@KevinRansom this one is now ready

**Comment by cartermp** [comment]
No it's not :)

**Comment by KevinRansom** [comment]
@cartermp lol …

**Comment by KevinRansom** [comment]
````
D:\a\1\s\src\fsharp\fscmain.fs(65,13): error FS0039: The value, namespace, type or module 'MSBuildReferenceResolver' is not defined. Maybe you want one of the following:   LegacyMSBuildReferenceResolver   ReferenceResolver [D:\a\1\s\src\fsharp\fsc\fsc.fsproj]
D:\a\1\s\src\fsharp\fsi\fsimain.fs(231,13): error FS0039: The value, namespace, type or module 'MSBuildReferenceResolver' is not defined. Maybe you want one of the following:   LegacyMSBuildReferenceResolver   ReferenceResolver [D:\a\1\s\src\fsharp\fsi\fsi.fsproj]
    0 Warning(s)
    2 Error(s)
````

**Comment by cartermp** [comment]
Now it's ready!

**Pull request merged**
