### PR TITLE
fix async task completion on UI thread

### PR DESCRIPTION
**Pull request by dsyme**
As discussed in https://github.com/dotnet/fsharp/issues/11946, we have situations where Roslyn is (somewhat unexpectedly) making synchronous, blocking task invocations from the Visual Studio UI thread.  

In the past most of these were completing synchronously, which didn't cause problems.  Recent changes (likely around project options) mean they are now completing asynchronously, trying to reschedule the completion on the UI thread.

Now no `async { ... }` code anywhere in FSharp.Editor is ever intended to run on the UI thread - if any async reschedule is needed it should always execute in the thread pool.   That is, our async code in FSharp.Editor is always backgroundAsync in the sense that it is valid switch away from the UI thread if it is ever started on the UI thread, e.g. [see the corresponding `backgroundTask { ... }` in RFC FS-1097](https://github.com/fsharp/fslang-design/blob/main/preview/FS-1097-task-builder.md#background-tasks-and-synchronization-context)

The short term fix is to change `RoslynHelpers.StartAsyncAsTask` to always `Async.SwitchToThreadPool` if started on the UI thread.  We should always have done this and it corresponds to the check in `RunImmediateExceptOnUI` we added recently.

The medium term fix is to rewrite all our `async { ... }` code in FSharp.Editor to just use `backgroundTask { ... }` anyway, since `task { ... }` and `backgroundTask { ... }` are now in preview.  However that's a larger job and needs care as we lose things like implicit cancellation token propagation and implicit cancellation checks.

### CODE REVIEW

**Comment by dsyme** [comment]
I have tested this manually and it resolves #11946.  We should use the product for a bit with the fix in place.

The fix may be necessary for 16.11 servicing release since I belive whatever is causing these problems will have crept into VS2019 16.10?

**Comment by dsyme** [comment]
@TIHan this is ready

**Review by TIHan — APPROVED** [review]

**Comment by TIHan** [comment]
// cc https://github.com/dotnet/fsharp/pull/11715

**Comment by dsyme** [comment]
Confirming the problematic PR is not in 16.10 or 16.11, so this hasn't made it out into non-preview releases https://github.com/dotnet/fsharp/commits/release/dev16.11

**Pull request merged**
