### PR TITLE
Add cyclic check for struct tuple and tests

### PR DESCRIPTION
**Pull request by ScottHutchinson**
Fixes Issue #3916.

### CODE REVIEW

**Review by cartermp — APPROVED** [review]
Thanks! This is great. Looks like there is a conflict, though.

**Comment by vzarytovskii** [comment]
> Thanks! This is great. Looks like there is a conflict, though.

I guess this is because I've reverted my PR with adding test cases to the ComponentTests suite.

**Comment by ScottHutchinson** [comment]
I either don't have access to resolve the conflict, or I don't know how to do it.

**Comment by cartermp** [comment]
@ScottHutchinson In this case you'll have to rebase against latest `main` with your changes. That will surface the conflict on your branch.

**Review by KevinRansom — APPROVED** [review]

**Comment by ScottHutchinson** [comment]
Oy. I suck at git. I've been trying for two hours to rebase and resolve the conflict. So I guess I will close the PR, delete this branch and start over.

**Comment by KevinRansom** [comment]
@ScottHutchinson , let me take a look for you.

**Comment by ScottHutchinson** [comment]
I have now opened PR #10645 to replace this one. Checks in progress.

**Pull request closed without merging**
