### PR TITLE
IL: optimize attribute cluster reading (Fixed version)

### PR DESCRIPTION
**Pull request by DedSec256**
Fixed version of https://github.com/dotnet/fsharp/pull/13821

This PR contains fix https://github.com/dotnet/fsharp/commit/1e0ebe5eb08f59227b8d990f0598b36b5502ccb1 for the loop counter that previously caused seek to hang in an unsorted table https://github.com/dotnet/fsharp/issues/14651. 
Search in a sorted table is also slightly refactored to be more clear.

Without this fix, the hang reproduced at build time and in the IDE while analyzing file `SplitApp.Android/MainActivity.fs` from the issue above, when trying to read attributes for assembly `System.Runtime.CompilerServices.Unsafe.dll (Metadata v4.0.30319)`. 

cc @auduchinok

### CODE REVIEW

**Review by auduchinok — APPROVED** [review]
@DedSec256 Thanks!

**Comment by auduchinok** [comment]
Would it be possible to write a test that references `System.Runtime.CompilerServices.Unsafe.DLL` and can reproduce the issue without your fixes?

**Comment by vzarytovskii** [comment]
This will probably have to go past net8, just to be safe

**Comment by psfinaki** [comment]
@DedSec256 hey Alex, this LGTM, if possible please add a test described by Eugene, then we can probably pull this in.

**Comment by DedSec256** [comment]
@psfinaki, I tried to add a test, but it requires the specific version of System.Runtime.CompilerServices.Unsafe.dll (Metadata v4.0.30319) on which the problem is known to reproduce. So we need to push this version of the library, or come up with something else.

**Comment by vzarytovskii** [comment]
> @psfinaki, I tried to add a test, but it requires the specific version of System.Runtime.CompilerServices.Unsafe.dll (Metadata v4.0.30319) on which the problem is known to reproduce. So we need to push this version of the library, or come up with something else.

Just have a separate manual test under `tests/projects/` which demonstrates the issue + uses a just built compiler. We don't run them for now, though we probably can add them as we do with trimming tests.

**Comment by vzarytovskii** [comment]
Just to be clear, the change compared to previous revision is an off-by-one fix?

**Comment by DedSec256** [comment]
Yes, the current version differs from the previous one by only one commit https://github.com/dotnet/fsharp/pull/15941/commits/1e0ebe5eb08f59227b8d990f0598b36b5502ccb1 that has two changes:
1. Fix for the loop counter that previously caused seek to hang in an unsorted table.
2. Search in a sorted table is also slightly refactored to be more clear.

**Review by T-Gro — APPROVED** [review]

**Review by psfinaki — APPROVED** [review]

**Pull request merged**
