### PR TITLE
Struct representation for active patterns [ RFC FS-1039 ]

### PR DESCRIPTION
**Pull request by yatli**
Implementation of part 1 of RFC https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1039-struct-representation-for-active-patterns.md

Suggestion: https://github.com/fsharp/fslang-suggestions/issues/612

Quick notes:

- `[<Struct>]` should be allowed on methods
- `[<Struct>]` should be constrained on APs.
- `APInfo` is syntactic and thus not suitable for type inference.
- So the actual type checking happens in pattern matching compilation
- A few more helpers in typed tree ops for `voption`
- Not sure what's the value counterpart for `Choice`?

### CODE REVIEW

**Comment by yatli** [comment]
As of 89b59d32ae5bf236afe6dbfba87a4db721147e31, first trial:

image

Didn't even scratch it :p

**Comment by yatli** [comment]
Setting breakpoint at PatternMatchCompilation.fs,L1199 -- didn't even hit.
Something else is asserting the type to be `'a option`

**Comment by yatli** [comment]
As of df61485:

image

Typecheck is OK with my hack but it compiles wrong code.
Need the address of the voption value.

**Comment by yatli** [comment]
That's all for me tonight.
(@dsyme @cartermp any hints?)

**Comment by dsyme** [comment]
@yatli Merged with main and I'll take a look.  Thanks for taking the lead on this

I'm not sure what design I prefer:

```
// the option in the PR
[<Struct>]
let (|CaseName|_|) x = ...

// Infer from return type
let (|CaseName|_|) x : int voption = ...

// A new attribute
[<ActivePatternStruct>]
let (|CaseName|_|) x = ...

// Target the return meta info
[<return: Struct>]
let (|CaseName|_|) x = ...

```

Of these the last looks best

**Comment by dsyme** [comment]
@yatli I have updated this so a basic example works.

1. Further testing will be needed 

2. I added a check that the Struct attribute is used only on partial active patterns.  Testing is needed for this

3. I think it would be great if we updated this to require `[<return: Struct>]`

4. There is a separate question of struct returns for multi-case active patterns.  That is tricky because we don't have any `ValueChoice` types in FSharp.Core and they would get quite large for cases > 3. This may require the use of .NET IL union representations for struct union types though I'm not sure they can be used for generic structs.

I used this code:
```fsharp

open System


[<Struct>] 
let (|Even|_|)(x:int) = if x % 2 = 0 then ValueSome (x/2) else ValueNone


let g (y: int) =
    match y with
    | Even n -> printfn "result = %d" n
    | _ ->printfn "%d is not even!" y
    
    
g 6
g 5
```

**Comment by dsyme** [comment]
Also we will need an RFC for this.  It's certainly pre-approved as a suggestion, I'm really glad we're getting to this

**Comment by yatli** [comment]
Thank you very much @dsyme !

Next I'll work on the tests and add the language feature flag.

> I think it would be great if we updated this to require [<return: Struct>]. I've added that to the RFC.

Yeah I think that'll be more intuitive. I'll see if I can rotate it down the tree.

> There is a separate question of struct returns for multi-case active patterns. That is tricky because we don't have any ValueChoice types in FSharp.Core and they would get quite large for cases > 3. This may require the use of .NET IL union representations for struct union types though I'm not sure they can be used for generic structs.

For non-parameterized types it works well.
But the runtime refuses to load a generic union struct (`Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more`) like this:

```c#
[StructLayout(LayoutKind.Explicit)]
struct M<T>
{
  [FieldOffset(0)]
  public int foo;
  [FieldOffset(8)]
  public string bar;
  [FieldOffset(8)]
  public T baz;
}
```

... which is unfortunate, but makes sense, because the runtime doesn't know if `T` is value or ref.

... which can be worked around with templated types rather than generic?

**Comment by Lanayx** [comment]
@dsyme Why is the second option with automatically inferred type is not appealing to you? Type inferring is native thing that everyone got used to and defining return type in attribute when it is well-known from function result feels redundant.

**Comment by dsyme** [comment]
> @dsyme Why is the second option with automatically inferred type not appealing to you? Type inference is native for F#, and everyone got used to it, defining return type in attribute when it is well-known from function result feels redundant.

Because the size of the type annotation is large, it's position awkward, and gives not real clarity about what's going on.  Also if we allow struct returns for multi-case active patterns the type annotations just get larger.

Inferring from the use of `ValueSome` and `ValueNone` might be feasible but is challenged by two things

- the order in which this information is laid down is the other way around - we first see `(|A|_|)` and then say "oh the return type is an option` and then process the body.  This ordering does have consequences.  

- it doesn't work for multi-case patterns where the pattern tags are used for each return case.

In contrast `[<return: Struct>]` is declarative enough.  At least it does what it says.

**Comment by yatli** [comment]
rebased to latest upstream.

**Comment by yatli** [comment]
@dsyme as of c6fed32:

- Language feature flag added
- `[<return:...>]` on bindings are rotated into return value
- Return target must be explicitly specified:

```F#
[<return:Struct>]
let (|Foo|_|) x = ValueSome() // OK

[<Struct>]
let (|Foo|_|) x = ValueSome() // Not OK
```

Also, if an attrib can target both return and method, without specifying the target it will never target the return value.

**Comment by yatli** [comment]
@dsyme that's all for me tonight. Most of the tasks are done now, except the custom attribute rotation problem as documented above.

**Comment by yatli** [comment]
rebased to latest upstream.

**Comment by yatli** [comment]
rebased to latest upstream.

**Comment by yatli** [comment]
Rebased to latest main, and the function binding return target rotation bug is fixed.

@dsyme I think it is ready for review.

**Comment by gsomix** [comment]
@cartermp Hey, any chance to get it merged in the near future? Thanks!

**Comment by dsyme** [comment]
> @cartermp Hey, any chance to get it merged in the near future? Thanks!

We need it green and merged with main

**Comment by dsyme** [comment]
I've merged with main and will take a close look.

> @dsyme @cartermp I think it is ready for review.

@yatli My apologies for not replying to this comment.

**Comment by Neftedollar** [comment]
Awesome!
THNX @yatli @dsyme @cartermp @gsomix

**Comment by dsyme** [comment]
Test failures
```
2021-06-03T13:11:29.5064669Z Conformance\PatternMatching\And (andPattern03.fs) -- failed
2021-06-03T13:11:29.6363917Z Conformance\PatternMatching\Named (activePatterns05.fs) -- failed
2021-06-03T13:11:29.6365884Z Conformance\PatternMatching\Named (activePatterns07.fs) -- failed
2021-06-03T13:11:29.6378163Z Conformance\PatternMatching\Named (ActivePatternOutsideMatch01.fs) -- failed
2021-06-03T13:11:29.6379146Z Conformance\PatternMatching\Named (ActivePatternOutsideMatch02.fs) -- failed
2021-06-03T13:11:29.6405392Z Conformance\PatternMatching\Named (NamedLiteral02.fs) -- failed
```

**Comment by dsyme** [comment]
I've fixed the tests, once it's green this is ready for design, test, implementation review

**Review by dsyme — APPROVED** [review]

**Comment by dsyme** [comment]
I decided to approve this, recalling that I've effectively done a review already as part of earlier work with @yatli.  These design is as good as we're going to get

I'll update the RFC too

**Review by vzarytovskii — APPROVED** [review]

**Comment by dsyme** [comment]
Tracking bug: https://github.com/dotnet/fsharp/issues/12250

**Comment by dsyme** [comment]
Thank you, this appears to be a bug.  I'll add it to dotnet/fsharp

**Pull request merged**
