### PR TITLE
Add ChangeToUpcast code fix

### PR DESCRIPTION
**Pull request by cartermp**
Operator:

image

Keyword:

image

Surfacing the improved message from https://github.com/dotnet/fsharp/issues/1127 into the code fixer, basically.

### CODE REVIEW

**Comment by cartermp** [comment]
This is ready for review

**Review by KevinRansom — CHANGES_REQUESTED** [review]
@cartermp, any chance of a test case?

**Comment by cartermp** [comment]
There's no test harness for these

**Review by TIHan — APPROVED** [review]

**Comment by cartermp** [comment]
@KevinRansom testing might be possible here, but it might get complicated. Would needs to create a mocking system to verify that certain things trigger. A different approach would be just to factor the logic into a function. But there is so little logic here that it feels like overkill

**Review by KevinRansom — APPROVED** [review]

**Pull request merged**
