### PR TITLE
CompilerOrder: set metadata for CompileFirst items

### PR DESCRIPTION
**Pull request by auduchinok**
Follow-up for #17791. Fixes the remaining case.

### CODE REVIEW

**Review by T-Gro — APPROVED** [review]

**Comment by auduchinok** [comment]
It's ready.

**Comment by auduchinok** [comment]
@vzarytovskii Could you guys please backport #17791 and this PR to .NET 8?

**Comment by vzarytovskii** [comment]
> @vzarytovskii Could you guys please backport #17791 and this PR to .NET 8?

It'll probably not gonna hit the approval bar. @KevinRansom

**Review by edgarfgp — APPROVED** [review]

**Review by KevinRansom — APPROVED** [review]

**Comment by KevinRansom** [comment]
@auduchinok 
Neither of these changes will make the backport bar.  Without either of these changes, everything works as designed and intended.  The bar for SDK changes, is along the lines of the bug breaks an existing designed feature, causes a serious program crash, obviously, security issues, and source code regressions.

**Review by KevinRansom — APPROVED** [review]
I wish I'd never added CompileFirst and CompileLast.  Come to think about it, I wish we could fix compile ordering to not be required.

**Comment by KevinRansom** [comment]
@auduchinok ---
we have given this some thought, chatted with a few people and we think we can try to includes these changes in the 8.0.4XX LTSbranch.  There is no guarantee, but given that these are very low risk changes and there is no good work around for you we will try to argue the case.

**Comment by auduchinok** [comment]
@KevinRansom Thank you very much! That will be really great if it's possible to merge it there!

**Pull request merged**
