### PR TITLE
Preserve original stacktrace in state machines if available

### PR DESCRIPTION
**Pull request by vzarytovskii**
## Description

Preserve original stacktrace in resumable state machines generated code, if avalable.

Before:
```fsharp
at Microsoft.FSharp.Core.CompilerServices.ResumableCode.TryFinallyCompensateDynamic[TData](ResumableStateMachine`1& sm, ResumptionFunc`1 mf, FSharpOption`1 savedExn) in /Users/u/code/fsharp3/src/FSharp.Core/resumable.fs:line 299
at Microsoft.FSharp.Core.CompilerServices.ResumableCode.TryFinallyAsyncDynamic[TData,T](ResumableStateMachine`1& sm, ResumableCode`2 body, ResumableCode`2 compensation) in /Users/u/code/fsharp3/src/FSharp.Core/resumable.fs:line 326
at VahterBanBot.Bot.onUpdate@391-46.Invoke(ResumableStateMachine`1& sm)
at VahterBanBot.Bot.onUpdate@389-48.Invoke(ResumableStateMachine`1& sm)
at <StartupCode$FSharp-Core>.$Tasks.initialResumptionFunc@168.Invoke(ResumableStateMachine`1& sm) in /Users/u/code/fsharp3/src/FSharp.Core/tasks.fs:line 168
at <StartupCode$FSharp-Core>.$Tasks.resumptionInfo@171.MoveNext(ResumableStateMachine`1& sm) in /Users/u/code/fsharp3/src/FSharp.Core/tasks.fs:line 177
      --- End of stack trace from previous location ---
at Program.webApp@110-2.MoveNext() in /Users/u/code/vahter-bot/src/VahterBanBot/Program.fs:line 115
```

After:
```fsharp
at VahterBanBot.Bot.onUpdate@392-1.Invoke(Activity banOnReplyActivity) in /Users/u/code/vahter-bot/src/VahterBanBot/Bot.fs:line 392
at VahterBanBot.Bot.onUpdate@391-44.Invoke(ResumableStateMachine`1& sm)
at Microsoft.FSharp.Core.CompilerServices.ResumableCode.TryFinallyAsyncDynamic[TData,T](ResumableStateMachine`1& sm, ResumableCode`2 body, ResumableCode`2 compensation) in /Users/u/code/fsharp3/src/FSharp.Core/resumable.fs:line 323
      --- End of stack trace from previous location ---
at Microsoft.FSharp.Core.CompilerServices.ResumableCode.TryFinallyCompensateDynamic[TData](ResumableStateMachine`1& sm, ResumptionFunc`1 mf, FSharpOption`1 savedExn) in /Users/u/code/fsharp3/src/FSharp.Core/resumable.fs:line 302
at Microsoft.FSharp.Core.CompilerServices.ResumableCode.TryFinallyAsyncDynamic[TData,T](ResumableStateMachine`1& sm, ResumableCode`2 body, ResumableCode`2 compensation) in /Users/u/code/fsharp3/src/FSharp.Core/resumable.fs:line 329
at VahterBanBot.Bot.onUpdate@391-46.Invoke(ResumableStateMachine`1& sm)
at VahterBanBot.Bot.onUpdate@389-48.Invoke(ResumableStateMachine`1& sm)
at <StartupCode$FSharp-Core>.$Tasks.initialResumptionFunc@168.Invoke(ResumableStateMachine`1& sm) in /Users/u/code/fsharp3/src/FSharp.Core/tasks.fs:line 168
at <StartupCode$FSharp-Core>.$Tasks.resumptionInfo@171.MoveNext(ResumableStateMachine`1& sm) in /Users/u/code/fsharp3/src/FSharp.Core/tasks.fs:line 177
      --- End of stack trace from previous location ---
at Program.webApp@110-2.MoveNext() in /Users/u/code/vahter-bot/src/VahterBanBot/Program.fs:line 115
```

Notice that it will now print a line exception originated from (topmost line in the stack trace above).

I want to additionally look into using the following attribute if available in code generated state machines:

https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.stacktracehiddenattribute?view=net-6.0

## Checklist

@T-Gro @psfinaki @0101 @abonie @KevinRansom I am not sure if we need a dedicated set of tests for this case. We don't usually do that, and how things are thrown (stack traces in particular) is an implementation detail. I will not add it unless any of you insist.

- [ ] ~~Test cases added~~ (N/A)
- [x] Release notes entry updated:

### CODE REVIEW

**Comment by vzarytovskii** [comment]
Note: this will only affect dynamically compiled state machines

**Comment by psfinaki** [comment]
Great stuff. Regarding testing: we can always _insist_, the questions is - how hard is it to add them and how else verify that nothing explodes.

Personally, this _feels_ safe to me, or more exactly small and isolated enough.

**Comment by vzarytovskii** [comment]
> Great stuff. Regarding testing: we can always _insist_, the questions is - how hard is it to add them and how else verify that nothing explodes.
> 
Will be easy to add, but might be tricky to verify w.r.t. line numbers and such, will probably be more code for testing infrastructure than the change itself.

**Review by 0101 — APPROVED** [review]

**Review by T-Gro — APPROVED** [review]

**Comment by vzarytovskii** [comment]
> > Will be easy to add, but might be tricky to verify w.r.t. line numbers and such, will probably be more code for testing infrastructure than the change itself.
> 
> Shouldn't be too bad. You can access the stack trace programmatically with `System.Diagnostics.StackTrace` and maybe just check the method name from the first frame, or whatever else you're interested in. Don't have to care about line numbers or any other specifics.

I decided not to do that for now, since we don't have such tests anyway.

**Pull request merged**
