### PR TITLE
Optimize SyntaxVisitorBase

### PR DESCRIPTION
**Pull request by kerams**
No need to dive down the second path before checking the result of the first dive.

---

Since `SyntaxVisitorBase` is the backbone for much of editor tooling, I was thinking of creating a benchmark project measuring the performance and allocations when visiting specific parts of the syntax tree, running on decently sized files, ideally something lifted from the compiler, like Optimizer or IlxGen. How hard would it then be to create a pipeline that we could trigger manually with a comment like they do in the runtime repo? It would then print a readout of the differences in the benchmark before and after the changes in the PR. It could also automatically run every day or week. I would love to see a nice interactive graph of what's going on over time.

### CODE REVIEW

**Comment by vzarytovskii** [comment]
It'd be great to have benchmarks for the FCS & co, I'd probably host/run them in dotnet/performance, since there's an infrastructure for it there.

I'm now in progress of working on PERFGUIDE - general advice and rules on how to perf test your changes. I'll probably include some guidance on how to integrate with dotnet/performance

**Comment by auduchinok** [comment]
Just wondering, could using the new state machine based lazy sequences be a good alternative approach in this and some similar cases?

**Review by vzarytovskii — APPROVED** [review]

**Comment by kerams** [comment]
There's also stuff like

```fsharp
[
    yield dive synPat synPat.Range traversePat
    yield dive synExpr synExpr.Range traverseSynExpr
    yield!
        [ for SynExprAndBang(pat=andBangSynPat; body=andBangSynExpr) in andBangSynExprs do
            yield (dive andBangSynPat andBangSynPat.Range traversePat)
            yield (dive andBangSynExpr andBangSynExpr.Range traverseSynExpr)]
    yield dive synExpr2 synExpr2.Range traverseSynExpr
]
|> pick expr
```

There's some logic in the `pick` function, so I am not sure if we could get away with the same optimization here. @baronfel, any thoughts?

**Review by KevinRansom — APPROVED** [review]

**Comment by auduchinok** [comment]
> @auduchinok, tryPick does stop iterating when it finds the result. The problem here was that the input list already contained dive results, whereas in other places diving occurs during the picking stage:

Yes, I was wondering about other cases where lists are created upfront and using lazy sequences together with `Seq.tryPick` could work better.

**Pull request merged**
