### PR TITLE
Detect get/set combination for GetStructuredToolTipText.

### PR DESCRIPTION
**Pull request by nojaf**
Fixes https://github.com/dotnet/fsharp/issues/15584.
Due to https://github.com/dotnet/fsharp/pull/15213, there are now two symbols for auto properties (which I still think is correct).
This leads to the double tooltip, as a first fix I'm only showing the tooltip for the getter.
Which was the original behaviour. 
Ideally, this would show `with get, set` but that proves to be a bit more challenging.

### CODE REVIEW

**Comment by auduchinok** [comment]
> Due to https://github.com/dotnet/fsharp/pull/15213, there are now two symbols for auto properties (which I still think is correct).

I think it's not. There should be a single symbol for the property on the identifier range. The property symbol should then return the separate accessors symbols in `GetterMethod` and `SetterMethod` properties when applicable. In addition to the property symbol, there may be accessors symbols reported at the accessor ranges.

We have another regression in tests showing exactly this case, where the additional setter symbol breaks things for us, and I was going to report it today as well. 🙂

**Comment by nojaf** [comment]
Yeah, a single symbol that captures both get and set would indeed be the cleanest.
In my defence, my previous PR only highlighted an existing problem:
- Two symbols were always created.
- The setter was always ignored due to having the same name as the getter.

I did some investigation and it gets complicated after:

https://github.com/dotnet/fsharp/blob/723b1dc6310d773070804c0d258b2227c77d1ef8/src/Compiler/Checking/CheckDeclarations.fs#L4143-L4228

`SynMemberDefn.AutoProperty` gets transformed into three members:
- `SynMemberDefn.LetBindings` to store the field
- `SynMemberDefn.Member` for the getter
- `SynMemberDefn.Member` for the setter

The members eventually end up in:
https://github.com/dotnet/fsharp/blob/723b1dc6310d773070804c0d258b2227c77d1ef8/src/Compiler/Checking/CheckDeclarations.fs#L921-L948

And once `AnalyzeAndMakeAndPublishRecursiveValue` is called, they will be added to the Sinks in

https://github.com/dotnet/fsharp/blob/256c7b240e063217a51b90d8886d0b789ceb066e/src/Compiler/Checking/CheckExpressions.fs#L1362-L1368

Maybe 

https://github.com/dotnet/fsharp/blob/256c7b240e063217a51b90d8886d0b789ceb066e/src/Compiler/Checking/CheckExpressions.fs#L1351-L1360

can be extended, not to report the two members.

And afterwards, report the `AutoProperty` somewhere around https://github.com/dotnet/fsharp/blob/723b1dc6310d773070804c0d258b2227c77d1ef8/src/Compiler/Checking/CheckDeclarations.fs#L958

**Review by T-Gro — APPROVED** [review]
OK as a hotfix for the current tooltip behavior.

**Comment by auduchinok** [comment]
@nojaf Thanks for such a good analysis!

> Maybe ... can be extended, not to report the two members.

Or the getter and setter could be reported at the `get` and `set` ranges instead.

> And afterwards, report the AutoProperty somewhere around

That sounds great, but I'm not sure yet how easy that would be. 🙂

**Comment by nojaf** [comment]
> Or the getter and setter could be reported at the get and set ranges instead.

Yeah, but when you have `member val Foo = "bla" with get, set`, if `get` and `set` correspond to the members, you do want to have some symbol for `Foo` right?

> That sounds great, but I'm not sure yet how easy that would be. 🙂

Yeah, got somewhere in https://github.com/dotnet/fsharp/pull/15589 but it is a can of worms for sure.

**Comment by auduchinok** [comment]
> Yeah, but when you have member val Foo = "bla" with get, set, if get and set correspond to the members, you do want to have some symbol for Foo right?

Yes, something like [`FSharpMemberOrFunctionOrValue(cenv, P pinfo, Item.Property (pinfo.PropertyName, [pinfo]))`](https://github.com/dotnet/fsharp/blob/4c0eb4d1794b46274e3837adfaac5626215135ee/src/Compiler/Symbols/Symbols.fs#L667).

**Pull request merged**
