### PR TITLE
Remove IVTs to legacy language service

### PR DESCRIPTION
**Pull request by cartermp**
Moved the dead code paths to no longer be IVT into FSharp.Compiler.Private.

### CODE REVIEW

**Comment by cartermp** [comment]
I have no clue what the ever loving hell this test does and why but it's failing: https://github.com/dotnet/fsharp/blob/027e8c9b58bba85afef26a2869f2c805b20bb427/vsintegration/tests/UnitTests/LegacyLanguageService/Tests.LanguageService.General.fs#L106-L120

**Comment by cartermp** [comment]
I modified the code to use the public API for the information it needs and removed the test in question. I can't for the life of me understand the value in that test.

**Comment by KevinRansom** [comment]
@cartermp Well, the tests are a sort of cheap evaluation of whether public types have been added or removed from those assemblies.  If public types are removed its potentially a breaking change, if they are added it's potentially an unintentional increase in surface are.

But that test does the job in a pretty bad way.  And probably adds little value.

**Comment by cartermp** [comment]
Yeah, in this case I don't think they're of value here because the primary things they're testing are now dead code paths anyways

**Pull request merged**
