### PR TITLE
Support Ctrl-W and Ctrl-U shortcuts in fsi

### PR DESCRIPTION
**Pull request by Swoorup**
First PR here: 

Fixes https://github.com/dotnet/fsharp/issues/10299

fsi-ctrl-uw-shortcuts

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=10370) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=10370) before we can accept your contribution.<br/><br/>:x: Swoorup [sign now](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=10370)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/fsharp?pullRequest=10370) it.</sub>

**Comment by vzarytovskii** [comment]
> First PR here: 
> 
> 
> 
> Fixes https://github.com/dotnet/fsharp/issues/10299
> 
> 
> 
> fsi-ctrl-uw-shortcuts
> 
> 
@Swoorup 
That's really awesome addition, thank you. Do you think it is worth it to have only spaces as delimiters, or some others as well (I am thinking dots and dashes)? What do you think?

**Comment by Swoorup** [comment]
@vzarytovskii Thats a good idea. 

I emulated the functionality based on my current shell [fish](https://fishshell.com/). I noticed at least by default python shell, fish and bash support only spaces as the delimiter. 

I noticed vim has slightly different behaviour with dots and dashes than spaces, i.e cut word has the following behaviour on the input text

```
in:123<spc><spc><spc>
out:

in:123---
out:123

in:123...
out:123

in:-123
out:-

in:.123
out:.

in:123.-.-
out:123
```

Which seems reasonable. It appears with all non-word characters. But not sure worth the complexity atm. It would be nice to have a block based parsing, i.e input characters are immediately parsed into some sort of syntax tree, so that it's possible to have immediate syntax highlighting, and more contextual information to perform operations like these.

**Review by KevinRansom — APPROVED** [review]
NIce.

Thank you

**Comment by vzarytovskii** [comment]
@Swoorup yeah, that makes sense. Thanks you a lot for that contribution!

**Review by vzarytovskii — APPROVED** [review]

**Pull request merged**
