### PR TITLE
Remove some needless uses of ToString() in FSharp.Editor

### PR DESCRIPTION
**Pull request by cartermp**
Noticed in the completion provider that we did some needless ToString()'ing and then found more of that

### CODE REVIEW

**Comment by KevinRansom** [comment]
@cartermp 
````
Fails : ShouldGiveSignatureHelpAtCorrectMarkers [35 s]
````

**Comment by cartermp** [comment]
Heh, it turns out that this uncovered a bug that tests missed because the backtracking to find an adjusted column was too permissive. This work found the bug.

**Comment by cartermp** [comment]
nuget failure

**Comment by cartermp** [comment]
Bugger, looks like there is indeed an issue with these tests. Unfortunately they are so difficult to decipher

**Comment by cartermp** [comment]
I have confimed that signature help works as well as it does without these changes manually, might need to tweak tests ...

**Review by TIHan — APPROVED** [review]
Apart from the one failing tests, this looks great.

**Comment by cartermp** [comment]
This whole damn test that's failing is absolutely wild. I might just revert the one part that's causing it to fail, since I'm honestly at a loss as to why it's failing. I'd need to rewrite these tests to be debuggable too, since the one test case is actually like 40 test cases and only the ones to do with type provider static parameters are failing.

**Pull request merged**
