### PR TITLE
Added support for #warnon pragma

### PR DESCRIPTION
**Pull request by 71**
This PR adds support for the `#warnon` pragma.

It has the exact same syntax as the `#nowarn` pragma, and simply re-enables the previously disabled warnings.

For instance, the following file...

```fsharp
#nowarn "25"
let f a = match a with [] -> 0
#warnon "25"

let g a = match a with [] -> 1

printfn "foo: %d" (f [])
```

... reports **nothing** when compiled without the patch, and the following warning with the patch.

```
foo.fs(8,17): warning FS0025: Incomplete pattern matches on this expression. For example, the value '[_]' may indicate a case not covered by the pattern(s).
```

This is more of a "conversation-starting" PR. I understand that documentation and tests will probably need to be added, but I'd like to get this work out there.

### CODE REVIEW

**Comment by dsyme** [comment]
Just to check, is this the same design as C#?

**Comment by 6A** [comment]
My goal with this PR is to mimick the `#pragma warning restore` directive in C#, if that's what you mean. However it can't re-enable all warnings, unlike the `#pragma warning restore` with no warning numbers in C#.

**Comment by cartermp** [comment]
@71 Sorry for not getting back on this - we're auditing some of the older PRs. Is this something you'd still like to pursue? Unfortunately there has been sigificant refactoring in the relevant files so this work would likely need to be redone. Additionally, some tests would be required (they can be added here, perhaps under a new folder callged `Pragmas`: https://github.com/dotnet/fsharp/tree/master/tests/fsharp/Compiler/Conformance)

**Comment by abelbraaksma** [comment]
@cartermp, though I wasn't the originator here, I have been playing with implementing this, as there's been so much requests for it.

I wasn't aware if this PR. If @71 likes to pursue this, that'd be great, otherwise, I'll offer to pick it up. Though the original lang suggestion still needs an RFC, I think.

**Comment by cartermp** [comment]
@abelbraaksma if you'd like, definitely feel free to fork against @71's fork and resubmit a PR. This one can be closed out in favor of that, so long as the original commits are still retained.

This should ideally have an RFC but since it's more of a compiler feature than a language feature (IMO) it might be fine without. I consider this to be similar to adding a new error message, which we don't typically add RFCs for unless they come with a larger feature.

**Comment by 71** [comment]
@abelbraaksma feel free to submit your own PR! As much as I find it interesting to play with the compiler, I won't have the time to work on this before a while.

If you don't have time / no longer want to tackle it I might work on it later anyway, but not before long.

**Comment by cartermp** [comment]
Thanks for getting back @71 - I'll close this out. @abelbraaksma if you're interested, please do submit a PR and we'll go from there!

**Pull request closed without merging**
