### PR TITLE
Prevent `dotnet` process spawn on compiler startup

### PR DESCRIPTION
**Pull request by dsyme**
Fixes https://github.com/dotnet/fsharp/issues/13960

@vzarytovskii I think searching for `"Microsoft.NETCore.App.Ref"` in the directory name is adequate for now.

I did a performance comparison and on my laptop running:

    C:\GitHub\dsyme\fsharp\artifacts\bin\fsc\Release\net7.0\fsc.exe @out.args

Before: 2.9s
After: 2.7s

The proportional effect is greater if crossgen is active and you can actually measure the effect in the SDK today, as the process spawn only kicks in if non-default assemblies are referenced, e.g. 

1. Make an `out.args` for a simple project referencing `Newtonsoft.Json`

2. `dotnet "\Program Files\dotnet\sdk\7.0.100-rc.1.22431.12\FSharp\fsc.dll" @out.args --times`

3. Then remove this reference from the list and repeat

         -r:C:\Users\donsy\.nuget\packages\newtonsoft.json\13.0.1\lib\netstandard2.0\Newtonsoft.Json.dll

Before: consistently 1.7s
After: consistently 1.5s

### CODE REVIEW

**Comment by dsyme** [comment]
@vzarytovskii This is ready

**Comment by baronfel** [comment]
Longer term it might be nice if the SDK surfaced some way of resolving named Frameworks from the current install location. We already ship resolvers for finding installed and usable SDKs, and I think the next step of "give me framework X from SDK Y" would enable use cases for scripting (like #r "framework: ...") that we've talked about here for a while.

**Comment by dsyme** [comment]
@vzarytovskii @KevinRansom ping :)

**Review by vzarytovskii — APPROVED** [review]

**Review by T-Gro — APPROVED** [review]

**Comment by vzarytovskii** [comment]
@KevinRansom can you please take a look at it?

**Review by KevinRansom — APPROVED** [review]

**Pull request merged**
