### PR TITLE
Split CompileOps.fs into sensible chunks

### PR DESCRIPTION
**Pull request by dsyme**
CompileOps.fs and CompilerOptions.fs were a big and complex beast - 6000 lines for the former.  

This finally takes the plunge to split it into related chunks, each much smaller and easier to make progress on.  

* `CompilerConfig.fs/fsi` - TcConfig and TcConfigBuilder
* `CompilerImports.fs/fsi` - TcImports and assembly resolution
* `CompilerDiagnostics.fs/fsi` - preparing, filtering and emitting diagnostics
* `ParseAndCheckInputs.fs/fsi` - parsing and checking one or a group of inputs
* `ScriptClosure.fs/fsi` - computing the script closure including resolving dependency managers
* `CompilerOptions.fs/fsi` - the big tables of options
* `OptimizeInputs.fs/fsi` - optimize and ilxgen for a collection of inputs

There is never a right time to do things like this unfortunately.  Let's get this in once the dust has settled on dev16.8.  I'm presuming I'll have to look after merge conflicts arising

There is no functional change in this PR

image

### CODE REVIEW

**Comment by dsyme** [comment]
This is ready.  

I checked and this won't conflict with any changes in dev16.8.  So I think we can merge this whenever we like.

**Review by TIHan — APPROVED** [review]
This makes sense to me, but we should get this is in soon as to avoid any conflicts.

@KevinRansom you ok with this?

**Comment by KevinRansom** [comment]
Oh great, I'm not going to know where anything is anymore :-)

**Review by KevinRansom — APPROVED** [review]
Sure ... 
having TcConfig / TcConfigBuilder out in CompilerConfig is certainly an improvement.

**Pull request merged**
