### PR TITLE
Improve AsyncMemoize tests

### PR DESCRIPTION
**Pull request by 0101**
Don't rely on arbitrary time delays to make the async tests work. This should hopefully avoid any flakiness.

### CODE REVIEW

**Review by vzarytovskii — APPROVED** [review]

**Comment by 0101** [comment]
Well now there's a bunch of random looking cancellation test failures. @auduchinok did you see something like this?

**Comment by 0101** [comment]
> @0101 I wasn't been able to look into it yet, but I think I've seen something similar when tried to update our FCS fork. Could you check if reverting #16348 in this branch will have any effect?

I put it in a separate branch https://github.com/dotnet/fsharp/pull/16536

**Comment by 0101** [comment]
So the tests seem to be passing with https://github.com/dotnet/fsharp/pull/16348 reverted (here: https://github.com/dotnet/fsharp/pull/16536) 

But all the failures also seem to be in my newly added code in Transparent Compiler. So I feel like I must be doing something wrong there with the thread static cancellation token.

**Comment by majocha** [comment]
I'm rather late to the party but I don't understand how can a `[<ThreadStatic>]` `Cancellable.Token` work in async context. There is no guarantee we'll stay on the same thread when executing a computation?

**Comment by 0101** [comment]
I think it's only expected to work within `node` since there we make sure we move it over to a new thread when we switch.

**Comment by vzarytovskii** [comment]
> I'm rather late to the party but I don't understand how can a `[<ThreadStatic>]` `Cancellable.Token` work in async context. There is no guarantee we'll stay on the same thread when executing a computation?

It's made for node builder, where we re-wrap thread static info (as we do with logger, etc).

**Comment by 0101** [comment]
> So the tests seem to be passing with #16348 reverted (here: #16536)
> 
> But all the failures also seem to be in my newly added code in Transparent Compiler. So I feel like I must be doing something wrong there with the thread static cancellation token.

Actually no, the failures don't only happen in the new code, since the experimental flag is not set in CI most of the tests are running with original BackgroundCompiler. 

I still don't understand why it happens, I didn't find any computations that aren't guarded by `Cancellable.UsingToken`. 

But still we should probably do the [revert](https://github.com/dotnet/fsharp/pull/16536)

**Review by T-Gro — APPROVED** [review]

**Comment by 0101** [comment]
The fixes got included with https://github.com/dotnet/fsharp/pull/16536

**Pull request closed without merging**
