### PR TITLE
Fix potential OCE in graph processing

### PR DESCRIPTION
**Pull request by majocha**
Surveying the code base for unobserved background jobs that may throw I noticed this `Async.Start` that takes a cancellation token but is not effectively catching cancellations. Theoretically it is possible that the cancellation occurs before `processNode` starts, resulting in an unhandled OperationCancelledException.

This could potentially impact Transparent Compiler (?), I might have also observed it when running tests concurrently in #17872.

### CODE REVIEW

**Comment by psfinaki** [comment]
So the failing [test](https://github.com/dotnet/fsharp/blob/8b0900c78e0fa1521ab06af06af410d8f7400414/tests/FSharp.Core.UnitTests/FSharp.Core/Microsoft.FSharp.Control/Cancellation.fs#L236) actually seems to be related... I am trying to understand what it's trying to achieve and test, it might be that it builds on top of a hack.

@0101 maybe you have an idea from the top of your head - given the TC context and your recent OCE investigations :)

**Comment by psfinaki** [comment]
Oh I see you're addressing this in a sibling [PR](https://github.com/dotnet/fsharp/pull/17923), sorry, reviewing this in order :D

**Comment by majocha** [comment]
> Oh I see you're addressing this in a sibling [PR](https://github.com/dotnet/fsharp/pull/17923), sorry, reviewing this in order :D

Yes I should mention it here, my guess is that failing test is unrelated, I just introduced flakiness recently and it's coincidental that it's about cancellation.

**Comment by jj-548** [comment]
I've seen Rider hanging in a situation that looks like could be caused by this issue - indefinitely waiting for some FCS work that never happens, according to the debugger.

It's a ~400 projects mixed C# & F# solution with parallel projects analysis enabled, so I can imagine race conditions are more likely than in smaller codebases.

So I'm definitely cheering for this to get merged 👍

**Review by 0101 — APPROVED** [review]

**Comment by 0101** [comment]
> I've seen Rider hanging in a situation that looks like could be caused by this issue - indefinitely waiting for some FCS work that never happens, according to the debugger.
> 
> It's a ~400 projects mixed C# & F# solution with parallel projects analysis enabled, so I can imagine race conditions are more likely than in smaller codebases.
> 
> So I'm definitely cheering for this to get merged 👍

Is Rider using Graph checking for analysis somehow?

**Review by psfinaki — APPROVED** [review]

**Comment by vzarytovskii** [comment]
> > I've seen Rider hanging in a situation that looks like could be caused by this issue - indefinitely waiting for some FCS work that never happens, according to the debugger.
> 
> > 
> 
> > It's a ~400 projects mixed C# & F# solution with parallel projects analysis enabled, so I can imagine race conditions are more likely than in smaller codebases.
> 
> > 
> 
> > So I'm definitely cheering for this to get merged 👍
> 
> 
> 
> Is Rider using Graph checking for analysis somehow?

Is it plumbed in checker at all?

**Comment by vzarytovskii** [comment]
> > > Is it plumbed in checker at all?
> 
> 
> 
> Only through Transparent Compiler. 

Yeah. I don't know if Rider exposes it. Probably @auduchinok should know.

**Comment by majocha** [comment]
Now I think my analysis here is rubbish, because `Async.Start` does not throw on cancellation.
I'll try to repro the issue properly and see if this change does anything at all or was it all placebo.

**Pull request merged**
