### PR TITLE
Fix 9369 - index setters with param array

### PR DESCRIPTION
**Pull request by dsyme**
It's possible to have an indexed setted property with param arrays - this is used by TorchSharp and other tensor libraries

https://github.com/dotnet/fsharp/issues/9369

### CODE REVIEW

**Comment by dsyme** [comment]
Hmmm CI not triggering?

**Comment by dsyme** [comment]
Sigh
```
  Error Message:
   System.ObjectDisposedException : Cannot write to a closed TextWriter.
```

**Comment by vzarytovskii** [comment]
> Sigh
> 
> ```
> 
>   Error Message:
> 
>    System.ObjectDisposedException : Cannot write to a closed TextWriter.
> 
> ```
> 
> 

@KevinRansom shall we for now merge the fix (the single thread)?

**Review by TIHan — APPROVED** [review]

**Review by KevinRansom — CHANGES_REQUESTED** [review]
Are we treating this as an interop bug, or a language feature?  It seems like a feature and should be under a language switch?

What do you think?

**Comment by dsyme** [comment]
> Are we treating this as an interop bug, or a language feature? It seems like a feature and should be under a language switch?

I feel it's a bug fix, it was always intended to work.

**Review by KevinRansom — APPROVED** [review]

**Comment by dsyme** [comment]
Reminds me to add testing for

* static param array indexers
* extension param array indexers
* equivalents defined in C#

**Review by vzarytovskii — APPROVED** [review]

**Pull request merged**
