### PR TITLE
Fix and refactor FCSBenchmarks

### PR DESCRIPTION
**Pull request by safesparrow**
Major cleanup and fixes of the benchmarks in `tests/FCSBenchmarks` projects.

## Changes in all benchmarks
* All benchmarks should now build and work
* Use [BDN's console API](https://benchmarkdotnet.org/articles/guides/console-args.html) to make the benchmarks more flexible (end-user can tweak the config without having to change code and build)
* General cleanup

### Changes in the notebook (`runner.ipynb`)
* Fix it
* Fix the commit-based benchmark which should now work at least with recent versions (it might still fail when building an old codebase)
* Replace multiple projects + String.Replace with a single project using MSBuild properties
* Refactor/cleanup
* Store results in JSON instead of CSV, put artifacts in separate directories (inside `.artifacts/`, read them at the end

### Changes in the BDN benchmark (now renamed to `HistoricalBenchmark.fsproj`)
* Refactor
* Add it to `VisualFSharp.sln`
* Add it to the `InternalsVisibleTo` list in `FSharp.Compiler.Service`

## Changes in FSharp.Compiler.Benchmarks
* Deduplicate some of the code by reusing code from `HistoricalBenchmark`
* Now depends on `HistoricalBenchmark` mainly to reuse the `SingleFileCompiler`. This might be somewhat controversial - `HistoricalBenchmark` needs to support old versions of FCS to allow doing a comparison, which can be limiting. However, currently this isn't a problem - once it is, we could either duplicate the code again or extract the shared bits to a separate project.

### CODE REVIEW

**Comment by vzarytovskii** [comment]
> @vzarytovskii Would you be able to review? Thanks!

Thanks for changes, they look good will do more thorough review tomorrow, once at my laptop :)

One thing which comes to mind is to add benchmarks to `FSharp.sln` too (and maybe ``FSharp.Compiler.Service.sln`, @auduchinok  wdyt?). Some people are not using the `VisulaFSharp.sln`.

**Comment by auduchinok** [comment]
> One thing which comes to mind is to add benchmarks to FSharp.sln too (and maybe ``FSharp.Compiler.Service.sln, @auduchinok wdyt?). Some people are not using the VisulaFSharp.sln`.

Yes, thanks. We only use the FSharp.Compiler.Service solution, so it would be useful.

**Comment by safesparrow** [comment]
@vzarytovskii Let me know if this is something worth merging and any changes you'd like to see :)

**Comment by safesparrow** [comment]
I did a few changes:
- moved all the logic from `BenchmarkComparison/runner.ipynb` into a new F# project `HistoricalBenchmark.Runner`
- added a few customisations
- made the benchmarking more robust and easier to run (one line of code in the notebook)

@vzarytovskii @KevinRansom Would it be possible to get the changes reviewed? If this is not a change you are willing to consider at this time that's fine - but I would be keen to know whether there is any point spending more time on this👍

**Review by vzarytovskii — APPROVED** [review]

**Comment by vzarytovskii** [comment]
> I did a few changes:
> 
> * moved all the logic from `BenchmarkComparison/runner.ipynb` into a new F# project `HistoricalBenchmark.Runner`
> * added a few customisations
> * made the benchmarking more robust and easier to run (one line of code in the notebook)
> * added three sample results
> 
> @vzarytovskii Vlad Zarytovskii FTE @KevinRansom Kevin Ransom FTE Would it be possible to get the changes reviewed? If this is not a change you are willing to consider at this time that's fine - but I would be keen to know whether there is any point spending more time on this👍

It looks great, sorry it was taking long time, we were a bit preoccupied with some other stuff :)

**Pull request merged**
