### PR TITLE
Repo cleanup

### PR DESCRIPTION
**Pull request by vzarytovskii**
As discussed previously, removing tests we never run (i.e. they don't run in CI or part of solution), some stress tests which we haven't touched in years, moving some examples to docs.

This will allow things like Copilot/Copilot workspace not try to index those or take into account. Also, won't trigger some scanners in CI.

### CODE REVIEW

**Review by KevinRansom — APPROVED** [review]

**Review by T-Gro — APPROVED** [review]

**Comment by brianrourkeboll** [comment]
@vzarytovskii Did you mean to delete TheBigFileOfDebugStepping.fsx?

If so, this part of the documentation should be updated:

https://github.com/dotnet/fsharp/blob/18315fa1ce0f09fcf3b22bc79dbba00fe1187a31/docs/debug-emit.md?plain=1#L13

**Comment by vzarytovskii** [comment]
I did, yeah. If it's used, we can restore it

**Comment by brianrourkeboll** [comment]
> If it's used, we can restore it

I was using it to manually verify debugging for my changes in #17067, and it did help me notice a couple bugs. It's not perfect, but it seems worth keeping around unless we have (and can document) a better alternative.

I'll restore it in that PR for now.

**Comment by vzarytovskii** [comment]
> > If it's used, we can restore it
> 
> 
> 
> I was using it to manually verify debugging for my changes in #17067, and it did help me notice a couple bugs. It's not perfect, but it seems worth keeping around unless we have (and can document) a better alternative.
> 
> 
> 
> I'll restore it in that PR for now.

Thanks!

**Pull request merged**
