### PR TITLE
use shipped FSharp.Core when using FSharp.Compiler.Service.sln

### PR DESCRIPTION
**Pull request by dsyme**
Fixes https://github.com/dotnet/fsharp/issues/12142

cc @KevinRansom @auduchinok

### CODE REVIEW

**Comment by auduchinok** [comment]
@dsyme Thanks a lot!

**Review by vzarytovskii — APPROVED** [review]

**Comment by baronfel** [comment]
How does this change interact with preview features like the resumable code builders, which may not be in the currently published FSharp.Core? I was expecting there to be failures or mismatches there.

**Comment by dsyme** [comment]
> How does this change interact with preview features like the resumable code builders, which may not be in the currently published FSharp.Core? I was expecting there to be failures or mismatches there.

The code of FCS currently builds without using these features

Note this is only when explicitly building src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.sln, which is not a mainline path, just a developer-friendly path

**Comment by auduchinok** [comment]
@dsyme This doesn't seem to fix #12142, and the error is still there in the tooling. The error in #12142 comes from a recent change in FSharp.Core that hasn't been published in a stable FSharp.Core version yet. #11888 changed both FSharp.Core and FCS code, which made FCS rely on a non-stable-published-yet FSharp.Core version.

**Comment by auduchinok** [comment]
It seems wrong that FCS solution actually builds despite the errors in the tools. It seems it uses another FSharp.Core reference for build.

**Comment by dsyme** [comment]
> This doesn't seem to fix #12142, and the errors are still there in the tooling. The error in #12142 comes from a recent change in FSharp.Core that hasn't been published in a stable FSharp.Core version yet

Really?  My impression is that this PR means that when using FSharp.Compiler.Service.sln, a public FSharp.Core is now referenced.   Can you send build logs and/or any other information showing the references being used in the IDE?  Also is the IDE Rider, and does that set SolutionName correctly when interpreting the project files?  Maybe you need to do a flush and restore?

**Comment by auduchinok** [comment]
> Really? My impression is that this PR means that when using FSharp.Compiler.Service.sln, a public FSharp.Core is now referenced. 

This is the exact source of the issue. The current FSharp.Core ([5.0.2](https://github.com/dotnet/fsharp/blob/ffbc0d410c776ad108811dcc9f01f3185e9a6e92/eng/Versions.props#L38) doesn't include changes from #11888 yet, but FCS already uses them.

**Comment by dsyme** [comment]
I see, so this passes because it doesn't build using FSharp.Compiler.Service.sln

We should 
1. add a CI job to build that solution.  
2. put in #if of some kind to allow building against the shipped FSharp.Core.

**Comment by auduchinok** [comment]
> Also is the IDE Rider, and does that set SolutionName correctly when interpreting the project files? Maybe you need to do a flush and restore?

The issue occurs in both Visual Studio and Rider for me. I've just tried to `git clean` and run `build.cmd` just in case something would behave differently, but it's the same, as I'd expect.

**Comment by dsyme** [comment]
> I've just tried to git clean and run build.cmd just in case something would behave differently, but it's the same, as I'd expect.

Yeah, you'll only get it on an explicit "msbuild src\fsharp\FSharp.Compiler.Service\FSharp.Compiler.Service.sln"

**Comment by vzarytovskii** [comment]
> I see, so this passes because it doesn't build using FSharp.Compiler.Service.sln
> 
> 
> 
> We should 
> 
> 1. add a CI job to build that solution.  
> 


We do build it on Windows, Linux and macOS on CI.

https://github.com/dotnet/fsharp/blob/63bef2c067601c6174a9b92aeac8004a8f5bfeca/azure-pipelines.yml#L395

**Comment by auduchinok** [comment]
It seems this change does a wrong thing? The preview package is exactly what should've been used (the preview of 5.0.3, needed for the recent FSharp.Core changes) instead of the published release package (5.0.2).

**Pull request merged**
