### PR TITLE
Removing reactor-queue dependencies

### PR DESCRIPTION
**Pull request by TIHan**
As part of 10292 we will do all of these:

* [x] All of the FSharpCheckFileResults operations will no longer use the Reactor and hence no longer by async.  
* [x] The four operations `Get*UsesOfAllSymbolsIn*`  were only async to support cancellation. For clarity these will no no longer by async and instead accept an optional cancellation token
* [x] `userOpName` is removed from all the operations which are no longer async (it is there for async causality tracing)
* [x] `StructuredDescriptionTextAsync` and `DescriptionTextAsync` no longer used the Reactor thread. They are marked as obsolete, and instead synchronous `StructuredDescriptionText` and `DescriptionText` should be used
* [x] The caches `scriptClosureCache` and `incrementalBuildersCache` are now usable from any thread
* [x] The optional argument `hasTextChangedSinceLastTypecheck` is removed from FSharpChecker API as it no longer needed by Visual F# Tools since 2017 rewrite 
* [x] The optional argument `textSnapshotInfo` is removed from FSharpChecker API as it only existed to pass back to `hasTextChangedSinceLastTypecheck`
* [x] Allows the IncrementalBuilder cache to be used on any thread. This is some minor preliminary work that needs to be done in order to make FCS less reactor-queue dependent.

### CODE REVIEW

**Comment by dsyme** [comment]
@TIHan as expected/discussed, one legacy test that relied on the "hasTextChangedSinceLastTypecheck" in the old language service no longer passes, I've simply removed the test

**Comment by TIHan** [comment]
Before we merge, we need to merge these first: https://github.com/dotnet/fsharp/pull/10310 and https://github.com/dotnet/fsharp/pull/10308
Those PRs, while isolated, are necessary to ensure safety.

**Review by cartermp — CHANGES_REQUESTED** [review]
Putting up a block for the other PRs to be merged

**Comment by dsyme** [comment]
@TIHan conflicts need to be resolved

**Comment by dsyme** [comment]
> @TIHan conflicts need to be resolved

I've done this now.  Might need to patch up some argument names

**Comment by dsyme** [comment]
> Before we merge, we need to merge these first: #10310 and #10308. Those PRs, while isolated, are necessary to ensure safety.

These have now been merged and integrated with this PR.

**Review by dsyme — APPROVED** [review]

**Review by cartermp — APPROVED** [review]

**Pull request merged**
