### PR TITLE
Further work on FCS API

### PR DESCRIPTION
**Pull request by dsyme**
This does some work (mostly to do with Range and Pos) to slowly move the FCS API towards a more intentional design surface area that we can iterate on and review and stabilise.

As background (included in a design doc in this PR), the "intended" FCS API is the parts under the namespaces

* FSharp.Compiler.SourceCodeServices.*
* FSharp.Compiler.Text.*
* FSharp.Compiler.TextLayout.*

These sections are generally designed with F#/.NET design conventions (e.g. types in namespaces, not modules, no nesting of modules etc.) and we will continue to iterate to make this so.

In contrast, the public parts of the compiler directly under `FSharp.Compiler.*` and `FSharp.AbstractIL.*` are
"incidental" and not really designed for public use apart from the hook for Jet Brains Rider
(Aside: In theory all these other parts could be renamed to FSharp.Compiler.Internal though there's no need to do that right now).   These internal parts tend to be implemented with the "module containing lots of stuff in one big file" approach for layers of the compiler.

The rationale here is that we eventually scrutinize everything under `FSharp.Compiler.SourceCodeServices.*` carefully for API design.

Because of this, I've been moving some "meant to be public" types from `FSharp.Compiler.XYZ` to `Text`.   This was done for a few types in the last FCS PR. In this one we do:

* `FSharp.Compiler.Range.range` --> `FSharp.Compiler.Text.Range` (with `range` abbreviation)
* `FSharp.Compiler.Range.pos` --> `FSharp.Compiler.Text.Pos` (with `pos` abbreviation)

The `Range` module is split into `Range` and `Pos`. 

This PR also 

* updates the baseline generator for FCS to only show declared members, and not inherited members, which makes the baseline tighter.

* replaces all uses of `__.` by `_.` throughout the whole codebase.

* adds a couple of signature files

### CODE REVIEW

**Comment by baronfel** [comment]
For what it's worth, we use the Range and Pos module functions quite a lot in FSAC because we have to map back and forth from LSP protocol positions and ranges (which have different indexing schemes and don't have an associated file path) to positions and ranges that the FCS APIs understand.  So I'd advocate for those to remain part of the FCS API and not necessarily relegated to FSharp.Compiler.

**Comment by auduchinok** [comment]
I agree with @baronfel, we have some similar usages too.

**Comment by dsyme** [comment]
> For what it's worth, we use the Range and Pos module functions quite a lot in FSAC because we have to map back and forth from LSP protocol positions and ranges (which have different indexing schemes and don't have an associated file path) to positions and ranges that the FCS APIs understand. So I'd advocate for those to remain part of the FCS API and not necessarily relegated to FSharp.Compiler.

OK This generally makes sense.  If you could list out what you use that would be great

**Comment by baronfel** [comment]
We use

# creation functions
* `Range.mkPos`
* `Range.mkRange`
* `Range.mkFileIndexRange` (though this one can possibly be replaced with `mkRange`, since the real goal here is to take a range and adjust either the start or end positions)
* `Range.unionRanges`
* `Pos.fromZ`

# comparison functions
* `Range.posEq`
* `Range.rangeContainsPos`
* `Range.rangeContainsRange`

# identity members
* `Range.rangeStartup` (for detecting if we're given a 'default'/nonsensical range from the compiler)

**Comment by dsyme** [comment]
@baronfel Thanks.  Yes we could put all this functionality on the types tbh (static members or instance members)

**Comment by dsyme** [comment]
@baronfel Could you give me a dump on which parts of FSharp.Compiler.PrettyNaming FsAutoComplete depends on? Thanks

@auduchinok Likewise for Rider?

thanks :)

**Comment by baronfel** [comment]
* `QuoteIdentifierIfNeeded`
* `KeywordNames`
* `TryChopPropertyName`
* `IsMangledOpName`
* `DemangleOperatorName`
* `IsOperatorName`
* `CompileOpName`

are what FSAC uses at the moment.

**Comment by cartermp** [comment]
Yeah, we use these in FSharp.Editor.dll as well. In theory this shouldn't be required, but the reality is that FCS APIs aren't nice enough to let us elide usage of this kind of stuff.

**Comment by auduchinok** [comment]
@dsyme It's this:
* `DecompileOpName`
* `FsiDynamicModulePrefix`
* `IsOperatorName`
* `QuoteIdentifierIfNeeded`
* `DecompileOpName`
* `CompileOpName`
* `IsMangledOpName`
* `IsActivePatternName`
* `IsInfixOperator`

**Comment by dsyme** [comment]
OK cool thanks all

> Yeah, we use these in FSharp.Editor.dll as well. In theory this shouldn't be required, but the reality is that FCS APIs aren't nice enough to let us elide usage of this kind of stuff.

Yes I just noticed FSharp.Editor doesn't have an IVT to FSHarp.COmpiler.Private.  That's great tbh, keeps us honest

I'll union the various requirements and internalise everything else

Looks like union (excluding FSHarp.Editor) is:
```
CompileOpName
DecompileOpName
DemangleOperatorName
FsiDynamicModulePrefix
KeywordNames
IsMangledOpName
IsOperatorName
IsActivePatternName
IsInfixOperator
QuoteIdentifierIfNeeded
TryChopPropertyName
```

**Comment by cartermp** [comment]
> Yes I just noticed FSharp.Editor doesn't have an IVT to FSHarp.COmpiler.Private.

Yes, this was intentional :) - I had to expose a few things to make that possible, but it's the right call overall.

We should have a think about better APIs for things like going to definition or finding a declaration list. The APIs for that are too low-level/difficult to work with and require every editor to access little utility functions like this and/or build their own to get access to other data that these APIs require.

**Comment by dsyme** [comment]
OK I've progressed this so the full surface area is now

* FSharp.Compiler.SourceCodeServices.* (analysis, compilation, tooling, lexing)
* FSharp.Compiler.Interactive.Shell.*  (scripting support)
* FSharp.Compiler.AbstractIL.*  (for ILAssemblyReader hook for Rider)
* FSharp.Compiler.SyntaxTree.*  (direct access to full untyped tree)

**Comment by cartermp** [comment]
@dsyme we should probably get some kind of documentation into an RFC as well, and let that serve as a process for using RFCs to drive new API work in FCS. For small additions it's probably not an issue, but eventually we'll want to do something about the fact that we expose our tree and that any additions to it will break all consumers. And we definitely want to make additions to it over time.

**Comment by dsyme** [comment]
@cartermp Yup.  Have started a discussion thread here: https://github.com/dotnet/fsharp/discussions/10786/  I think it's ok to do this one via discussion in this repo, no formal RFC needed

**Comment by dsyme** [comment]
> @TIHan I moved ISourceText from FSharp.Compiler.Text into FSharp.Compiler.SourceCodeServices ...

I thought this over and I'm undoing this.  FSharp.Compiler.Text is a perfectly good namespace and we should really move Range and Pos and other basic text related things into there

**Comment by dsyme** [comment]
This is ready now

**Comment by dsyme** [comment]
@cartermp @vzarytovskii @KevinRansom @TIHan approval requested to get this merged and integrated with other branch work. I know there are a lot of files touched but the vast majority are just a couple of lines of 'open' decl changes or entirely cosmetic.

**Review by vzarytovskii — APPROVED** [review]

**Review by KevinRansom — APPROVED** [review]

**Comment by dsyme** [comment]
Thanks @vzarytovskii @KevinRansom

**Pull request merged**
