### PR TITLE
Separator between member and type annotation interpreted as operator

### PR DESCRIPTION
**Pull request by edgarfgp**
Attempts to fix https://github.com/dotnet/fsharp/issues/4607

Current Behaviour: 

Screenshot 2023-09-05 103030

I'm learning my way through the Lexing and Parsing phase.

Updated `lex.fsl` and `LexFilter.fs` 

```fsharp

type IFoo<'T> =
    // Note:  extra space after >
    abstract member Bar<'T> : name: string -> unit

type IFoo<'T> =
    // Note: No extra space after > 
    abstract member Bar<'T>: name: string -> unit
```

With these changes you will be able to define `>:` as an operator that was not allowed before
```fsharp
let (>:) a b = a + b
```

- [x] See what CI says
- [x] Ask if there is a better way of doing this 
- [x] Move tests to an appropriate place

### CODE REVIEW

**Comment by edgarfgp** [comment]
@vzarytovskii Would it be an acceptable change to allow `>:`  to allow this to be parsed?

**Comment by vzarytovskii** [comment]
> @vzarytovskii Would it be an acceptable change to allow `>:`  to allow this to be parsed? 

Not sure, it's been deliberately deprecated, probably for a reason?

**Comment by edgarfgp** [comment]
> > @vzarytovskii Would it be an acceptable change to allow `>:`  to allow this to be parsed?
> 
> Not sure, it's been deliberately deprecated, probably for a reason?

From what I can see it seems that the combination of `>:` could potentially be used in the future in F# similar to `:>`, `:?>` etc.

Is that in the F# team plans? The error recovery and reporting for this scenario are currently bad

**Comment by vzarytovskii** [comment]
We don't have plans to use it, @dsyme might have some insight on why is it disallowed.

**Review by auduchinok — CHANGES_REQUESTED** [review]
The change to the token processing seems to be good from a glance, but I think that we should not enable new operators unless there's an approved language suggestion.

**Comment by edgarfgp** [comment]
> The change to the token processing seems to be good from a glance, but I think that we should not enable new operators unless there's an approved language suggestion.

Thanks for the review. I went through the lex.fsl rules and noticed that we are doing the same for, ie `<^ , </`, ^>` Also, the fact the `GREATER and COLON` already exist made this a relatively small change(Not having to add a new token `GREATER_COLON maybe`

This change will make `>:` no longer a potential reserved operator for the compiler and allow people to define an operator that was not allowed before.

But if have a better way of dealing with this specific issue, any suggestion is welcome :)

**Comment by auduchinok** [comment]
> But if you have a better way of dealing with this specific issue, any suggestion is welcome :)

We can produce an error about this operator during type checking.

**Comment by dsyme** [comment]
@edgarfgp This looks like a nice fix. It's so good to remove these glitches.

Regarding `>:` - AFAIK there are no plans to use this or other operators containing `:`

**Comment by edgarfgp** [comment]
By removing the check in for  `>:` at the `lex.fsl` and update `LexFilter.fs`, it fixes the issue but at the same times makes possible to define a custom operator `:>` or even allows to use this in almost every possible scenario that you can imagine  which is problematic. So to mitigate this I added a check for the `>:` during the type checking which cover most of the cases.
But  it is impossible  to check for cases where it was previously not allowed like:
```fsharp
module >: = ...
module `>:` = ...
type >: = ...

```

So I would love to get some feedback in the following questions:

- How bad would be allow `>:` to be used as custom operator.
- We could prevent this by adding a check  in parser level to check when `:>` is used as  `module, namespace, type` names ?

**Review by T-Gro — APPROVED** [review]

**Comment by T-Gro** [comment]
> By removing the check in for `>:` at the `lex.fsl` and update `LexFilter.fs`, it fixes the issue but at the same times makes possible to define a custom operator `:>` or even allows to use this in almost every possible scenario that you can imagine which is problematic. So to mitigate this I added a check for the `>:` during the type checking which cover most of the cases. But it is impossible to check for cases where it was previously not allowed like:
> 
> ```fsharp
> module >: = ...
> module `>:` = ...
> type >: = ...
> ```
> 
> So I would love to get some feedback in the following questions:
> 
> * How bad would be allow `>:` to be used as custom operator. ?
> * We could prevent this by adding a check  in parser level to check when `:>` is used as  `module, namespace, type` names ?

Since there are no plans for using it by F# itself, I do not see a reason for not allowing this as a custom operator.
(also the code would get simpler if typechecker would not have to actively guard against it...)

**Review by psfinaki — APPROVED** [review]
Good stuff. IMO one of the things that should just work and is otherwise confusing for newcomers. Thanks! :)

**Comment by edgarfgp** [comment]
(also the code would get simpler if typechecker would not have to actively guard against it...)

Yeah if we allowing this new operator i think we can avoid guarding against it in the typechecker

**Comment by edgarfgp** [comment]
Will update this PR to remove check in the typechecker

**Comment by T-Gro** [comment]
Good, looks cleaner now.

**Comment by T-Gro** [comment]
@edgarfgp :

The allowed custom operators are listed at https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/symbol-and-operator-reference/ .

Which is this .md document in the docs repo:
https://github.com/dotnet/docs/blob/main/docs/fsharp/language-reference/symbol-and-operator-reference/index.md

Could you please add it as well, since it is now an allowed pair? (and was not before)

**Comment by brianrourkeboll** [comment]
It looks like this new operator group `…>…:…` has the same precedence and associativity as any other infix operator starting with `>`, right?

**Pull request merged**
