### PR TITLE
Print VS info during the build

### PR DESCRIPTION
**Pull request by psfinaki**
Shamelessly stealing this from [Razor](https://github.com/dotnet/razor/commit/e43938f33fda169c38ba8134992322662033e2ce) - credits go to @ryanbrandenburg.

image

### CODE REVIEW

**Review by davidwengier — APPROVED** [review]

**Review by KevinRansom — APPROVED** [review]

**Comment by T-Gro** [comment]
Can we please do it outside of the slowest jobs?
Semantically, makes most sense to have it just in "testVs".

Ideally if it can be at least avoided for "testDesktop", because that is the slowest job of them all.

**Comment by psfinaki** [comment]
> Can we please do it outside of the slowest jobs?

It's really just 5 seconds - see the screenshot :) IMO not worth complicating the pipeline logic. We can split it later if we have more auxiliary steps like this.

**Review by abonie — APPROVED** [review]

**Comment by T-Gro** [comment]
So we need it 4 times or don't?
I don't think things would be more complicated if this would run e.g. automatically together with the testVs option (handled within the build script, where it already has its own code block in the powershell script).

**Comment by psfinaki** [comment]
Alright, I'll move things around a bit next time I'm here.

**Pull request merged**
