### PR TITLE
[WIP] Investigate SourceLink Linux Failures

### PR DESCRIPTION
**Pull request by BenVillalobos**
Reverting https://github.com/dotnet/fsharp/pull/8716 to repro and investigate https://github.com/dotnet/fsharp/issues/8726.

The issue is caused by MSBuild somehow not finding Microsoft.SourceLink.Common.props.

### CODE REVIEW

**Comment by brettfo** [comment]
@BenVillalobos invited you to be a maintainer on this repo to hopefully solve the access problems.

**Comment by BenVillalobos** [comment]
@brettfo thank you!

**Comment by BenVillalobos** [comment]
New pipeline build here: https://dev.azure.com/dnceng/public/_build/results?buildId=608634&view=results

**Comment by BenVillalobos** [comment]
@rainersigwald you seemed to hit the same issue that I'm getting now with those changes. Any idea what's up here? The regular .sln hasn't changed and the generated binlog doesn't seem super useful considering the error points to an unchanged file.

**Comment by rainersigwald** [comment]
Looks like it's trying to load a `.sln` as an XML-based project, which I have indeed seen before but don't know what's up right now. I also don't repro on my Mac running the sourcebuild script. So  ???

When we saw this before it was with MSBUILDNOINPROCNODE=1 which shouldn't be the case here.

**Comment by BenVillalobos** [comment]
Question from Marc: Are we double sure that this thing isn't being set in some way that we're not expecting?

**Pull request closed without merging**
