### PR TITLE
fix 11620

### PR DESCRIPTION
**Pull request by dsyme**
1. fixes regression #11620
2. re-enables `--optimize-` testing for some key test suites in tests/fsharp/core. If this was enabled we would have avoided this regression.  It used to be enabled a long time ago but somewhere along the way we dropped it.
3. fixes a bug with debug-code for `genericmeasures` that was revealed through (2)

Note that because of slow compilation speeds in repeatedly invoking the external `fsc` process in `tests/fsharp/core` tests this will add 5min or so to the execution of the `FSharpSuite` tests, depending on the speed of your system.  We should move this test suite to use in-memory compilation via FCS rather than compilation via the .NET SDK.

### CODE REVIEW

**Review by TIHan — APPROVED** [review]

**Comment by TIHan** [comment]
@jonsequitur should we try to put this fix into servicing for 16.10?

**Comment by dsyme** [comment]
Two failing tests:

```
2021-06-30T15:34:59.7336691Z   Failed innerpoly-GENERATED_SIGNATURE [2 s]
2021-06-30T15:56:12.3427046Z   Failed unitsOfMeasure [4 s]
```

I may separate out the fix for units of measure found via the additional testing

**Comment by dsyme** [comment]
@TIHan @jonsequitur I strongly expect we'll need this as a servicing fix.  The bug would have been caught by our existing test suite if the `--optimize-` code generation had been enabled for this chunk of our testing.  So I expect it will occur in user code in debug mode.

**Comment by dsyme** [comment]
@TIHan @jonsequitur  Will leave the servicing fix and branch propagation in your hands :)

**Pull request merged**
