### PR TITLE
Added `FSharpReferencedProject.CreateFromILModuleReader`

### PR DESCRIPTION
**Pull request by TIHan**
@auduchinok , this adds the API you requested to `FSharpReferencedProject`. Let me know if you want any changes.

### CODE REVIEW

**Comment by auduchinok** [comment]
@TIHan, thanks a lot! It seems it will work.

Do I get it right that invalidation in case of a change of a referenced module should be done by invalidating referencing projects by passing `FSharpProjectOptions` to `FSharpChecker`? If yes and if such module is referenced by many F# projects and/or is often updated, it's going to trigger many invalidations via `FSharpChecker`. Could it be easier to have mutable timestamps in referenced modules, so it would be checked the same way it's currently done for real assemblies and source files?

**Comment by TIHan** [comment]
> Do I get it right that invalidation in case of a change of a referenced module should be done by invalidating referencing projects by passing FSharpProjectOptions to FSharpChecker?

If a referenced module has changed, you can pass the updated `FSharpProjectOptions` with the updated referenced projects to a `FSharpChecker` parse/check file call - this will create a new incremental build internally, but the old one will probably be staying around in the cache until evicted.
In VS, we detect a reference change and we call `InvalidateConfiguration` and/or `ClearCache` from `FSharpChecker` before making anymore calls to `FSharpChecker`.

> Could it be easier to have mutable timestamps in referenced modules, so it would be checked the same way it's currently done for real assemblies and source files?
I wouldn't expose it as a mutable, but maybe passing a `unit -> DateTime` would be ok.

**Comment by auduchinok** [comment]
> I wouldn't expose it as a mutable, but maybe passing a unit -> DateTime would be ok.

Passing a function sounds good!

**Review by cartermp — APPROVED** [review]

**Comment by auduchinok** [comment]
@TIHan Thanks again, it looks really good now!

**Pull request merged**
