### PR TITLE
Revert "Fix parsing interpolated strings with unmatched braces"

### PR DESCRIPTION
**Pull request by abonie**
Reverts dotnet/fsharp#14182, since it causes https://github.com/dotnet/fsharp/issues/14757

### CODE REVIEW

**Comment by vzarytovskii** [comment]
Cc @baronfel we will backport it to 17.5 and release 201 for FCS.

@abonie could you please make sure it fixes the codefixes problem?

**Comment by abonie** [comment]
@vzarytovskii a code fix becomes available with the revert so it looks like it will fix the issue

**Pull request merged**
