### PR TITLE
Add missing instance member parameter code fix

### PR DESCRIPTION
**Pull request by cartermp**
Adds this 'lil boi

image

### CODE REVIEW

**Comment by smoothdeveloper** [comment]
Curious, can VS code fixer like this have a menu that would prompt for giving the name in case `_` only gets us half way there?

Not a big deal, but could be a valid addition to this code fixer.

Also, maybe one hardcoded option for `this` if this is a F# coding guideline / increase the "code I like" factor, when self reference is desired. VS code fixer is good place to suggest it.

I personally use `x` more than `this`, so I'd like an option to put my own name in the list as well.

**Comment by heronbpv** [comment]
Adding to @smoothdeveloper suggestion, is it possible to infer from context, as in, if other members in the type are using this/x/self/etc, suggest it, and "_" otherwise?

**Comment by cartermp** [comment]
That could be an interesting follow up, but it's not something I'm interested in taking on here.

**Review by brettfo — APPROVED** [review]

**Comment by KevinRansom** [comment]
@cartermp : it's interesting that the error message uses the suggestion

- ````x.Member(args) =````

and the codefixer adds: ````_.Member(args) =````

I can see arguments either way, but without contextual analysis, the error message should probably match the fixer and propose ````_.Foo()```` in this case.

What do you think?

**Comment by cartermp** [comment]
I will just switch to `x` for now. It's also used quite a bit as examples online.

**Pull request merged**
