### PR TITLE
Fix regression for FS0725

### PR DESCRIPTION
**Pull request by edgarfgp**
As discovered by [failing test]( https://github.com/fsharp/FsAutoComplete/pull/1153#issuecomment-1693079092 )  on `FsAutoComplete` in F# 8 we no longer show `FS0725` in cases where it is supposed to.

```fsharp

module Tests
    type A = { X: int }
    type B = B of int
    match None with
    | None 1 -> ()  // FS0725
    
    match None with
    | None (1, 2) -> () // FS0725
    
    match None with
    | None [] -> () // FS0725
    
    match None with
    | None [||] -> () // FS0725
    
    match None with
    | None { X = 1 } -> () // FS0725
    
    match None with
    | None (B 1) -> ()   // FS0725
    
    match None with
    | None (x, y) -> ()  // FS0725
    
    match None with
    | None false -> ()  // FS0725

    match None with
    | None x -> ()  //FS0725
    
    match None with
    | None _ -> ()  // F#7 this compiles. In F#8 this shows FS3548
    
    type C = | C
    
    let myDiscardedArgFunc(C _) = ()  // F#7 this compiles. In F#8 this shows FS3548
    
    let myDiscardedArgFunc2(C c) = ()  // FS0725

```

PR that introduced the regression https://github.com/dotnet/fsharp/pull/14055

### CODE REVIEW

**Comment by edgarfgp** [comment]
On a second look while working on this fix. I think for 

```fsharp
match None with
    | None x -> ()  // F#7 raises FS0725, F#8 this shows FS3548
    
    match None with
    | None x -> ()  // In F#8 this shows Warning FS3548 instead of Error FS0725 ? I think is should as it was in F#7
    
    type C = | C
    
    let myDiscardedArgFunc(C _) = ()  // F#7 this compiles. In F#8 this shows FS3548
    
    let myDiscardedArgFunc2(C c) = () // In F#8 this shows Warning FS3548 instead of Error FS0725 ? I think is should be as it was in F#7
```

Any thoughts? cc @vzarytovskii

**Comment by vzarytovskii** [comment]
> On a second look while working on this fix. I think for 
> 
> ```fsharp
>     match None with
>     | None x -> ()  // In F#8 this shows Warning FS3548 instead of Error FS0725 ? I think is should as it was in F#7
>     
>     type C = | C
>         
>     let myDiscardedArgFunc2(C c) = () // In F#8 this shows Warning FS3548 instead of Error FS0725 ? I think is should be as it was in F#7
> ```
> 
> Any thoughts? cc @vzarytovskii 

Yeah, I guess we shouldn't downgrade error to warning here.

**Comment by edgarfgp** [comment]
> > On a second look while working on this fix. I think for
> > ```fsharp
> >     match None with
> >     | None x -> ()  // In F#8 this shows Warning FS3548 instead of Error FS0725 ? I think is should as it was in F#7
> >     
> >     type C = | C
> >         
> >     let myDiscardedArgFunc2(C c) = () // In F#8 this shows Warning FS3548 instead of Error FS0725 ? I think is should be as it was in F#7
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any thoughts? cc @vzarytovskii
> 
> Yeah, I guess we shouldn't downgrade error to warning here.

Also the FS3548 error message does not really match what is happening here

**Comment by edgarfgp** [comment]
This is ready

**Review by vzarytovskii — APPROVED** [review]

**Review by T-Gro — APPROVED** [review]

**Pull request merged**
