### PR TITLE
Add examples for FSharp.Core.Result module functions

### PR DESCRIPTION
**Pull request by sharno**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=12148) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=12148) before we can accept your contribution.<br/><br/>:x: sharno [sign now](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=12148)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/fsharp?pullRequest=12148) it.</sub>

**Review by KevinRansom — APPROVED** [review]
Thank you for this pr

**Comment by dsyme** [comment]
I fixed up a few things.  Thank you for this!

**Review by dsyme — APPROVED** [review]

**Review by vzarytovskii — APPROVED** [review]

**Comment by dsyme** [comment]
The license/cla check was stuck for some reason

**Comment by sharno** [comment]
@dsyme 
Thank you!
Do I need to do anything on my side to fix the CLA check or is it good now?

**Comment by dsyme** [comment]
All done, thank you @sharno!  Please feel free to continue on with more examples :))

**Pull request merged**
