### PR TITLE
Reset FCS versions

### PR DESCRIPTION
**Pull request by KevinRansom**
Prepare to release fcs 39.0.0  --- breaking changes here:  https://github.com/dotnet/fsharp/commit/b23b2a0f99f12ece94c5ad89aabb9169d51091f3

### CODE REVIEW

**Comment by cartermp** [comment]
What's the diff between 38.0.2 and 38.0.3?

**Review by cartermp — CHANGES_REQUESTED** [review]
Putting up a block for now, is there an actual diff we're releasing? If this includes everything we merged from `main`, then this needs a major version bump because it incorporate several breaking changes.

**Comment by KevinRansom** [comment]
@cartermp, what breaks did we introduce to main?

**Comment by cartermp** [comment]
I'm looking, i suspect it was @dsyme's huge FCS changes

**Comment by KevinRansom** [comment]
> I'm looking, i suspect it was @dsyme's huge FCS changes

I updated the title with the commit of the breaks.

**Comment by baronfel** [comment]
This also has the de-async work that Phillip did months ago.

**Comment by cartermp** [comment]
No no, that was Don :)

**Review by cartermp — APPROVED** [review]

**Pull request merged**
