### PR TITLE
fire event when a value is bound at the root of a script evaluation

### PR DESCRIPTION
**Pull request by brettfo**
~~Also adds a function to get runtime type and value given a (root) identifier's name.~~

This is to enable a hypothetical "watch" or "locals" window in notebooks.

### CODE REVIEW

**Comment by abelbraaksma** [comment]
I may be OT here, but 'given an identifier's name' is not enough, as often the same names are in scope.

We'd need name and location in source to du that correctly.

Currently, in VS, the locals window works (it'll show multiple times the same name, but with different values), but hovering over a value doesn't. Neither the correct stack frame, nor the actual value belonging to the variable will be shown when names overlap.

**Comment by brettfo** [comment]
If using this in a debugger then yes, you'll need the location to properly map an identifier to a variable, but in a script context where this is to be used the source location is essentially line 1, column 0.  The added function _could_ have been implemented as `fsi.EvalExpression(variableName)` because the return value of that function is a type and value (and some other stuff), and perhaps it should have been done that way; I'm open to either approach, but I went with what's in this PR because that's how the value of the special variable `it` is extracted after a submission [here](https://github.com/dotnet/fsharp/blob/b757c165dcf28829f3431f3a678de1486b3b5db7/src/fsharp/fsi/fsi.fs#L1188-L1202) and I wanted to mirror that.

**Comment by KevinRansom** [comment]
@abelbraaksma 
the key is, this Api is retrieving top level values created in fsi, and so everything here is at the same scope, so existing values with the same name are hidden, and we currently have no scenarios for retrieving the hidden values.

So ... 
````
> let a =
-     let a = 1
-     let b = 3
-     a * b;;
val a : int = 3
````
Essentially, the only retrievable item is the top level a.
````
val a : int = 3
````
if a had been assigned a different value prior to this code submission then it is no longer retrievable.  And if a was defined twice in a single submission then it would generate a duplicate definition error.
````
> let a = 10
- let a =
-     let a = 1
-     let b = 3
-     a * b;;

  let a =
  ----^

stdin(21,5): error FS0037: Duplicate definition of value 'a'
````
I hope this helps.

**Comment by brettfo** [comment]
After speaking with @KevinRansom and finding a better place to add the relevant event, I've decided to remove the function `GetIdentifierValueType` simply because that information can already be retrieved from interactive with the `EvalExpression` that I mentioned above.

The benefit is that this PR is now much simpler.

Thanks to @ abelbraaksma and Kevin for the probing questions that led to a better implementation and design.

**Pull request merged**
