### PR TITLE
(Empty/NoEmpty)-bodied named computation expression should produce the same AST

### PR DESCRIPTION
**Pull request by edgarfgp**
## Description

Investigating if it is feasible to produce the same AST for (Empty/NoEmpty)-bodied named computation expression

[Fantomas](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQBCArojXABOYABQBKMMAgBfADrJ5vfkNESpABjDS8BSLAAeAByrJoFAC6CesENKA)

```fsharp
Builder () {  }

// Produces
SynExpr.App(
      flag = ExprAtomicFlag.NonAtomic,
      isInfix = false,
      funcExpr =
          SynExpr.App(
              flag = ExprAtomicFlag.NonAtomic,
              isInfix = false,
              funcExpr = SynExpr.Ident(Ident("Builder", R("(1,0--1,7)"))),
              argExpr = SynExpr.Const(constant = SynConst.Unit, range = R("(1,8--1,10)")),
              range = R("(1,0--1,10)")
          ),
      argExpr = SynExpr.Record(baseInfo = None, copyInfo = None, recordFields = [], range = R("(1,11--1,15)")),
      range = R("(1,0--1,15)")
  )
```

```fsharp
Builder () { 0 }

// Produces
SynExpr.App(
  flag = ExprAtomicFlag.NonAtomic,
  isInfix = false,
  funcExpr =
      SynExpr.App(
          flag = ExprAtomicFlag.NonAtomic,
          isInfix = false,
          funcExpr = SynExpr.Ident(Ident("Builder", R("(3,0--3,7)"))),
          argExpr = SynExpr.Const(constant = SynConst.Unit, range = R("(3,8--3,10)")),
          range = R("(3,0--3,10)")
      ),
  argExpr = SynExpr.ComputationExpr(hasSeqBuilder = false, expr = SynExpr.Const(constant = SynConst.Int32(0), range = R("(3,13--3,14)")), range = R("(3,11--3,16)")),
  range = R("(3,0--3,16)")
)
```

Fixes # (issue, if applicable)

## Checklist

- [ ] Test cases added
- [ ] Performance benchmarks added in case of performance changes
- [ ] Release notes entry updated

### CODE REVIEW

**Comment by brianrourkeboll** [comment]
Yeah, the only downsides to this approach I [noted in the RFC](https://github.com/fsharp/fslang-design/blob/3a46bc9342f4c2c38d09617b4d95909697e7b9d6/RFCs/FS-1144-empty-bodied-computation-expressions.md#update-the-parser) were:

>### Cons
>
>* The AST no longer represents what the user wrote. That is, the user wrote `builder { }`, not `builder { () }`, but the distinction between these is no longer possible to represent in the AST.
>* It may be difficult to foresee [all potential effects on and interactions with existing parsing behavior](https://github.com/dotnet/fsharp/issues/16448). At a glance, the parsing of expressions involving curly braces `{ … }` is already rather complex and involves multiple layers of non-obvious fallthroughs, etc.

**Comment by edgarfgp** [comment]
Thanks @brianrourkeboll. Im thinking that if we are already [re-writing](https://github.com/edgarfgp/fsharp/blame/935b796dc841b6346f655421bb791c1764ab1570/src/Compiler/Checking/Expressions/CheckExpressions.fs#L8546) the Untyped AST during type checking . We can do that in the parser so we avoid the rewrite part ?.

**Comment by brianrourkeboll** [comment]
> Im thinking that if we are already [re-writing](https://github.com/edgarfgp/fsharp/blame/935b796dc841b6346f655421bb791c1764ab1570/src/Compiler/Checking/Expressions/CheckExpressions.fs#L8546) the Untyped AST during type checking . We can do that in the parser so we avoid the rewrite part ?.

Yeah sorry, I didn't mean to imply that doing it in the parser was categorically bad. Those were just the reasons why I chose not to modify the parser in the RFC.

I see that Florian has a potential solution to https://github.com/fsprojects/fantomas/issues/3140 in https://github.com/fsprojects/fantomas/pull/3141, but if we wanted to be more explicit — and since it looks like AST consumers need to update their handling of this scenario regardless — another alternative would be [this](https://github.com/fsharp/fslang-design/blob/3a46bc9342f4c2c38d09617b4d95909697e7b9d6/RFCs/FS-1144-empty-bodied-computation-expressions.md#update-the-ast):

>## Update the AST
>
>In the untyped abstract syntax tree, update
>
>```fsharp
>SynExpr.ComputationExpr of hasSeqBuilder: bool * expr: SynExpr * range: range
>```
>
>to
>
>```fsharp
>SynExpr.ComputationExpr of hasSeqBuilder: bool * expr: SynExpr option * range: range
>```
>
>and update the parser to parse
>
>```fsharp
>builder { }
>```
>
>as
>
>```fsharp
>SynExpr.App
>    (ExprAtomicFlag.NonAtomic,
>      false,
>      SynExpr.Ident (Ident ("builder", m)),
>      SynExpr.ComputationExpr (false, None, m),
>      m)
>```
>
>### Pros
>
>* The AST actually more closely represents what the user wrote — _if_ their intent was to write the application of a computation expression builder value to an empty computation expression body. (See also cons below.)
>* Minimal changes needed in the typechecker — just treat
>
>  ```fsharp
>  SynExpr.ComputationExpr (false, None, m)
>  ```
>
>  the same as
>
>  ```fsharp
>  SynExpr.ComputationExpr (false, Some (SynExpr.Const (SynConst.Unit, range0)), m)
>  ```
>
>### Cons
>
>* In the absence of a body and additional type information, it is theoretically just as likely that the user is attempting to apply a function to an incomplete record construction expression. In this case, the AST now diverges from the user's intent.
>* Both parsing and typechecking must be updated.
>* Represents a breaking change to the untyped AST.
>* As in the previous alternative, there is risk and complexity in making changes to the parser's treatment of curly-braced expressions.

**Comment by edgarfgp** [comment]
Thanks Brian. Yeah updating `SynExpr.ComputationExpr` to `SynExpr.ComputationExpr of hasSeqBuilder: bool * expr: SynExpr option * range: range`  and adding an extra `SynExpr.EmptyRecordOrComputationExpr of range: range
` it makes the AST close to the user will write. See my last commit.

**Pull request closed without merging**
