### PR TITLE
Fix error reporting for PackageManager

### LINKED ISSUE #8775: FsiEvaluationSession.EvalInteraction reports some errors as successess wirth error messages,
fsi.exe correctly reports an invalid #r as an error.
````
> #r "nugt:FSharp.Data"; let_="";;

  #r "nugt:FSharp.Data"; let_="";;
  ^^^^^^^^^^^^^^^^^^^^^

stdin(1,1): error FS3216: Package manager key 'nugt' was not registered in [c:\kevinransom\fsharp\artifacts\bin\fsi\Deb
ug\netcoreapp3.0; c:\kevinransom\fsharp\artifacts\bin\fsi\Debug\netcoreapp3.0\], []. Currently registered: nuget


  #r "nugt:FSharp.Data"; let_="";;
  ^^^^^^^^^^^^^^^^^^^^^

stdin(1,1): error FS3217: Processing of a script fragment has stopped because an exception has been raised

>
````
FsiEvaluationSession.EvalInteraction incorrectly reports them as Success with error messages.

### PR DESCRIPTION
**Pull request by KevinRansom**
Fixes #8775 

When executing code similar to:
````
#r "nugt:FSharp.Data"; let _=();;
````
FsiEvaluationSession.EvalInteraction returns that evaluation as a success, but with error messages.  It should report it as a failure with error messages.

This PR adds a new state for FsiInteractionStepStatus CompletedWithAlreadyReportedError, this is for errors that have been reported to the error logger, but aren't realized as exceptions.

### CODE REVIEW

**Comment by KevinRansom** [comment]
@Phillip, please don't merge.

**Comment by cartermp** [comment]
Wouldn't have been able to even if I wanted :)

image

**Comment by KevinRansom** [comment]
I have to consider, how  this is surfaced in scripting.  So far something either succeeds or fails with an exception.

**Comment by KevinRansom** [comment]
Thank's phillip, I tried writing some tests for this today, and realized that there is the consumption side of the api's to consider.

**Comment by KevinRansom** [comment]
@cartermp, tests ready.

**Comment by cartermp** [comment]
Needs WIP removed to allow merging if that's what you're after here

**Comment by KevinRansom** [comment]
@cartermp, it does indeed. :-)

**Pull request merged**
