### PR TITLE
Fix for subtype pattern matching 

### PR DESCRIPTION
**Pull request by dsyme**
This fixes https://github.com/dotnet/fsharp/issues/13175

Added a systematic test matrix

### CODE REVIEW

**Review by vzarytovskii — APPROVED** [review]

**Comment by dsyme** [comment]
@vzarytovskii Could you take a careful look at https://github.com/dotnet/fsharp/blob/c46476742d5444952862c8615983a59dd6b96780/src/Compiler/Checking/PatternMatchCompilation.fs#L436 and see if there are obvious test cases/matrix that we should add?  I think I need more eyes on the test matrix for this.

**Comment by dsyme** [comment]
> and see if there are obvious test cases/matrix that we should add? I think I need more eyes on the test matrix for this.

We can merge this and add the tests separately

**Comment by vzarytovskii** [comment]
> > and see if there are obvious test cases/matrix that we should add? I think I need more eyes on the test matrix for this.
> 
> We can merge this and add the tests separately

Agree, we should merge this one, while I'm looking at some more potential tests.
What shall we do with servicing? @KevinRansom @brettfo

**Comment by dsyme** [comment]
> What shall we do with servicing? @KevinRansom @brettfo

This unfortunately needs to be a priority for all servicable branches that have the problem...

**Comment by vzarytovskii** [comment]
dev17.2 PR is here - https://github.com/dotnet/fsharp/pull/13190

**Pull request merged**
