### PR TITLE
Update .NET Core SDK in FCS

### PR DESCRIPTION
**Pull request by auduchinok**
Building FCS on a clean machine with only .NET Core 3.1 SDK installed is not possible due to a dependency on an outdated SDK. This PR updates the dependency.

### CODE REVIEW

**Comment by auduchinok** [comment]
Am I missing some place to advance the dotnet version in Linux_FCS build?

**Comment by cartermp** [comment]
There's more to it, unfortunately. Similar issue here: https://github.com/dotnet/fsharp/pull/8039/files

Maybe @brettfo knows more, but it's something to do with available SDKs in CI

**Comment by auduchinok** [comment]
@brettfo Is there something I could do to have the SDK updated?

**Comment by cartermp** [comment]
Weirdly enough the root is already updated here: https://github.com/dotnet/fsharp/blob/master/global.json#L3

And this only repros on the Linux build...

**Comment by auduchinok** [comment]
Yay, it's green!

**Pull request merged**
