### PR TITLE
VS: use VersionStamp for ISourceText hash

### PR DESCRIPTION
**Pull request by majocha**
This is just to test and do some benchmarks if it gains us anything.

The service uses `ISourceText.GetHashCode()` throughout in cache keys (#15114).
The editor overrides that GetHashCode() using `SourceText.GetChecksum()` which sounds relatively expensive.

Using VersionStamp instead theoretically would be faster.
Anyway, passing what effectively is source version in an overridden `GetHashCode` looks a bit hacky. Maybe doing it explicitly would be nicer?

### CODE REVIEW

**Comment by majocha** [comment]
Ok, so this passes tests locally but fails in CI.

**Comment by T-Gro** [comment]
> Ok, so this passes tests locally but fails in CI.

Did you try running in Release locally? It is a few tests from EditorTests.

**Comment by majocha** [comment]
Yes it passes EditorTests locally in release. Something counterintuitive is going on. I'll try to do git clean later and maybe get a local repro.

**Comment by majocha** [comment]
OK, so `VersionStamp.GetHashCode()` does not include `globalIncrement` value, it only takes timestamp and `localIncrement`, which is zero for a new document:

https://sourceroslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Solution/VersionStamp.cs,142

In Editor Tests all files are named C:\test.fs which altogether leads to random conflicts whenever two tests start at exactly same time.
If the above hypothesis is wrong and this still fails , I give up 🤪

**Comment by majocha** [comment]
The same gotcha I fell for:
https://github.com/dotnet/fsharp/blob/c6e2b7f4f6d1de11425a96b3c6f7c7790ed7b29d/vsintegration/src/FSharp.Editor/LanguageService/FSharpProjectOptionsManager.fs#L331

This hash can be very non-unique and together with my code from this PR caused collisions.

**Comment by majocha** [comment]
@T-Gro, I found out that while VersionStamp is solid, it's GetHashCode generates tons of collisions and is really unsuitable for telling instances apart. What's worse we already use it in a few places in the editor, for example here:
https://github.com/dotnet/fsharp/blob/c6e2b7f4f6d1de11425a96b3c6f7c7790ed7b29d/vsintegration/src/FSharp.Editor/LanguageService/FSharpProjectOptionsManager.fs#L331

It may or may not cause random fails in VS. It definitely caused random fails in CI in this PR.

**Comment by T-Gro** [comment]
> @T-Gro, I found out that while VersionStamp is solid, it's GetHashCode generates tons of collisions and is really unsuitable for telling instances apart. What's worse we already use it in a few places in the editor, for example here:
> 
> https://github.com/dotnet/fsharp/blob/c6e2b7f4f6d1de11425a96b3c6f7c7790ed7b29d/vsintegration/src/FSharp.Editor/LanguageService/FSharpProjectOptionsManager.fs#L331
> 
> It may or may not cause random fails in VS. It definitely caused random fails in CI in this PR.

That is bad (and unexpected).

So VersionStamp is OK for equality, there it works.
For hashing scenarios, we would need to go with a custom equalitycomparer ;; or a composite type (e.g. project+document+version) ?

**Comment by T-Gro** [comment]
Btw. doing  the equivalent of VersionStamps .ToString() and hashing that  - that should be unique enough, right?

**Comment by majocha** [comment]
> > @T-Gro, I found out that while VersionStamp is solid, it's GetHashCode generates tons of collisions and is really unsuitable for telling instances apart. What's worse we already use it in a few places in the editor, for example here:
> > https://github.com/dotnet/fsharp/blob/c6e2b7f4f6d1de11425a96b3c6f7c7790ed7b29d/vsintegration/src/FSharp.Editor/LanguageService/FSharpProjectOptionsManager.fs#L331
> > 
> > It may or may not cause random fails in VS. It definitely caused random fails in CI in this PR.
> 
> That is bad (and unexpected).
> 
> So VersionStamp is OK for equality, there it works. For hashing scenarios, we would need to go with a custom equalitycomparer ;; or a composite type (e.g. project+document+version) ?



> So VersionStamp is OK for equality, there it works.
Looks like VersionStamp itself is good for identity, even it's ToString() representation is unique, just it's hashcode is useless. 

> For hashing scenarios, we would need to go with a custom equalitycomparer ;; or a composite type (e.g. project+document+version) ?

We already use composite keys in the service: (name, sourceHash, FSharpOptions).This was failing here in tests, because we had same name, same hash , and FSharpOptions also relied on VersionStamp.GetHashCode(). Nuts 🙂
We could maybe ask Roslyn to expose the globalIncrement from VersionStamp for us if we insist on int / int64. Hacky way would be to just parse the string representation, because it already contains that unique number.

> Btw. doing the equivalent of VersionStamps .ToString() and hashing that - that should be unique enough, right?

Yes that is good enough, just feels dirty 🙂

**Comment by T-Gro** [comment]
Going via the .ToString() |> hash route is dirty/allocatey, but the members are private.
More dirty and less allocatey would be using reflection for reading the fields we need ;; or possibly hijacking the (internal) iobjectwritable.

**Comment by majocha** [comment]
Reflection sounds cool until Roslyn changes implementation and stuff starts randomly throwing exceptions. There are already some accommodations for F# in Roslyn repo. Maybe there's a way to expose a helper or an extension method that would convert `VersionStamp` to unique `int` or `int64` for us?

**Comment by T-Gro** [comment]
We can raise a PR in Roslyn repo to include the VersionStamp._globalIncrement in int's .GetHashCode implementation, if that would be all it takes.

**Comment by majocha** [comment]
I'm not 100% sure TBH. The more I read the source code of VersionStamp the more confusing it is to me.

**Comment by vzarytovskii** [comment]
> Ah, debugger to the rescue:
> The unique value kinda gets passed from one field to the other:
> image
> 
> image
> 
> 
> 
> 
> 
> > We can raise a PR in Roslyn repo to include the VersionStamp._globalIncrement in int's .GetHashCode implementation, if that would be all it takes.
> 
> Yes, it would be sufficient for our purposes.

Do we know where does VersionStamp come from? If it's VS, changing its implementation details might be problematic.

**Comment by vzarytovskii** [comment]
> > Do we know where does VersionStamp come from? If it's VS, changing its implementation details might be problematic.
> 
> It's from Roslyn:
> https://github.com/dotnet/roslyn/blob/315c2e149ba7889b0937d872274c33fcbfe9af5f/src/Workspaces/Core/Portable/Workspace/Solution/VersionStamp.cs

I see, we probably want to talk to @CyrusNajmabadi or @tmat about that in this case.

**Comment by CyrusNajmabadi** [comment]
I would not make this change. Definitely use actual checksums.  You will be in pain if you do not.

**Comment by majocha** [comment]
Makes sense. I'd keep an eye on that `GetHashCode()` use we already have in FSharpProjectOptionsManager. Could this potentially cause rare and sporadic errors on solution load?

**Pull request closed without merging**
