### PR TITLE
fix #7861 add references for attribute elements

### LINKED ISSUE #7861: Missing assembly reference for type used in attributes
Consider an attribute having a public property with a type from `System.Drawing` assembly defined in a `net461` class library project:
```fsharp
namespace AttributeAssemblyReferenceRepro

open System
open System.Drawing 

type FooAttribute() =
    inherit Attribute()

    member val Prop: FontStyle = Unchecked.defaultof<_> with get, set
```

When used in another `net461` project, it doesn't make the compiler generate a reference to `System.Drawing` assembly in the output assembly.
```fsharp
module Module

open System.Drawing
open AttributeAssemblyReferenceRepro

[<Foo(Prop = FontStyle.Bold)>]
do ()
```

A workaround is to use any type from `System.Drawing` somehow else, so the missing reference is added:

```fsharp
type T(p: FontStyle) =
    class end
```

The following .NET Core SDK is used:
```
$ dotnet --version
3.0.100
```

### PR DESCRIPTION
**Pull request by chillitom**
a potential fix for #7861

### CODE REVIEW

**Comment by chillitom** [comment]
I've tested this manually and I believe it to be working, unfortunately i couldn't try the exact repro provided as I'm developing on Linux and can't target net461.

If someone could point me in the direction of a suitable example I'd be happy to try and write unit tests.

**Comment by auduchinok** [comment]
@chillitom You can try targeting `net461` and adding a packager reference to `Microsoft.NETFramework.ReferenceAssemblies`.

**Comment by cartermp** [comment]
@chillitom sorry for not reviewing earlier, this now has a conflict. Could you resolve that?

**Comment by cartermp** [comment]
Will close out for now. Please ping if you're like this re-opened.

**Comment by dsyme** [comment]
Continued at https://github.com/dotnet/fsharp/pull/12937. Thanks @chillitom

**Pull request closed without merging**
