### PR TITLE
Added 'GetValues' to InteractiveSession

### PR DESCRIPTION
**Pull request by TIHan**
This adds a new API to `InteractiveSession` called `GetValues`. It returns a list of currently bound values within an interactive session.

While we added `GetBoundValues` to `FsiEvaluationSession`, there was no way to get the list of bound values from within FSI itself. With this PR, now you will be able to. It's able to by wrapping over the call to `GetBoundValues` from `FsiEvaluationSession`.

Untitled

// cc @Krzysztof-Cieslak 

There are probably more APIs that we need to add that are related to this, such as `GetTypes : unit -> InteractiveType`, `GetFunctions : unit -> InteractiveFunction`, `GetModules : unit -> InteractiveModule` - all to get the types, functions, and modules that are bound at the root-level. It's most likely we will do this, and of course there will be separate PRs for them.

@cartermp @dsyme -  since you can get access to `InteractiveSession` as soon as you launch `fsi.exe`, `InteractiveSession` is much more public facing than `FsiEvaluationSession`. Do you all think that the names `InteractiveValue` and `GetValues` make sense as a public API? We are likely to add more APIs similar to this, I want to make sure that we follow a consistent pattern.

### CODE REVIEW

**Comment by Krzysztof-Cieslak** [comment]
Some more context from my side: 

* In Ionide we don't host FSI using FCS or any special process, but rather we spawn `dotnet fsi` / `fsi.exe` in a terminal session hosted in Code - as such we don't have access to `FsiEvaluationSession`
* We currently provide an "experimental" feature called `FSI Watcher` - essentially, it's an additional view user can open which presents all values, types and functions bound in current FSI session. (screenshot below)
* To get the info we use really hacky reflection-based code (https://github.com/ionide/ionide-vscode-fsharp/blob/master/release/watcher/watcher.fsx#L7-L18) - having this API, and potentially additional ones such as `GetTypes` would simplify it a lot
* Also in general, I like idea of adding more APIs to `InteractiveSession` - this can potentially enable people to build richer tooling experience, which is a good thing.

image

**Comment by TIHan** [comment]
@Krzysztof-Cieslak , looking at how the watcher is working now, you are using `AddPrinter` as the callback after an evaluation. I tested calling `GetValues` from within the callback and it will not give the latest up-to date values because internally it hasn't recorded it yet. Maybe we could do something different, maybe provide a better event or callback to listen to that fires after everything has been updated after an evaluation.

**Comment by Krzysztof-Cieslak** [comment]
> Also, is there a reason for not hosting FSI in Ionide?

It is just the simplest solution - it's way easier to just spawn `dotnet fsi` / `fsi.exe` then do anything else. And given that Ionide/VSCode users are more used to using command-line tools etc - using `dotnet fsi` provides them exactly the same thing as they would run in manually in their terminal. 

> Maybe we could do something different, maybe provide a better event or callback to listen to that fires after everything has been updated after an evaluation.

Yes, that would be next good step. `AddPrinter` is obviously not designed to be used in a way I do it, it's a terrible hack - but that's the only place where we can plug "event handler" in current `fsi`. 

There's actually the biggest question here - do we want to allow users/tooling vendors to expand REPL experience like that? If so we should definitely add those additional events and APIs

**Comment by KevinRansom** [comment]
@TIHan, what do you want to do with this PR?

**Comment by TIHan** [comment]
@KevinRansom we might need to discuss with @jonsequitur and @cartermp if we want to expose this behavior in FSI. In side conversations, it felt like one should just use FsiEvaluationSession to get this information and not FSI.exe itself.

**Comment by KevinRansom** [comment]
@TIHan, yes that matches my recollection.

**Comment by KevinRansom** [comment]
Closing this, we can reactivate it, if we decide to expose this functionality on fsi at some future point.

**Pull request closed without merging**
