### PR TITLE
try adding dependency manager resolutions to the typecheck config

### PR DESCRIPTION
**Pull request by baronfel**
Might address #10762, but I need to figure out where a test would go.

The thought was that we could register the resolved dlls in the typechecker's reference list, but then I needed a range to use and figured the range of the package manager expression that caused the reference was the natural one to use.

### CODE REVIEW

**Comment by KevinRansom** [comment]
@baronfel, the errors are unrelated to your PR.

**Review by KevinRansom — DISMISSED** [review]
Oh right, we generate #r's so the editor never finds out about.  this is good.

Thanks for this.

**Review by KevinRansom — APPROVED** [review]
Okay, got it. 

Thanks for this.

Kevin

**Review by cartermp — APPROVED** [review]
Thanks! I tried to find if there was a good place to add a smoke test for unused opens, but setting that up could be tricky and it's really just affected by this underlying issue you address. Once FCS knows about the dll, the assembly service will be able to look into that dll for symbols and forward them into any code fixers.

**Pull request merged**
